"""AP Science (3 units x 7 topics) and AP ELA (3 units x 7 topics)"""

AP_SCIENCE = [
  # Unit 1 - AP Biology
  [
    {"title":"Cell Structure and Function","problems":[
      {"q":"Compare the structure and function of smooth ER and rough ER.","ex":"Think about ribosomes and what they synthesize.","a":"Rough ER has ribosomes on its surface and synthesizes/modifies proteins destined for export or the membrane. Smooth ER lacks ribosomes and is involved in lipid synthesis, carbohydrate metabolism, and detoxification.","diff":"medium"},
      {"q":"Explain how the sodium-potassium pump maintains the resting membrane potential.","ex":"Consider active transport and ion concentrations.","a":"The Na⁺/K⁺ pump uses ATP to move 3 Na⁺ out and 2 K⁺ in per cycle, creating a net negative charge inside the cell (−70 mV). This electrochemical gradient is essential for nerve and muscle function.","diff":"hard"},
      {"q":"Why is the fluid mosaic model an apt description of the cell membrane?","ex":"Think about phospholipid movement and protein distribution.","a":"'Fluid' because phospholipids and proteins can move laterally within the bilayer. 'Mosaic' because various proteins are embedded throughout the bilayer in a patchwork pattern, serving diverse functions.","diff":"medium"},
      {"q":"What is endosymbiotic theory and what evidence supports it?","ex":"Think about the origins of mitochondria and chloroplasts.","a":"Endosymbiotic theory proposes mitochondria and chloroplasts evolved from free-living prokaryotes engulfed by ancestral eukaryotic cells. Evidence: both have their own circular DNA, double membranes, 70S ribosomes, and reproduce by binary fission.","diff":"hard"}
    ]},
    {"title":"DNA Replication","problems":[
      {"q":"List the three key enzymes in DNA replication and their roles.","ex":"Think about unwinding, priming, and extending.","a":"Helicase: unwinds the double helix at the replication fork. Primase: synthesizes short RNA primers to start each new strand. DNA polymerase III: extends the new strand by adding nucleotides (5′ to 3′ only).","diff":"medium"},
      {"q":"Why is one strand synthesized continuously and the other in fragments?","ex":"Consider the 5′ to 3′ constraint of DNA polymerase.","a":"DNA polymerase can only add nucleotides to the 3′ end. The leading strand runs toward the fork (continuous synthesis). The lagging strand runs away from the fork, requiring repeated repriming → Okazaki fragments joined by DNA ligase.","diff":"hard"},
      {"q":"What is semi-conservative replication? What experiment proved it?","ex":"Think about how parental strands are distributed.","a":"Semi-conservative: each new DNA molecule consists of one original parental strand and one newly synthesized strand. The Meselson-Stahl experiment (1958), using heavy ¹⁵N isotopes, confirmed this model.","diff":"medium"},
      {"q":"What would happen if telomerase were completely absent in somatic cells?","ex":"Consider what happens to chromosome ends during each replication.","a":"Without telomerase, chromosomes shorten with each replication (end-replication problem). Over time, cells reach the Hayflick limit and enter senescence or apoptosis. This is already largely true in somatic cells; telomerase is most active in stem cells and cancer cells.","diff":"hard"}
    ]},
    {"title":"Transcription and Translation","problems":[
      {"q":"Write the mRNA sequence transcribed from DNA template strand 3′-TACGGATCC-5′.","ex":"RNA polymerase reads 3′ to 5′ and synthesizes 5′ to 3′. RNA uses U instead of T.","a":"5′-AUGCCUAGG-3′","diff":"easy"},
      {"q":"What does the codon AUG signal and which amino acid does it code for?","ex":"AUG is special for two reasons.","a":"AUG is the start codon — it initiates translation. It codes for Methionine (Met). Every polypeptide begins with Met (sometimes cleaved later).","diff":"easy"},
      {"q":"Explain the role of tRNA in connecting codons to amino acids.","ex":"Think about the anticodon and amino acid attachment site.","a":"tRNA carries a specific amino acid at its 3′ CCA end. Its anticodon loop base-pairs with the complementary mRNA codon at the ribosome A site, ensuring the correct amino acid is added to the growing polypeptide.","diff":"medium"},
      {"q":"What is a nonsense mutation and what is its effect on protein synthesis?","ex":"Consider what type of codon results.","a":"A nonsense mutation changes a sense codon to a stop codon (UAA, UAG, or UGA). This prematurely terminates translation, producing a truncated, usually nonfunctional protein.","diff":"medium"}
    ]},
    {"title":"Cell Division: Mitosis and Meiosis","problems":[
      {"q":"List the phases of mitosis in order and briefly describe each.","ex":"PMAT: Prophase, Metaphase, Anaphase, Telophase.","a":"Prophase: chromosomes condense, spindle forms, nuclear envelope breaks down. Metaphase: chromosomes align at the metaphase plate. Anaphase: sister chromatids pulled to opposite poles. Telophase: nuclear envelopes re-form, chromosomes decondense; followed by cytokinesis.","diff":"easy"},
      {"q":"How does meiosis I differ from mitosis in terms of what separates during anaphase?","ex":"Think about homologous pairs vs. sister chromatids.","a":"In meiosis I anaphase, homologous chromosome pairs separate. In mitosis (and meiosis II) anaphase, sister chromatids separate. Meiosis I is therefore reductional division (2n→n).","diff":"medium"},
      {"q":"Explain how crossing over during meiosis I increases genetic diversity.","ex":"Where does crossing over occur and what is exchanged?","a":"During prophase I, homologous chromosomes pair up (synapsis) and exchange segments at chiasmata (crossing over). This recombines alleles from maternal and paternal chromosomes, creating new allele combinations not present in either parent.","diff":"medium"},
      {"q":"A human cell has 46 chromosomes. How many chromosomes will each cell have after meiosis I and after meiosis II?","ex":"Track ploidy through each division.","a":"After meiosis I: 23 chromosomes (each still consisting of two sister chromatids). After meiosis II: 23 chromosomes (each a single chromatid). Gametes are haploid (n=23).","diff":"easy"}
    ]},
    {"title":"Mendelian Genetics and Beyond","problems":[
      {"q":"Two parents are Aa × Aa. What fraction of offspring are (a) dominant phenotype (b) homozygous dominant?","ex":"Punnett square: AA, Aa, Aa, aa.","a":"(a) 3/4 show dominant phenotype; (b) 1/4 are AA (homozygous dominant)","diff":"easy"},
      {"q":"In incomplete dominance, red (RR) × white (WW) flowers produce pink (RW) offspring. What are the F2 genotype and phenotype ratios?","ex":"Cross RW × RW.","a":"Genotypes: 1RR:2RW:1WW; Phenotypes: 1 red : 2 pink : 1 white (ratio = 1:2:1 for both)","diff":"medium"},
      {"q":"A color-blind man (X^b Y) and a carrier woman (X^B X^b) have children. What are the probabilities for each child?","ex":"Set up a sex-linked Punnett square.","a":"Daughters: 1/2 normal carrier (X^B X^b), 1/2 color-blind (X^b X^b). Sons: 1/2 normal (X^B Y), 1/2 color-blind (X^b Y). Overall: 1/4 of all children color-blind.","diff":"hard"},
      {"q":"Explain why two loci on the same chromosome may not show independent assortment.","ex":"Consider what determines independent assortment.","a":"Mendel's law of independent assortment applies to genes on different chromosomes. Genes on the same chromosome are linked and tend to be inherited together unless crossing over occurs between them. The closer the loci, the stronger the linkage.","diff":"hard"}
    ]},
    {"title":"Evolution and Natural Selection","problems":[
      {"q":"Distinguish between stabilizing, directional, and disruptive selection with an example of each.","ex":"Think about what happens to the distribution of a trait.","a":"Stabilizing: favors intermediate phenotypes (birth weight in humans — very low or high weight has lower survival). Directional: favors one extreme (antibiotic resistance — resistant bacteria increasingly favored). Disruptive: favors both extremes (beak size in finches on islands with only large or small seeds).","diff":"hard"},
      {"q":"A population of beetles has q²=0.16 (frequency of homozygous recessive). Find allele and genotype frequencies under Hardy-Weinberg.","ex":"q=√0.16; p=1−q; then p², 2pq.","a":"q=0.4; p=0.6; p²(BB)=0.36; 2pq(Bb)=0.48; q²(bb)=0.16","diff":"medium"},
      {"q":"What are the five conditions for Hardy-Weinberg equilibrium?","ex":"Any violation causes evolution.","a":"(1) Large population (no genetic drift); (2) random mating; (3) no mutations; (4) no gene flow (migration); (5) no natural selection. If all hold, allele frequencies remain constant.","diff":"medium"},
      {"q":"How does the concept of 'fitness' in evolutionary biology differ from its colloquial meaning?","ex":"Fitness in biology is not about physical strength.","a":"Evolutionary fitness means reproductive success — an organism's ability to survive and reproduce, passing alleles to the next generation. A weak but highly fertile organism has higher fitness than a strong but infertile one.","diff":"easy"}
    ]},
    {"title":"Cellular Respiration and Photosynthesis","problems":[
      {"q":"Write the overall equation for aerobic cellular respiration and identify where each stage occurs.","ex":"Three stages: glycolysis, Krebs, ETC.","a":"C₆H₁₂O₆+6O₂→6CO₂+6H₂O+~36–38 ATP. Glycolysis: cytoplasm; Pyruvate oxidation and Krebs cycle: mitochondrial matrix; ETC: inner mitochondrial membrane.","diff":"easy"},
      {"q":"What is the role of NAD⁺ in glycolysis and why must it be regenerated?","ex":"Think about what happens in lactic acid fermentation.","a":"NAD⁺ accepts electrons/H⁺ from glucose oxidation, becoming NADH. Since the cell has a limited NAD⁺ supply, it must be regenerated. In anaerobic conditions, fermentation (lactic acid or alcohol) regenerates NAD⁺ so glycolysis can continue.","diff":"hard"},
      {"q":"What are the light-dependent and light-independent (Calvin cycle) reactions of photosynthesis?","ex":"Light reactions occur in thylakoids; Calvin in stroma.","a":"Light-dependent: in thylakoid membranes; sunlight splits H₂O (releasing O₂), produces ATP and NADPH. Calvin cycle (stroma): uses ATP and NADPH to fix CO₂ into G3P (glyceraldehyde-3-phosphate), ultimately producing glucose.","diff":"medium"},
      {"q":"Compare the products of fermentation in yeast vs. muscle cells.","ex":"Both types of fermentation regenerate NAD⁺.","a":"Yeast: alcoholic fermentation → ethanol + CO₂ + NAD⁺. Muscle cells: lactic acid fermentation → lactate + NAD⁺. Both produce only 2 ATP (from glycolysis); neither can access the Krebs cycle or ETC without oxygen.","diff":"medium"}
    ]}
  ],
  # Unit 2 - AP Chemistry
  [
    {"title":"Atomic Structure and Electron Configuration","problems":[
      {"q":"Write the ground-state electron configuration of Fe (Z=26) and identify its valence electrons.","ex":"Fill in order: 1s,2s,2p,3s,3p,3d,4s.","a":"[Ar]3d⁶4s²; valence electrons: 4s²3d⁶ (8 total, or 2 in outermost shell)","diff":"medium"},
      {"q":"Explain the periodic trend in atomic radius across a period and down a group.","ex":"Consider nuclear charge and shielding.","a":"Across a period (left→right): atomic radius decreases — more protons pull electrons closer; shielding stays roughly constant. Down a group: radius increases — each successive period adds a new electron shell, increasing distance from nucleus.","diff":"medium"},
      {"q":"The photoelectric effect showed light behaves as particles. Explain the key observation that supports this.","ex":"Think about threshold frequency, not intensity.","a":"Below a threshold frequency, no electrons are ejected regardless of light intensity. Above threshold, electrons are ejected immediately. This implies light arrives in discrete packets (photons) with energy E=hν; only photons with sufficient energy (frequency) can eject an electron.","diff":"hard"},
      {"q":"Write the electron configuration of Cu (Z=29) and explain why it deviates from the expected [Ar]3d⁹4s².","ex":"Consider the extra stability of filled/half-filled d subshells.","a":"Actual: [Ar]3d¹⁰4s¹. A completely filled 3d subshell is especially stable. One electron moves from 4s to 3d to achieve this, making Cu an exception to the Aufbau principle.","diff":"hard"}
    ]},
    {"title":"Chemical Bonding and Molecular Geometry","problems":[
      {"q":"Draw the Lewis structure for SO₂. Does it have resonance structures?","ex":"S is central; total valence electrons: 6+6+6=18.","a":"S=O double bond and S−O single bond with lone pairs; yes, SO₂ has two resonance structures (the double bond alternates). Actual bond order is 1.5.","diff":"medium"},
      {"q":"Using VSEPR, predict the shape of PCl₅.","ex":"Count electron domains around P.","a":"5 bonding pairs, 0 lone pairs → trigonal bipyramidal, 120° (equatorial) and 90° (axial) bond angles.","diff":"medium"},
      {"q":"Rank the following by increasing boiling point: CH₄, NH₃, H₂O. Justify.","ex":"Identify the dominant intermolecular force for each.","a":"CH₄ < NH₃ < H₂O. CH₄ has only weak London dispersion forces. NH₃ and H₂O both hydrogen bond, but H₂O forms more H-bonds per molecule (2 donor, 2 acceptor) and has a higher degree of molecular association.","diff":"hard"},
      {"q":"What is the bond order in O₂ according to molecular orbital theory? Is O₂ diamagnetic or paramagnetic?","ex":"Fill MOs in order of energy; bond order=(bonding−antibonding)/2.","a":"Bond order = (8 bonding − 4 antibonding)/2 = 2 (double bond). O₂ has 2 unpaired electrons in degenerate π* orbitals → paramagnetic.","diff":"hard"}
    ]},
    {"title":"Stoichiometry and Limiting Reagents","problems":[
      {"q":"How many moles of CO₂ are produced when 22 g of CO reacts with excess O₂? (2CO + O₂ → 2CO₂)","ex":"Molar mass CO=28 g/mol; use mole ratio.","a":"22/28=0.786 mol CO × (2 mol CO₂/2 mol CO)=0.786 mol CO₂","diff":"easy"},
      {"q":"In the reaction N₂+3H₂→2NH₃, if 5 mol N₂ and 12 mol H₂ are mixed, which is limiting? How many moles of NH₃ form?","ex":"Calculate moles of NH₃ each reactant can produce.","a":"N₂ produces 10 mol NH₃; H₂ produces 8 mol NH₃. H₂ is limiting → 8 mol NH₃ produced.","diff":"medium"},
      {"q":"A reaction has theoretical yield 80 g but only 60 g is collected. Calculate percent yield.","ex":"% yield = (actual/theoretical) × 100.","a":"60/80 × 100 = 75%","diff":"easy"},
      {"q":"In the reaction 2Al+3Cl₂→2AlCl₃, how many grams of AlCl₃ form from 5.4 g Al and excess Cl₂? (Al=27, Cl=35.5)","ex":"Convert g Al to mol, use mole ratio, convert to grams AlCl₃.","a":"5.4/27=0.2 mol Al → 0.2 mol AlCl₃ × 133.5 g/mol = 26.7 g","diff":"medium"}
    ]},
    {"title":"Gas Laws and Kinetic Molecular Theory","problems":[
      {"q":"A gas at 2.0 atm and 300 K occupies 5.0 L. Find the volume at 1.0 atm and 600 K.","ex":"Use combined gas law: P₁V₁/T₁=P₂V₂/T₂.","a":"V₂=(2.0×5.0×600)/(1.0×300)=20.0 L","diff":"medium"},
      {"q":"Calculate the molar mass of a gas if 4.5 g occupies 2.24 L at STP.","ex":"At STP, 1 mol = 22.4 L.","a":"Moles = 2.24/22.4 = 0.1 mol; molar mass = 4.5/0.1 = 45 g/mol","diff":"easy"},
      {"q":"Explain why real gases deviate from ideal behavior at high pressure and low temperature.","ex":"Consider the two assumptions of ideal gas law that fail.","a":"At high pressure, gas particles are compressed closer together and intermolecular forces become significant (attractive). At low temperature, particle kinetic energy is low, so attractions dominate. Ideal gas law assumes no intermolecular forces and negligible particle volume — both fail in these conditions.","diff":"hard"},
      {"q":"Which effuses faster — N₂ or CO₂ — and by what factor? (Graham's law)","ex":"Rate ∝ 1/√(molar mass).","a":"Rate(N₂)/Rate(CO₂)=√(44/28)=√(11/7)≈1.25. N₂ effuses ~1.25 times faster than CO₂.","diff":"medium"}
    ]},
    {"title":"Thermodynamics and Gibbs Free Energy","problems":[
      {"q":"A reaction releases 120 kJ and has ΔS=+200 J/K at 298 K. Calculate ΔG and determine spontaneity.","ex":"ΔG=ΔH−TΔS; watch units (kJ vs J).","a":"ΔG=−120,000−298(200)=−120,000−59,600=−179,600 J=−179.6 kJ. ΔG<0 → spontaneous","diff":"medium"},
      {"q":"At what temperature does a reaction with ΔH=+50 kJ and ΔS=+100 J/K become spontaneous?","ex":"Set ΔG=0 to find crossover temperature.","a":"0=ΔH−TΔS → T=ΔH/ΔS=50,000/100=500 K. Spontaneous above 500 K.","diff":"medium"},
      {"q":"Explain Hess's Law and use it to find ΔH for A→C given: A→B ΔH₁=−40 kJ; B→C ΔH₂=+15 kJ.","ex":"ΔH is a state function — path doesn't matter.","a":"Hess's Law: ΔH for A→C = ΔH₁+ΔH₂ = −40+15 = −25 kJ. The total enthalpy change is independent of the intermediate steps.","diff":"medium"},
      {"q":"What is the standard enthalpy of formation (ΔHf°) of an element in its standard state?","ex":"By definition.","a":"Zero. The standard enthalpy of formation of any element in its most stable form at 1 atm and 25°C is defined as 0 kJ/mol.","diff":"easy"}
    ]},
    {"title":"Chemical Equilibrium","problems":[
      {"q":"Write the equilibrium expression K for: N₂(g)+3H₂(g) ⇌ 2NH₃(g).","ex":"K=[products]^stoich/[reactants]^stoich. Exclude pure solids/liquids.","a":"K=[NH₃]²/([N₂][H₂]³)","diff":"easy"},
      {"q":"Apply Le Chatelier's principle: what happens to N₂+3H₂⇌2NH₃ when (a) H₂ is added, (b) NH₃ is removed, (c) pressure is increased?","ex":"Each disturbance — predict the system's response.","a":"(a) Shift right (more NH₃ produced); (b) Shift right (replaces removed NH₃); (c) Shift right (toward fewer moles of gas: 2 vs. 4)","diff":"medium"},
      {"q":"For 2SO₂+O₂⇌2SO₃, at equilibrium [SO₂]=0.2M, [O₂]=0.1M, [SO₃]=0.4M. Calculate K.","ex":"Substitute into equilibrium expression.","a":"K=[0.4]²/([0.2]²[0.1])=0.16/(0.004)=40","diff":"medium"},
      {"q":"A reaction has K=1×10⁻⁸. What does this tell you about the equilibrium position?","ex":"Interpret the magnitude of K.","a":"K<<1 indicates that at equilibrium, reactants strongly predominate. Very little product is present — the reaction barely proceeds to the right.","diff":"easy"}
    ]},
    {"title":"Acids, Bases, and Electrochemistry","problems":[
      {"q":"Calculate the pH of 0.01 M HCl.","ex":"HCl is a strong acid — fully dissociates.","a":"[H⁺]=0.01 M; pH=−log(0.01)=2","diff":"easy"},
      {"q":"A buffer contains 0.3 M acetic acid (pKa=4.74) and 0.3 M sodium acetate. Find the pH using Henderson-Hasselbalch.","ex":"pH=pKa+log([A⁻]/[HA])","a":"pH=4.74+log(0.3/0.3)=4.74+0=4.74","diff":"medium"},
      {"q":"In a galvanic cell, Zn|Zn²⁺||Cu²⁺|Cu: which is the anode and which is the cathode? Write the half-reactions.","ex":"Oxidation at anode; reduction at cathode.","a":"Anode (oxidation): Zn→Zn²⁺+2e⁻. Cathode (reduction): Cu²⁺+2e⁻→Cu. E°cell=+0.34−(−0.76)=+1.10 V","diff":"medium"},
      {"q":"How does electrolysis differ from a galvanic cell?","ex":"Consider energy flow direction.","a":"A galvanic cell converts chemical energy to electrical energy (spontaneous, ΔG<0). Electrolysis uses electrical energy to drive a non-spontaneous chemical reaction (ΔG>0) — e.g., electroplating, producing Al from Al₂O₃.","diff":"medium"}
    ]}
  ],
  # Unit 3 - AP Physics and Environmental Science
  [
    {"title":"Kinematics in 1D and 2D","problems":[
      {"q":"A ball is thrown upward at 20 m/s. Find max height and time to reach it. (g=10 m/s²)","ex":"v=v₀−gt at max height v=0.","a":"t=2 s; h=v₀t−½gt²=40−20=20 m","diff":"easy"},
      {"q":"A projectile is launched at 30° with v₀=40 m/s. Find horizontal range. (g=10 m/s²)","ex":"R=v₀²sin(2θ)/g","a":"R=1600×sin60°/10=160×(√3/2)=80√3≈138.6 m","diff":"medium"},
      {"q":"A car decelerates from 30 m/s to rest over 90 m. Find the deceleration.","ex":"v²=v₀²+2ax; v=0.","a":"0=900+2a(90) → a=−5 m/s²","diff":"easy"},
      {"q":"A ball is dropped from a building 80 m tall. How long to hit the ground and what is its speed at impact? (g=10 m/s²)","ex":"h=½gt²; v=gt","a":"t=√(2×80/10)=4 s; v=10×4=40 m/s","diff":"easy"}
    ]},
    {"title":"Newton's Laws and Forces","problems":[
      {"q":"A 12 kg box on a frictionless surface is pushed by two forces: F₁=30 N east and F₂=16 N west. Find acceleration.","ex":"Net force = F₁−F₂; F_net=ma.","a":"F_net=14 N east; a=14/12≈1.17 m/s² east","diff":"easy"},
      {"q":"A 5 kg block rests on a surface with μk=0.3. A 20 N force is applied horizontally. Find acceleration. (g=10 m/s²)","ex":"Friction force f=μkN=μk mg; net force=applied−friction.","a":"f=0.3×50=15 N; net=20−15=5 N; a=5/5=1 m/s²","diff":"medium"},
      {"q":"An elevator of mass 800 kg accelerates upward at 2 m/s². Find the tension in the cable. (g=10 m/s²)","ex":"T−mg=ma; upward positive.","a":"T=m(g+a)=800(12)=9600 N","diff":"medium"},
      {"q":"Two blocks (3 kg and 5 kg) are connected by a string over a frictionless pulley (Atwood machine). Find acceleration and tension. (g=10 m/s²)","ex":"a=(m₂−m₁)g/(m₁+m₂); T=m₁(g+a).","a":"a=(5−3)×10/8=2.5 m/s²; T=3(10+2.5)=37.5 N","diff":"medium"}
    ]},
    {"title":"Work, Energy, and Power","problems":[
      {"q":"A 4 kg box is pushed 10 m along a frictionless floor with 20 N force at 0°. Find work done and final speed if starting from rest.","ex":"W=Fd cosθ; then W=ΔKE.","a":"W=200 J; 200=½(4)v² → v=10 m/s","diff":"easy"},
      {"q":"A 2 kg ball falls 15 m. Find its speed just before impact using energy conservation. (g=10 m/s²)","ex":"mgh=½mv²","a":"v=√(2×10×15)=√300≈17.3 m/s","diff":"easy"},
      {"q":"A motor lifts a 500 kg elevator 20 m in 10 seconds. Find the power output. (g=10 m/s²)","ex":"P=W/t; W=mgh.","a":"W=500×10×20=100,000 J; P=100,000/10=10,000 W=10 kW","diff":"medium"},
      {"q":"A spring (k=200 N/m) is compressed 0.1 m. What is the elastic potential energy and the speed of a 0.5 kg block when the spring is released?","ex":"PE=½kx²; PE→KE.","a":"PE=½(200)(0.01)=1 J; 1=½(0.5)v² → v=2 m/s","diff":"medium"}
    ]},
    {"title":"Momentum and Collisions","problems":[
      {"q":"A 0.5 kg ball moving at 8 m/s collides with a stationary 1.5 kg ball. They stick together. Find final velocity.","ex":"Conservation of momentum: p₁=p_total; elastic? inelastic?","a":"m₁v₁=(m₁+m₂)v_f; 0.5×8=2×v_f; v_f=2 m/s","diff":"easy"},
      {"q":"In an elastic collision, a 2 kg ball at 6 m/s hits a stationary 2 kg ball. What happens?","ex":"For equal masses in elastic collision: velocities exchange.","a":"The first ball stops (v₁f=0) and the second ball moves at 6 m/s. Momentum and kinetic energy are both conserved.","diff":"medium"},
      {"q":"Calculate the impulse delivered to a 0.4 kg ball that changes velocity from 5 m/s to −3 m/s (rebounds).","ex":"Impulse=Δp=m(v_f−v_i)","a":"J=0.4(−3−5)=0.4(−8)=−3.2 N·s (in the direction opposite to initial motion)","diff":"medium"},
      {"q":"A rocket expels exhaust gases backward at 400 m/s and burns 2 kg of fuel per second. Find the thrust force.","ex":"Thrust=rate of mass expulsion × exhaust speed.","a":"F=Δm/Δt × v_exhaust=2×400=800 N","diff":"hard"}
    ]},
    {"title":"Rotational Motion and Gravitation","problems":[
      {"q":"A wheel accelerates from 0 to 60 rad/s in 5 seconds. Find angular acceleration and the number of rotations.","ex":"α=Δω/t; θ=½αt²; rotations=θ/(2π).","a":"α=12 rad/s²; θ=½(12)(25)=150 rad; rotations=150/(2π)≈23.9","diff":"medium"},
      {"q":"Find the gravitational force between two 1000 kg masses separated by 10 m. (G=6.67×10⁻¹¹)","ex":"F=Gm₁m₂/r²","a":"F=6.67×10⁻¹¹×10⁶/100=6.67×10⁻⁷ N","diff":"easy"},
      {"q":"What is a satellite's orbital speed at height h above Earth if Earth's radius is R and surface g is known?","ex":"Gravity provides centripetal force: mg(R/(R+h))²=(mv²)/(R+h).","a":"v=√(gR²/(R+h))","diff":"hard"},
      {"q":"A torque of 15 N·m acts on a flywheel with moment of inertia 3 kg·m². Find the angular acceleration.","ex":"τ=Iα","a":"α=τ/I=15/3=5 rad/s²","diff":"easy"}
    ]},
    {"title":"Waves, Sound, and Light","problems":[
      {"q":"A wave has frequency 500 Hz and wavelength 0.68 m. Find wave speed.","ex":"v=fλ","a":"v=500×0.68=340 m/s","diff":"easy"},
      {"q":"A sound source at 800 Hz moves toward a stationary observer at 40 m/s. Find observed frequency. (v_sound=340 m/s)","ex":"Doppler: f'=f×(v/(v−v_s)) for source approaching.","a":"f'=800×(340/(340−40))=800×(340/300)=800×1.133≈907 Hz","diff":"hard"},
      {"q":"Light travels from glass (n=1.5) into air (n=1.0). Find the critical angle for total internal reflection.","ex":"sin θc=n₂/n₁","a":"sin θc=1/1.5=0.667 → θc≈41.8°","diff":"medium"},
      {"q":"Two slits separated by 0.5 mm produce an interference pattern. The third bright fringe is 3 mm from center on a screen 1 m away. Find wavelength.","ex":"y_m=mλL/d; m=3.","a":"λ=yd/(mL)=(0.003×0.0005)/(3×1)=5×10⁻⁷ m=500 nm","diff":"hard"}
    ]},
    {"title":"Ecosystems, Climate, and Human Impact","problems":[
      {"q":"Explain the difference between the carbon cycle in a pre-industrial vs. modern atmosphere.","ex":"Consider fossil fuel burning and deforestation.","a":"Pre-industrial: carbon cycled naturally among atmosphere, oceans, biosphere, and lithosphere in near balance. Modern: burning fossil fuels releases ancient carbon stored for millions of years, and deforestation reduces carbon sequestration — net addition of CO₂ to atmosphere exceeds natural removal rates.","diff":"medium"},
      {"q":"What is a keystone species and how does removing one affect ecosystem structure?","ex":"Think about sea otters and sea urchins/kelp.","a":"A keystone species has a disproportionately large impact on its ecosystem relative to its abundance. Removing one causes cascading trophic effects. Example: removing sea otters → sea urchin population explosion → destruction of kelp forests → loss of habitat for dozens of species.","diff":"medium"},
      {"q":"Describe the mechanism by which CFCs cause stratospheric ozone depletion.","ex":"Think about UV, Cl radicals, catalytic destruction.","a":"UV radiation breaks down CFCs in the stratosphere, releasing Cl radicals. Each Cl atom catalytically destroys thousands of O₃ molecules: Cl+O₃→ClO+O₂; ClO+O→Cl+O₂. The Cl atom is not consumed, making it a persistent catalyst.","diff":"hard"},
      {"q":"What is the IPAT equation and how is it used in environmental science?","ex":"I=P×A×T","a":"IPAT: Environmental Impact = Population × Affluence (consumption per person) × Technology (environmental impact per unit of consumption). It shows that impact results from the interaction of human numbers, wealth/consumption levels, and the environmental efficiency of technology used.","diff":"medium"}
    ]}
  ]
]

AP_ELA = [
  # Unit 1 - AP Lang: Rhetoric and Argumentation
  [
    {"title":"Ethos, Pathos, and Logos","problems":[
      {"q":"Identify the appeal: 'According to a 2022 Harvard study, students who sleep 8+ hours score 15% higher on standardized tests.'","ex":"Which appeal does empirical research represent?","a":"Logos — statistical evidence from a credible source appeals to reason and logic to support the claim.","diff":"easy"},
      {"q":"Identify the appeal: 'As a survivor of domestic violence, I know firsthand the failure of our current legal protections.' Explain how it functions.","ex":"Consider what the speaker is establishing.","a":"Ethos — the speaker establishes personal credibility through lived experience, positioning themselves as an authentic and knowledgeable voice on the issue.","diff":"easy"},
      {"q":"A charity advertisement shows a malnourished child with the caption 'For just $1 a day, you can change a life.' Analyze the appeal used and any potential weakness.","ex":"Identify the appeal, then consider how an audience might resist it.","a":"Pathos — the image and personal cost figure trigger empathy and guilt. Weakness: emotional manipulation without addressing systemic causes or providing evidence the donation is effective may be seen as exploitative.","diff":"medium"},
      {"q":"Can a single passage use all three appeals simultaneously? Write a one-paragraph example and label each appeal.","ex":"Think about a speech on a policy issue.","a":"Example: 'As a physician with 20 years in emergency medicine [ethos], I have watched patients die waiting for insulin they couldn't afford — deaths that are preventable and unconscionable [pathos]. Studies show insulin cost-sharing policies reduce hospitalizations by 30% in comparable countries [logos]. We must act now.'","diff":"hard"}
    ]},
    {"title":"Rhetorical Devices and Figures of Speech","problems":[
      {"q":"Identify the device and its effect: 'We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields.' (Churchill)","ex":"Look for repetition at the beginning of clauses.","a":"Anaphora — repetition of 'we shall fight' creates rhythmic momentum, collective resolve, and emotional intensity. The accumulation of repeated commitment signals absolute determination.","diff":"easy"},
      {"q":"Explain the difference between antithesis and paradox, with an example of each.","ex":"Both involve contrast, but differently.","a":"Antithesis: contrasting ideas in parallel structure ('Ask not what your country can do for you, ask what you can do for your country'). Paradox: a seemingly contradictory statement that reveals a deeper truth ('Less is more'; 'I must be cruel to be kind').","diff":"medium"},
      {"q":"What is a rhetorical question and when is it most effective? Give an example.","ex":"Think about what a rhetorical question does to the audience.","a":"A rhetorical question is posed for effect, not to receive an answer — it draws the audience into the argument or highlights the obvious. Most effective when the answer is self-evident. Example: 'If we can send a man to the moon, why can't we provide clean water to every citizen?'","diff":"easy"},
      {"q":"Analyze the effect of this chiasmus: 'It's not the size of the dog in the fight; it's the size of the fight in the dog.'","ex":"Identify the grammatical inversion and its meaning.","a":"Chiasmus reverses grammatical structure (A-B / B-A: 'dog...fight' / 'fight...dog'). Effect: creates a memorable, aphoristic quality and emphasizes that willpower and spirit matter more than physical size — the inversion enacts the argument itself.","diff":"medium"}
    ]},
    {"title":"Analyzing Arguments","problems":[
      {"q":"Identify the claim, grounds, and warrant in this argument: 'You should exercise daily. Research shows it reduces depression by 40%. Mental health is just as important as physical health.'","ex":"Claim=the conclusion; grounds=evidence; warrant=underlying assumption that links them.","a":"Claim: you should exercise daily. Grounds: research shows 40% depression reduction. Warrant: exercise that improves mental health (which is important) is worth doing.","diff":"medium"},
      {"q":"What is a logical fallacy? Identify the fallacy in: 'My grandfather smoked all his life and lived to 90, so smoking can't be that dangerous.'","ex":"One example ≠ a pattern.","a":"Anecdotal evidence / hasty generalization — using a single exceptional case to refute statistical evidence. The grandfather's longevity is statistically exceptional; population-level data consistently shows smoking causes premature death.","diff":"medium"},
      {"q":"Explain ad hominem and why it weakens an argument.","ex":"Consider what ad hominem attacks rather than addresses.","a":"Ad hominem attacks the person making an argument rather than the argument itself (e.g., 'You can't trust her climate views — she drives an SUV'). It weakens argument because a person's character or consistency is logically irrelevant to the truth or merit of their claim.","diff":"easy"},
      {"q":"What is a 'straw man' fallacy? Construct an example.","ex":"Think about how one misrepresents an opponent's position.","a":"Straw man: distorting or exaggerating an opponent's position to make it easier to attack. Example: If someone argues for stricter gun regulations, responding with 'They want to take away all your guns and leave you defenseless' — this attacks a fabricated extreme rather than the actual position.","diff":"medium"}
    ]},
    {"title":"Rhetorical Situation (SOAPS)","problems":[
      {"q":"Analyze the rhetorical situation of Lincoln's Gettysburg Address using SOAPS.","ex":"S=Speaker, O=Occasion, A=Audience, P=Purpose, S=Subject.","a":"Speaker: President Abraham Lincoln. Occasion: dedication of Soldiers' National Cemetery, 4 months after Battle of Gettysburg (Nov. 1863). Audience: attendees including survivors, families, politicians, general public. Purpose: honor the dead, reframe the war as a fight for equality and national rebirth. Subject: sacrifice and national purpose.","diff":"medium"},
      {"q":"How does understanding the occasion change the interpretation of a text?","ex":"Think about how context shapes meaning.","a":"Occasion provides the urgent context that motivated the text. A speech at a funeral means differently than the same words in a political rally. Understanding occasion reveals the speaker's constraints, what prompted them to speak, and what the audience already believed — all of which shape rhetorical choices.","diff":"medium"},
      {"q":"How might the same argument be constructed differently for a scientific journal vs. a community newsletter?","ex":"Think about how audience affects diction, evidence, and tone.","a":"Scientific journal: technical vocabulary, quantitative evidence, formal tone, citations, assumes expert knowledge, passive voice. Community newsletter: plain language, concrete examples, emotional appeals, direct tone, no jargon, assumes general audience. Same core argument, but audience shapes every rhetorical choice.","diff":"medium"},
      {"q":"Why is identifying purpose essential to rhetorical analysis?","ex":"Consider the difference between to inform, persuade, entertain, inspire.","a":"Purpose explains why the author made specific rhetorical choices. An author writing to persuade will emphasize appeals and emotional language; one writing to inform will prioritize clarity and evidence. Misidentifying purpose leads to misinterpreting the text's strategies and success.","diff":"easy"}
    ]},
    {"title":"Concession and Refutation","problems":[
      {"q":"What is the difference between a concession and a refutation? Why include a concession at all?","ex":"Think strategically about argumentation.","a":"Concession: acknowledging a valid point in the opposing argument. Refutation: explaining why your position still holds despite the concession. Including a concession demonstrates intellectual honesty and strengthens ethos — it shows you've considered counterarguments rather than ignored them.","diff":"easy"},
      {"q":"Write a concession-refutation sentence for: Claim: 'School should start later.' Counterargument: 'It would disrupt parent work schedules.'","ex":"Concede the point, then pivot with 'however' or 'nevertheless'.","a":"'While it is true that later start times may require adjustments to family and work schedules, the well-documented benefits of adolescent sleep — including improved mental health, academic performance, and reduced accident rates — far outweigh the logistical inconveniences.'","diff":"medium"},
      {"q":"What makes a refutation more effective than simply ignoring the opposing argument?","ex":"Consider the effect on audience trust.","a":"Addressing opposing views directly demonstrates confidence in your position, builds credibility (ethos), and prevents the audience from dismissing your argument because an obvious objection was never answered. It shows rigorous thinking rather than selective presentation.","diff":"easy"},
      {"q":"Identify the weakness in this refutation: 'Some say electric cars are too expensive, but electric cars are clearly the future.' Rewrite it more effectively.","ex":"Does the original actually address the concern?","a":"Original weakness: the refutation doesn't address the cost concern — it just reasserts the claim. Better: 'While EVs have higher upfront costs, long-term fuel and maintenance savings typically offset this within 4–5 years, and expanding federal incentives are rapidly lowering the purchase price barrier.'","diff":"hard"}
    ]},
    {"title":"Tone, Diction, and Syntax","problems":[
      {"q":"How does word choice (diction) establish tone? Give an example of two words with the same denotation but different connotations.","ex":"Think about how 'thin' vs. 'gaunt' differ.","a":"Diction shapes emotional coloring and attitude. Example: 'slender' vs. 'bony' — both mean thin, but 'slender' implies attractiveness/grace, while 'bony' implies unhealthy thinness. An author's diction choices reveal their attitude toward the subject and shape the reader's perception.","diff":"easy"},
      {"q":"Analyze how the syntax of this sentence creates urgency: 'No more delays. No more excuses. No more waiting.'","ex":"Consider sentence length, structure, and repetition.","a":"The three short, declarative sentences create a staccato rhythm that mimics impatience and finality. The parallel structure (anaphora: 'No more') builds cumulative force. Brevity signals the speaker has no patience for qualification — the time for action is now.","diff":"medium"},
      {"q":"What is the effect of using second-person ('you') in persuasive writing?","ex":"Think about the relationship between writer and reader.","a":"Second-person directly implicates the reader, making the argument personal and harder to dismiss. It creates intimacy and urgency — the reader is no longer a passive observer but a participant. However, overuse can feel presumptuous or alienating if the reader doesn't identify with the 'you' being described.","diff":"medium"},
      {"q":"Compare the effect of passive voice vs. active voice in: 'Mistakes were made' vs. 'The administration made mistakes.'","ex":"Consider agency and accountability.","a":"Passive voice ('mistakes were made') obscures the agent — who is responsible is ambiguous, reducing accountability and emotional impact. Active voice ('the administration made mistakes') assigns clear responsibility, is more direct, and is generally more persuasive and honest. Passive voice is sometimes used deliberately to evade accountability.","diff":"medium"}
    ]},
    {"title":"AP Exam Multiple Choice Strategies","problems":[
      {"q":"When an AP Lang MC question asks for the 'primary purpose' of a passage, what should you look for?","ex":"Consider the overall function, not just one detail.","a":"Look for the dominant goal driving the entire text — persuade, inform, celebrate, critique, eulogize, etc. Check the overall structure, what the author returns to most, and the closing emphasis. Eliminate answers that describe a minor detail or only part of the passage.","diff":"easy"},
      {"q":"A question asks about the 'effect of the transition in paragraph 4.' What does this typically require you to analyze?","ex":"Think about how structure serves argument.","a":"Analyze how the paragraph connects to what came before and after — whether it concedes, pivots, escalates, or provides evidence. Note transitional words or phrases ('however,' 'therefore,' 'in contrast') and explain what logical or rhetorical relationship they establish.","diff":"medium"},
      {"q":"What is the best strategy for handling a 'closest in meaning' vocabulary-in-context question?","ex":"Don't rely on the word's most common meaning.","a":"Re-read the sentence and surrounding context without looking at the answer choices. Predict what the word means in context, then select the choice closest to your prediction. The 'trap' answer is usually the word's most common dictionary definition, which often doesn't fit the specific context.","diff":"medium"},
      {"q":"How should you approach AP Lang free-response questions to maximize scores?","ex":"Think about time management and essay structure.","a":"Read the prompt carefully to identify the specific task. For rhetorical analysis: don't just identify devices — analyze HOW they work to achieve purpose. For argument: develop a clear, specific thesis; use evidence from the text/sources; include commentary explaining how evidence supports your claim. Manage time: ~40 minutes per essay.","diff":"medium"}
    ]}
  ],
  # Unit 2 - AP Lang: Writing
  [
    {"title":"Rhetorical Analysis Essay","problems":[
      {"q":"What is the key difference between a summary and a rhetorical analysis?","ex":"Think about what each focuses on.","a":"A summary describes what a text says (content/argument). A rhetorical analysis examines HOW a text achieves its purpose — analyzing the author's strategies, devices, and appeals and evaluating their effectiveness on the intended audience.","diff":"easy"},
      {"q":"Write a strong thesis for a rhetorical analysis of a speech arguing for environmental protection.","ex":"Identify the author's purpose and key strategies used.","a":"Example: 'Through vivid imagery of ecological destruction, an appeal to shared moral responsibility, and an urgent tone that escalates throughout, [Author] persuades [audience] that environmental inaction represents a moral failure with irreversible consequences.'","diff":"medium"},
      {"q":"What should body paragraphs in a rhetorical analysis contain?","ex":"Remember: don't just identify devices — explain effect.","a":"Each body paragraph should: (1) identify a specific rhetorical strategy or device; (2) provide textual evidence (quote or paraphrase); (3) analyze how that strategy functions and WHY the author chose it; (4) connect the analysis back to the author's overall purpose or effect on the audience.","diff":"medium"},
      {"q":"What is a common error students make in rhetorical analysis essays?","ex":"Think about what's missing when students just 'name-drop' devices.","a":"'Listing without analyzing' — identifying devices (e.g., 'the author uses pathos') without explaining the specific effect on the specific audience or how it serves the author's purpose. Analysis requires explaining the 'so what' — why that choice matters in context.","diff":"easy"}
    ]},
    {"title":"Argumentative Essay","problems":[
      {"q":"What makes a strong argumentative thesis different from a weak one?","ex":"Consider specificity, debatability, and reasoning.","a":"Strong thesis: makes a specific, debatable claim with clear reasoning (e.g., 'The US should adopt ranked-choice voting because it reduces political polarization and gives voters more meaningful choices.'). Weak: too vague ('Voting systems are important'), a fact not open to debate, or a statement of personal preference without reasoning.","diff":"easy"},
      {"q":"How should you incorporate a counterargument into an argumentative essay effectively?","ex":"Think about placement and treatment.","a":"Present the counterargument fairly and accurately (don't create a straw man), then refute it with evidence or reasoning that shows your position is stronger. Placement: often works best in the middle of the essay after establishing your own argument. This demonstrates intellectual rigor and strengthens credibility.","diff":"medium"},
      {"q":"What is the role of evidence commentary in an argumentative essay?","ex":"Why can't evidence speak for itself?","a":"Commentary explains how evidence supports your claim — it's the analysis that connects the quote/statistic to your argument. Without commentary, the reader must draw the connection themselves and may not reach the same conclusion. Commentary also shows your reasoning process, which is what the essay is actually being graded on.","diff":"medium"},
      {"q":"Your essay argues that social media harms teen mental health. Evaluate whether this evidence is appropriate: 'My friend has been anxious since she got Instagram.'","ex":"Consider the type of evidence and its limitations.","a":"Weak evidence — it is purely anecdotal (one individual case). It cannot be generalized to establish a causal relationship between social media and mental health at a population level. Stronger evidence would be large-scale longitudinal studies with control groups (e.g., 'A 2023 meta-analysis of 42 studies found a significant correlation between daily social media use >3 hours and clinical anxiety in adolescents').","diff":"medium"}
    ]},
    {"title":"Synthesis Essay","problems":[
      {"q":"What is the essential task in an AP Lang synthesis essay and how does it differ from a research essay?","ex":"Think about what sources are for.","a":"A synthesis essay requires you to develop your own argument and support it by drawing on provided sources — not to summarize them. Sources are evidence for YOUR thesis, not the thesis themselves. Unlike a research essay where you choose sources, in AP Lang all sources are provided and you must use at least 3.","diff":"easy"},
      {"q":"What does it mean to 'cite a source without quote-dropping'?","ex":"What must surround a quotation?","a":"Quote-dropping: inserting a quote without context or analysis. Proper citation: introduce the source ('According to Source B, a 2020 study found...'), provide the quote or paraphrase, then explain how it supports your specific argument. The quote should never begin or end a paragraph.","diff":"medium"},
      {"q":"How should you handle two sources that seem to contradict each other?","ex":"Can both sources still be used in the same argument?","a":"Contradiction between sources can be handled in several ways: acknowledge the complexity and explain which source is more credible/applicable to your specific claim; use both to illustrate a nuanced debate; or use each source to support different aspects of your argument. Never simply ignore a contradicting source you've cited.","diff":"hard"},
      {"q":"What is the difference between paraphrasing and plagiarizing a source?","ex":"Consider attribution and transformation.","a":"Paraphrasing: restating the source's idea in your own words with citation (still requires a source reference). Plagiarism: using someone's words or ideas without attribution, or copying a source's exact phrasing even with minor word changes. In AP exams, always indicate which source you're using (e.g., 'Source C argues...').","diff":"easy"}
    ]},
    {"title":"Thesis Construction","problems":[
      {"q":"A strong thesis should answer what four questions?","ex":"Think about what information a thesis must convey.","a":"(1) What is your claim/position? (2) Why is it true (what reasoning)? (3) What is at stake (significance)? (4) How does your argument unfold (roadmap — optional for AP)? A strong thesis is debatable, specific, and arguable.","diff":"medium"},
      {"q":"Revise this weak thesis: 'Technology has changed society in many ways.'","ex":"Make it specific, arguable, and reasoned.","a":"Revised: 'While technological innovation has increased access to information and global connectivity, its accelerated displacement of middle-skill jobs without adequate retraining infrastructure threatens to widen economic inequality rather than lift all workers.'","diff":"medium"},
      {"q":"What is a 'so what' thesis and why does it matter?","ex":"Think about what distinguishes a sophisticated thesis.","a":"A 'so what' thesis makes clear why your argument matters — what's at stake, what implications follow, or what needs to change. Example: instead of 'Social media harms teens,' a 'so what' thesis says 'Social media's harm to teen mental health demands immediate policy intervention because the psychological damage is measurable, accelerating, and disproportionately affects girls.' The stakes are explicit.","diff":"hard"},
      {"q":"Can a thesis be a question? Explain.","ex":"Think about the function of a thesis.","a":"Generally no. A thesis is a claim — a position you will defend. A question opens inquiry rather than asserting a defensible position. However, a question can sometimes introduce the essay, with the thesis following it as the answer. In AP free-response, your thesis must be a clear, argumentative statement, not a question.","diff":"easy"}
    ]},
    {"title":"Evidence Integration and Commentary","problems":[
      {"q":"What are three ways to incorporate textual evidence?","ex":"Think about direct quotes, paraphrase, and summary.","a":"(1) Direct quotation: exact words in quotation marks with attribution. (2) Paraphrase: restate the idea in your own words (still cite the source). (3) Summary: condense a longer passage's main point. Each requires attribution. Direct quotes should be used for memorable wording or precise claims; paraphrase for explaining complex ideas.","diff":"easy"},
      {"q":"What is the 'sandwich' method for incorporating evidence?","ex":"Think about what goes before and after the quote.","a":"Introduce-Quote-Analyze: (1) Introduce the source/context; (2) provide the quote or evidence; (3) analyze how it supports your specific claim. The analysis (bottom bun) is the most critical part and is often the shortest in student writing — it should be longer than the quote.","diff":"easy"},
      {"q":"Your evidence is: 'Test scores increased 12% after the intervention (Source D).' Write a commentary sentence that connects it to the claim that tutoring programs are effective.","ex":"Explain what the statistic means for your argument.","a":"'This 12% improvement demonstrates that targeted tutoring interventions produce measurable, statistically meaningful gains — the kind of quantifiable evidence that distinguishes effective programs from those with only anecdotal support.'","diff":"medium"},
      {"q":"Why should commentary be at least as long as the quoted evidence?","ex":"Think about what graders are evaluating.","a":"The essay is evaluated on your reasoning, not the source's. A long quote with minimal commentary suggests you cannot analyze — you're letting the source do your thinking. Commentary is where you demonstrate understanding of how evidence functions within an argument, which is the core AP skill being assessed.","diff":"medium"}
    ]},
    {"title":"Revision and Style Editing","problems":[
      {"q":"What are three common sentence-level errors that weaken AP writing?","ex":"Think about wordy phrases, unclear pronouns, weak verbs.","a":"(1) Wordiness: 'Due to the fact that' → 'Because'; 'in order to' → 'to'. (2) Vague pronoun reference: 'This shows that...' (what does 'this' refer to?). (3) Weak verb choices: 'is important' → 'demonstrates,' 'reveals,' 'challenges.' Eliminating these makes prose more precise and authoritative.","diff":"medium"},
      {"q":"Revise this wordy sentence: 'In my personal opinion, it seems like it might be possible that the policy could potentially have negative effects.'","ex":"Remove hedging and redundancy.","a":"'The policy may have negative effects.' Or stronger: 'The policy will harm [specific group] by [specific mechanism].' Every word should earn its place.","diff":"easy"},
      {"q":"What is passive voice and when is it rhetorically appropriate to use it?","ex":"Consider when the agent of action should be emphasized.","a":"Passive voice: the subject receives the action ('Mistakes were made'). Usually weaker than active. Appropriate when: the agent is unknown ('The artifact was discovered in 1922'), the agent is unimportant, or when deliberately avoiding assigning blame (common in diplomatic or scientific writing). In AP essays, prefer active voice.","diff":"medium"},
      {"q":"How does varying sentence structure improve argumentative writing?","ex":"Think about rhythm, emphasis, and engagement.","a":"Monotonous sentence structure (all similar length/type) makes prose feel flat and makes it hard to emphasize key claims. Varying structure creates rhythm, places emphasis strategically (short sentences after long ones hit harder), and demonstrates syntactic sophistication. Mix simple declarative statements with longer, subordinate-clause sentences to control pacing.","diff":"medium"}
    ]},
    {"title":"Timed Writing Strategies","problems":[
      {"q":"How should you allocate time across three AP Lang free-response questions in 2 hours 15 minutes?","ex":"Consider reading, planning, and writing time.","a":"Approximately: Q1 (Synthesis) — 15 min reading sources + 40 min writing. Q2 (Rhetorical Analysis) — 5 min reading + 40 min writing. Q3 (Argument) — 40 min writing. Reserve 5 min for review. Adapt based on your strengths.","diff":"easy"},
      {"q":"What is the minimum time you should spend planning before writing an AP essay?","ex":"Consider what planning prevents.","a":"At least 5–7 minutes. Planning should include: reading the prompt carefully, identifying the task, drafting a thesis, and outlining 2–3 body paragraph topics with evidence. Planning prevents structural problems that are much harder to fix mid-essay — disorganized essays rarely earn top scores.","diff":"easy"},
      {"q":"If you run out of time, which part of the essay is most important to complete?","ex":"Think about where most points are assigned.","a":"The thesis is most critical — essays without a defensible thesis cannot earn a top score. If pressed for time, ensure your thesis and at least one fully developed body paragraph are complete. A strong introduction with a sophisticated thesis plus one well-analyzed paragraph outscores a complete but superficial essay.","diff":"medium"},
      {"q":"How should you approach a synthesis prompt if you disagree with all the sources?","ex":"You still need to write an argument using the sources.","a":"You don't have to agree with the sources — you need to use them as evidence for YOUR argument. You can use sources you disagree with to represent the opposing view (then refute them), or find aspects of each source that support a nuanced position. The prompt tests your ability to build an argument from evidence, not your personal agreement with that evidence.","diff":"hard"}
    ]}
  ],
  # Unit 3 - AP Literature
  [
    {"title":"Poetry: Form and Meter","problems":[
      {"q":"Identify the meter: 'Shall I compare thee to a summer's day?' Scan the line.","ex":"Mark stressed (/) and unstressed (u) syllables.","a":"u / | u / | u / | u / | u /  — five iambic feet = iambic pentameter (the most common meter in English poetry and drama).","diff":"medium"},
      {"q":"What is the difference between a Petrarchan and Shakespearean sonnet in structure and typical volta placement?","ex":"Count lines and rhyme scheme.","a":"Petrarchan (Italian): ABBAABBA CDECDE (octave + sestet); volta typically at line 9. Shakespearean (English): ABAB CDCD EFEF GG (three quatrains + couplet); volta often at line 13 (final couplet).","diff":"easy"},
      {"q":"What is enjambment and what effect does it create compared to an end-stopped line?","ex":"Consider how meaning flows across line breaks.","a":"Enjambment: sentence or phrase continues beyond the line break without punctuation. Creates momentum, mimics natural speech, can create double meanings at the break. End-stopped lines pause at the end, creating finality and emphasis. Skilled poets vary both for rhythmic and semantic effect.","diff":"medium"},
      {"q":"Identify the poetic form: a 3-line poem, syllable pattern 5-7-5, about nature or a moment.","ex":"Japanese poetic tradition.","a":"Haiku — a Japanese form, typically 17 syllables in three lines (5-7-5), traditionally focusing on a moment in nature with a seasonal reference (kigo) and often a 'cutting word' (kireji) that creates a juxtaposition or pause.","diff":"easy"}
    ]},
    {"title":"Poetry: Figurative Language and Imagery","problems":[
      {"q":"Analyze the metaphor: 'Hope is the thing with feathers / That perches in the soul' (Dickinson). What does each vehicle suggest about the tenor?","ex":"Vehicle = the image; tenor = what is described.","a":"Hope (tenor) is compared to a bird (vehicle). 'Feathers' suggests lightness, delicacy, and lift. 'Perches in the soul' suggests hope is always present but quiet, resting inside the person rather than external. The comparison implies hope is natural, persistent, and fundamentally human.","diff":"medium"},
      {"q":"Distinguish between a simile and a metaphor. Which is typically more forceful and why?","ex":"Consider what comparison each makes.","a":"Simile: explicit comparison using 'like' or 'as' ('My love is like a red rose'). Metaphor: direct equation ('My love is a red rose'). Metaphors are generally more forceful because they assert identity rather than similarity — they collapse the distance between the compared things, making the comparison more immersive.","diff":"easy"},
      {"q":"Identify the type of imagery and its effect in: 'The fog comes on little cat feet' (Sandburg).","ex":"Which sense does it engage? What other devices are present?","a":"Visual and tactile imagery, personification (fog as cat), and metaphor. The effect: fog's quiet, stealthy, unhurried arrival is rendered concrete and gentle — entirely unlike its typical representation as ominous or threatening. The cat comparison makes the fog feel domesticated, almost affectionate.","diff":"medium"},
      {"q":"What is synesthesia in poetry? Give an example.","ex":"Think about mixing sensory impressions.","a":"Synesthesia: describing one sense using the language of another (e.g., 'the loud color of her dress,' 'a bitter cold that tasted of iron'). It creates unusual, vivid sensory combinations that draw attention to the experience and suggest how senses blend in heightened emotional states.","diff":"hard"}
    ]},
    {"title":"Fiction: Narrative Voice and Point of View","problems":[
      {"q":"Compare first-person and third-person limited point of view. What does each gain and sacrifice?","ex":"Consider intimacy, reliability, and scope.","a":"First-person: intimate, immediate, creates strong character voice; limited to narrator's knowledge; potentially unreliable. Third-person limited: follows one character's perspective but uses 'he/she/they'; slightly more distance but more flexibility; can maintain irony between narrator's language and character's perception.","diff":"medium"},
      {"q":"What is an unreliable narrator? Cite two signals that might indicate unreliability.","ex":"Think about what makes a narrator's account suspect.","a":"An unreliable narrator's account cannot be fully trusted. Signals: (1) Contradictions between what the narrator claims and what events suggest ('I am perfectly sane,' but their descriptions reveal paranoia). (2) Other characters' reactions contradict the narrator's self-presentation. Also: mental illness, youth/inexperience, strong bias, or stated self-interest.","diff":"medium"},
      {"q":"What is free indirect discourse? Give an example from a typical literary context.","ex":"It blends third-person narration with a character's thoughts.","a":"Free indirect discourse presents a character's thoughts/speech in the third-person narrator's voice without quotation marks or 'he thought.' Example: 'She turned from the window. What did he want from her, anyway? She would not give him the satisfaction.' The questions are her thoughts, not the narrator's — but they appear without 'she thought.'","diff":"hard"},
      {"q":"How does an omniscient narrator differ from an unreliable narrator in terms of authority?","ex":"Consider what each narrator knows and how trustworthy they are.","a":"An omniscient narrator has access to all characters' thoughts and the 'truth' of events — their authority is total. An unreliable narrator has limited, biased, or distorted access to truth — their authority is compromised. Reading an unreliable narrator requires reading against the text, inferring what 'really' happened.","diff":"medium"}
    ]},
    {"title":"Fiction: Character, Conflict, and Theme","problems":[
      {"q":"What is a foil character and how does it function in literature?","ex":"Think about contrasting traits.","a":"A foil is a character whose contrasting traits highlight the qualities of another (usually the protagonist). Example: Laertes foils Hamlet — both have murdered fathers, but Laertes acts decisively while Hamlet deliberates, emphasizing Hamlet's paralysis. Foils clarify characterization through contrast rather than direct description.","diff":"easy"},
      {"q":"Distinguish between internal and external conflict. Can one character face both?","ex":"Think about the sources of conflict.","a":"External conflict: character vs. another character, nature, society, or fate — an obstacle in the world. Internal conflict: character vs. themselves — competing desires, moral dilemmas, psychological struggle. Yes, characters frequently face both simultaneously — Hamlet's external conflict (revenge his father) is intertwined with internal conflict (his philosophical paralysis about action).","diff":"easy"},
      {"q":"How is theme different from subject or topic?","ex":"Consider the level of abstraction.","a":"Subject/topic: what the work is about on a surface level ('loneliness,' 'war'). Theme: a complete statement or insight about that topic that emerges from the work's events and characterization. Example: topic = 'war'; theme = 'War dehumanizes both the victor and the vanquished' (All Quiet on the Western Front).","diff":"medium"},
      {"q":"What is a dynamic vs. static character? Which is more common in literary fiction and why?","ex":"Think about character development.","a":"Dynamic: changes significantly through the story (learns, grows, regresses). Static: remains essentially unchanged. Literary fiction tends to favor dynamic protagonists — the arc of change is often the story's heart. However, well-crafted static characters can powerfully embody a theme or serve as a foil to a dynamic protagonist.","diff":"medium"}
    ]},
    {"title":"Drama: Structure and Dramatic Devices","problems":[
      {"q":"Explain dramatic irony and why it is particularly powerful in tragedy.","ex":"Consider the audience's position vs. the character's.","a":"Dramatic irony: the audience knows something crucial that a character does not. In tragedy, this creates sustained dread — we watch characters move toward doom they cannot see. In Oedipus Rex, the audience knows Oedipus killed his father and married his mother before he does, making each step toward discovery unbearable.","diff":"medium"},
      {"q":"What is Aristotle's concept of catharsis and why is it central to tragedy?","ex":"Think about the emotional experience of watching tragedy.","a":"Catharsis: the emotional purging (of pity and fear) that Aristotle argued tragedy produces in the audience. Watching a great character fall through a combination of fate and hamartia (fatal flaw) evokes these emotions and then releases them — leaving the audience with a sense of order, justice, and emotional clarity rather than simple sadness.","diff":"hard"},
      {"q":"How does the aside function differently from a soliloquy?","ex":"Consider who is addressed and when each is used.","a":"Soliloquy: a character speaks alone onstage, revealing inner thoughts to the audience (no other character present, or others don't hear). Aside: a brief remark directed to the audience while other characters are present but cannot hear — often ironic or conspiratorial. Soliloquies are extended; asides are brief.","diff":"medium"},
      {"q":"What is a hamartia and how does it differ from a simple character flaw?","ex":"Consider its role in the tragic arc.","a":"Hamartia (Greek: 'error of judgment'): the fatal flaw or mistake that leads to a tragic hero's downfall. It differs from a simple character flaw in that it is specifically connected to the hero's greatness — it is often an excess of the same quality that makes them exceptional (Oedipus's relentless pursuit of truth; Macbeth's ambition). Tragedy requires this flaw to be internally connected to the protagonist's downfall.","diff":"hard"}
    ]},
    {"title":"Open-Ended Literary Essay","problems":[
      {"q":"What distinguishes a top-scoring AP Literature open-ended essay from an average one?","ex":"Think about thesis, evidence, and analysis depth.","a":"Top scores: sophisticated, specific thesis that addresses the prompt's complexity; evidence drawn precisely from the text; analysis explains HOW literary techniques create meaning; clear connection between technique and theme; avoids plot summary. Average: general thesis; relies on plot summary; identifies devices without explaining their effect; generic statements about 'the author's message.'","diff":"medium"},
      {"q":"What does it mean to 'read a work as a whole' in an open-ended essay?","ex":"Think about how individual passages connect to larger meaning.","a":"Analyzing a work as a whole means connecting your chosen passage or technique to the text's larger themes, structure, and meaning — not analyzing it in isolation. Every specific observation should be tied back to what it reveals about the work's central concerns. A character detail should illuminate theme; a structural choice should reflect meaning.","diff":"medium"},
      {"q":"Why is it risky to write about very popular or commonly chosen texts on the AP Lit exam?","ex":"Think about how your essay is evaluated.","a":"Popular texts (Hamlet, The Great Gatsby) are written about by many students, and graders quickly notice formulaic or generic analysis. These essays are compared against many others on the same text. Less common texts or sophisticated readings of common texts stand out. More importantly, students who choose familiar texts often rely on what they remember rather than analyzing the specific prompt.","diff":"easy"},
      {"q":"A prompt asks you to analyze how a character's relationship with a symbol reveals theme. Outline a response for Fitzgerald's The Great Gatsby using the green light.","ex":"Connect symbol → character → theme.","a":"The green light across the bay symbolizes Gatsby's yearning for Daisy and, by extension, the American Dream. Gatsby reaches toward it — literally and metaphorically — positioning it as perpetually attainable yet never achieved. Fitzgerald uses this to reveal the theme that the American Dream is built on illusion: its value lies in the longing itself; possession would destroy the fantasy. Gatsby's death — after finally meeting Daisy — confirms that the dream collapses when confronted with reality.","diff":"hard"}
    ]},
    {"title":"Thematic Analysis Across Major Works","problems":[
      {"q":"How does the theme of social class function differently in Pride and Prejudice vs. The Great Gatsby?","ex":"Consider each novel's historical context and resolution.","a":"In Pride and Prejudice (Regency England), class is rigid but marriage can bridge it — Elizabeth's wit and virtue ultimately allow her to transcend her status. In Gatsby (1920s America), class is more fluid in appearance but more ruthless in practice — Gatsby reinvents himself but is ultimately destroyed by 'old money' snobbery, suggesting the American Dream is a myth for those not born into privilege.","diff":"hard"},
      {"q":"Compare how Orwell's 1984 and Huxley's Brave New World imagine dystopian control.","ex":"Think about fear vs. pleasure as mechanisms of control.","a":"Orwell's 1984: control through fear, surveillance (Big Brother), pain, and the destruction of truth (doublethink). Citizens are oppressed by force. Huxley's Brave New World: control through pleasure, conditioning, and soma (a happiness drug). Citizens are so pacified by gratification they don't resist. Both warn against totalitarianism but diagnose different dangers — brutality vs. comfortable complacency.","diff":"hard"},
      {"q":"What does it mean for a text to be 'morally ambiguous' and why do literary authors often prefer this to clear moral lessons?","ex":"Think about what realism and complexity require.","a":"Moral ambiguity means the text resists easy categorization of characters or actions as simply good or evil — it presents ethical complexity where reasonable people disagree. Authors prefer this because it mirrors reality, invites readers to engage actively rather than passively receive a lesson, and creates more lasting resonance. A purely didactic text tells the reader what to think; an ambiguous one trusts them to think for themselves.","diff":"hard"},
      {"q":"How does the setting of To Kill a Mockingbird function beyond physical backdrop?","ex":"Think about time, place, and what they represent symbolically.","a":"Maycomb, Alabama, in the 1930s is not just a setting — it embodies institutional racism, small-town myopia, and the social pressures that distort justice. The heat, the courthouse, the Radley house, and the town's geography all serve as physical manifestations of the novel's themes. Scout's gradual understanding of the town mirrors the reader's education in how social systems perpetuate injustice even among 'good' people.","diff":"hard"}
    ]}
  ]
]
