"""AP Arts: 5 units matching curriculum"""

def P(q,ex,a,diff): return {"q":q,"ex":ex,"a":a,"diff":diff}
def T(title,problems): return {"title":title,"problems":problems}

AP_ARTS = [
  # Unit 1 — AP Art History
  [
    T("Ancient Mediterranean",[
      P("What are the key characteristics of ancient Egyptian art and why did they persist for 3,000 years?","Think canon, frontalism, and religious function.","Egyptian art followed strict conventions: composite view (head and legs in profile, torso frontal) — shows all body parts clearly regardless of naturalism; hierarchical scale (size = importance — pharaoh larger than subjects); conceptual representation (what is known, not what is seen). Conventions persisted because art served religious and political functions (commemorate, make eternal) rather than aesthetic pleasure — naturalism would undermine these functions. Canon of proportions: grid system ensures standard proportions across all representations of the human figure.","medium"),
      P("How did Greek sculpture evolve from Archaic to Classical to Hellenistic?","Think stylistic progression and historical context.","Archaic (600–480 BCE): kouroi — rigid, frontal, formulaic smile, Egyptian influence. Classical (480–323 BCE): contrapposto stance (weight shift creates natural pose), idealized beauty, harmony and balance (Polykleitos's Doryphoros; Parthenon sculpture). Hellenistic (323–31 BCE): greater emotionalism, movement, drama, suffering (Laocoön, Nike of Samothrace), wide range of subjects including old age and childhood. Reflects historical context: Archaic — city-states developing; Classical — Athens' golden age, confidence; Hellenistic — Alexander's empire, cosmopolitan, diverse influences.","hard"),
      P("What is the significance of the Parthenon as an architectural and cultural monument?","Think Doric order, iconographic program, and political meaning.","Parthenon (Athens, 447–432 BCE): Doric temple dedicated to Athena Parthenos. Architecture: refined Doric order with optical refinements (entasis on columns, subtle curvature of stylobate) — counteract visual distortion and create feeling of perfection. Iconographic program: metopes (Gigantomachy, Amazonomachy, Centauromachy, Trojan War — Greeks vs. forces of chaos), frieze (Panathenaic procession — all Athenians participate, unusually civic for a temple), pediments (birth of Athena, contest with Poseidon). Political meaning: Pericles' monument to Athenian greatness, funded partly by tribute from allies — imperialism expressed as piety.","hard"),
      P("What is the function of the Great Pyramids and how do they reflect Egyptian worldview?","Think afterlife beliefs and royal power.","Great Pyramids at Giza (c. 2550–2490 BCE): mortuary complexes for pharaohs Khufu, Khafre, Menkaure. Function: eternal home for pharaoh's ka (life force); ensure successful afterlife → guarantee of cosmic order on earth. Materials: millions of limestone blocks, granite inner chambers, originally smooth white Tura limestone casing. Scale communicates: pharaoh's divine status; absolute power; eternal duration. Sphinx: guardian of Khafre's complex; human head (pharaoh) on lion body (power). Complex includes: mortuary temple, valley temple, causeway — processional ritual architecture, not just tomb.","medium"),
      P("How did Roman art adapt Greek traditions for Roman purposes?","Think eclecticism, verism, and political propaganda.","Roman art: eclecticism — combined Greek forms with Etruscan traditions and local innovation. Key Roman contributions: (1) Veristic portraiture — realistic, unflattering likenesses of patrician faces (ancestors) — communicated experience, virtue, moral authority (contrast with Greek idealization); (2) Historical relief sculpture — continuous narrative of specific events (Column of Trajan — 200 scenes spiraling upward); (3) Architecture: concrete (opus caementicium) enabled large interior spaces (Pantheon's dome). Function: political propaganda, commemorate military victories, demonstrate Roman power. Augustus used art systematically to legitimize rule and define Roman identity.","hard"),
      P("What characterizes Byzantine art and how did it serve the Church?","Think gold, hieratic scale, and theological function.","Byzantine art (330–1453 CE): formal, flat, hierarchical — rejected Classical naturalism for theological clarity. Key features: gold backgrounds (divine light, not earthly space); hieratic scale (Christ/Virgin larger than saints, who are larger than humans); frontal poses (direct engagement with viewer); elongated proportions; lack of shadow (non-physical realm). Icons: images of sacred figures used in devotion — iconography strictly prescribed. Iconoclasm controversy (726–843): debate over whether images were idolatry → icons eventually vindicated as 'windows to the sacred.' Function: not to depict world but to make visible the divine — art as theology.","medium"),
      P("What is the Laocoön and why was it significant to later European art?","Think Hellenistic drama and Renaissance rediscovery.","Laocoön and His Sons (c. 200–50 BCE, Roman copy of Greek original): marble sculpture group; Trojan priest Laocoön and sons attacked by sea serpents for warning about Trojan Horse. Characteristics: extreme emotionalism (anguished expressions), writhing movement, complex interlocking forms, physical suffering and struggle. Rediscovered in Rome (1506) in presence of Michelangelo → profound influence: confirmed for Renaissance artists that Greek art depicted extreme emotion and dynamic movement (correcting earlier view that it was serene). Winckelmann later argued it showed 'noble simplicity and quiet grandeur' — influential misreading that shaped Neoclassicism.","hard"),
      P("How did the function and design of Greek temples differ from Egyptian temples?","Think civic vs. priestly access.","Greek temples: exterior is the sacred space — designed to be seen from outside, especially the statue within; priests and aristocrats enter but ordinary worshippers outside in temenos (sacred precinct). Design: post-and-lintel construction; columns as primary aesthetic feature; sculptural program on exterior (metopes, frieze, pediments). Egyptian temples: processional interior — increasingly restricted spaces as you approach sanctuary (only pharaoh and priests enter innermost). Design: massive stone walls (permanence), hypostyle halls with forest of columns blocking light, sanctuary in deepest darkness. Greek: democratic public spectacle; Egyptian: hierarchical restricted access.","hard"),
    ]),
    T("Medieval and Islamic Art",[
      P("What is illuminated manuscript and what role did monasteries play?","Think medieval book culture.","Illuminated manuscripts: hand-lettered books with decorative elements — gold leaf, silver, vivid pigments — illuminating (lighting up) the text. Produced in monastery scriptoria — monks (and later lay professionals) copied and decorated sacred texts (Bibles, Psalters, Books of Hours). Lindisfarne Gospels (c. 715–20): interlace patterns, zoomorphic forms, Insular/Hiberno-Saxon style. Book of Kells (c. 800): extraordinary complexity. Function: sacred text given visual glory to honor God; portable objects of devotion; preserved ancient knowledge. Universities and cities later created commercial book production.","medium"),
      P("What are the key features of Gothic architecture?","Think structural innovation and spiritual purpose.","Gothic architecture (12th–15th century): (1) Pointed arch — distributes weight more efficiently than rounded Romanesque arch; (2) Ribbed vault — directs weight to specific points (piers); (3) Flying buttress — external arched support carries thrust outward, frees walls from structural burden. Result: walls can be thin, filled with stained glass — light floods interior. Spiritual symbolism: verticality (aspiration toward heaven), light (God as divine light — Abbot Suger). Chartres, Notre-Dame, Salisbury. Scale: cathedrals could take centuries to build — community commitment. Stained glass windows: visual Bible for largely illiterate congregations.","hard"),
      P("What are the key features of Islamic art and why does it avoid figural representation?","Think geometric, calligraphic, and arabesque.","Islamic art: (1) Geometric patterns — complex, infinitely extendable interlace and star patterns; symbolize infinite nature of Allah; (2) Calligraphy — the highest art form; Arabic script as sacred decoration (Quran cannot be translated — Arabic is sacred language); (3) Arabesque — flowing plant-based ornament; (4) Limited figural representation in religious contexts — hadith tradition discourages depicting living beings (only God creates life; images could become idols). Religious architecture: mosque — qibla wall with mihrab facing Mecca; minaret; courtyard with fountain for ritual washing. Figurative art exists in secular contexts (Persian manuscript painting).","medium"),
      P("What is the significance of the Hagia Sophia?","Think architectural innovation and cultural meaning.","Hagia Sophia (Constantinople/Istanbul, 532–37 CE): built by Justinian as greatest Christian church. Innovation: massive dome on pendentives (spherical triangles allowing circular dome to rest on square base) — solution to dome-over-square problem. 40 windows at base of dome create illusion it floats on light. Scale: 180 feet high, 102-foot diameter dome — largest for 1,000 years. Cultural history: Byzantine church (until 1453) → Ottoman mosque (columns added, mosaics plastered over) → secular museum (1934) → mosque again (2020). Represents intersection of Christian, Byzantine, Islamic, and modern Turkish identity.","hard"),
    ]),
    T("Renaissance and Baroque",[
      P("What are the key characteristics of Italian Renaissance art?","Think humanism, perspective, and classical revival.","Italian Renaissance (15th–16th century): (1) Linear perspective — Brunelleschi's discovery; single vanishing point creates illusion of 3D space; (2) Classical revival — study of Greek and Roman texts and sculpture; idealized human form; (3) Humanism — focus on human potential and earthly experience; (4) Patronage — Medici and Church commissioned work; (5) Scientific study of anatomy (Leonardo's dissections) → naturalistic representation. Key figures: Masaccio (perspective in fresco), Donatello (freestanding David), Botticelli (mythological subjects), Leonardo (sfumato, universal genius), Michelangelo (Sistine Chapel, David), Raphael (School of Athens).","medium"),
      P("How does the Baroque style differ from Renaissance ideals?","Think drama, movement, and Counter-Reformation context.","Baroque (17th century): reaction to Protestant Reformation — Catholic Church used dramatic art to inspire faith and demonstrate Counter-Reformation power. Characteristics: (1) Dramatic use of light and shadow (chiaroscuro/tenebrism — Caravaggio); (2) Dynamic movement, diagonal compositions vs. Renaissance stability; (3) Emotional intensity and immediacy; (4) Engagement of viewer (Bernini's Ecstasy of St. Teresa); (5) Illusionistic ceiling paintings (trompe l'oeil). Bernini: unified architecture, sculpture, and painting in theatrical ensembles. Rembrandt: Baroque in northern Protestant context — psychological portraits, light from darkness, ordinary subjects treated with dignity.","hard"),
      P("What is the significance of Leonardo da Vinci's Last Supper?","Think iconography and compositional innovation.","Last Supper (Milan, 1495–98): depicts moment Christ announces betrayal ('one of you will betray me'). Compositional innovation: Christ at center with window creating halo effect; 12 apostles divided into groups of 3 (symmetrical but dynamic); each apostle reacts distinctively to announcement — psychological characterization unprecedented. Leonardo used experimental technique (tempera and oil on gesso on plaster — not true fresco) → began deteriorating almost immediately. Iconographic choice: Leonardo emphasizes psychological drama over traditional Eucharistic moment. Judas also illuminated (not dark) — Christ's love extends even to betrayer.","medium"),
      P("What is Velázquez's Las Meninas and why is it considered groundbreaking?","Think self-reflexivity and the nature of representation.","Las Meninas (1656): Spanish royal court; Infanta Margarita surrounded by ladies-in-waiting, dwarfs, dog. Velázquez himself appears at left, painting — a large canvas is visible from behind. In the background mirror: reflection of King Philip IV and Queen Mariana — the subjects of Velázquez's canvas? Or us, the viewers, reflected? Viewer simultaneously sees the painting being made, the court watching it made, and the royals who may be posing. Groundbreaking: questions relationship between artist, subject, and viewer; makes the act of representation itself the subject; Foucault analyzed it as representing representation. Considered among greatest paintings for its conceptual complexity.","hard"),
      P("How does Michelangelo's Sistine Chapel ceiling communicate humanist and theological ideas?","Think iconographic program and formal achievement.","Sistine Chapel ceiling (1508–12): nine scenes from Genesis; Prophets and Sibyls (who foretold Christ); Ancestors of Christ. Central panels: Creation of the World, Adam, Eve; Fall and Expulsion; Noah. Creation of Adam: God reaches toward Adam; gap between fingers — divine life force transmitted but also the gap between human and divine. Technique: true fresco (plaster, pigment, water — bonds permanently); Michelangelo painted upside down on scaffolding. Humanist theology: human body (nude figures) as vehicle of divine expression; neoplatonic ideas — beauty of body reflects beauty of soul. Last Judgment (1534–41): added altar wall — more somber, post-sack-of-Rome world.","hard"),
    ]),
    T("19th and Early 20th Century Art",[
      P("What were the major art movements of the 19th century?","Think Neoclassicism, Romanticism, Realism, Impressionism.","Sequence: Neoclassicism (late 18th–early 19th c.): reaction to Baroque excess; classical antiquity models; moral seriousness (David's Death of Marat). Romanticism (early 19th c.): emotion, imagination, sublime nature, exotic subjects (Delacroix, Friedrich, Géricault). Realism (mid 19th c.): everyday working-class subjects without idealization (Courbet, Millet) — challenge to academic hierarchy of subjects. Impressionism (1860s–80s): capturing fleeting visual impression of light and color; plein air painting; loose brushwork; rejected by official Salon (exhibited independently). Post-Impressionism: Cézanne (structure, geometry), Seurat (pointillism), Gauguin (primitivism), Van Gogh (expressionistic).","medium"),
      P("What is Impressionism and how did it challenge academic tradition?","Think technique, subjects, and reception.","Impressionism (Monet, Renoir, Degas, Berthe Morisot, Pissarro): rejected academic conventions of smooth finish, historical/mythological subjects, studio composition. Instead: visible brushstrokes capturing transient effects of light; everyday modern life subjects (café, boat races, ballet); plein air (outdoors) painting to capture natural light. Reception: initially ridiculed — 'Impression, Sunrise' (Monet) mockingly named movement. Technique: complementary colors side by side (eye mixes them); short, loose brushstrokes; unmixed pigments. Legacy: opened art to subjective perception, personal vision, and rejection of academic hierarchy — essential step toward modernism.","medium"),
      P("What is Cubism and how did it transform Western art?","Think Picasso, Braque, and the representation of space.","Cubism (Picasso and Braque, 1907–14): rejected single-viewpoint perspective (dominant since Renaissance). Analytic Cubism: monochromatic, fragmented objects shown simultaneously from multiple viewpoints — deconstructs object into facets. Synthetic Cubism: collage (newspaper, wallpaper) introduced into painting — acknowledges the painting as object, not window. Les Demoiselles d'Avignon (Picasso, 1907): proto-Cubist; African mask influence; multiple viewpoints; violated beauty standards — profoundly shocking. Impact: ended Renaissance pictorial convention; opened art to abstraction; influenced architecture, design, literature; demonstrated art could engage with concept, not just appearance.","hard"),
      P("What is the significance of Vincent van Gogh's work?","Think expressive use of color and influence on Expressionism.","Van Gogh (1853–90): Post-Impressionist; used color and brushwork expressively rather than descriptively — yellow for spiritual radiance, blue for anxiety, swirling forms for energy. Key works: Starry Night (1889), Sunflowers, The Bedroom, Potato Eaters. Technique: thick impasto brushstrokes with visible texture; intense saturated color; emotional intensity. Reception: sold only one painting in his lifetime. Legacy: direct influence on German Expressionism (Die Brücke, Der Blaue Reiter) — color as emotional expression rather than description; opened path to abstraction. Letters to brother Theo reveal sophisticated artistic philosophy.","medium"),
    ]),
    T("Modern and Contemporary Art",[
      P("What is Abstract Expressionism and why was it significant?","Think New York School and gesture vs. field painting.","Abstract Expressionism (NYC, 1940s–50s): first major American art movement; became dominant post-WWII. Two strands: (1) Action painting (Pollock, de Kooning) — gesture, process, physical act of painting; Pollock's drip technique; 'the painting has a life of its own'; (2) Color Field (Rothko, Newman) — large areas of pure color; spiritual, contemplative; no representational content. Context: WWII trauma; existentialist philosophy; automatic drawing from Surrealism; jazz improvisation parallel. Cold War significance: US government promoted AbEx as evidence of American freedom vs. Soviet socialist realism (CIA funded international exhibitions).","hard"),
      P("What is Pop Art and what does it say about consumer culture?","Think Warhol, Lichtenstein, and mass media.","Pop Art (UK and US, 1950s–60s): used imagery from popular/commercial culture — advertising, comics, celebrities, consumer goods. Warhol: Campbell's Soup Cans, Marilyn Monroe silkscreens — repetition comments on mass production and celebrity commodification; silk-screen printing replicated commercial reproduction. Lichtenstein: comic strip panels enlarged and aestheticized. Ambivalence: celebrates or critiques consumer culture? Both — accepts commercial imagery as artistic subject while making it strange. Context: post-WWII American consumer boom; television; advertising as dominant visual language. Challenged high/low art distinction; broke abstract expressionism's seriousness.","medium"),
      P("What is Conceptual Art and how does it challenge traditional definitions of art?","Think Duchamp's legacy and art as idea.","Conceptual Art (1960s+): the concept or idea is the artwork — execution and object are secondary or unnecessary. Duchamp's readymades (Fountain, 1917 — urinal signed 'R. Mutt') anticipated: if artist designates something as art, it is art; raises questions about what makes something art (institutional theory of art). Conceptual examples: Sol LeWitt (instructions = work; execution by anyone); Joseph Kosuth (One and Three Chairs — chair, photograph, dictionary definition); Yoko Ono (instruction pieces). Challenges: art requires skill and beauty? Institutional critique: what role do galleries and museums play in determining what counts as art?","hard"),
      P("What is feminist art and how did it challenge the art historical canon?","Think Judy Chicago and institutional critique.","Feminist art (1970s+): challenged male-dominated art history and institutions. Linda Nochlin's essay 'Why Have There Been No Great Women Artists?' (1971): argued 'genius' narrative excluded women through systemic barriers, not lack of talent. Judy Chicago's The Dinner Party (1974–79): monumental collaborative installation — triangular table with 39 place settings for historical women; challenges hierarchies of craft vs. fine art. Guerrilla Girls: anonymous feminist art collective exposed gender and racial imbalance in museum collections and exhibitions. Miriam Schapiro: femmage — elevated domestic arts (quilts, fabrics) to fine art status. Consequence: expansion of art history to include previously marginalized artists and subjects.","hard"),
      P("What is site-specific art and why does location matter?","Think earthworks and installation art.","Site-specific art: created for particular location; cannot be relocated without fundamentally changing it. Earthworks/Land Art (1960s–70s): Smithson's Spiral Jetty (1970, Great Salt Lake) — 1,500-foot basalt spiral; scale beyond gallery; relationship to entropy and time; inaccessibility is part of the work. Cristo and Jeanne-Claude: temporary installations wrapping landmarks (Wrapped Reichstag) — temporary nature emphasizes impermanence; participatory process with communities. Installation art: transforms gallery space into environment (Louise Bourgeois, Yayoi Kusama's Infinity Rooms). Site-specificity: challenges mobility and commodification of art objects; integrates environmental, social, and political context.","hard"),
    ]),
    T("Global Contemporary Art",[
      P("How has globalization affected contemporary art?","Think biennials, diaspora artists, and global markets.","Global contemporary art: art world no longer centered exclusively in Western Europe and New York. Major biennials: Venice (oldest), São Paulo, Documenta (Kassel), Istanbul, Shanghai, Sydney — present international artists on equal platform. Diaspora artists: Yinka Shonibare (British-Nigerian), Kara Walker (US), El Anatsui (Ghanaian/international) — engage with colonial history, identity, migration. Global art market: major auction houses in Hong Kong; collectors in China, Middle East, India. Tensions: Western institutions still dominate art historical narrative; 'global' art can mean Western galleries showing selected non-Western artists; questions of authenticity, exoticism, and whose stories are told.","hard"),
      P("What is Indigenous art and how does it challenge Western art history?","Think ownership, appropriation, and living traditions.","Indigenous art: not merely 'primitive' or historical — living, evolving traditions. Aboriginal Australian art: dot painting (contemporary form developed 1970s in Papunya); Dreamtime cosmology; land rights. Maori ta moko (tattoo) and whakairo (carving). Northwest Coast Native American totem poles: family crests, clan histories, not 'primitive idols.' Challenges to Western art history: (1) Art history as discipline erased Indigenous contributions; (2) Museums hold stolen/colonial objects (repatriation debates); (3) Appropriation of Indigenous designs without permission or credit; (4) Indigenous art evaluated by Western aesthetic criteria that don't match its purposes. Self-determination: Indigenous artists controlling their own representation.","hard"),
    ]),
    T("Materials, Techniques, and Processes",[
      P("What is fresco and how does it differ from tempera and oil painting?","Think medium properties and history.","Fresco: pigment applied to wet plaster — bonds permanently as plaster dries; cannot easily be corrected; must work quickly; extremely durable (Sistine Chapel, Pompeii). Buon fresco (true fresco) vs. secco fresco (dry plaster — less durable). Tempera: pigment mixed with egg yolk; quick-drying; allows precise, fine brushwork; jewel-like colors; limited blending. Oil painting (developed 15th century in Flanders): pigment in linseed or walnut oil; dries slowly → allows blending, layering, glazing, correction; rich colors, depth; became dominant European technique. Each medium shapes what's possible — fresco favors large gestures; tempera favors fine detail; oil enables both.","medium"),
      P("What is printmaking and what are its major techniques?","Think reproduction and multiples.","Printmaking: art produced by transferring ink from matrix to paper/fabric — allows multiples (editions). Major techniques: (1) Relief printing (woodcut, linocut) — cut away areas that won't print; raised areas take ink; high contrast; bold lines (Dürer's woodcuts); (2) Intaglio (etching, engraving, aquatint) — incise lines into metal plate; ink in grooves; wiped clean; pressed onto paper; fine lines (Rembrandt's etchings); (3) Screen printing (silkscreen/serigraphy) — ink pushed through mesh screen; stencil blocks areas; Warhol's silkscreens; (4) Lithography — greasy image on flat stone; water repels oil, oil repels water; chemical process. Significance: democratized art distribution; multiples vs. unique objects.","medium"),
    ]),
    T("Global Prehistory and Early Culture",[
      P("What is the significance of cave paintings at Lascaux and Altamira?","Think earliest art and its purposes.","Cave paintings (c. 17,000–15,000 BCE, Lascaux; c. 15,000 BCE, Altamira): among oldest known art — images of horses, bison, aurochs, deer; some human handprints. Significance: demonstrate symbolic thinking; represent first known artistic tradition. Purpose (debated): hunting magic (sympathetic — depicting animals helps hunters); shamanic vision states; territorial markers; narrative/memory; aesthetic pleasure. Formal sophistication: artists exploited natural contours of cave wall to suggest volume; depicted movement; showed knowledge of animal anatomy. Deep in caves — not living space; deliberate access to darkness for ritual purposes?","medium"),
      P("What is the Venus of Willendorf and what does it suggest about prehistoric society?","Think prehistoric figurine and interpretation.","Venus of Willendorf (c. 28,000–25,000 BCE): small limestone figure (~4 inches); exaggerated breasts, hips, belly; no facial features; may have had red ochre paint. Found across broad geographic area suggests wide cultural network. Interpretations: fertility goddess/idol; self-portrait by pregnant woman; idealized female form from male gaze; carried talisman; representation of ancestral mother. No certain interpretation — we cannot know prehistoric intent. Significance: demonstrates that prehistoric humans created representational art; 'Venus' figurines found widely across Europe → shared cultural practices or trade networks.","medium"),
    ]),
  ],
  # Unit 2 — AP Music Theory
  [
    T("Pitch and Notation",[
      P("What are the elements of the staff, clefs, and how are pitches notated?","Think treble, bass, and ledger lines.","Staff: five horizontal lines and four spaces; pitches assigned to lines and spaces. Treble clef (G clef): curls around second line, marking G4; lines bottom to top: E-G-B-D-F ('Every Good Boy Does Fine'); spaces: F-A-C-E. Bass clef (F clef): dots bracket fourth line, marking F3; lines bottom to top: G-B-D-F-A ('Good Boys Do Fine Always'); spaces: A-C-E-G. Ledger lines: extend staff above/below for out-of-range pitches. Octave designations: C4 = middle C. Grand staff: treble and bass connected by brace.","easy"),
      P("What are intervals and how do you identify them?","Think number and quality.","Interval: distance between two pitches. Number: count lines and spaces from lower to upper note (include both notes). Quality: major, minor, perfect, augmented, diminished — depends on exact half-step count. Perfect intervals: unison (0), 4th (5 half-steps), 5th (7), octave (12). Major intervals: 2nd (2), 3rd (4), 6th (9), 7th (11). Minor: one half-step smaller than major. Diminished: one half-step smaller than minor/perfect. Augmented: one half-step larger than major/perfect. Consonant: unisons, 3rds, 5ths, 6ths, octaves. Dissonant: 2nds, 7ths, tritone (augmented 4th/diminished 5th).","medium"),
      P("How do major and minor scales differ structurally?","Think half-step and whole-step patterns.","Major scale: W-W-H-W-W-W-H (whole/half-step pattern). Always sounds 'bright,' 'stable,' 'happy.' Minor scales: Natural minor: W-H-W-W-H-W-W (same as major starting on 6th scale degree). Harmonic minor: raised 7th degree creates leading tone (V chord becomes major → stronger resolution). Melodic minor: raised 6th and 7th ascending; reverts to natural minor descending. Minor character: 'darker,' 'sadder' than major — flattened 3rd, 6th, 7th give different emotional quality. Circle of fifths: organizes all major and minor key signatures by number of sharps/flats.","medium"),
      P("What is the chromatic scale and what are enharmonic equivalents?","Think 12 half-steps and spelling.","Chromatic scale: all 12 half-steps within an octave — every adjacent black and white key on piano. Enharmonic equivalents: same pitch, different names — C# = Db, F# = Gb, G# = Ab, A# = Bb, D# = Eb. Context determines spelling: G major scale uses F# (not Gb); Db major scale uses Gb (not F#). Music theory uses correct spelling to reveal harmonic function. Accidentals: sharp (#) raises one half-step; flat (b) lowers one half-step; natural (♮) cancels previous accidental; double sharp (×) raises two half-steps; double flat (bb) lowers two half-steps.","medium"),
      P("What is the overtone series and why is it important?","Think acoustics and harmony.","Overtone series (harmonic series): when a note sounds, it produces the fundamental pitch plus a series of higher frequencies (overtones/harmonics) at progressively smaller intervals — octave, perfect 5th, perfect 4th, major 3rd, minor 3rd... Explains: why certain intervals sound consonant (they appear early in the overtone series — octaves, 5ths, 3rds); why major chord feels 'stable' (its pitches reflect the overtone series); orchestration (horns naturally produce overtone series). Acoustic foundation for Western harmony — consonance is not arbitrary cultural convention but reflects natural acoustic relationships.","hard"),
    ]),
    T("Rhythm and Meter",[
      P("What is the difference between simple and compound meter?","Think beat division.","Simple meter: each beat divides into two equal parts. Time signatures: 2/4 (duple simple), 3/4 (triple simple), 4/4 (quadruple simple) — top number = beats per measure; bottom number = note value = one beat. Compound meter: each beat divides into three equal parts. Time signatures: 6/8 (duple compound), 9/8 (triple compound), 12/8 (quadruple compound) — top number = number of eighth notes; actual beat = dotted quarter note. 6/8 feels like two beats (each a dotted quarter, divided into three eighths). Key distinction: in simple, 4/4 quarter note = one beat; in compound 6/8, dotted quarter = one beat.","medium"),
      P("What is syncopation and how is it used in music?","Think off-beat emphasis.","Syncopation: displacement of expected accent — emphasis falls on normally weak beats or weak parts of beats. Types: (1) Tie across the barline or beat; (2) Accent on weak beat; (3) Rest on strong beat. Examples: ragtime (Scott Joplin) — characteristic syncopated rhythmic patterns; jazz; funk; hip-hop. Effect: creates rhythmic tension, forward momentum, dance-ability, unexpected energy. Hemiola: rhythmic device where two measures of triple meter are momentarily perceived as three measures of duple — common in Baroque and Renaissance cadences.","medium"),
    ]),
    T("Harmony and Chord Progressions",[
      P("What are the primary triads and their functions in major keys?","Think I, IV, V and harmonic function.","Primary triads: Tonic (I): stable, goal of motion; Subdominant (IV): pre-dominant, moves toward V; Dominant (V): creates tension that resolves to I. Roman numerals indicate scale degree of root; upper case = major; lower case = minor. In major keys: I, IV, V are major; ii, iii, vi are minor; vii° is diminished. Harmonic function: tonic function (I, vi, iii — stable/resting); subdominant function (IV, ii — motion); dominant function (V, vii° — tension/pull toward tonic). Most tonal music follows patterns: I → IV → V → I or I → ii → V → I.","medium"),
      P("What is voice leading and why does it matter?","Think smooth melodic motion in harmonic progressions.","Voice leading: melodic motion of individual voices in a harmonic progression. Rules: (1) Contrary motion preferred (voices move in opposite directions); (2) Avoid parallel fifths and octaves (creates hollow sound, weakens independence); (3) Resolve tendency tones correctly (7th scale degree rises to tonic; 4th scale degree falls to 3rd); (4) Common tones held when possible; (5) Voice crossing avoided; (6) Avoid large leaps — prefer steps. Why it matters: good voice leading creates smooth, independent melodic lines in each voice; bad voice leading sounds choppy, creates unintended harmonic effects, loses contrapuntal independence.","hard"),
      P("What is the circle of fifths and how is it used?","Think key relationships and modulation.","Circle of fifths: visual diagram arranging all 12 major (and relative minor) keys by fifth relationships — each adjacent key shares all but one note; moving clockwise adds sharps (or removes flats); counterclockwise adds flats. Uses: (1) Remember key signatures (C=0, G=1♯, D=2♯, etc.); (2) Understand modulation paths (easiest modulations to adjacent keys); (3) Chord progressions frequently move by descending fifths (IV-VII-III-VI-II-V-I is a complete fifth cycle). Relative minors: each major key shares a key signature with a minor key a minor third below (C major / A minor).","medium"),
      P("What is a secondary dominant and how does it create harmonic color?","Think tonicization.","Secondary dominant: a major or dominant 7th chord built on a scale degree other than the dominant — temporarily tonicizes (creates brief sense of tonic for) a non-tonic chord. Notation: V/V (five of five), V/IV (five of four), etc. Example in C major: V/V = A major chord (A-C#-E) → creates pull to D/G chord. Effect: adds harmonic richness and color; momentarily brightens or darkens; creates surprises within the key. Tonicization: brief emphasis on non-tonic chord through its own dominant — not a full modulation but a momentary expansion of harmonic language.","hard"),
    ]),
    T("Form and Analysis",[
      P("What are the common musical forms in Western tonal music?","Think binary, ternary, sonata, rondo.","Binary form (AB): two sections, often repeated; each section moves between keys. Ternary form (ABA): three sections; A section returns after contrasting B section. Sonata form (exposition-development-recapitulation): most important form in Classical period; exposition introduces two contrasting themes in different keys; development manipulates these themes harmonically and motivically; recapitulation returns both themes in tonic. Rondo form (ABACADA...): recurring main theme alternates with contrasting episodes. Theme and variations: theme stated then transformed through variations in rhythm, harmony, melody, texture. 32-bar song form (AABA): standard in jazz standards and popular music.","medium"),
      P("How do you analyze a piece using Roman numeral chord analysis?","Think harmonic reduction.","Roman numeral analysis: identifies harmonic progression underlying a piece. Process: (1) Identify key (look at key signature and cadences); (2) Identify each chord (root, quality, inversion); (3) Assign Roman numeral based on position in key; (4) Note inversions (6 = first inversion, 6/4 = second inversion); (5) Note seventh chords (7 after Roman numeral); (6) Identify non-chord tones (passing tones, neighbor tones, suspensions, appoggiaturas). Goal: reveals harmonic logic beneath the surface — what is the tonal journey of the piece? Where does tension build and resolve?","hard"),
    ]),
    T("Counterpoint and Texture",[
      P("What is counterpoint and what are the species?","Think independent melodic lines.","Counterpoint: art of combining two or more independent melodic lines that are harmonically coherent. Species counterpoint (Fux, 18th c.): pedagogical system with five species. First species (1:1): one note against each note of cantus firmus — uses consonances, contrary motion. Second species (2:1): two notes against one; passing tones allowed on weak beats. Third species (4:1): four notes against one; passing and neighbor tones. Fourth species (syncopation): suspensions — dissonance on strong beat, consonance on weak; creates expressive tension. Fifth species (florid): combines all previous species. Used to teach Bach chorales, Baroque counterpoint, and voice-leading principles.","hard"),
      P("What is the difference between monophonic, homophonic, and polyphonic texture?","Think how voices relate.","Monophonic: single melodic line, no harmony (Gregorian chant, solo flute melody). Homophonic: melody with harmonic accompaniment — one voice leads, others support (hymn, most pop songs); includes homorhythmic (chordal — all voices same rhythm). Polyphonic (contrapuntal): two or more equally important, independent melodic lines simultaneously (Bach fugue, Renaissance motet, round/canon). Heterophonic: multiple voices perform same melody with simultaneous variations — common in non-Western traditions (gamelan, some folk music). Texture creates feeling of density, complexity, or transparency — Baroque favors polyphony; Classical favors homophony with expressive melody.","medium"),
    ]),
    T("Music Listening and History",[
      P("What are the main periods of Western music history and their characteristics?","Think Medieval through Contemporary.","Medieval (500–1400): Gregorian chant (monophonic); organum (early polyphony); Notre Dame school (Perotin, Leonin). Renaissance (1400–1600): polyphony; imitative counterpoint; word painting; Palestrina, Josquin. Baroque (1600–1750): basso continuo; tonality established; major/minor system; Bach, Handel, Vivaldi; fugue, concerto grosso, opera. Classical (1750–1820): sonata form; symphony; string quartet; balance, clarity; Haydn, Mozart, Beethoven. Romantic (1820–1900): expanded harmony; program music; nationalism; extreme emotion; Brahms, Wagner, Liszt, Schubert. 20th century: diverse — Impressionism, Expressionism, Serialism, Neoclassicism, Minimalism, Electronic.","medium"),
      P("What is a fugue and how does it work?","Think Bach and imitative counterpoint.","Fugue: contrapuntal composition based on a subject (theme) that appears in successive voices through imitation. Structure: Exposition — subject stated in first voice (tonic), answered in second voice (dominant), continued in remaining voices; episodes — developmental passages based on motivic fragments from subject; middle entries — subject returns in various keys; final entry/stretto (subject overlaps in multiple voices) → cadence in tonic. Subject qualities: distinctive, often with leap and step motion; sets up rhythmic and melodic character of entire fugue. Bach's Well-Tempered Clavier: 24 preludes and fugues in every major and minor key — demonstrates equal temperament tuning.","hard"),
    ]),
    T("Ear Training and Sight-Singing",[
      P("What is solfège and how is it used in music education?","Think movable-do and fixed-do systems.","Solfège: system of syllables for singing pitches — do-re-mi-fa-sol-la-ti-do. Movable-do: 'do' is always tonic (first scale degree), regardless of key — facilitates understanding of scale relationships and tonal function. Fixed-do: 'do' is always C — facilitates absolute pitch recognition; used in many European countries. American conservatories often use movable-do for ear training. Sight-singing: reading and singing music at first glance without an instrument. Rhythmic solfège: uses syllables for rhythmic values. Combined: sight-singing and ear training develop musicianship — ability to hear what you see and see what you hear.","medium"),
    ]),
    T("Music in Cultural Context",[
      P("How does music function differently across cultures?","Think ritual, social, and aesthetic functions.","Musical functions: (1) Ritual and ceremony — religious music across all cultures (Gregorian chant, Quranic recitation, Balinese gamelan, Native American ceremonial); (2) Social bonding — work songs, protest songs, national anthems, folk music; (3) Entertainment and aesthetic pleasure; (4) Storytelling — opera, song cycle, film score; (5) Identity — national, ethnic, generational. Non-Western traditions: Indian classical music — ragas (melodic frameworks) and talas (rhythmic cycles) with improvisation; different aesthetic (not European harmony-based). Music is universal human activity — but its specific forms, functions, and values vary dramatically by culture.","medium"),
    ]),
  ],
  # Unit 3 — AP Studio Art 2-D Design
  [
    T("Elements of Design",[
      P("What are the elements of design?","Think line, shape, color, value, texture, space.","Elements of 2-D design: (1) Line — defines edges, creates movement, conveys emotion (jagged=agitation, curved=calm); (2) Shape — positive (figure) and negative (ground) shapes; geometric vs. organic; (3) Color — hue (name), value (lightness/darkness), saturation/intensity; (4) Value — light and dark; creates illusion of form, contrast, emphasis; (5) Texture — visual or tactile surface quality; (6) Space — positive and negative space; foreground/middle/background; perspective; (7) Form — 3-D quality in 2-D work through value modeling. Artists manipulate these elements to create meaning and visual experience.","easy"),
      P("What is color theory and how is the color wheel used?","Think primary, secondary, tertiary, and color relationships.","Color wheel: Primary colors (red, yellow, blue — cannot be mixed from others). Secondary: orange (R+Y), green (Y+B), violet (B+R). Tertiary: mixing adjacent primary and secondary. Warm colors (red, orange, yellow): advance visually, energetic, stimulating. Cool colors (blue, green, violet): recede, calming, spatial. Color relationships: Complementary (opposite on wheel — maximum contrast, vibrate when adjacent); Analogous (adjacent — harmony, unity); Split-complementary; Triadic. Value: tints (add white), shades (add black), tones (add gray). Color creates mood, emphasis, spatial effects, and symbolic meaning.","medium"),
    ]),
    T("Principles of Design",[
      P("What are the principles of design?","Think balance, emphasis, movement, rhythm, unity.","Principles of 2-D design: (1) Balance — symmetrical (mirror), asymmetrical (visual weight balanced without symmetry), radial (from center); (2) Emphasis/focal point — what draws eye first; created through contrast, placement, isolation, color; (3) Movement — eye path through composition; created by line, repetition, value gradation; (4) Rhythm — repetition with variation; creates visual beat; (5) Pattern — repetition of design element; (6) Unity — elements feel cohesive, belong together; through repetition, proximity, similarity; (7) Variety — contrast and difference preventing monotony. Principles are the relationships between elements — how elements are organized to create meaning.","medium"),
    ]),
    T("Drawing Techniques",[
      P("What is contour drawing and how does it develop observation skills?","Think hand-eye coordination.","Contour drawing: continuous line following the edges and surface ridges of a subject without lifting the pencil (pure contour) or with occasional glances at paper (modified contour). Blind contour: draw without looking at paper — trains eye-hand coordination; forces real looking rather than symbol drawing (drawing what you 'know' about an object). Gesture drawing: quick (30–60 seconds) drawings capturing the essence, movement, and proportion of a subject — not details. Used to: develop observational accuracy; break habit of drawing from imagination/symbol; understand form and proportion. Cross-contour: lines across the surface indicating 3D form.","medium"),
      P("How do artists create the illusion of three-dimensional space on a 2-D surface?","Think linear perspective and atmospheric perspective.","Methods for creating spatial illusion: (1) Linear perspective — parallel lines converge to vanishing point(s) on horizon line; one-point (frontal), two-point (corner view), three-point (dramatic height); (2) Overlapping — objects in front obscure those behind; (3) Size variation — objects appear smaller as they recede; (4) Placement — objects lower in picture plane appear closer; (5) Value — objects lighter and less defined in background (atmospheric/aerial perspective); (6) Color — warm colors advance, cool recede; (7) Detail — more detail in foreground, less in background. Artists choose which techniques serve their intent — some deliberately flatten space.","medium"),
    ]),
    T("Portfolio and Concept",[
      P("What is a sustained investigation in AP Studio Art?","Think process and concept development.","AP Studio Art Portfolio: Sustained Investigation — 15 images showing process of investigation around a central question or concept. Requirements: demonstrate inquiry, experimentation, revision, and development over time. NOT a collection of unrelated 'best work.' Must show: (1) Initial exploration; (2) Experimentation with materials and approaches; (3) Revision in response to feedback; (4) Growth and development of ideas. Selected Works: 5 images of finished works demonstrating mastery. Process documentation: sketches, studies, works in progress. Concept question should be genuinely investigative: not 'I will paint portraits' but 'How does fragmentation of the portrait reveal constructed identity?'","hard"),
    ]),
    T("Art Historical Connections",[
      P("How does 2-D design connect to historical and contemporary artistic traditions?","Think formal relationships across time.","2-D design connects to: Egyptian tomb paintings (hieratic scale, flat color); Japanese woodblock prints (Hokusai, Hiroshige — flat color areas, bold line, negative space); Cubism (multiple viewpoints on 2-D surface); constructivism (geometric abstraction, diagonal composition); graphic design (Bauhaus — form follows function); contemporary illustration, motion graphics, UX design, architecture. Understanding design principles as historical developments: perspective (Renaissance revolution); flat design (modernist rejection of illusion); grid systems (Bauhaus and Swiss design). Contemporary digital design builds on centuries of 2-D design thinking.","medium"),
    ]),
    T("Materials and Processes",[
      P("What are the major drawing media and their characteristics?","Think graphite, charcoal, ink, pastel.","Major 2-D media: Graphite (pencil): precise control; broad value range; versatile; smudgeable; most fundamental drawing tool. Charcoal: extremely versatile value range; easy to blend and erase; powdery; works on textured surfaces; expressive, gestural. Ink (pen/brush): permanent; high contrast; line quality varies with tool; wash techniques for value. Pastel: color media; chalky; blendable; layerable; oil pastels (waxy, resist water) vs. soft pastels. Watercolor: transparent; luminous; washes and glazes; unforgiving (hard to correct). Acrylic: versatile; fast-drying; matte or glossy; thick or thin; can be used like oil or watercolor. Each medium has unique characteristics that shape what's possible — material choice is part of artistic decision.","medium"),
    ]),
  ],
  # Unit 4 — AP Studio Art 3-D Design
  [
    T("Three-Dimensional Elements",[
      P("How do the elements and principles of design apply to 3-D work?","Think space, mass, and form in three dimensions.","3-D elements: Mass/volume — actual three-dimensional bulk (positive space occupied by sculpture); Space — negative space (air around and through sculpture — as important as mass); Form — the shape and structure of the 3-D object; Texture — actual tactile surface quality (not illusion); Line — implied through edges, wire, or linear elements; Color — actual surface color. Key difference from 2-D: viewer moves around a 3-D work; it exists in real space with real shadows; scale relationships are actual not illusionistic. Balance in 3-D: actual physical stability as well as visual balance; works can be kinetic (Calder's mobiles).","medium"),
      P("What are the major sculptural processes?","Think additive, subtractive, assembly.","Sculptural processes: (1) Subtractive — remove material from block (carving stone or wood); Michelangelo's 'angel in the marble'; subtractive forces respect for material, each decision permanent; (2) Additive — build up from smaller pieces (clay modeling, casting, welding); allows experimentation and revision; (3) Assemblage — combine found objects (Picasso's Bull's Head from bicycle seat and handlebars; Louise Nevelson's wooden assemblages); (4) Casting — create mold, pour material (bronze casting lost-wax process); allows multiples; surface retains fine detail; (5) Construction — building with industrial materials (Richard Serra's steel plates); (6) Digital fabrication — 3D printing.","medium"),
    ]),
    T("Materials and Process",[
      P("How does material choice affect meaning in sculpture?","Think material as content.","Material as meaning: Stone (marble): permanence, classical tradition, difficulty — conveys timelessness and high cultural status. Bronze: permanence, ability to create multiples, classical tradition. Wood: organic warmth, grain pattern, natural material — connection to living world. Found objects: connect to industrial/consumer society; readymade aesthetic; Duchamp's legacy. Fabric/soft materials: Oldenburg's soft sculptures challenge expectations of solid form; Christo's wrapped landscapes. Concrete: industrial, civic, anonymous. Steel: industrial strength, large scale possible (Serra). Contemporary: artists increasingly aware that material choice carries ideological content — using indigenous materials to assert cultural identity.","hard"),
      P("What is installation art and how does it use space?","Think environment and viewer experience.","Installation art: artwork that transforms and occupies a space; viewer enters and moves through it. Creates environment rather than discrete object. Key characteristics: (1) Site-responsive — responds to specific space; (2) Temporal — often temporary; (3) Immersive — viewer inside work; (4) Can incorporate multiple media (sound, light, video, smell, temperature); (5) Often conceptually driven. Examples: Louise Bourgeois's giant spider Maman; Kusama's Infinity Mirror Rooms; Turrell's light installations; Eliasson's weather project (artificial sun in Tate Modern Turbine Hall). Questions: where does the artwork end? What counts as part of the work? Role of viewer in completing meaning.","hard"),
    ]),
    T("Ceramic and Fiber Arts",[
      P("What is the history and significance of ceramics?","Think function vs. aesthetics.","Ceramics: among oldest human art forms — clay vessels from 20,000+ years ago. Techniques: hand-building (pinch, coil, slab), wheel-throwing, mold-pressing. Firing: bisque (first firing — removes water); glaze firing (second firing — seals and decorates). Types: earthenware (lower fire, porous), stoneware (medium fire, durable), porcelain (high fire, translucent, delicate). Function vs. art debate: ceramics often dismissed as 'craft' (functional, not fine art). Contemporary ceramics: Peter Voulkos challenged this — expressionist ceramics deliberately non-functional; Lucie Rie; Ken Price. Vessels across cultures: Greek amphorae, Chinese porcelain (trade goods), Native American pottery as cultural record.","medium"),
    ]),
    T("Public Art and Context",[
      P("What issues surround public art?","Think access, controversy, and community.","Public art: art in public spaces accessible to all — murals, sculpture, memorials. Issues: (1) Who decides? Commission processes; community input vs. artistic vision; (2) Controversial works: Serra's Tilted Arc (1981) — minimalist sculpture in NYC plaza; blocked workers' path; overwhelmingly unpopular; removed 1989 after public hearing; artist protested; (3) Confederate monuments — public art as political assertion; ongoing removal debates; (4) Graffiti/street art — unauthorized public art (Banksy); criminal vs. artistic expression; (5) Accessibility — art should be physically accessible; (6) Cultural representation — whose histories are commemorated in public space?","hard"),
    ]),
    T("Portfolio Documentation",[
      P("How is 3-D portfolio documentation different from 2-D?","Think photography and multiple views.","3-D portfolio documentation: 3-D work must be photographed for portfolio submission — creates unique challenges. Requirements: show multiple views (front, side, back, detail shots); consistent, neutral background; good lighting to reveal form (avoid flat, shadowless light — use directional lighting to reveal volume); appropriate scale reference when helpful. Digital documentation: high resolution; color accuracy. Process documentation: in-progress photos show development from sketch through final. The photograph of a sculpture is itself a representation — must thoughtfully capture what is significant about the work. Scale matters: a 6-inch and 6-foot work photograph similarly — must convey actual scale somehow.","medium"),
    ]),
  ],
  # Unit 5 — AP Studio Art Drawing
  [
    T("Observational Drawing",[
      P("What is observational drawing and why is it foundational?","Think seeing and recording.","Observational drawing: drawing from direct observation of real subjects (still life, figure, landscape, objects) — not from imagination or memory. Foundational because: (1) Trains accurate seeing — we typically see what we expect, not what is actually there; (2) Develops hand-eye coordination; (3) Builds vocabulary of visual facts (how light wraps a form, how space recedes); (4) Teaches understanding of structure, proportion, value. Skills: measuring proportions (pencil held at arm's length); comparing angles; negative space drawing; value observation (identify lightest, darkest, midtones before drawing); edge quality (hard edges = sudden value change; soft = gradual). Life drawing (nude figure) considered highest observational challenge.","medium"),
      P("How do you draw the human figure with accurate proportions?","Think landmarks and unit measurement.","Figure drawing proportions: ideal adult figure ~8 heads tall; chin to nipple ~1 head; nipple to navel ~1 head; navel to pubic area ~1 head; pubic area to mid-thigh ~1 head; mid-thigh to mid-calf ~1 head, etc. Key landmarks: eye level at half of head; shoulder width ~2 heads; hip width slightly narrower than shoulders in males, similar in females. Structural approach: gesture → major volumes (egg for head, cylinder for torso, etc.) → skeleton/armature → muscles → surface detail. Foreshortening: limbs pointing toward viewer appear shorter — requires accurate observation of ellipses and compressed proportions. Quick gesture studies precede sustained observational drawings.","hard"),
    ]),
    T("Mark-Making and Value",[
      P("What are the different ways to create value in drawing?","Think hatching, blending, and mark density.","Value creation techniques: (1) Hatching — parallel lines; closer lines = darker value; (2) Cross-hatching — layers of hatching at different angles; (3) Stippling — dots; more dots = darker; pointillist quality; (4) Blending — smear with finger, blending stump, chamois; creates smooth gradients (charcoal, graphite); (5) Erasing — erase to create lights (especially with charcoal); (6) Scumbling — irregular, non-directional marks; (7) Contour shading — hatching lines follow the form (like contour lines on a map). Mark character contributes to expressive quality — hatching can suggest rigidity, blending warmth, stippling patience and precision.","medium"),
      P("How does light create the illusion of form?","Think the seven elements of shading.","Light on form — seven elements: (1) Highlight — brightest spot where light hits directly; (2) Light — area receiving full light; (3) Halftone — middle value; transition between light and shadow; (4) Core shadow — darkest area of the shadow on the form (where light can't reach even by bounce); (5) Reflected light — light bouncing from surrounding surfaces into shadow (lightens shadow edge — not as light as lit area); (6) Cast shadow — shadow cast by object onto surface; darkest at base of object; (7) Occlusion shadow — very dark where objects meet surfaces. Understanding these zones allows convincing 3-D illusion through value only.","hard"),
    ]),
    T("Compositional Drawing",[
      P("What is compositional drawing and how do you approach a composition?","Think organization and visual hierarchy.","Compositional drawing: organizing visual elements within the picture plane to create effective, meaningful arrangement. Approach: (1) Thumbnail sketches — small, quick studies of different arrangements before committing; (2) Rule of thirds — divide picture into 9 equal parts; place focal points at intersections; (3) Viewfinder — frame hands or cut cardboard to explore cropping; (4) Negative space — design the spaces around subjects as carefully as subjects themselves; (5) Value structure — plan lights and darks to create clear hierarchy; (6) Entry and exit points — guide viewer's eye into and through image. Avoid: centering everything; symmetrical boredom; equal weight across composition.","medium"),
    ]),
    T("Drawing Media and Materials",[
      P("How do different drawing papers affect the final work?","Think surface texture and absorbency.","Drawing surfaces: Smooth/hot press: fine detail possible; graphite shows every mark; ink spreads predictably. Toothy/cold press or rough: charcoal and pastel grip the surface (tooth); loose-feeling; more texture visible. Newsprint: inexpensive; gray tone; acidic (yellows quickly) — only for practice. Sketchbook: acid-free for longevity; varies in surface. Bristol: very smooth; excellent for pen and ink; marker friendly. Toned paper (gray, tan, brown): allows working from midtone toward light (white chalk/pastel) AND dark simultaneously — efficient; creates unified atmospheric quality. Vellum: smooth, translucent; used for technical drawing and transfer. Surface choice shapes what's possible with each medium.","medium"),
    ]),
    T("Drawing as Sustained Practice",[
      P("What makes drawing a sustained investigation in AP Studio Art?","Think inquiry, experimentation, and development.","Sustained investigation in drawing: 15-image portfolio showing development of an investigation around a central concept or question. Not a collection of unrelated drawings — must show inquiry process. Examples of sustained questions: 'How does the hand reveal identity and vulnerability?' 'What does the intersection of built and natural environments look like through fragment and decay?' 'How can drawing mark-making translate sound into visual form?' Evidence of investigation: multiple approaches tried, dead ends explored, revisions made in response to criticism, conceptual refinement visible. Drawing skill is necessary but not sufficient — AP evaluates both technical execution and conceptual development.","hard"),
    ]),
    T("Figure, Portrait, and Still Life",[
      P("What is the significance of the figure and portrait in drawing tradition?","Think humanist tradition and contemporary extensions.","Figure and portrait: central to Western drawing tradition since Renaissance (Leonardo's anatomical studies; Michelangelo's figure drawings; Rembrandt's self-portraits). Why significant: human figure carries emotional resonance and embodied knowledge; portrait explores identity, psychology, power. Contemporary extensions: Lucian Freud (unsparingly honest, flesh-focused); Jenny Saville (large-scale, confrontational female bodies); Kara Walker (black silhouette figures exploring slavery's legacy); Alice Neel (empathetic, psychologically penetrating portraits). Figure drawing challenges: foreshortening, proportion, capturing expression without cliché, revealing the particular person not a generic figure.","medium"),
    ]),
  ]
]
