"""AP Languages: 8 units matching curriculum"""

def P(q,ex,a,diff): return {"q":q,"ex":ex,"a":a,"diff":diff}
def T(title,problems): return {"title":title,"problems":problems}

AP_LANGS = [
  # Unit 1 — AP Chinese Language and Culture
  [
    T("Spoken and Written Chinese",[
      P("How does Mandarin's tonal system work and why is it essential?","Think four tones plus neutral.","Mandarin has four tones plus a neutral (light) tone. 1st tone: high, level (mā — mother). 2nd tone: rising, as if asking a question (má — hemp/numb). 3rd tone: dipping, falls then rises (mǎ — horse). 4th tone: falling sharply (mà — scold/curse). Neutral: short, unstressed (ma — question particle). The same syllable 'ma' means four different things depending on tone — tone is phonemic (changes meaning). Tonal errors don't just sound foreign; they change the meaning entirely. Practice: listen to native speakers, use apps with tone training, speak aloud with feedback.","medium"),
      P("What is the difference between simplified and traditional Chinese characters?","Think historical and political context.","Simplified characters: adopted by People's Republic of China (1950s–60s) to increase literacy; fewer strokes, some characters look quite different from traditional. Used in: mainland China, Singapore, Malaysia. Traditional characters: preserved in Taiwan, Hong Kong, Macau, many overseas Chinese communities; maintain historical form, often more visually complex. AP Chinese exam uses simplified characters. Pinyin: romanization system for Mandarin pronunciation; not a writing system but a learning tool. Characters are logographs — each represents a morpheme (unit of meaning), not a sound. Radical: semantic component that gives hint to meaning category.","medium"),
      P("What are key features of Chinese grammar structure?","Think topic-comment and measure words.","Key features: (1) No inflection — no verb conjugation (tense marked by time words and aspect markers: 了, 过, 着); no noun plurals (number + measure word); (2) Topic-comment structure — topic stated first, then comment about it; (3) Measure words (量词) — required between number and noun: 一本书 (one 'volume' book), 一只猫 (one 'small animal' cat); (4) Serial verb constructions — multiple verbs in sequence; (5) Particles — 的 (modifier), 地 (adverbial), 得 (complement), 了 (completion), 吗 (yes/no question), 呢 (follow-up question). SVO word order generally, but very flexible with topic-fronting.","hard"),
    ]),
    T("Cultural Contexts",[
      P("What are key aspects of Chinese cultural values reflected in language use?","Think Confucian values and social hierarchy.","Confucian influence: (1) Hierarchy and respect — formal address terms (您 nín vs. 你 nǐ for 'you'); titles used instead of names (老师 lǎoshī 'teacher'); family terms extended to non-relatives (older neighbor called '阿姨' auntie); (2) Face (面子 miànzi) — public dignity; indirect communication to avoid embarrassing others; compliments and gifts handled with ritualized modesty; (3) Group orientation — collective harmony over individual expression; (4) Food culture as social bonding — meals as primary social context; food as care; (5) Filial piety (孝顺 xiàoshun) — respect for elders and ancestors fundamental to family structure.","medium"),
      P("How does Chinese society discuss education and career expectations?","Think high-pressure academic culture.","Education culture: Gaokao (高考) — national college entrance exam; arguably most high-stakes test in the world; determines university placement; students prepare years in advance. '985' and '211' universities: elite tiers. Academic pressure: tiger parenting (严格的父母); extra tutoring (补习班); summer programs. Career expectations: traditional prestige in 'iron rice bowl' government jobs, medicine, law, finance; shifting with tech sector. Vocabulary: 内卷 (nèijuǎn — 'involution,' hyper-competitive academic/work environment); 躺平 (tǎng píng — 'lying flat,' rejecting hustle culture). These reflect generational tensions in contemporary Chinese society.","hard"),
    ]),
    T("Reading Comprehension",[
      P("What strategies help with reading authentic Chinese texts?","Think character recognition and context.","Reading strategies: (1) Radical recognition — identify the semantic component in unfamiliar characters to guess meaning category; (2) Context inference — use surrounding characters/sentences to infer unknown vocabulary; (3) Compound words — most Chinese vocabulary is two or more characters; knowing individual characters helps decode compounds; (4) Register awareness — written Chinese (书面语) differs significantly from spoken (口语); news more formal; social media more colloquial; (5) Chunking — identify 4-character set phrases (成语 chéngyǔ); (6) Grammar patterns — recognize verbal aspect markers, BA construction, BEI passive. Reading widely across registers develops both vocabulary and cultural literacy.","hard"),
    ]),
    T("Writing Skills",[
      P("How do you write a formal email or letter in Chinese?","Think register and structure.","Formal Chinese letter/email: Opening: address with title and name (尊敬的XX老师); purpose statement early. Body: clear paragraph structure; formal vocabulary (请, 恳请 for requests rather than 我要); complete sentences; appropriate verb aspects and particles. Closing: polite formulaic closing (此致/敬礼 for letters; 期待您的回复 'looking forward to your reply'); your name and date. Register: formal written Chinese avoids contractions, colloquialisms; uses complete subject-verb-object sentences; no 呢/吗 question particles (use declarative + 吗? only in less formal); appropriate measure words and particles throughout. AP Writing: demonstrate range of vocabulary and grammatical structures; address prompt specifically.","medium"),
    ]),
    T("Interpersonal Communication",[
      P("What are common politeness strategies in Chinese conversation?","Think indirectness and face-saving.","Politeness strategies: (1) Indirect refusal — rarely say直接说 'no'; instead 'maybe' (也许), 'inconvenient' (不方便), 'need to think about it' (再考虑考虑); (2) Modesty formulas — when receiving compliments, deflect (哪里哪里 'not at all,' 还差得远呢 'still far from good enough'); (3) Meal offers — host insists food is insufficient; guest praises effusively regardless; (4) Age and family status questions — normal small talk in Chinese culture (how old? married? children?) — not intrusive as in Western contexts; (5) Toasting culture (干杯) — elaborate hierarchy of toasting order at meals; (6) Giving and receiving with two hands — shows respect for objects and person.","medium"),
    ]),
    T("Listening Comprehension",[
      P("What challenges do AP Chinese students face with listening and how do you overcome them?","Think tonal variation and colloquial speech.","Listening challenges: (1) Tonal reduction in fast speech — tones often neutralized or merged in colloquial speech; (2) Regional accents — standard Mandarin (普通话) vs. regional varieties; (3) Vocabulary gaps — colloquial vocabulary and internet slang not in textbooks; (4) Speed — authentic speech much faster than classroom; (5) Reduced pronunciation — syllables blend, final consonants disappear. Strategies: (1) Daily exposure to authentic content (Chinese news, podcasts, drama series); (2) Shadowing — imitate native speakers immediately; (3) Listen for key content words rather than every syllable; (4) Use context from situation to fill gaps; (5) Ask for repetition/clarification in practice (再说一遍 'say again').","hard"),
    ]),
    T("Presentational Speaking",[
      P("How do you give an effective presentation in Chinese?","Think organization and vocabulary range.","Presentation strategies: (1) Introduction — state topic and main points (今天我要讲的是...); (2) Clear organization — use transition phrases (首先...其次...最后... first, then, finally); (3) Vocabulary range — demonstrate both formal vocabulary and nuanced vocabulary; use chéngyǔ (成语 four-character idioms) appropriately; (4) Specific examples and evidence — rather than vague statements; (5) Cultural connection — connect topic to Chinese cultural context when relevant; (6) Conclusion — summary + personal stance (我认为/总的来说); (7) Register maintenance — formal presentational context requires avoiding colloquial fillers. Pronunciation: tone accuracy, not perfection — clear communication prioritized.","medium"),
    ]),
    T("Contemporary Chinese Society",[
      P("What are major themes in contemporary Chinese society visible in media and conversation?","Think urbanization, technology, and generational change.","Contemporary themes: (1) Urbanization — massive internal migration; 农村 (countryside) vs. 城市 (city); 留守儿童 (left-behind children whose parents migrated for work); (2) Tech innovation — 微信 WeChat, 支付宝 Alipay, TikTok (抖音 Dǒuyīn); digital economy; (3) Environment — pollution (雾霾 wùmái smog), clean energy push, carbon neutrality goals; (4) Belt and Road Initiative (一带一路) — global infrastructure investment; (5) Demographic challenges — aging population, declining birth rate after one-child policy; (6) Generational differences — 90后 (post-90s), 00后 (post-2000) generation with different values from parents. These themes appear in AP exam reading and listening materials.","hard"),
    ]),
    T("Grammar Deep Dive",[
      P("What is the 把 (bǎ) construction and when is it used?","Think disposal of objects.","把 construction: 主语 + 把 + 宾语 + 动词 + 补语. Used when: (1) The action 'disposes of' or does something significant to a specific, definite object; (2) The result of the action is expressed (complement required); (3) Object is moved, changed, or affected. Examples: 我把书放在桌子上。(I put the book on the table.) 她把作业做完了。(She finished the homework.) Cannot use 把 with: non-disposal verbs (是, 有, 喜欢); indefinite objects ('a book'); without a complement after the verb. Contrast: 我看书 (I read books — general); 我把书看完了 (I finished reading THAT book — disposal with result).","hard"),
      P("How do aspect markers function in Mandarin?","Think 了, 过, 着.","Aspect markers indicate how an action unfolds in time (not tense — Chinese has no tense). 了 (le): (1) Verbal 了 after verb = completion (我吃了。I ate.); (2) Sentence-final 了 = change of state/new situation (天黑了。It got dark.). 过 (guò): past experience that is no longer occurring (我去过中国。I've been to China [at some point].); implies no longer in that state. 着 (zhe): ongoing state or continuous action (她戴着帽子。She is wearing a hat [state].); used in background descriptions. These three markers can combine: 我去过，去了两次。Common error: using 了 like English past tense — it marks completion, not past time.","hard"),
    ]),
  ],
  # Unit 2 — AP French Language and Culture
  [
    T("Pronunciation and Phonetics",[
      P("What are the key pronunciation challenges in French for English speakers?","Think liaison, élision, and nasals.","Key challenges: (1) Liaison — final consonant (normally silent) pronounced when next word begins with vowel/h-muet: les_enfants (lay-ZAN-fan); required, optional, or forbidden by context; (2) Élision — vowel dropped before vowel/h-muet: le + école = l'école; (3) Nasal vowels (an/en, in/ain, on, un) — vowel nasalized, 'n' not fully pronounced; (4) U sound — pursed lips, unrounded, no English equivalent; (5) R — uvular fricative; (6) Silent final consonants (generally) except c, r, f, l (CaReFuL); (7) Intonation — French more level, rising at phrase end; (8) Enchaînement — linking final consonant to initial vowel of next word.","hard"),
      P("What is the difference between formal (vous) and informal (tu) address?","Think register and social relationships.","Vouvoiement (vous) vs. tutoiement (tu): Tu: family, close friends, children, peers, informal social settings. Vous: strangers, elders, authority figures, formal contexts, professional settings, plural address. Rules not absolute — vary by region (Quebec more informal), professional culture, social class. Wrong register is a social error — using tu with a professor may seem presumptuous; vous with a close friend seems cold. Children use tu with each other; adults use vous initially and may shift to tu as relationship develops. Digital communication has made tu more common; some workplaces encourage tu for all colleagues.","medium"),
    ]),
    T("Grammar Essentials",[
      P("How do French verbs work with être vs. avoir in passé composé?","Think DR and MRS VANDERTRAMP and pronominal verbs.","Passé composé formation: avoir + past participle (most verbs) OR être + past participle (specific intransitive verbs + all pronominal verbs). DR MRS VANDERTRAMP (être verbs): Devenir, Revenir, Monter, Rester, Sortir, Venir, Aller, Naître, Descendre, Entrer, Rentrer, Tomber, Retourner, Arriver, Mourir, Partir. With être: past participle agrees in gender and number with subject (Elle est allée; Ils sont partis). All reflexive/pronominal verbs use être: Je me suis lavé(e). Avoir verbs: past participle agrees with preceding direct object if present (Les fleurs que j'ai achetées — 'flowers' is feminine plural preceding direct object).","hard"),
      P("When do you use the subjunctive in French?","Think triggers and contexts.","Subjunctive (subjonctif): expresses doubt, emotion, necessity, uncertainty, or subjectivity. Triggered by: (1) Expressions of necessity/obligation: il faut que, il est nécessaire que; (2) Expressions of wish/will: vouloir que, désirer que, préférer que; (3) Expressions of emotion: être content que, avoir peur que, regretter que; (4) Expressions of doubt/possibility: douter que, il est possible que (but: il est probable que → indicative!); (5) Certain conjunctions: bien que, quoique (although), pour que (so that), avant que (before), à moins que (unless); (6) Superlatives followed by relative clause. NOT triggered by: espérer que (hope), penser que (affirmative), il est probable que. Different subject in each clause required.","hard"),
    ]),
    T("Reading and Text Analysis",[
      P("How do you analyze a French literary text for the AP exam?","Think close reading in French.","Text analysis approach: (1) Identify genre, register, and approximate period; (2) Summarize main ideas; (3) Identify the author's purpose and audience; (4) Analyze literary devices: figures of style (métaphore, comparaison, personnification, hyperbole, ironie, antithèse, anaphore); narrative voice (narrateur omniscient, point de vue interne); time and space; (5) Identify cultural context — how does this text reflect French/Francophone culture?; (6) Analyze language level — formal vs. familiar register, vocabulary richness, sentence complexity. AP reading tasks: identify main idea, interpret vocabulary in context, make inferences, identify author's stance, analyze literary or rhetorical devices.","hard"),
      P("What are major themes in French and Francophone literature?","Think existentialism, colonialism, identity.","French literary themes: Existentialism — Sartre (L'être et le néant; Huis clos 'Hell is other people'), Camus (L'Étranger, La Peste — absurdism, authenticity). Colonialism and postcolonialism — Francophone authors from Senegal (Senghor, Sembène), Morocco (Tahar Ben Jelloun), Quebec, Caribbean (Aimé Césaire — Négritude movement). Identity and immigration — Leïla Slimani, Faïza Guène. Realism — Balzac's Comédie humaine, Flaubert's Madame Bovary (free indirect discourse, irony). Existentialist feminism — Simone de Beauvoir (Le Deuxième Sexe). Contemporary: French literature engages immigration, diversity, national identity, Europe.","hard"),
    ]),
    T("Cultural Knowledge",[
      P("What are key cultural practices in France relevant to the AP exam?","Think laïcité, cuisine, education.","Key French cultural concepts: (1) Laïcité — strict secularism; separation of church and state (1905 law); no religious symbols in public schools; headscarf debates; differs from US religious freedom model; (2) Grande cuisine — gastronomy as cultural heritage (UNESCO recognized); French food culture (bistro, brasserie, boulangerie); AOC designations for wine and cheese; (3) Education — baccalauréat exam (like French Gaokao); Sciences Po, grandes écoles (elite institutions separate from universities); philosophy required in terminal (final) year; (4) Grèves — strikes as cultural institution; labor rights deeply valued; (5) Les grandes vacances — month-long August holiday; everything closes.","medium"),
      P("What is the Francophone world and why is it culturally significant?","Think scope and diversity.","La Francophonie: ~300 million French speakers worldwide; French is official language in 29 countries. Regions: France and Western Europe; Sub-Saharan Africa (Senegal, Côte d'Ivoire, Democratic Republic of Congo — largest French-speaking country by population); North Africa (Morocco, Algeria, Tunisia — Maghreb); Caribbean (Haiti, Guadeloupe, Martinique — French territories); Quebec; Pacific islands. Significance: French language carries different cultural histories in each region; Francophone literature explores colonial history, identity, hybridity. OIF (Organisation internationale de la Francophonie) promotes linguistic and cultural diversity. AP exam intentionally includes Francophone (non-French) perspectives.","medium"),
    ]),
    T("Writing Skills",[
      P("How do you write a strong argumentative essay in French?","Think French essay structure.","French essay structure — dissertation: Introduction: (1) Accroche (hook — surprising statistic, quotation, striking observation); (2) Présentation du sujet (present the topic in context); (3) Problématique (the central question the essay will answer); (4) Annonce du plan (announce the structure: 'Nous verrons d'abord...puis...enfin...'). Body: 2–3 parts, each with 2–3 paragraphs; each paragraph: topic sentence + examples/evidence + analysis. Conclusion: Bilan (summary of argument) + Ouverture (broader perspective or question beyond the essay). Avoid: 'I think' in formal essay (no 'je pense'); assertions without support; pure summary. AP essays: demonstrate grammatical range, vocabulary precision, organized argument.","hard"),
    ]),
    T("Interpersonal Communication",[
      P("How does formal French conversation differ from informal?","Think register markers.","Formal French: (1) Vous for address; (2) Conditional for requests (Pourriez-vous... rather than Pouvez-vous...); (3) Full negation (ne...pas, not just 'pas' alone); (4) Avoidance of filler words (euh is common but excessive use marks informal); (5) Complete sentences; (6) Standard pronunciation (no elision of ne in formal contexts). Informal French: (1) Tu; (2) Ne deletion (j'sais pas instead of je ne sais pas); (3) Inversion replaced by rising intonation for questions (T'as faim? instead of As-tu faim?); (4) Verlan (backslang: l'envers = verlan; meuf from femme; keuf from flic); (5) Informal vocabulary; (6) Text abbreviations in digital communication.","medium"),
    ]),
    T("Listening and Film",[
      P("What is important to know about French cinema for cultural literacy?","Think nouvelle vague and contemporary film.","French cinema: Nouvelle Vague (New Wave, 1950s–60s): Godard (À bout de souffle), Truffaut (Les 400 coups) — rejected studio conventions; jump cuts, location shooting, improvisation; auteur theory (director as author). Contemporary French film: Amélie (Jeunet, 2001 — nostalgic whimsy, Paris); Les Intouchables (2011 — disability, class, race); La Haine (1995, Kassovitz — banlieue youth, police violence, immigration — essential for understanding French social tensions). Award culture: César (French Oscar); Cannes Film Festival. Film as cultural document: French films often engage explicitly with social and political issues — immigration, class, gender, colonial history.","medium"),
    ]),
    T("Advanced Grammar",[
      P("How does the passé simple differ from the passé composé and when is each used?","Think written vs. spoken past.","Passé simple (literary past): used in formal written narrative — novels, official histories, fairy tales (il était... puis il alla... il trouva...). Not used in spoken French (except very formal speech or parody). Passé composé: used in all spoken French AND modern informal/journalistic writing for past actions. The same 'meaning' (completed past action) is expressed differently in written formal narrative (passé simple) vs. spoken/modern (passé composé). AP reading: must recognize and understand passé simple in authentic texts. AP writing/speaking: use passé composé; passé simple in formal narrative essay shows sophistication.","hard"),
    ]),
  ],
  # Unit 3 — AP German Language and Culture
  [
    T("German Case System",[
      P("How does the German case system work?","Think four cases and their functions.","German has four cases determining word form based on grammatical function: (1) Nominative (Nominativ): subject of the sentence — wer/was? (Who/what does the action?); (2) Accusative (Akkusativ): direct object — wen/was? (Who/what receives action?); (3) Dative (Dativ): indirect object — wem? (To/for whom?); after certain prepositions (mit, nach, seit, von, zu, bei, gegenüber, aus, außer); (4) Genitive (Genitiv): possession — wessen? (Whose?); increasingly replaced by von + dative in spoken German. Articles change: der Mann (N) → den Mann (A) → dem Mann (D) → des Mannes (G). Adjective endings also change by case, gender, and definiteness — master these to write correctly.","hard"),
      P("What are the most important German prepositions and their cases?","Think two-way prepositions.","Two-way prepositions (Wechselpräpositionen) — take ACCUSATIVE for movement toward (wohin?), DATIVE for location (wo?): an, auf, hinter, in, neben, über, unter, vor, zwischen. Example: Ich gehe in die Küche (Acc — movement). Das Buch liegt in der Küche (Dat — location). Always accusative: durch, für, gegen, ohne, um, bis, entlang, wider. Always dative: mit, nach, seit, von, zu, bei, gegenüber, aus, außer. Always genitive: wegen, trotz, während, statt, anstatt, aufgrund. Separable verb prefixes: some preposition-based prefixes (an, auf, ein, aus, mit, nach, vor, zu, ab, bei) separate in main clauses.","hard"),
    ]),
    T("German Culture and Society",[
      P("What are key cultural values and practices in German-speaking countries?","Think Pünktlichkeit, Directness, and Gründlichkeit.","German cultural values: (1) Pünktlichkeit (punctuality) — being on time is a mark of respect; late is disrespectful; (2) Gründlichkeit (thoroughness) — doing things completely and correctly; quality craftsmanship (Qualitätsarbeit); (3) Directness — Germans tend toward direct, frank communication; 'Nein' is not rude; less small talk before business; (4) Datenschutz (data privacy) — exceptionally strong privacy culture; GDPR emerged partly from German sensibility; (5) Trennung (separation of spheres) — formal vs. informal relationships clearly demarcated; Sie vs. du not casual; (6) Umweltschutz (environmental protection) — strong green consciousness; Grüner Punkt recycling; Renewable energy (Energiewende); (7) Feierabend — clear distinction between work time and leisure time.","medium"),
      P("How does Germany grapple with its 20th century history?","Think Erinnerungskultur.","Erinnerungskultur (culture of remembrance): Germany takes deliberate responsibility for WWII and Holocaust — contrasts with many countries' difficulty confronting colonial crimes. Mechanisms: Stolpersteine (stumbling stones) — small brass plaques in sidewalks naming Holocaust victims at their last address; Holocaust memorials throughout Germany (Berlin Memorial to Murdered Jews of Europe); Gedenkstätten (memorial sites — Dachau, Sachsenhausen); school curriculum mandatory; Holocaust denial criminalized; Bundestag debates on remembrance. Vergangenheitsbewältigung (working through the past): ongoing process, never 'completed.' Contrasts with DDR/East Germany which initially avoided this reckoning.","hard"),
    ]),
    T("Grammar Structures",[
      P("How do separable and inseparable verb prefixes work in German?","Think word order implications.","Separable prefixes (trennbare Vorsilben): prefix separates from verb in simple tenses; goes to end of clause. Common: an-, auf-, aus-, ein-, vor-, zu-, ab-, mit-, nach-. Example: anrufen (to call) → Ich rufe meinen Freund an. In subordinate clauses and infinitive constructions, stays attached: Er versucht, mich anzurufen. Inseparable prefixes (untrennbare Vorsilben): never separate; stress on verb stem: be-, emp-, ent-, er-, ge-, miss-, ver-, zer-. Example: besuchen → Ich besuche ihn (not: *Ich suche ihn be). Some prefixes can be either (umfahren — to drive around [separable] OR to run over [inseparable] — different meaning!). Participles: separable = ge between prefix and stem (angerufen); inseparable = no ge- (besucht).","hard"),
      P("What is the difference between Modal and Infinitive constructions in German?","Think double infinitive.","Modal verbs (dürfen, können, mögen, müssen, sollen, wollen): take infinitive without zu at end of clause. Present: Ich kann schwimmen. Past (conversational): Ich habe schwimmen können (double infinitive — two infinitives at end; normal past participle pushed out). Infinitive constructions with zu: lassen, sehen, hören, helfen also take bare infinitive. Other verbs take zu + infinitive: Ich versuche zu schlafen. Um...zu: in order to — Ich gehe in die Bibliothek, um zu studieren. Sentence-final position: in subordinate clauses, all verbal elements go to end — compound tenses create 'verb cluster' at end: ...weil er gestern hat kommen wollen. (because he wanted to come yesterday).","hard"),
    ]),
    T("Contemporary German Issues",[
      P("What major contemporary issues affect German-speaking societies?","Think immigration, energy, and European integration.","Contemporary German issues: (1) Immigration and integration — 2015–16 refugee crisis (1 million+ arrivals); Willkommenskultur vs. skepticism; integration success and challenges; rise of AfD (Alternative für Deutschland); (2) Energiewende — transition from nuclear and fossil fuels to renewables; Atomausstieg (nuclear phase-out) accelerated after Fukushima; energy security highlighted by Ukraine war and Russian gas dependence; (3) European integration — Germany as EU economic anchor; eurozone leadership; tensions between German fiscal orthodoxy and southern European needs; (4) Digitalisierung — Germany slower than expected in digital transformation despite industrial strength; (5) Rentensystem — pension system under demographic pressure.","medium"),
    ]),
    T("German Literature and Media",[
      P("What are key works and authors in German literature?","Think Goethe, Brecht, and contemporary writers.","German literary canon: Goethe (Faust — humanity's quest for knowledge and meaning; Werther — sentimentalism); Schiller (Wilhelm Tell, Die Räuber — freedom and moral integrity); Kafka (Die Verwandlung/The Metamorphosis, Der Process/The Trial — alienation, bureaucracy, absurdism); Bertolt Brecht (Mutter Courage, Der gute Mensch von Sezuan — epic theater, Verfremdungseffekt/alienation effect, Marxist critique); Heinrich Böll (post-WWII moral reckoning); Günter Grass (Die Blechtrommel/The Tin Drum — German guilt, magical realism); Christa Wolf (GDR perspective, women's experience); Contemporary: Herta Müller (Nobel Prize, Romanian-German), Daniel Kehlmann, Jenny Erpenbeck.","hard"),
    ]),
    T("Spoken German",[
      P("How does spoken German differ from written German?","Think colloquial forms and regional variation.","Spoken vs. written German: (1) Conversational past: spoken German uses Perfekt (haben/sein + past participle) for past actions; literary Präteritum (simple past) is written form (except modal verbs and sein/haben which are always Präteritum in speech); (2) Contraction: in der → in'ner, in das → ins, an dem → am, bei dem → beim; (3) Filler words (Füllwörter): eigentlich, halt, mal, irgendwie, irgendwo, doch — add nuance and soften; (4) Diminutives: -chen and -lein common in informal speech; (5) Dialects: Bavarian (Bayern), Swiss German (Schweizerdeutsch — very different!), Austrian German, Plattdeutsch. Hochdeutsch (standard German) is the prestige form taught in schools.","medium"),
    ]),
    T("Reading Strategies",[
      P("How do you decode complex German sentence structure?","Think verb-second rule and embedded clauses.","German sentence structure rules: (1) Verb-second (V2): finite verb is always second element in main clause — regardless of what starts the sentence; if adverb or object starts, subject follows verb: Gestern bin ich ins Kino gegangen (Yesterday am I to the cinema gone); (2) Subordinate clauses: verb goes to END: ...weil er krank war (...because he was sick); (3) Relative clauses: verb at end; relative pronoun agrees in gender with noun; (4) Extended attributes: German can build extremely long noun phrases with multiple embedded modifiers before the noun — read backwards from noun to unpack: die im Buch beschriebene, von vielen gelesene Geschichte (the in the book described, by many read story = the story described in the book and read by many).","hard"),
    ]),
  ],
  # Unit 4 — AP Italian Language and Culture
  [
    T("Italian Language Structure",[
      P("How does Italian verb conjugation work across the main tenses?","Think -are, -ere, -ire and key tenses.","Italian verb conjugation: Three infinitive types: -are (parlare), -ere (credere), -ire (dormire/capire with -isc-). Present (presente): regular patterns + many irregulars (essere, avere, andare, fare, venire, etc.). Past: Passato prossimo (avere/essere + past participle — for conversation) vs. Imperfetto (habitual/descriptive past — ero, eri, era, eravamo, eravate, erano). Future: stem + endings (-ò, -ai, -à, -emo, -ete, -anno); also 'stare per + infinitive' for near future. Conditional: -rei, -resti, -rebbe endings. Subjunctive (congiuntivo): after verbs of desire, doubt, emotion, opinion; che triggers it. Imperative: tu form often = present. Gerund: -ando/-endo; used with stare.","hard"),
      P("What are key features of Italian phonology?","Think double consonants and vowel sounds.","Italian pronunciation features: (1) Double consonants (geminate): must be held longer — matter for meaning: pala (shovel) vs. palla (ball); sono (I am) vs. sonno (sleep); (2) Pure vowels — 5 vowel sounds, more precise than English; no diphthongs in same way; (3) Open vs. closed e/o: regional variation but significant; (4) c/g: soft (ch/j) before i/e; hard (k/g) before a/o/u — 'dolce' (dohl-cheh) vs. 'cosa' (koh-zah); (5) gli: palatal lateral (like 'million' compressed) — figlio, moglie; (6) gn: palatal nasal (like 'canyon') — bagno, gnocchi; (7) Stress: generally on penultimate syllable but exceptions important; accents on final syllable mark exceptions (città, caffè, perché).","medium"),
    ]),
    T("Italian Culture",[
      P("What are essential cultural concepts in Italian society?","Think family, food, and regional identity.","Italian cultural concepts: (1) La famiglia — central institution; extended family networks; intergenerational bonds; mammismo (strong mother-son attachment); (2) La bella figura — making a good impression; appearance, style, presentation of self; antithesis is la brutta figura; (3) Campanilismo — pride in one's local town/region; identity as from Rome, Milan, Naples, Sicily more than as 'Italian'; (4) Food culture — regional gastronomy; Sunday family lunch; slow food movement (founded in Italy by Carlo Petrini); DOP/IGP protected designations; aperitivo culture in Milan; espresso rituals; (5) Dolce far niente — pleasure of doing nothing; legitimate leisure; (6) Arte — Italy's extraordinary artistic heritage as national identity.","medium"),
      P("How does Italy's regional diversity manifest culturally and economically?","Think North-South divide and dialects.","Italian regional diversity: North-South divide (il divario Nord-Sud): North (Milan, Turin, Bologna) — industrial, wealthy, efficient; South (Mezzogiorno — Naples, Sicily, Calabria) — agricultural, poorer, high unemployment, organized crime challenges. Historical: Italy unified only in 1861; regional identities predate 'Italy.' Dialects: Venetian, Neapolitan, Sicilian, Milanese are distinct enough to be called separate languages by some linguists; Standard Italian (lingua standard) based on Tuscan (Dante's Florence). Cuisine: pizza from Naples; risotto from North; pasta shapes are regional; wine regions (Chianti, Barolo, Prosecco). Regional differences remain significant despite 160+ years of unified state.","hard"),
    ]),
    T("Grammar and Usage",[
      P("When do you use the subjunctive in Italian?","Think congiuntivo triggers.","Italian congiuntivo (subjunctive): used in subordinate clauses after: (1) Verbs of desire/will: volere che, desiderare che, preferire che; (2) Verbs of belief/opinion (uncertain): pensare che, credere che, sembrare che, parere che; (3) Verbs of emotion: essere felice che, avere paura che, dispiacere che; (4) Impersonal expressions: è necessario che, è possibile che, bisogna che; (5) Conjunctions: benché/sebbene (although), affinché/perché (so that), prima che (before), a meno che (unless), senza che (without). Different subject in each clause required. Indicative used after: essere certo che (certain), è ovvio che (obvious) — these introduce certainty not uncertainty.","hard"),
      P("How do Italian pronouns work?","Think direct, indirect, and combined pronouns.","Italian object pronouns: Direct object (DO): mi, ti, lo/la, ci, vi, li/le (me, you, him/her, us, you all, them). Indirect object (IO): mi, ti, gli/le, ci, vi, gli (to me, to you, to him/her, to us, to you all, to them). Position: before conjugated verb (Lo vedo — I see him); attached to infinitive (Voglio vederlo); attached to gerund (Vedendolo). Double pronouns: IO before DO; IO changes: mi→me, ti→te, ci→ce, vi→ve, gli/le→glie-: Glielo do (I give it to him/her). Position with modal + infinitive: can go before modal or attach to infinitive: Lo voglio comprare / Voglio comprarlo. Stressed pronouns (after prepositions): me, te, lui/lei, noi, voi, loro.","hard"),
    ]),
    T("Italian Literature and Art",[
      P("Who are the major figures in Italian literature?","Think Dante, Petrarch, Boccaccio, and modern writers.","Italian literary canon: Medieval/Renaissance: Dante Alighieri (La Divina Commedia — Hell, Purgatory, Paradise; established literary Italian); Petrarch (Canzoniere — sonnets to Laura; founding figure of humanism; Petrarchan sonnet form); Boccaccio (Decameron — 100 tales in plague setting; realism, human comedy). Renaissance: Machiavelli (Il Principe — political realism); Ariosto (Orlando Furioso — epic). Modern: Manzoni (I Promessi Sposi — first Italian novel); Pirandello (theater, Sei personaggi in cerca d'autore — Nobel Prize); Calvino (Se una notte d'inverno un viaggiatore — postmodern); Primo Levi (Se questo è un uomo — Holocaust memoir); Elena Ferrante (L'amica geniale — contemporary Naples, female experience).","hard"),
    ]),
    T("Conversational Italian",[
      P("What expressions are essential for natural Italian conversation?","Think discourse markers and politeness.","Essential conversational expressions: Allora: all-purpose discourse marker — 'so,' 'then,' 'well'; begins responses, transitions. Dunque: 'therefore,' 'so' (more formal). Insomma: 'in short,' 'so-so,' 'well' — softens or summarizes. Cioè: 'that is,' 'I mean' — clarifies or corrects. Magari: 'maybe,' 'perhaps,' 'I wish!' — multipurpose and frequently used. Dai!: 'come on!' encouragement or mild exasperation. Ecco: 'there you go,' 'exactly,' 'here' — confirms or presents. Prego: 'you're welcome,' 'please go ahead,' 'here you are' — extremely versatile. Figurati/si figuri: 'don't mention it,' 'of course.' Meno male: 'thank goodness.' Beato te: 'lucky you.'","medium"),
    ]),
    T("Reading and Writing",[
      P("How do you approach writing formal Italian?","Think register and structure.","Formal Italian writing: (1) Lei (formal 'you' — capitalized) for second-person singular; (2) Conditional for requests (potrebbe instead of può — 'could you' vs 'can you'); (3) Subjunctive in subordinate clauses expressing uncertainty, opinion, desire; (4) Passato remoto (not prossimo) for distant historical past in formal writing; (5) Avoid contractions and colloquialisms; (6) Complex sentence structures — relative clauses, gerund constructions (avendo letto...), participial phrases; (7) Formal vocabulary — Latinisms and learned vocabulary; avoid false anglicismi in formal contexts. Email: Gentile + title (Gentile Professore,); Distinti saluti/Cordiali saluti as closing; state purpose in first paragraph.","medium"),
    ]),
    T("Contemporary Italy",[
      P("What are major contemporary issues in Italian society?","Think demographics, politics, and economy.","Contemporary Italian issues: (1) Demographic crisis — one of world's lowest birth rates; aging population; immigration to fill labor gaps; (2) Emigrazione — educated young Italians leaving for Germany, UK, Switzerland (cervelli in fuga — 'brain drain'); (3) Populism and political instability — Italy averages a new government roughly every year; coalition politics; rise of Fratelli d'Italia (Brothers of Italy) and other parties challenging traditional center; (4) Economy — North-South gap persists; public debt (~150% GDP); informal economy; (5) Mafia — Cosa Nostra (Sicily), Camorra (Naples), 'Ndrangheta (Calabria) — still significant economic forces despite judicial progress (Falcone, Borsellino assassinated 1992); (6) Cultural heritage preservation — balancing tourism with preservation.","hard"),
    ]),
  ],
  # Unit 5 — AP Japanese Language and Culture
  [
    T("Japanese Writing Systems",[
      P("What are the three Japanese writing systems and how are they used?","Think hiragana, katakana, and kanji.","Japanese uses three scripts simultaneously: (1) Hiragana (ひらがな): 46 syllabic characters; used for grammatical particles, verb/adjective endings, native Japanese words; soft, cursive appearance; (2) Katakana (カタカナ): 46 syllabic characters (same sounds as hiragana); used for foreign loanwords (テレビ/terebi=TV), foreign names, onomatopoeia, emphasis; more angular; (3) Kanji (漢字): Chinese-derived characters; thousands in use; joyo kanji = 2,136 required for daily literacy; combined with hiragana/katakana in normal text. Modern Japanese text mixes all three naturally: 今日は天気がいいです。(Today the weather is good.) — 今日 (kanji), は、が、い (hiragana), です (hiragana).","medium"),
      P("What is the Japanese honorific system (keigo)?","Think three levels of politeness.","Keigo (敬語) — formal/respectful language system: (1) Teineigo (丁寧語): polite language — ~です/~ます verb forms; appropriate for most formal contexts; (2) Sonkeigo (尊敬語): respectful language — elevates the actions of the person being spoken to/about; special verb forms (いらっしゃる for いる/ある/行く/来る; おっしゃる for 言う; なさる for する); (3) Kenjōgo (謙譲語): humble language — lowers the speaker's own actions to show respect; (参る for 行く/来る; 申す for 言う; いただく for もらう). Context: keigo essential in business, customer service, meeting elders; major source of difficulty for learners; Japanese children explicitly taught in school. Wrong keigo is socially significant error.","hard"),
    ]),
    T("Grammar Structure",[
      P("How does Japanese sentence structure differ from English?","Think SOV and particles.","Japanese is SOV (Subject-Object-Verb) — verb always at end of sentence: 私はリンゴを食べます (I apple eat). Particles: grammatical markers attached to nouns indicating their function: は(wa) — topic marker; が(ga) — subject marker; を(wo) — direct object; に(ni) — direction, location, time; で(de) — location of action, means; の(no) — possession; と(to) — and, with; も(mo) — also; から(kara) — from; まで(made) — until/to. Adjectives before nouns; modifying clauses before nouns; adverbs before verbs. Verb conjugation indicates tense, politeness, and mood — subjects often omitted (context clears ambiguity). Sentence-final particles: ね (seeking agreement), よ (assertion), か (question).","hard"),
      P("What is the difference between は (wa) and が (ga)?","Think topic vs. subject.","は vs. が: most challenging distinction for Japanese learners. は marks TOPIC — what the sentence is ABOUT (may or may not be subject); introduces contrast or known information: 私は学生です (As for me, I am a student). が marks GRAMMATICAL SUBJECT — new information, emphasis, or specific identification: 誰が来ましたか — 山田さんが来ました (Who came? Yamada came). Key uses of が: (1) New/unknown information (first mention); (2) After question words (誰が, 何が); (3) Subordinate clauses; (4) Stative verbs (わかる, できる, ある, いる — these require が not は); (5) Exclusive identification (これが私の本です — THIS is my book, not that). は signals contrast or given information; が signals new/focused subject.","hard"),
    ]),
    T("Japanese Culture",[
      P("What are key cultural values in Japanese society?","Think wa, amae, and giri.","Japanese cultural concepts: (1) 和 (wa) — harmony; avoiding conflict; group cohesion over individual assertion; consensus decision-making (nemawashi — informal consultation before formal meeting); (2) 甘え (amae) — presuming on another's goodwill; social indulgence and dependence; the comfort of dependence on trusted others; (3) 義理 (giri) — social duty and obligation; reciprocal gift-giving (return gifts expected); repaying social debts; (4) 本音と建前 (honne to tatemae) — true feelings vs. public face; public behavior may not reflect private opinion; maintaining social harmony through polite indirection; (5) 恥 (haji) — shame as social regulator; reputation and community standing; (6) 侘び寂び (wabi-sabi) — aesthetic of impermanence, imperfection, and incompleteness.","hard"),
      P("How does Japanese school and work culture shape society?","Think entrance exams and karoshi.","Education: entrance exam system (受験戦争 — examination war); elementary → middle → high school → university, each requiring competitive exams; juku (塾 — cram schools) common from elementary; university admissions highly prestigious (Todai — Tokyo University at apex). Work culture: 過労死 (karoshi — death from overwork); long hours culturally expected; 空気を読む (kuuki wo yomu — 'read the air' — understand unspoken expectations); seniority system (nenko joretsu) valued experience over performance in traditional companies; lifetime employment (shushin koyo) declining; work-life balance (work-style reform, 働き方改革) actively discussed as social problem. Demographic: low birth rate partly attributed to work culture; young women declining marriage and motherhood.","hard"),
    ]),
    T("Reading Japanese",[
      P("How do you read Japanese text efficiently?","Think kanji recognition and particle navigation.","Reading strategies: (1) Kanji recognition — high-frequency kanji carry most meaning; scan for content kanji; particles and grammatical elements in hiragana help parse structure; (2) Find the verb at end of sentence — work backward to understand predicate; (3) Identify topic (は) and subject (が) first; (4) Modifying clauses before nouns — everything before の or the modified noun is a modifier; (5) Nominalization — verb/adjective + こと or の turns clause into a noun phrase; (6) Context inference — kanji compounds often have transparent meaning (電話 = electric + speech = telephone); (7) Register — formal text (keigo forms, -de gozaimasu) vs. casual (informal verb forms, sentence-final particles).","hard"),
    ]),
    T("Listening and Speaking",[
      P("What challenges do learners face with spoken Japanese?","Think pitch accent and speed.","Spoken Japanese challenges: (1) Pitch accent — Tokyo dialect uses pitch distinctions (not tone like Chinese but pitch patterns matter for some words: hashi with high-low = chopsticks; low-high = bridge); not as critical as Chinese tones but contributes to nativeness; (2) Reduction in fast speech — particles reduced or dropped; sentences end abruptly; (3) Male vs. female speech — historically gendered vocabulary and speech patterns (ore/boku for 'I' in male speech; watashi in female/formal; ore is very casual male); (4) Kansai dialect — Osaka/Kyoto/Kobe region has distinctive dialect distinct from Tokyo standard; (5) Speed — newscaster speed very fast; casual conversation elliptical. Listening practice: Japanese news (NHK), anime (casual speech), variety shows (colloquial).","medium"),
    ]),
    T("Contemporary Japan",[
      P("What are major themes in contemporary Japanese society?","Think aging, technology, and gender.","Contemporary Japan: (1) Aging society (超高齢社会) — world's oldest society; 29%+ over 65; nursing care demands; robot care workers; immigration debate; (2) Population decline — birth rate 1.2; rural depopulation; ghost towns; government pro-natalist policies; (3) Hikikomori (引きこもり) — social withdrawal; estimated 1 million who barely leave home; youth isolation; (4) Gender inequality — Japan ranks very low on gender parity indices; slow progress in political and corporate leadership (though improving); (5) Cool Japan — cultural exports (anime, manga, video games, fashion); soft power strategy; (6) Environmental issues — nuclear energy debate post-Fukushima; coral reef bleaching; (7) US-Japan alliance — Okinawa base controversy.","medium"),
    ]),
    T("Japanese Literature and Media",[
      P("What are important works of Japanese literature?","Think classical and modern traditions.","Japanese literary landmarks: Classical: The Tale of Genji (源氏物語, Murasaki Shikibu, c. 1000 CE) — world's first novel?; court romance; psychological depth. Modern: Soseki Natsume (Kokoro — Meiji era change, alienation); Kawabata Yasunari (Snow Country — Nobel Prize, mono no aware); Mishima Yukio (provocative, nationalist, ritual suicide); Oe Kenzaburo (Nobel Prize, Hiroshima legacy, family disability); Murakami Haruki (Norwegian Wood, Kafka on the Shore — global readership, surrealism, West-Japan cultural synthesis); Ogawa Yoko (The Memory Police — quiet, unsettling). Manga and anime as literature: Miyazaki (Studio Ghibli), Osamu Tezuka (Astro Boy, Buddha) elevated as serious artistic tradition.","hard"),
    ]),
  ],
  # Unit 6 — AP Latin
  [
    T("Latin Grammar Foundations",[
      P("How does the Latin case system work?","Think six cases and their functions.","Latin nouns decline in six cases: (1) Nominative: subject (Marcus amat — Marcus loves); (2) Genitive: possession, 'of' (libri Marci — of Marcus's book); (3) Dative: indirect object, 'to/for' (Marco dat — gives to Marcus); (4) Accusative: direct object, motion toward (Marcum videt — sees Marcus; Romam it — goes to Rome); (5) Ablative: many functions — separation 'from,' instrument 'with/by,' location 'in' (with prepositions); ablative absolute; (6) Vocative: direct address (O Marce! — O Marcus!). Five declensions: nouns sorted by genitive singular ending. Adjectives agree with nouns in case, number, and gender — not necessarily same ending. Latin's inflected system means word order is flexible (SOV typical but variable).","hard"),
      P("How does Latin verb conjugation work?","Think four conjugations and tenses.","Latin verbs conjugate for person, number, tense, mood, and voice. Four conjugations: 1st (-āre), 2nd (-ēre), 3rd (-ere), 4th (-īre). Six tenses: Present (I love), Imperfect (I was loving/used to love), Future (I will love), Perfect (I loved/have loved), Pluperfect (I had loved), Future Perfect (I will have loved). Two voices: Active and Passive. Three moods: Indicative (fact), Subjunctive (command, doubt, purpose, indirect statement), Imperative (command). Principal parts: four forms that allow conjugation of all tenses (amo, amare, amavi, amatum). The subjunctive is extensively used in subordinate clauses — purpose (ut + subj), result (ut + subj), indirect command (ut + subj), cum clauses, indirect question.","hard"),
    ]),
    T("Reading Vergil and Caesar",[
      P("What are the key features of Vergil's Aeneid?","Think epic conventions and Augustan ideology.","Aeneid (Vergil, 19 BCE): 12 books; Aeneas flees Troy → Italy → founds Rome's ancestors. Epic conventions: invocation of Muse; in medias res beginning; divine machinery (Juno vs. Venus, Jupiter); epic similes; descent to Underworld (Book 6 — Aeneas meets Anchises); formulaic epithets. Dactylic hexameter: the meter of Homeric epic; Latin hexameter is quantitative (long/short syllables, not stress). Augustan ideology: Aeneas embodies Roman virtues (pietas — duty to gods, family, state); Rome's destiny (imperium sine fine — empire without end); Augustus as fulfillment of Rome's founding myth; written under Augustus's patronage. Tragic elements: Dido's death; Turnus's death — victory is not uncomplicated.","hard"),
      P("What characterizes Caesar's Latin style in the Gallic Wars?","Think third person and clarity.","Caesar's De Bello Gallico: written in clear, precise, 'classical' Latin — model of Latin prose style; third person ('Caesar did this' not 'I did') — military dispatch style; creates impression of objectivity; famous opening: 'Gallia est omnis divisa in partes tres.' Features: ablative absolutes (frequently used for background action); indirect statement with accusative + infinitive; cum clauses; relatively simple vocabulary for accessibility; periodic sentences. Historical context: Caesar wrote to justify his conquest of Gaul (58–50 BCE) to Roman public and Senate; political purpose behind apparent factual reporting; Vercingetorix's perspective entirely absent — read critically for what's omitted.","hard"),
    ]),
    T("Latin in Context",[
      P("How does Latin connect to modern languages and English vocabulary?","Think Romance languages and Latinate English.","Latin as linguistic ancestor: (1) Romance languages (Italian, Spanish, French, Portuguese, Romanian) evolved directly from Vulgar Latin — Latin as spoken by ordinary Romans; (2) English has vast Latinate vocabulary layer (alongside Germanic core): 'liberty' (libertas), 'justice' (justitia), 'education' (educatio), legal/medical/scientific terminology; (3) Derivatives: knowing Latin roots unlocks English vocabulary (aud- = hear → audit, auditor, audible; port- = carry → portable, transport, import; dict- = say → diction, predict, contradict); (4) Prefixes: pre-, post-, anti-, sub-, super-, inter-, trans-, dis-, con-/com-; (5) Legal Latin: habeas corpus, ex post facto, mens rea, prima facie; (6) Scientific nomenclature: binomial (genus species) in Latin.","medium"),
      P("What is the importance of mythology in reading Latin texts?","Think divine machinery and allusions.","Latin literature saturated with mythology — cannot read without it: Vergil's Aeneid requires knowing Trojan War (Homer), Olympian gods and their quarrels, underworld geography (Tartarus, Elysium, Styx, Charon, Cerberus). Ovid's Metamorphoses: 250 myths involving transformation — most comprehensive Latin mythology source. Key figures: Jupiter (king of gods), Juno (his wife, enemy of Rome/Aeneas), Venus (love, Aeneas's mother), Mars (war, father of Romulus), Mercury (messenger), Neptune (sea), Pluto (underworld), Apollo (sun, poetry, prophecy), Diana (moon, hunting), Minerva (wisdom). Roman vs. Greek names: Jupiter=Zeus, Juno=Hera, Venus=Aphrodite, Mars=Ares, Mercury=Hermes, Neptune=Poseidon, Pluto=Hades, Minerva=Athena.","medium"),
    ]),
    T("Advanced Latin Constructions",[
      P("What is the ablative absolute and how is it used?","Think participial phrase with ablative noun.","Ablative absolute: participial phrase in the ablative case, consisting of a noun + participle (both ablative), grammatically independent of the main clause. Translates as: 'with X having been done,' 'after X was done,' 'when X was done,' 'since X was done,' 'although X was done.' Examples: Caesare duce, milites fortiter pugnaverunt. (Caesar being the leader / With Caesar as leader, the soldiers fought bravely.) Omnibus rebus paratis, iter fecerunt. (With all things having been prepared, they made the journey.) Key: subject of ablative absolute is DIFFERENT from main clause subject — if same, use a simple participial phrase instead. Frequently used for background circumstances.","hard"),
      P("How does indirect statement work in Latin?","Think accusative + infinitive.","Indirect statement (oratio obliqua): after verbs of saying, thinking, knowing, perceiving — main clause verb + accusative subject + infinitive. Present infinitive: action simultaneous with main verb. Perfect infinitive: action prior to main verb. Future infinitive (future active participle + esse): action subsequent to main verb. Examples: Dico Marcum bonum esse. (I say Marcus to be good / I say Marcus is good.) Dico Marcum venisse. (I say Marcus to have come / I say Marcus came.) Romani putabant Caesarem vincturum esse. (The Romans thought Caesar would be about to conquer.) Passive indirect statement: passive infinitive forms. Negation: non before accusative or infinitive. Reflexive se/suus in indirect statement refers to subject of main verb.","hard"),
    ]),
    T("Roman History and Culture",[
      P("What are the major periods of Roman history and their significance?","Think Republic, Civil Wars, Empire.","Roman historical periods: Kingdom (753–509 BCE): legendary founding, Romulus, seven kings, expelled. Republic (509–27 BCE): Senate, consuls, checks on power; expansion across Mediterranean; Punic Wars (Carthage — Hannibal); Social War; Gracchi brothers' reforms; Marius and Sulla's civil wars; Caesar, Pompey, Crassus (First Triumvirate); Caesar's crossing of Rubicon; assassination (44 BCE). Principate/Early Empire (27 BCE–284 CE): Augustus → Julio-Claudians → Flavians → Five Good Emperors (Nerva, Trajan, Hadrian, Antoninus Pius, Marcus Aurelius) → Severans → Crisis of 3rd century. Late Empire (284–476 CE): Diocletian → Constantine (312 CE — Christianity); barbarian migrations; Western collapse 476 CE; Eastern (Byzantine) Empire survives until 1453.","hard"),
    ]),
    T("Ovid and Poetry",[
      P("What makes Ovid's poetry distinctive?","Think wit, elegance, and transformation.","Ovid (43 BCE–17 CE): most playful and intellectually sophisticated Augustan poet. Metamorphoses: 15 books; 250 myths involving physical transformation; from creation to Julius Caesar's apotheosis; elegiac couplets and hexameter; wit and irony; psychological complexity of characters (Daphne, Narcissus, Pygmalion, Medea). Ars Amatoria: Art of Love — mock-didactic poem teaching how to seduce; too subversive for Augustus → exiled to Tomis (Black Sea) with Tristia and Epistulae ex Ponto. Style: elegance, wit (callida iunctura — clever joining), wordplay; very un-Vergilian in tone; treated seriously as literary art but undermined Augustan moral reform. Influence: medieval and Renaissance literature saturated with Ovid.","hard"),
    ]),
    T("Translation Techniques",[
      P("How do you approach translating Latin accurately?","Think parsing and meaning.","Translation process: (1) Identify the main verb — its tense, mood, voice determine clause type; (2) Find the subject (nominative); (3) Find direct object (accusative); (4) Identify subordinate clauses — cum clauses, purpose clauses (ut + subj), relative clauses, indirect statement; (5) Parse every form before translating — identify case, number, gender of nouns; person, number, tense, mood, voice of verbs; (6) Watch for compound sentences; (7) Address ablative absolute and participial phrases; (8) Use vocabulary knowledge and context to disambiguate; (9) Produce fluent English that preserves the Latin's meaning. Common errors: confusing nominative and accusative in neuters; missing ablative absolute; wrong tense for infinitive in indirect statement.","hard"),
    ]),
  ],
  # Unit 7 — AP Spanish Language and Culture
  [
    T("Spanish Grammar Review",[
      P("When do you use ser vs. estar?","Think permanent vs. temporary — but with important exceptions.","Ser: (1) Identity — nationality, profession, religion: Soy americano; (2) Characteristics — physical/personality: Es alto, Es inteligente; (3) Origin: Es de México; (4) Material: Es de oro; (5) Relationships: Es mi hermano; (6) Time/date: Son las tres; (7) Passive voice with past participle: El libro fue escrito por García Márquez; (8) Location of events: La conferencia es en Madrid. Estar: (1) Location of people/objects: Está en casa; (2) Temporary states: Está cansado; (3) Results of actions: La puerta está abierta; (4) Progressive tenses: Está comiendo; (5) Emotions: Está feliz hoy. Key exceptions: muerto (dead) takes estar; with adjectives, ser vs. estar can change meaning: Es aburrido (He's boring) vs. Está aburrido (He's bored).","hard"),
      P("How does the Spanish subjunctive work?","Think WEIRDO categories.","Subjunctive (subjuntivo) triggers — WEIRDO: Wishes (querer que, desear que, esperar que), Emotion (alegrarse de que, tener miedo de que, sorprender que), Impersonal expressions (es necesario que, es importante que, es posible que), Recommendations/Requests (recomendar que, pedir que, sugerir que), Doubt/Denial (dudar que, no creer que, negar que), Ojalá (I hope that — always subjunctive). Conjunctions triggering subjunctive: para que, antes de que, aunque (when hypothetical), a menos que, con tal de que, sin que. Sequence of tenses: present/future main verb → present subjunctive; past main verb → imperfect subjunctive. Subjunctive vs. infinitive: same subject = infinitive (Quiero ir); different subject = que + subjunctive (Quiero que él vaya).","hard"),
    ]),
    T("Hispanic Culture",[
      P("What are key themes in Hispanic culture across different regions?","Think diversity within unity.","Spanish-speaking world: 20 countries + Spain; enormous diversity within shared language. Shared: Spanish language, Catholic heritage (though secularism growing), independence movements (1810s-20s), machismo/familismo tensions, magical realism in literature. Regional distinctions: Mexico — indigenous heritage (Aztec, Maya), Day of the Dead, muralism (Rivera, Orozco), NAFTA/trade dependence on US. Argentina — European immigration, tango, strong literary tradition (Borges, Cortázar), political volatility (peronism). Caribbean — Afro-Caribbean influences (Cuba, Puerto Rico, Dominican Republic); salsa, merengue; colonial sugar economy legacy. Spain — flamenco, Semana Santa, civil war memory (Franco 1939–75), regional identities (Catalonia, Basque, Galicia), EU membership and secularism.","hard"),
      P("What is magical realism and why is it associated with Latin American literature?","Think García Márquez and Boom literature.","Magical realism: literary mode where magical elements are presented as normal within realistic narrative — no distinction made between magic and mundane; characters accept extraordinary events without surprise. Associated with Latin American because: (1) Indigenous and African cosmologies naturally integrate spiritual and physical worlds; (2) Colonial history created surreal juxtapositions (European rationalism over indigenous spiritual worldview); (3) Political violence so extreme it seemed unreal (required new narrative forms). Gabriel García Márquez: Cien años de soledad (One Hundred Years of Solitude, 1967) — Nobel Prize; Macondo; Buendía family through generations; rain of yellow butterflies, levitation, woman ascending to heaven while hanging laundry. Boom generation: 1960s–70s Latin American novel explosion (Vargas Llosa, Fuentes, Cortázar, Donoso).","hard"),
    ]),
    T("Advanced Grammar",[
      P("How do the preterite and imperfect tenses work together?","Think completed action vs. background.","Preterite (pretérito indefinido): completed actions at specific time; events that move the narrative forward; sequence of completed events; interrupting action. Imperfect (pretérito imperfecto): background description; habitual/repeated past action; ongoing state; was + -ing; age/time/weather in past. Key contrast: Cuando llegué, ella leía (When I arrived [pret — completed], she was reading [imp — ongoing]). Story structure: imperfect sets the scene; preterite tells what happened. Trigger words: preterite (ayer, la semana pasada, de repente, en ese momento); imperfect (siempre, cada día, antes, generalmente). Meaning shifts: Supe (I found out) vs. Sabía (I knew); Pude (I managed to) vs. Podía (I was able to); Quise (I tried to) vs. Quería (I wanted to).","hard"),
      P("What are common mistakes English speakers make in Spanish?","Think false cognates and preposition use.","Common errors: (1) False cognates — embarazada = pregnant (not embarrassed); actual = current (not actual); realizar = to achieve/carry out (not to realize); molestar = to bother (not molest); sensible = sensitive (not sensible); (2) Por vs. para — por (exchange, duration, cause, per, through, on behalf of); para (purpose, destination, deadline, recipient, opinion); (3) Preposition omission — En español hablan (They speak Spanish — no 'in'); (4) Gender agreement — el agua (feminine but masculine article with initial stressed 'a'); (5) Subject pronouns — often unnecessary in Spanish (omit more than English); (6) Subjunctive triggers — English uses indicative where Spanish requires subjunctive ('when I arrive' = cuando llegue — future hypothetical needs subjunctive).","medium"),
    ]),
    T("Reading Hispanic Texts",[
      P("How do you analyze a Spanish-language text for the AP exam?","Think genre, register, and purpose.","AP Spanish reading tasks: (1) Identify source and genre (newspaper article, literary excerpt, email, infographic, advertisement); (2) Read title, caption, and visual elements first; (3) Read for main idea (idea principal); (4) Identify purpose (informar, persuadir, entretener, narrar); (5) Note register (formal/informal vocabulary, usted vs. tú); (6) Inference questions — what is implied but not stated?; (7) Vocabulary in context — use surrounding sentences to determine meaning of unfamiliar word; (8) Attitude/tone — how does the author feel about the subject?; (9) Cross-text comparison — how do two texts treat the same topic differently? AP texts drawn from print and digital sources across Spanish-speaking world — Latinoamérica and España represented.","medium"),
    ]),
    T("Writing Skills",[
      P("How do you write an effective argumentative essay in Spanish?","Think structure and evidence.","AP Spanish argumentative essay (Ensayo argumentativo): draws on 3 sources (audio, printed text, graph). Structure: Introduction — thesis clearly stating your position (La contaminación del plástico representa una crisis medioambiental urgente que requiere acción inmediata); Body paragraphs — each with claim + evidence from sources (attributed: Según la fuente número 1... En la entrevista con el experto...); must incorporate and cite all three sources; concede counterargument then refute; Conclusion — restate thesis with deeper insight + call to action or broader implications. Quality indicators: specific evidence from sources; range of vocabulary and grammar; subjunctive in appropriate places; transition words; clear argumentation; no unsupported generalizations.","hard"),
    ]),
    T("Interpersonal Communication",[
      P("What are effective strategies for AP Spanish speaking tasks?","Think simulated conversation and presentational speech.","AP Speaking tasks: (1) Simulated Conversation — 5 exchanges; listen to response, then have 20 seconds to reply; strategies: ask clarifying questions (¿Podría decirme más sobre...?); express opinions (En mi opinión..., Desde mi perspectiva..., Me parece que...); react to what was said (Es interesante lo que dices..., Entiendo tu punto pero...); elaborate (Además... Por otro lado... Sin embargo...); (2) Cultural Comparison — 4 minutes; compare your community with Spanish-speaking community on a cultural theme; use specific examples; avoid stereotypes; show cultural knowledge. Both: demonstrate range of vocabulary, grammatical accuracy, and natural communication — not scripted-sounding perfection.","medium"),
    ]),
    T("Contemporary Latin America and Spain",[
      P("What are major contemporary issues in the Spanish-speaking world?","Think migration, inequality, and democracy.","Contemporary issues: (1) Migration — Central American families fleeing violence and poverty; US-Mexico border; Venezuelan exodus (6+ million fleeing economic collapse); intra-regional migration; (2) Inequality — Latin America among world's most unequal regions; Gini coefficients; urban-rural gaps; indigenous communities; (3) Democratic fragility — Venezuela (authoritarian drift), Nicaragua (Ortega dictatorship), Bolivia tensions; but also democratic resilience; (4) Femicidio (femicide) — epidemic of gender-based violence; #NiUnaMenos movement; (5) Climate — Amazon deforestation (Brazil, Peru); rising seas threatening Caribbean; drought in Chile and Argentina; (6) Spain — Catalan independence movement; post-Franco memory; economic recovery after 2008 crisis; younger generation's precariedad laboral (job insecurity).","hard"),
    ]),
  ],
  # Unit 8 — AP Spanish Literature and Culture
  [
    T("Medieval and Renaissance Literature",[
      P("What is the significance of El Cid in Spanish literature?","Think epic hero and national identity.","Cantar de Mio Cid (c. 1200): only preserved Spanish medieval epic; recounts deeds of Rodrigo Díaz de Vivar (El Cid — from Arabic 'lord/master'). Historical: real 11th-century Castilian noble exiled by Alfonso VI; fought for both Christian and Muslim lords (pragmatic, not purely religious). Literary: epic conventions (repetition, epithets, oral style); realistic detail (unlike French chansons de geste); focus on honor (honra) and social rehabilitation; Reconquista context (Christian kingdoms reclaiming Iberian Peninsula from Moors). Significance: first major Spanish literary work; established themes of honor, loyalty, and Castilian identity; model of Spanish literary hero — competent, honorable, warrior.","medium"),
      P("What is the picaresque novel and why is it important?","Think Lazarillo de Tormes and social satire.","Picaresque (picaresca): Spanish narrative genre; protagonist is pícaro (rogue, scoundrel) from low social class; narrates own life episodically; serves various masters (each represents social class/institution); social satire (exposes hypocrisy of church, nobility, society). Lazarillo de Tormes (1554, anonymous): first picaresque; Lázaro serves blind beggar, priest, nobleman — each episode exposes their hypocrisy; first-person confession structure addressed to 'Vuestra Merced.' Significance: (1) First prose narrative with continuous protagonist development; (2) Realistic portrayal of ordinary life (vs. idealized chivalric romance); (3) Social criticism through irony; (4) Challenges honor society's false values; (5) Genre influenced European novel (Defoe, Fielding, Dickens).","hard"),
    ]),
    T("Golden Age (Siglo de Oro)",[
      P("What is Don Quijote and why is it considered the first modern novel?","Think Cervantes and self-consciousness.","Don Quijote (Cervantes, Part I 1605, Part II 1615): hidalgo (minor nobleman) reads too many chivalric romances → believes himself knight-errant; sets out with Sancho Panza (peasant squire). Why 'first modern novel': (1) Self-conscious narrative — characters in Part II have read Part I; author appears; multiple narrative levels; (2) Psychological character development; (3) Explores relationship between literature and reality; (4) Multiple interpretive layers — simultaneously comedy, tragedy, social satire; (5) Neither pure comedy nor pure tragedy. Major themes: idealism vs. realism (Quijote's vision vs. Sancho's pragmatism); the power and danger of fiction; social hierarchy; identity and self-construction. Most translated work after the Bible.","hard"),
      P("How does Lope de Vega's drama represent the comedia nueva?","Think Spanish national theater.","Lope de Vega (1562–1635): most prolific playwright in history (~1,800+ plays, 400+ survive); invented the comedia nueva — new form of Spanish theater. Features: three acts (vs. classical five); mixed tragic and comic elements (vs. classical separation); honor (honra) as central theme; variety of poetic meters for different situations; galán (romantic lead), dama (lady), gracioso (comic servant — like Shakespeare's fool), padre/rey; popular verse forms (romance, sonnet); action over philosophical reflection. Arte Nuevo de Hacer Comedias (1609): Lope's manifesto — rejected classical rules to please popular audiences. Key plays: Fuenteovejuna (collective honor; villagers kill tyrannical commander), El perro del hortelano. Influenced European theater.","hard"),
    ]),
    T("19th Century Literature",[
      P("What is Romanticism in Spanish literature?","Think Espronceda and Bécquer.","Spanish Romanticism (1830s–1860s): delayed compared to France and England; political context of liberal vs. conservative conflict. Characteristics: individualism; emotion over reason; nature as reflection of inner state; medieval themes; nationalism; outcasts and rebels as heroes. José de Espronceda: 'El estudiante de Salamanca,' 'Canción del pirata' — Byronic heroes, defiance, passion. Gustavo Adolfo Bécquer: Rimas y Leyendas — most beloved Romantic poet; pure lyric; love, loss, and the ineffable (things that cannot be expressed in words); 'Los ojos verdes,' 'El monte de las ánimas.' Costumbrismo: parallel movement depicting Spanish customs and characters realistically — sketch tradition.","medium"),
      P("What is Realism in 19th-century Spanish literature?","Think Galdós and social criticism.","Spanish Realism (1870s–1900): influenced by Balzac, Dickens, Zola. Benito Pérez Galdós: most important Spanish Realist novelist; Episodios Nacionales (46 novels chronicling 19th-century Spanish history); Fortunata y Jacinta (social classes, love, women's fate); Misericordia (charity, poverty, religious faith); Doña Perfecta (religious fanaticism vs. progressive liberalism). Leopoldo Alas 'Clarín': La Regenta — provincial capital, repressed female desire, Church and aristocracy's suffocating power; considered greatest Spanish Realist novel after Galdós. Characteristics: detailed social observation; middle-class settings; implicit social criticism; female characters constrained by society; determinism.","hard"),
    ]),
    T("Generation of 98 and Modernismo",[
      P("What was the Generation of 1898 and what problems did it address?","Think Spain's crisis of identity.","Generation of 1898: group of Spanish writers responding to Spain's defeat in Spanish-American War (1898) — lost Cuba, Puerto Rico, Philippines; end of empire; national crisis. Crisis del 98 prompted deep examination of Spanish identity and national problems. Writers: Miguel de Unamuno (existential philosophy; Del sentimiento trágico de la vida; Niebla — metafiction); Antonio Machado (Campos de Castilla — Castilian landscape as meditation on Spain's soul; 'Caminante, son tus huellas...'); Ramón del Valle-Inclán (esperpento — grotesque distortion as method; Luces de Bohemia); Pío Baroja (nihilistic novels; Basque roots). Common concerns: spiritual regeneration; Europeanization vs. Spanish essence; rural Spain as authentic; philosophical pessimism.","hard"),
      P("What is Modernismo in Latin American poetry?","Think Rubén Darío and aesthetic revolution.","Modernismo: first major literary movement originating in Latin America (late 19th century) — reversed cultural dependence on Spain. Rubén Darío (Nicaragua): leading figure; Azul (1888), Prosas Profanas, Cantos de Vida y Esperanza. Characteristics: aesthetic refinement; musicality of verse (perfect meter, rich sound patterns); French Symbolism and Parnassianism influence; exotic imagery (swans, versailles, Orient); Latin American landscape; cosmopolitanism; 'art for art's sake.' Reaction: to bourgeois utilitarianism of 19th century; created autonomous aesthetic realm. Influence: returned to Spain, revitalizing Spanish poetry (Generación del 98 partly reacted against it); foundation for 20th-century Spanish-language poetry (Lorca, Neruda trace debt to Darío).","hard"),
    ]),
    T("20th Century Poetry",[
      P("What is Federico García Lorca's contribution to Spanish literature?","Think duende, tragedy, and political silencing.","García Lorca (1898–1936): most celebrated 20th-century Spanish poet and playwright; killed by Nationalist forces at start of Civil War. Poetry: Romancero Gitano (Gypsy Ballads) — mythologized Andalusian gypsy culture; Poeta en Nueva York — Surrealist response to modern city; intense imagery, duende (dark inspiration, presentiment of death). Plays: Bodas de Sangre (Blood Wedding), Yerma, La Casa de Bernarda Alba — trilogy of rural tragedies; female oppression; honor; frustrated desire; natural imagery; Greek tragedy structure. Duende: Lorca's concept of dark, earthy, death-aware inspiration essential to flamenco and authentic art. His death gave his work additional political resonance — symbol of Republican Spain silenced.","hard"),
      P("What characterizes Pablo Neruda's poetry?","Think love, politics, and Chile.","Pablo Neruda (1904–1973, Chile): most widely read Spanish-language poet; Nobel Prize 1971. Major works: Veinte poemas de amor y una canción desesperada (1924) — erotic love poetry; extraordinary popularity. Residencia en la tierra — Surrealist/expressionist; dark, tumultuous imagery. Canto General (1950): epic political poem; history of Latin America; indigenous heritage; imperialism; Communist commitment (Neruda was Communist Party member). Odas elementales: celebration of ordinary objects (tomato, salt, artichoke, socks) with wonder and political egalitarianism. Style evolves dramatically across career — from romantic to Surrealist to political epic to accessible odes. 'Para que tú me oigas' and 'Tonight I can write...' among most anthologized love poems.","hard"),
    ]),
    T("Contemporary Literature",[
      P("What is the Boom of Latin American literature?","Think major authors and international impact.","The Boom (1960s–1970s): explosive international recognition of Latin American literature. Context: Cuban Revolution (1959) generated political and intellectual ferment; innovative publishing industry in Spain and Argentina; translations reaching global audiences. Major authors: Gabriel García Márquez (Cien años de soledad, Colombia); Mario Vargas Llosa (La ciudad y los perros, La fiesta del Chivo, Peru — Nobel Prize 2010); Julio Cortázar (Rayuela — Hopscotch, Argentina; reader-participation structure); Carlos Fuentes (La muerte de Artemio Cruz, Mexico); José Donoso (El obsceno pájaro de noche, Chile). Characteristics: magical realism, technical experimentation, political engagement, long complex novels, questioning Western narrative conventions. Post-Boom: women writers (Isabel Allende), shorter forms, less experimentalism.","hard"),
      P("Who are the major contemporary Spanish and Latin American authors?","Think post-Franco Spain and post-Boom generation.","Contemporary literature: Post-Franco Spain: Juan Marsé (Sin noticias de Gurb); Juan Goytisolo (exile, sexuality, Islam); Almudena Grandes (Las edades de Lulú, El corazón helado — Civil War memory). Latin America: Roberto Bolaño (Los detectives salvajes, 2666, Chile/Mexico — epic, dark, literary detective fiction; died 2003; enormous posthumous influence); Elena Ferrante-esque wave of women writers; Valeria Luiselli (México/US — migration, essay, autofiction); Daniel Sada (baroque Mexican prose); Carmen Boullosa; Edmundo Paz Soldán. Contemporary themes: memory and trauma (Civil War in Spain; dictatorships in Latin America); migration and borders; gender and sexuality; postmodern textuality; neoliberalism's effects on daily life.","hard"),
    ]),
    T("Drama and Theater",[
      P("How does Calderón de la Barca's drama represent the honor code?","Think La vida es sueño and honor plays.","Calderón de la Barca (1600–1681): greatest Spanish Baroque playwright; court dramatist for Philip IV. La vida es sueño (Life is a Dream, 1635): prince Segismundo imprisoned from birth; freed temporarily; commits crimes; returns to prison; given second chance — chooses virtue over passion; life as dream = reality uncertain; free will vs. fate; honor and self-mastery. Honor plays (dramas de honor): El médico de su honra — husband kills innocent wife on mere suspicion of dishonor; disturbing, morally complex; reflects (and critiques?) honor code's extremity. Auto sacramental: allegorical religious one-act plays; Calderón wrote finest examples. Baroque style: concepto (conceptism — intellectual wit, complex metaphors); culteranismo (Góngora's obscure Latinate style).","hard"),
    ]),
    T("Literary Analysis in Spanish",[
      P("How do you analyze a Spanish literary text for the AP Literature exam?","Think narrative techniques and cultural context.","AP Spanish Literature analysis: (1) Identify narrative perspective — first person (limited, biased), third person omniscient, limited omniscient; (2) Time structure — linear, non-linear, flashback (analepsis), flash-forward (prolepsis); (3) Literary devices — metáfora, símil, personificación, hipérbole, anáfora, aliteración, oxímoron, paradoja; (4) Space/setting — realistic vs. symbolic; (5) Character types — protagonista, antagonista, foil; psychological depth; (6) Major themes — connect to cultural/historical context; (7) Register and style — formal/colloquial, archaic/contemporary; (8) Intertextuality — what other texts does this reference? Write in Spanish with literary vocabulary: narrador, protagonista, trama, desenlace, clímax, tema, motivo, símbolo, punto de vista.","hard"),
    ]),
  ]
]
