"""AP Science: 7 units matching curriculum (Bio, Chem, EnvSci, Physics 1, Physics 2, Physics C Mech, Physics C E&M)"""

def T(title, problems):
    return {"title": title, "problems": problems}

def P(q, ex, a, diff):
    return {"q": q, "ex": ex, "a": a, "diff": diff}

AP_SCIENCE = [
  # Unit 1 — AP Biology
  [
    T("Chemistry of Life", [
      P("What properties of water make it essential for life?","Think about polarity, cohesion, adhesion, and specific heat.","Water's polarity allows hydrogen bonding, creating: (1) Cohesion (water-water attraction) — enables transpiration in plants; (2) Adhesion (water-surface attraction) — capillary action; (3) High specific heat — moderates temperature; (4) Solvent properties — dissolves ionic and polar molecules; (5) Ice less dense than liquid — lakes freeze from top, protecting aquatic life.","medium"),
      P("Distinguish between dehydration synthesis and hydrolysis.","Think about water's role in each.","Dehydration synthesis (condensation): monomers join by releasing a water molecule — builds polymers (proteins, carbs, nucleic acids, lipids). Hydrolysis: water molecule is added to break the bond between monomers — digestion is hydrolysis. They are reverse reactions.","easy"),
      P("Compare the four macromolecule classes: carbohydrates, lipids, proteins, nucleic acids.","Think about monomers, functions, and key features.","Carbohydrates: monomer=monosaccharide; energy storage (glycogen, starch), structural (cellulose). Lipids: glycerol+fatty acids; energy storage (fats), membrane structure (phospholipids), hormones (steroids). Proteins: monomer=amino acid; enzymes, structural, transport, signaling. Nucleic acids: monomer=nucleotide; genetic information storage (DNA) and expression (RNA).","medium")
    ]),
    T("Cell Structure and Function", [
      P("Compare prokaryotic and eukaryotic cells.","Think about membrane-bound organelles and nucleus.","Prokaryotes: no nucleus (DNA in nucleoid region), no membrane-bound organelles, smaller (1–10 μm), circular DNA. Examples: bacteria, archaea. Eukaryotes: membrane-bound nucleus, membrane-bound organelles (mitochondria, ER, Golgi), larger (10–100 μm), linear chromosomes. Examples: protists, fungi, plants, animals.","easy"),
      P("What is the function of the endomembrane system?","Think about ER, Golgi, and vesicles.","The endomembrane system processes and ships proteins/lipids: Rough ER studded with ribosomes — synthesizes and folds membrane/secretory proteins. Smooth ER — lipid synthesis, detoxification. Golgi apparatus — modifies, sorts, and packages proteins into vesicles for secretion or delivery to organelles. Vesicles transport materials between compartments.","medium"),
      P("How does the fluid-mosaic model describe the cell membrane?","Think about phospholipids, proteins, and membrane fluidity.","The fluid-mosaic model (Singer & Nicolson, 1972): the membrane is a fluid phospholipid bilayer (hydrophilic heads outward, hydrophobic tails inward) embedded with proteins (integral and peripheral). 'Fluid' — lipids and proteins can move laterally. 'Mosaic' — proteins of various types are embedded throughout. Cholesterol regulates fluidity (prevents crystallization at low temp, prevents excessive fluidity at high temp).","medium")
    ]),
    T("Cellular Energetics (Photosynthesis and Respiration)", [
      P("Write the overall equations for photosynthesis and cellular respiration and explain how they are related.","Think about reactants and products of each.","Photosynthesis: 6CO₂+6H₂O+light → C₆H₁₂O₆+6O₂. Cellular respiration: C₆H₁₂O₆+6O₂ → 6CO₂+6H₂O+ATP. They are essentially reverse reactions — photosynthesis stores energy in glucose, respiration releases it. Carbon cycles between atmosphere and organisms through these reactions.","easy"),
      P("Describe the two stages of photosynthesis and where each occurs.","Think about light-dependent and light-independent reactions.","Light reactions (thylakoid membranes): light absorbed by chlorophyll; water split (photolysis) → O₂ released; ATP and NADPH produced; electron transport drives ATP synthase. Calvin cycle (stroma): ATP and NADPH used to fix CO₂ into G3P (3-carbon sugar) via RuBisCO; three turns fix 3CO₂ and produce 1 G3P net, which is used to build glucose.","medium"),
      P("Explain why aerobic respiration yields far more ATP than anaerobic fermentation.","Think about electron transport chain vs. substrate-level phosphorylation.","Aerobic respiration: ~30–32 ATP per glucose — most from oxidative phosphorylation (electron transport chain + chemiosmosis using O₂ as final electron acceptor). Fermentation: only 2 ATP per glucose (from glycolysis alone, substrate-level phosphorylation). Fermentation regenerates NAD⁺ to keep glycolysis running but produces only lactate or ethanol — no additional ATP from ETC.","medium")
    ]),
    T("Cell Communication and Cell Cycle", [
      P("Describe the three stages of cell signaling.","Think about reception, transduction, response.","(1) Reception: signal molecule (ligand) binds to specific receptor on target cell (surface receptor or intracellular). (2) Transduction: signal is relayed and amplified through a cascade of molecular changes (second messengers like cAMP, protein kinase cascades). (3) Response: change in cell activity — altered enzyme activity, gene expression, or cellular behavior.","medium"),
      P("What are proto-oncogenes and tumor suppressor genes, and what happens when they mutate?","Think about the accelerator and brake analogy.","Proto-oncogenes: normal genes that promote cell division (growth factors, their receptors, signal transducers). Mutation → oncogene → stuck in 'on' position → excessive proliferation (cancer). Tumor suppressor genes: normally inhibit cell division or trigger apoptosis (p53, Rb). Mutation (loss of function) → removes brakes on division → cancer. Cancer typically requires mutations in multiple genes.","hard"),
      P("Describe the four phases of the cell cycle and checkpoint control.","Think about G1, S, G2, M phases.","G1: cell grows, prepares for DNA synthesis (checkpoint: is cell large enough? Is environment favorable?). S: DNA replication. G2: cell prepares for division (checkpoint: DNA correctly replicated?). M (Mitosis): cell divides. Checkpoints use CDKs and cyclins to regulate progression. M checkpoint: are chromosomes properly attached to spindle? Apoptosis (programmed cell death) is triggered if errors aren't corrected.","medium")
    ]),
    T("Heredity and Genetics", [
      P("What is the difference between Mendelian and non-Mendelian inheritance? Give an example of each.","Think about complete dominance vs. exceptions.","Mendelian: one gene, two alleles, complete dominance (one allele masks the other). Example: pea plant height (T tall over t short). Non-Mendelian examples: Codominance — both alleles fully expressed (AB blood type). Incomplete dominance — heterozygote is intermediate (red + white flower → pink). Multiple alleles — more than two alleles in population (ABO blood type has IA, IB, i). Polygenic — many genes affect one trait (skin color, height).","medium"),
      P("Solve: Aa × Aa cross. What fraction of offspring are homozygous dominant?","Use a Punnett square.","Aa × Aa: AA:Aa:aa = 1:2:1 = 25%:50%:25%. Homozygous dominant (AA) = 25% = 1/4.","easy"),
      P("What is the chromosomal basis of sex determination in humans, and how does X-linkage affect inheritance patterns?","Think about X and Y chromosomes and carrier females.","Humans: XX=female, XY=male. Y chromosome carries SRY gene (testis-determining factor). X-linked traits: gene on X chromosome — males (XY) have only one X so a single recessive allele causes the trait (hemizygous). Females (XX) need two recessive alleles to express the trait; one gives carrier status. Result: X-linked recessives (color blindness, hemophilia) appear more often in males.","medium")
    ]),
    T("Gene Expression and Regulation", [
      P("Trace the flow of genetic information from DNA to protein (the central dogma).","Think about transcription and translation locations.","DNA (nucleus) → Transcription → pre-mRNA → RNA processing (splicing, capping, poly-A tail) → mRNA → exits nucleus → Translation (ribosome in cytoplasm) → polypeptide → post-translational modification → functional protein. Direction: DNA→RNA→Protein. Reverse transcriptase (retroviruses) can go RNA→DNA, but normally information doesn't flow back from protein.","easy"),
      P("How do the lac operon and trp operon illustrate gene regulation by environmental signals?","Think about inducible vs. repressible operons.","Lac operon (inducible): repressor protein normally blocks transcription; when lactose is present, an inducer (allolactose) binds the repressor and inactivates it → transcription of lactose-digesting enzymes. Trp operon (repressible): repressor is inactive until tryptophan (corepressor) binds it → activated repressor blocks transcription. Both are negative feedback systems that efficiently regulate enzyme production based on nutrient availability.","hard"),
      P("What is epigenetics and how does DNA methylation affect gene expression?","Think about heritable changes not in DNA sequence.","Epigenetics: heritable changes in gene expression without changes to DNA sequence. DNA methylation: methyl groups added to cytosine (CpG sites) → compacts chromatin → silences gene transcription. Histone modification (acetylation): opens chromatin → increases transcription. Environmental factors (diet, stress, toxins) can alter epigenetic marks. Some epigenetic changes are heritable across generations (transgenerational epigenetics).","hard")
    ]),
    T("Natural Selection and Evolution", [
      P("State the four conditions necessary for natural selection.","Think about variation, heritability, selection pressure, and differential reproduction.","(1) Variation: individuals differ in traits. (2) Heritability: traits are passed from parent to offspring (genetic basis). (3) Selection pressure: environment favors some variants over others. (4) Differential reproductive success: individuals with favorable variants leave more offspring. Result: favored allele frequencies increase over generations — population adapts to its environment.","easy"),
      P("Explain the difference between directional, stabilizing, and disruptive natural selection.","Think about which phenotypes are favored.","Directional: favors one extreme phenotype; shifts population mean in one direction (e.g., antibiotic resistance). Stabilizing: favors the intermediate phenotype; reduces variation (e.g., birth weight in humans — very small or very large babies have lower survival). Disruptive: favors both extremes over the intermediate; can lead to two subpopulations (e.g., bill size in Darwin's finches during drought).","medium"),
      P("What is the Hardy-Weinberg principle and what are its five conditions?","Think about what causes evolution.","Hardy-Weinberg: in the absence of evolutionary forces, allele and genotype frequencies remain constant. Equation: p²+2pq+q²=1. Five conditions (must all be met for H-W equilibrium): (1) Large population (no genetic drift), (2) Random mating, (3) No mutation, (4) No gene flow (no migration), (5) No natural selection. H-W equilibrium is a null model — deviations indicate evolution is occurring.","medium")
    ]),
    T("Ecology and Population Dynamics", [
      P("Define and compare the three levels of ecology: population, community, and ecosystem.","Think about scale and interactions.","Population ecology: studies groups of same species — growth, size, density, age structure. Community ecology: studies interactions among different species — predation, competition, symbiosis, succession. Ecosystem ecology: studies living (biotic) and nonliving (abiotic) components and energy/nutrient flow — food webs, nutrient cycles, energy pyramids.","easy"),
      P("Compare logistic and exponential population growth models.","Think about the effect of carrying capacity.","Exponential growth: dN/dt=rN — unlimited resources, population grows geometrically (J-shaped curve). Not realistic long-term. Logistic growth: dN/dt=rN(K−N)/K — growth slows as population approaches carrying capacity K (S-shaped/sigmoidal curve). Growth is fastest at N=K/2 (inflection point). Most populations follow logistic growth when resource-limited.","medium"),
      P("What is the difference between primary and secondary ecological succession?","Think about the starting conditions.","Primary succession: begins on bare substrate with no soil (after glacial retreat, volcanic rock, sand dunes). Pioneer species (lichen, mosses) begin soil formation. Very slow. Secondary succession: begins after disturbance in area that already has soil (after fire, clear-cutting, abandonment of farmland). Starts with fast-growing pioneer species, progresses to climax community. Faster than primary because soil is already present.","medium")
    ])
  ],
  # Unit 2 — AP Chemistry
  [
    T("Atomic Structure and Properties", [
      P("Explain how the photoelectric effect supports the particle nature of light.","Think about photons and threshold frequency.","The photoelectric effect (Einstein, 1905): when light shines on metal, electrons are ejected — but only if frequency exceeds a threshold, regardless of intensity. This proves light comes in discrete packets (photons) with energy E=hf. Below threshold: no electrons ejected (photon energy too low), even with bright light. Above threshold: electrons ejected immediately. Classical wave theory couldn't explain the threshold — particle nature of light (photons) was required.","hard"),
      P("Write the electron configuration of Fe (Z=26) and Fe²⁺.","Think about filling order and removing electrons from highest energy level.","Fe (Z=26): 1s²2s²2p⁶3s²3p⁶3d⁶4s² or [Ar]3d⁶4s². Fe²⁺: remove 2 electrons from 4s first (higher energy subshell loses electrons first). Fe²⁺: [Ar]3d⁶.","medium"),
      P("Explain the trend in electronegativity across periods and down groups.","Think about nuclear charge and atomic radius.","Across a period (left→right): electronegativity increases — more protons pull electrons more strongly, atomic radius decreases. Down a group (top→bottom): electronegativity decreases — increased shielding from inner electrons reduces effective nuclear charge; larger atomic radius places bonding electrons farther from nucleus. Most electronegative: F. Least: Cs/Fr.","medium")
    ]),
    T("Molecular and Ionic Compound Structure", [
      P("Predict the geometry of SO₃ using VSEPR theory.","Think about electron domains and molecular geometry.","Lewis structure: S is central atom, double-bonded to three O atoms. 3 bonding domains, 0 lone pairs on S. VSEPR: 3 electron domains → trigonal planar geometry. Bond angles: 120°. Molecular shape: trigonal planar.","medium"),
      P("Distinguish between ionic, polar covalent, and nonpolar covalent bonds.","Think about electronegativity differences.","Ionic: large electronegativity difference (ΔEN>1.7 approx.) — electron transferred from metal to nonmetal; forms ions (NaCl). Polar covalent: moderate ΔEN (0.4–1.7) — electrons shared unequally; creates partial charges δ+/δ− (H₂O, HCl). Nonpolar covalent: ΔEN<0.4 — electrons shared equally (H₂, N₂, C-H bonds).","medium"),
      P("How does VSEPR predict that water is bent rather than linear?","Think about lone pairs.","O in H₂O has 2 bonding pairs and 2 lone pairs = 4 electron domains → tetrahedral electron geometry. Lone pairs repel more strongly than bonding pairs, compressing the H-O-H bond angle from the ideal 109.5° to ~104.5°. Molecular geometry (counting only atoms): bent/V-shaped. The bent shape makes water polar overall (bond dipoles don't cancel).","hard")
    ]),
    T("Intermolecular Forces and Properties", [
      P("Rank these in order of increasing boiling point: CH₄, HF, H₂O, HCl.","Think about the types of intermolecular forces in each.","IMFs: CH₄ — only London dispersion (weakest). HCl — dipole-dipole + London. HF — hydrogen bonding + London. H₂O — hydrogen bonding + London (more extensive network than HF due to 2 H-bond donors). Ranking: CH₄ < HCl < HF < H₂O. (H₂O has unexpectedly high bp because of its extensive H-bond network with 2 donors and 2 acceptors.)","medium"),
      P("Explain why dissolving NaCl in water involves both enthalpy and entropy changes.","Think about lattice energy and hydration energy.","Enthalpy: breaking NaCl lattice (endothermic, requires lattice energy) vs. hydration of ions by water (exothermic). For NaCl, ΔH_soln is slightly positive but small. Entropy: dissolving increases disorder (solid → dispersed ions in solution) → ΔS>0. ΔG=ΔH−TΔS; even with slightly positive ΔH, the large +ΔS makes ΔG negative → dissolution is spontaneous. Entropy drives NaCl dissolution.","hard"),
      P("What is surface tension and why is it higher in water than in ethanol?","Think about cohesive forces.","Surface tension: the force per unit length or energy per unit area at a liquid surface, caused by unbalanced cohesive forces on surface molecules. Water: extensive hydrogen bonding network creates strong cohesive forces → high surface tension (72 mN/m). Ethanol: has H-bonds but also a nonpolar ethyl group that disrupts the H-bond network → lower surface tension (~22 mN/m). Water's surface tension is the reason some insects can walk on water.","medium")
    ]),
    T("Chemical Reactions", [
      P("Balance the equation: Fe₂O₃+CO→Fe+CO₂","Count atoms of each element; adjust coefficients.","Unbalanced: Fe₂O₃+CO→Fe+CO₂. Fe: 2 on left, need 2 right → 2Fe. O: 3+1=4 left, 2 right → need 2CO₂ (4 O right) and fix CO count. Recount: Fe₂O₃+3CO→2Fe+3CO₂. Check: Fe:2=2✓, O:3+3=6=6✓, C:3=3✓. Balanced.","easy"),
      P("Classify each reaction: (a) 2H₂+O₂→2H₂O (b) CaCO₃→CaO+CO₂ (c) Zn+2HCl→ZnCl₂+H₂","Think about synthesis, decomposition, single replacement, double replacement, combustion.","(a) Synthesis (combination): two elements/compounds combine → one product. (b) Decomposition: one compound breaks into simpler substances. (c) Single replacement: one element displaces another in a compound (Zn is more active than H, displaces it from HCl).","easy"),
      P("Calculate the theoretical yield of H₂O when 4g H₂ reacts with 32g O₂.","Think about mole ratios and limiting reagent.","2H₂+O₂→2H₂O. Moles H₂=4/2=2 mol; moles O₂=32/32=1 mol. Ratio needed: 2:1 H₂:O₂. We have exactly 2:1 → both are consumed. Moles H₂O=2 mol. Mass=2×18=36g H₂O.","medium")
    ]),
    T("Kinetics", [
      P("For the rate law rate=k[A]²[B], how does the rate change if [A] doubles?","Think about the order with respect to A.","Second order in A: rate ∝ [A]². If [A] doubles → [A]²=4×original [A]² → rate quadruples (×4), assuming [B] constant.","easy"),
      P("Explain the effect of a catalyst on activation energy and rate.","Think about the energy diagram.","A catalyst provides an alternative reaction pathway with lower activation energy (Ea). On the energy diagram, the transition state peak is lower. Lower Ea → exponentially more molecules have sufficient energy to react (Arrhenius equation: k=Ae^{−Ea/RT}) → faster rate. The catalyst is not consumed (regenerated) and does not change ΔH (reactant and product energies unchanged).","medium"),
      P("What is the integrated rate law for a first-order reaction, and how is half-life derived from it?","Think about ln[A] vs time.","First-order: rate=k[A]. Integrated: ln[A]=ln[A]₀−kt. Half-life: at t=t½, [A]=[A]₀/2. ln([A]₀/2)=ln[A]₀−kt½ → ln(1/2)=−kt½ → t½=0.693/k. Key feature: t½ is constant for first-order reactions (independent of concentration). Radioactive decay follows first-order kinetics.","medium")
    ]),
    T("Thermodynamics", [
      P("State the first and second laws of thermodynamics in plain language.","Think about energy conservation and entropy.","First law: energy is conserved — it can be converted between forms but cannot be created or destroyed. ΔU=q+w (internal energy change = heat added + work done on system). Second law: in any spontaneous process, total entropy of the universe increases (ΔS_universe>0). No process is perfectly efficient; some energy is always lost to disorder.","easy"),
      P("Predict spontaneity using ΔG=ΔH−TΔS for: ΔH=−50kJ, ΔS=+100J/K at 298K.","Calculate ΔG and interpret sign.","ΔG=ΔH−TΔS=−50,000J−(298)(100J/K)=−50,000−29,800=−79,800J=−79.8kJ. ΔG<0 → spontaneous (favorable) at 298K. Both enthalpy (exothermic) and entropy (+ΔS) favor spontaneity.","medium"),
      P("What is Hess's Law and how is it used to calculate ΔH for a reaction?","Think about adding reactions like algebraic equations.","Hess's Law: ΔH is a state function — independent of path. Therefore, ΔH for a reaction can be calculated by adding the ΔH values of steps that sum to the overall reaction. Technique: flip reactions as needed (changes sign of ΔH), multiply by coefficients (multiplies ΔH), add all ΔH values. Standard enthalpies of formation (ΔH°f) can be used: ΔH°rxn=ΣΔH°f(products)−ΣΔH°f(reactants).","medium")
    ]),
    T("Equilibrium", [
      P("Write the equilibrium expression Kc for: N₂(g)+3H₂(g)⇌2NH₃(g)","Only include gases and aqueous species; raise to stoichiometric power.","Kc=[NH₃]²/([N₂][H₂]³). Pure solids and liquids are excluded from K expressions.","easy"),
      P("If Qc<Kc for a reaction, which direction will it proceed?","Think about Q vs K comparison.","Q<K: the ratio of products to reactants is less than at equilibrium → reaction proceeds forward (toward products) to increase Q until Q=K. If Q>K: reaction proceeds in reverse. If Q=K: at equilibrium.","easy"),
      P("How does Le Chatelier's Principle predict the effect of increasing pressure on N₂(g)+3H₂(g)⇌2NH₃(g)?","Think about moles of gas on each side.","Increasing pressure (decreasing volume) shifts equilibrium toward the side with fewer moles of gas. Left side: 1+3=4 mol gas. Right side: 2 mol gas. The equilibrium shifts right (toward NH₃) when pressure increases. This is why the Haber process for ammonia uses high pressure.","medium")
    ]),
    T("Acids and Bases", [
      P("What is the pH of a 0.01M HCl solution? Of a 0.01M NaOH solution?","HCl is a strong acid; NaOH is a strong base.","HCl: strong acid, fully dissociates. [H⁺]=0.01=10⁻². pH=−log(10⁻²)=2. NaOH: strong base, fully dissociates. [OH⁻]=0.01=10⁻². pOH=2. pH=14−2=12.","easy"),
      P("Calculate the pH of a 0.1M acetic acid solution (Ka=1.8×10⁻⁵).","Weak acid equilibrium: HA⇌H⁺+A⁻","ICE table: [H⁺]=x, [CH₃COO⁻]=x, [CH₃COOH]=0.1−x≈0.1. Ka=x²/0.1=1.8×10⁻⁵ → x²=1.8×10⁻⁶ → x=1.34×10⁻³. pH=−log(1.34×10⁻³)≈2.87.","hard"),
      P("How does a buffer resist pH changes and what is the Henderson-Hasselbalch equation?","Think about conjugate acid-base pairs.","A buffer contains a weak acid (HA) and its conjugate base (A⁻) in similar concentrations. Adding acid: A⁻+H⁺→HA (base absorbs acid). Adding base: HA+OH⁻→A⁻+H₂O (acid absorbs base). Henderson-Hasselbalch: pH=pKa+log([A⁻]/[HA]). At equal concentrations, pH=pKa. Buffer works best within ±1 pH unit of pKa.","medium")
    ]),
    T("Electrochemistry", [
      P("In an electrochemical cell, what occurs at the anode and cathode?","Think about oxidation and reduction — which electrode does each.","Anode: oxidation occurs (loses electrons); connected to negative terminal in galvanic cell. Cathode: reduction occurs (gains electrons); connected to positive terminal. Mnemonic: AnOx RedCat (Anode Oxidation, Reduction Cathode).","easy"),
      P("Calculate the standard cell potential for: Zn→Zn²⁺+2e⁻ (E°=+0.76V) and Cu²⁺+2e⁻→Cu (E°=+0.34V).","E°cell=E°cathode−E°anode","E°cell=E°cathode−E°anode=0.34−(−0.76)=1.10V. Positive cell potential → spontaneous reaction. Zn is the anode (oxidized); Cu is the cathode (reduced).","easy"),
      P("How does the Nernst equation relate cell potential to concentration?","Think about non-standard conditions.","Nernst equation: E=E°−(RT/nF)lnQ = E°−(0.0592/n)logQ at 25°C. Where n=moles of electrons, Q=reaction quotient. At standard conditions (Q=1): E=E°. As products accumulate (Q increases): E decreases. At equilibrium (Q=K): E=0 (cell is dead). The Nernst equation shows how concentration affects voltage.","hard")
    ]),
    T("Nuclear Chemistry", [
      P("Write and balance a nuclear equation for alpha decay of uranium-238.","Alpha particle = ₂⁴He","²³⁸₉₂U → ₂⁴He + ²³⁴₉₀Th. Conservation: mass numbers 238=4+234 ✓; atomic numbers 92=2+90 ✓.","medium"),
      P("What is radioactive half-life? If a 100g sample has t½=10 years, how much remains after 30 years?","Apply: A=A₀(1/2)^(t/t½)","30 years = 3 half-lives. A=100(1/2)³=100/8=12.5g.","easy"),
      P("Compare nuclear fission and fusion in terms of energy release and practical applications.","Think about reactants and current technology.","Fission: heavy nucleus (U-235, Pu-239) splits into lighter nuclei + neutrons + energy. Used in nuclear reactors and weapons. Chain reaction possible. Fusion: light nuclei (H isotopes — deuterium and tritium) merge to form He + neutron + energy. Powers the sun. Releases ~3× more energy per unit mass than fission. Requires extreme conditions (10⁷ K); not yet commercially viable (fusion energy research ongoing — ITER, NIF).","hard")
    ])
  ],
  # Unit 3 — AP Environmental Science
  [
    T("Earth Systems and Resources", [
      P("Describe the four Earth systems and how they interact.","Think about lithosphere, hydrosphere, atmosphere, biosphere.","Lithosphere: solid rock, crust, mantle. Hydrosphere: all water (oceans, rivers, ice, groundwater). Atmosphere: gases surrounding Earth. Biosphere: all living organisms. Interaction example: volcanic eruption (lithosphere) releases CO₂ (atmosphere) which warms climate (atmosphere changes hydrosphere ice melt) which affects habitats (biosphere). Earth systems exchange energy and matter continuously.","medium"),
      P("Explain plate tectonics and its environmental consequences.","Think about where plates interact and what happens.","Plate tectonics: Earth's crust is divided into plates that move (driven by mantle convection). Consequences: divergent boundaries (plates apart) — mid-ocean ridges, new seafloor, volcanic activity; convergent boundaries (plates together) — subduction zones, volcanoes, mountains, earthquakes; transform boundaries (plates slide past) — strike-slip faults (San Andreas). Volcanoes and earthquakes are environmentally significant events.","medium"),
      P("What is the difference between renewable and nonrenewable resources?","Think about timescale of replenishment.","Renewable: replenished at a rate comparable to use on human timescales (solar, wind, water, biomass, geothermal). Nonrenewable: formed over millions of years; not replenished on human timescales (fossil fuels — coal, oil, natural gas; nuclear fuels). Sustainable use: using renewable resources at rates that allow regeneration; using nonrenewable resources efficiently while developing alternatives.","easy")
    ]),
    T("The Living World: Ecosystems", [
      P("Describe energy flow through a food chain using the 10% rule.","Think about trophic levels and energy loss.","Energy is lost (~90%) at each trophic level to heat, respiration, and waste. Only ~10% is transferred to the next level. Example: 10,000 kcal of plants → 1,000 kcal to herbivores → 100 kcal to primary carnivores → 10 kcal to secondary carnivores. This limits food chain length and explains why herbivore populations are always larger than predator populations.","easy"),
      P("What is the difference between primary and net productivity?","Think about gross photosynthesis vs. what's left after respiration.","Gross primary productivity (GPP): total rate of photosynthesis — total solar energy fixed by plants. Net primary productivity (NPP): GPP minus energy used by plants for respiration. NPP=GPP−R. NPP represents energy available to consumers. Highest NPP: tropical rainforests, wetlands, estuaries. Lowest: open oceans, deserts.","medium"),
      P("Compare mutualism, commensalism, and parasitism.","Think about +/+ vs. +/0 vs. +/− interactions.","Mutualism (+/+): both species benefit (mycorrhizal fungi and plant roots — fungi get sugars; plant gets nutrients). Commensalism (+/0): one benefits, other unaffected (barnacles on whales). Parasitism (+/−): one benefits, other harmed (tapeworm in host). These interspecific interactions shape community structure.","easy")
    ]),
    T("Populations", [
      P("What factors determine whether a population grows, shrinks, or stays stable?","Use the BIDE model.","Population change: BIDE — Births + Immigration − Deaths − Emigration. Population grows when B+I>D+E. Key rate: r = (b+i)−(d+e). r>0: growing; r=0: stable; r<0: declining. Human population: growth rate ~1%/year (still growing); demographic transition theory predicts stabilization as nations develop.","easy"),
      P("What is the difference between density-dependent and density-independent population regulation?","Think about what kinds of factors increase in effect as population grows.","Density-dependent: limiting factors whose effect intensifies with increasing population density — competition for food/space, predation, disease, parasitism. Tend to create negative feedback (regulate population around carrying capacity). Density-independent: factors unrelated to population size — weather, natural disasters, climate change. A severe frost kills the same percentage regardless of population density.","medium"),
      P("What is an ecological footprint and why does it matter for sustainability?","Think about resource consumption and carrying capacity.","Ecological footprint: amount of biologically productive land and water needed to support one person's resource consumption and absorb their waste. Current status: average American footprint ~8 global hectares; Earth's biocapacity is ~1.7 global hectares/person. Humanity collectively uses ~1.7 Earths — we are in ecological overshoot, depleting natural capital faster than it regenerates. Sustainability requires reducing footprint to within Earth's biocapacity.","medium")
    ]),
    T("Earth's Atmosphere", [
      P("Describe the composition and layers of Earth's atmosphere.","Think about gases and altitude layers.","Composition: N₂ (78%), O₂ (21%), Ar (0.9%), CO₂ (0.04%). Layers by temperature profile: Troposphere (0–12km): weather occurs; temperature decreases with altitude. Stratosphere (12–50km): ozone layer absorbs UV; temperature increases with altitude. Mesosphere (50–80km): temperature decreases; meteors burn here. Thermosphere (>80km): very thin; high energy absorption; auroras. Weather and greenhouse gases are tropospheric phenomena.","medium"),
      P("Explain the greenhouse effect and distinguish it from the enhanced greenhouse effect.","Think about natural vs. anthropogenic.","Natural greenhouse effect: greenhouse gases (H₂O, CO₂, CH₄, N₂O) absorb outgoing infrared radiation and re-radiate it in all directions — warming Earth ~33°C above what it would be without them (essential for life). Enhanced greenhouse effect: burning fossil fuels and deforestation increase GHG concentrations, trapping more heat → global warming, climate change. Without the natural greenhouse effect, Earth would average −18°C; we're at +15°C, but rising.","medium"),
      P("What causes stratospheric ozone depletion and why is it concerning?","Think about CFCs and UV radiation.","Chlorofluorocarbons (CFCs) from aerosols and refrigerants rise to the stratosphere where UV breaks them down → releases Cl atoms → catalytic chain reaction destroys ozone: Cl+O₃→ClO+O₂ (one Cl can destroy ~100,000 ozone molecules). Ozone depletion allows more UV-B to reach Earth's surface → increased skin cancer, cataracts, crop damage. Montreal Protocol (1987) phased out CFCs; ozone layer slowly recovering.","medium")
    ]),
    T("Land and Water Use", [
      P("What are the environmental impacts of industrial agriculture?","Think about soil, water, and biodiversity.","Impacts: (1) Soil erosion — tillage and monocultures leave soil exposed; (2) Soil degradation — repeated cultivation depletes organic matter, fertility; (3) Water pollution — fertilizer runoff causes eutrophication; pesticide runoff harms aquatic life; (4) Aquifer depletion — irrigation draws down groundwater faster than recharge; (5) Biodiversity loss — monocultures reduce habitat variety; pesticides harm non-target species; (6) GHG emissions — livestock (CH₄), fertilizer production, and land clearing.","medium"),
      P("What is the tragedy of the commons and how does it apply to fisheries?","Think about shared resources and individual incentives.","Tragedy of the commons (Hardin, 1968): when a resource is shared (common), each individual's rational self-interest leads to overexploitation, ultimately destroying the resource for all. Fisheries example: each fishing company maximizes catch for profit; no individual company has incentive to reduce catch (another will take their share). Without regulation, fisheries collapse (Atlantic cod). Solutions: regulation, privatization, or community governance (Ostrom's work on commons management).","hard"),
      P("What is eutrophication and how does it create hypoxic dead zones?","Think about nutrient enrichment, algae, and oxygen.","Eutrophication: excess nutrients (nitrogen, phosphorus from agricultural runoff and sewage) enrich water bodies → algal blooms → algae block sunlight → aquatic plants die → algae die → bacteria decompose algae using dissolved O₂ → oxygen depleted → hypoxia → fish and invertebrates suffocate → 'dead zone.' Gulf of Mexico dead zone (from Mississippi River nutrients) is a major example.","medium")
    ]),
    T("Energy Resources and Consumption", [
      P("Compare fossil fuels in terms of carbon intensity and environmental impact.","Think about coal, oil, and natural gas.","Coal: highest carbon content; produces most CO₂ per energy unit; also emits SO₂ (acid rain), NOₓ, mercury, particulates. Oil: moderate carbon content; produces CO₂, NOₓ; spill risk. Natural gas: lowest carbon intensity among fossil fuels (produces 50% less CO₂ than coal per energy); less particulates; but methane leaks during extraction are a concern (CH₄ is ~80× more potent GHG than CO₂ over 20 years). All are nonrenewable and release CO₂.","medium"),
      P("Explain how solar photovoltaic cells work.","Think about the photoelectric effect and semiconductors.","Solar cells (photovoltaic): photons from sunlight strike semiconductor (typically silicon) → excite electrons to higher energy states → in the p-n junction, these electrons flow in one direction (direct current). DC electricity is converted to AC by an inverter. No moving parts, no emissions during operation. Lifecycle environmental costs: manufacturing uses energy and materials; end-of-life panel disposal. Rapidly becoming the cheapest electricity source in human history.","medium"),
      P("What are the environmental trade-offs of nuclear power?","Think about low-carbon vs. waste and risk.","Pros: zero CO₂ during operation, very high energy density (small fuel volume), reliable baseload power, very low land use. Cons: radioactive waste requires isolation for thousands of years; risk of catastrophic accident (Chernobyl, Fukushima); high construction cost and time; uranium mining impacts; water use for cooling. Net assessment: nuclear produces ~15× fewer deaths per TWh than coal and very low carbon footprint, but public perception, cost, and waste remain challenges.","hard")
    ]),
    T("Atmospheric Pollution", [
      P("What are the primary pollutants that cause photochemical smog and how is it formed?","Think about NOₓ, VOCs, and sunlight.","Primary pollutants (from vehicles, industry): NOₓ (nitrogen oxides) and VOCs (volatile organic compounds). Photochemical smog formation: UV sunlight breaks NO₂ → NO + O (atomic oxygen) → O + O₂ → O₃ (ground-level ozone). VOCs react with NO in presence of sunlight → additional ozone and peroxy compounds. Ground-level ozone is the main component of smog — irritates lungs, damages crops. Worse in sunny, warm cities (Los Angeles).","medium"),
      P("Explain acid deposition: causes, chemistry, and ecological effects.","Think about SO₂, NOₓ, and pH.","Causes: burning coal and oil releases SO₂; combustion releases NOₓ. Chemistry: SO₂+H₂O→H₂SO₃→H₂SO₄ (sulfuric acid); NOₓ+H₂O→HNO₃ (nitric acid). These dissolve in precipitation (acid rain) or deposit as dry particles. Ecological effects: acidifies lakes (kills fish, amphibians); leaches nutrients (Ca, Mg) from soil; damages trees (especially at high elevations); corrodes buildings and statues (marble, limestone).","medium"),
      P("What is the difference between indoor and outdoor air pollution in terms of health impacts?","Think about where people spend most time.","Outdoor: fine particulates (PM2.5) from vehicles/industry → lung inflammation, heart disease, cancer; ozone → respiratory damage. Indoor: often worse than outdoor. Sources: radon (from soil → lung cancer — #2 cause in US), secondhand smoke, formaldehyde (building materials), VOCs (cleaning products, paint), CO from combustion. People spend ~90% of time indoors. Poor ventilation concentrates pollutants. Developing world: indoor cookfire smoke kills millions annually.","hard")
    ]),
    T("Aquatic and Terrestrial Pollution", [
      P("What is biomagnification and which pollutants exhibit it most strongly?","Think about fat-soluble chemicals and food chain concentration.","Biomagnification: concentration of a substance increases at each trophic level in a food chain. Mechanism: organisms at each level eat many prey individuals; fat-soluble toxins accumulate in fatty tissue rather than being excreted. By the time you reach top predators, concentrations are millions of times greater than in water. Pollutants that biomagnify: DDT (caused thin eagle eggshells → near-extinction), PCBs, mercury (converted to methylmercury by bacteria). High-trophic-level species (tuna, eagles, orcas) are most affected.","medium"),
      P("What is the difference between point source and non-point source water pollution?","Think about identifiable vs. diffuse sources.","Point source: pollution discharged from an identifiable, discrete location — pipe from factory or sewage treatment plant. Easier to regulate and control (US Clean Water Act). Non-point source: pollution from diffuse, widespread areas — agricultural runoff (fertilizers, pesticides), urban stormwater, atmospheric deposition. Harder to regulate. Non-point source pollution is the leading cause of water quality problems in the US today.","easy"),
      P("How does plastic pollution in the ocean affect marine ecosystems?","Think about ingestion, entanglement, and microplastics.","Plastics: 8 million tons enter oceans annually. Effects: (1) Entanglement — seabirds, turtles, marine mammals trapped in plastic debris; (2) Ingestion — animals mistake plastic for food; fills stomach without nutrition; (3) Microplastics (<5mm) — from degraded plastic or microbeads; ingested by plankton → enters food web; carry toxic chemicals; (4) Leaching — plastics release chemicals (BPA, phthalates) as they degrade. Estimated 5.25 trillion plastic pieces in ocean; persists for hundreds of years.","medium")
    ]),
    T("Global Change", [
      P("What is the evidence for human-caused climate change?","Think about multiple independent lines of evidence.","Evidence: (1) Rising atmospheric CO₂ (from 280 ppm pre-industrial to 420+ ppm today); (2) Isotopic signature of CO₂ matches fossil fuel burning (depleted in ¹³C); (3) Rising global average temperature (+1.1°C since pre-industrial); (4) Sea level rise (thermal expansion + ice melt); (5) Arctic sea ice loss; (6) Ocean acidification (CO₂+H₂O→H₂CO₃); (7) Glacial retreat worldwide; (8) Shift in species ranges toward poles and higher elevations. Multiple independent lines of evidence are consistent with human-caused warming.","medium"),
      P("What are the projected consequences of 2°C vs. 4°C of global warming?","Think about sea level, extreme weather, and biodiversity.","2°C (Paris Agreement target): 90% of coral reefs degraded; Arctic sea ice mostly gone in summer; significant sea level rise; more frequent extreme weather. 4°C (if emissions continue unchecked): up to 1 meter sea level rise by 2100 (threatening coastal cities); mass coral extinction; major agricultural disruption in tropics; up to 40% species face extinction; increased conflict over resources. The difference between 2°C and 4°C is enormous in human and ecosystem impact.","hard"),
      P("What strategies exist for reducing greenhouse gas emissions and which are most impactful?","Think about energy, transport, and land use.","Most impactful: (1) Energy: transition from fossil fuels to renewables (solar, wind); nuclear as low-carbon baseload; improve efficiency; (2) Transport: electrification of vehicles; public transit; (3) Buildings: energy efficiency, heat pumps; (4) Industry: green hydrogen, carbon capture; (5) Land use: reduce deforestation; restore forests; reduce beef consumption (cattle emit CH₄); (6) Carbon pricing: makes emissions costly → incentivizes all of the above. IPCC identifies rapid, deep emissions cuts in all sectors as necessary to limit warming to 1.5–2°C.","medium")
    ])
  ],
  # Unit 4 — AP Physics 1: Algebra-Based
  [
    T("Kinematics", [
      P("A car accelerates from 0 to 60 mph (27 m/s) in 6 seconds. Find acceleration.","a=(v-v₀)/t","a=(27−0)/6=4.5 m/s².","easy"),
      P("A ball is thrown upward at 20 m/s. Find max height and time to reach it.","At max height, v=0; use v²=v₀²−2g·Δy.","0=400−2(10)h → h=20m. Time: v=v₀−gt → 0=20−10t → t=2s.","medium"),
      P("A ball is thrown horizontally at 15 m/s from a 45m cliff. Find horizontal range and time of flight.","Vertical: free fall. Horizontal: constant velocity.","Vertical: 45=½(10)t² → t=3s. Horizontal: x=15×3=45m.","medium")
    ]),
    T("Forces and Newton's Laws", [
      P("A 10kg block is pushed by 50N force with 20N friction. Find acceleration.","F_net=ma.","F_net=50−20=30N. a=30/10=3 m/s².","easy"),
      P("Explain Newton's Third Law and give a specific example with forces labeled.","Action-reaction pairs — same magnitude, opposite direction, on DIFFERENT objects.","Example: A rocket engine pushes combustion gases downward (action); gases push rocket upward (reaction). The action and reaction are equal in magnitude but on different objects, so they don't cancel. Misconception: they do cancel — they don't, because they act on different objects.","medium"),
      P("A 5kg block sits on a surface with μs=0.4, μk=0.3. What minimum force starts it moving? What force sustains motion?","fs,max=μs·N; fk=μk·N","N=mg=50N. Minimum to start: fs,max=0.4×50=20N. Kinetic friction (during motion): fk=0.3×50=15N. Static friction is always greater than kinetic.","medium")
    ]),
    T("Circular Motion and Gravitation", [
      P("A car turns in a circle of radius 50m at 20 m/s. Find centripetal acceleration.","ac=v²/r","ac=400/50=8 m/s² (directed toward center).","easy"),
      P("Compare gravitational force between two objects when the distance is doubled.","Use F=Gm₁m₂/r².","F∝1/r². Distance doubles → r²×4 → F decreases to F/4.","easy"),
      P("A satellite orbits at height h above Earth (radius R). Derive its orbital speed.","Gravity provides centripetal force: GMm/(R+h)²=mv²/(R+h).","GMm/(R+h)²=mv²/(R+h) → v²=GM/(R+h) → v=√(GM/(R+h)). Higher orbit → slower orbital speed.","hard")
    ]),
    T("Energy and Work", [
      P("A 2kg ball falls 10m. Calculate work done by gravity.","W=Fd cosθ; gravity acts in direction of motion.","W=mgh=2×10×10=200J.","easy"),
      P("State the work-energy theorem and explain its significance.","Think about net work and kinetic energy change.","Work-energy theorem: W_net=ΔKE=½mv²−½mv₀². The net work done on an object equals its change in kinetic energy. Significance: connects forces (work) to motion (kinetic energy) without needing time — allows energy methods to solve problems that would be complex with kinematics.","medium"),
      P("A 3kg block slides down a 4m ramp at 30°. If the bottom speed is 5 m/s, find energy lost to friction.","Use conservation of energy with friction loss.","Height: h=4sin30°=2m. PE initial=mgh=60J. KE final=½(3)(25)=37.5J. Energy lost to friction=60−37.5=22.5J.","medium")
    ]),
    T("Momentum", [
      P("Two carts collide and stick (perfectly inelastic). Cart 1: 2kg at 6 m/s. Cart 2: 4kg at rest. Find final velocity.","Conservation of momentum: p_initial=p_final.","p_i=2×6=12 kg·m/s. (2+4)v_f=12 → v_f=2 m/s.","easy"),
      P("Explain why a long follow-through in sports (baseball bat, tennis racket) increases the force on the ball.","Think about impulse-momentum theorem.","Impulse: J=FΔt=Δp. For a given change in momentum (hitting the ball), longer contact time (follow-through) means less force required — BUT if you can maintain force over longer time, you get greater impulse → greater momentum change → ball leaves faster. Coaches teach follow-through to maintain contact force over longer time.","hard"),
      P("A 1500kg car moving at 20 m/s hits a wall and stops in 0.1s. Find average force.","J=FΔt=Δp","Δp=0−1500×20=−30,000 N·s. F=Δp/Δt=−30,000/0.1=−300,000N (toward wall). Magnitude: 300 kN — about 20× the car's weight. Crumple zones extend Δt to reduce F.","medium")
    ]),
    T("Simple Harmonic Motion", [
      P("What are the defining characteristics of simple harmonic motion?","Think about the restoring force and energy.","SHM: oscillatory motion where restoring force is proportional to displacement: F=−kx. Characteristics: (1) Period is independent of amplitude; (2) Energy alternates between KE and PE; (3) Displacement, velocity, and acceleration vary sinusoidally. Examples: mass on spring, simple pendulum (small angles), LC circuit, molecular vibrations.","medium"),
      P("A spring with k=200 N/m has a 0.5kg mass attached. Find the period of oscillation.","T=2π√(m/k)","T=2π√(0.5/200)=2π√(0.0025)=2π×0.05=0.314s.","easy"),
      P("At what position in a mass-spring system is (a) KE maximum, (b) PE maximum, (c) acceleration maximum?","Think about energy transformation in SHM.","(a) KE maximum: at equilibrium (x=0) — all energy is kinetic. (b) PE maximum: at amplitude (x=±A) — spring fully stretched/compressed, all energy is potential. (c) Acceleration maximum: at amplitude (x=±A) — restoring force is greatest here (F=−kx; largest when x is largest). These three happen at two different locations.","medium")
    ]),
    T("Waves and Sound", [
      P("A wave has frequency 500 Hz and wavelength 0.68m. Find wave speed.","v=fλ","v=500×0.68=340 m/s (speed of sound in air).","easy"),
      P("Explain why sound travels faster in solids than in gases.","Think about the medium's properties.","Wave speed depends on medium: v=√(elasticity/density). Solids have very high elastic modulus (particles are tightly coupled) — disturbing one particle quickly disturbs neighbors. The high restoring force transmits vibrations rapidly. Though solids are also denser, elasticity increases more than density. Liquids: intermediate. Gases: low elasticity, low coupling → slower sound.","medium"),
      P("A train moving toward you blows its horn at 440 Hz. You hear 480 Hz. Explain using the Doppler effect.","Think about wavefront compression.","Doppler effect: as source moves toward observer, emitted wavefronts are compressed → shorter wavelength → higher frequency observed. As source moves away: wavefronts spread → longer wavelength → lower frequency. Formula: f_obs=f_source·(v±v_obs)/(v∓v_source). Used in speed guns, weather radar, medical ultrasound, and astronomy (redshift/blueshift).","medium")
    ]),
    T("Electric Charge and Fields", [
      P("Two charges of +2μC and −3μC are 0.5m apart. Find the electrostatic force.","F=kq₁q₂/r²; k=9×10⁹ N·m²/C²","F=9×10⁹×(2×10⁻⁶)(3×10⁻⁶)/(0.25)=9×10⁹×6×10⁻¹²/0.25=0.216N. Attractive (opposite charges).","medium"),
      P("What is an electric field and how does it differ from electric force?","Think about source charge vs. test charge.","Electric field E: force per unit charge at a location in space — E=F/q. It exists due to source charges, independent of whether a test charge is present. Electric force: F=qE — the force experienced by a specific charge q in the field. E is a property of space; F depends on what charge is placed there. Units: E in N/C or V/m; F in N.","medium"),
      P("Describe how the electric field between parallel plates is created and its key properties.","Think about uniform field.","Parallel plates: one plate positive, one negative. The fields from each plate add between the plates → uniform electric field E=V/d (voltage/separation) pointing from + to − plate. Properties: (1) Field lines are parallel and equally spaced; (2) Field is constant in magnitude between plates; (3) E is nearly zero outside the plates. Used in capacitors, cathode ray tubes, and mass spectrometers.","medium")
    ]),
    T("DC Circuits", [
      P("Three resistors 6Ω, 3Ω, 2Ω in series with a 12V battery. Find total resistance and current.","Series: R_total=R₁+R₂+R₃; I=V/R.","R=6+3+2=11Ω. I=12/11≈1.09A.","easy"),
      P("Two 6Ω resistors are in parallel with a 12V battery. Find equivalent resistance and total current.","Parallel: 1/R=1/R₁+1/R₂","1/R=1/6+1/6=2/6 → R=3Ω. I_total=12/3=4A. Each resistor: I=12/6=2A.","medium"),
      P("A 60W light bulb operates at 120V. Find resistance and current.","P=V²/R=VI=I²R","I=P/V=60/120=0.5A. R=V/I=120/0.5=240Ω. Also: R=V²/P=14400/60=240Ω ✓","easy")
    ])
  ],
  # Unit 5 — AP Physics 2: Algebra-Based
  [
    T("Fluids", [
      P("State Pascal's Principle and explain how a hydraulic lift works.","Pressure applied to enclosed fluid transmits equally in all directions.","Pascal: pressure applied to enclosed fluid is transmitted undiminished throughout. Hydraulic lift: small force F₁ on small piston area A₁ creates pressure P=F₁/A₁. This pressure transmitted to large piston (area A₂). F₂=P·A₂=F₁(A₂/A₁). If A₂=20A₁, output force is 20× input force — a mechanical advantage. Work is conserved: small force × large distance = large force × small distance.","medium"),
      P("Explain Archimedes' Principle and why a steel ship floats.","Think about buoyant force = weight of displaced fluid.","Archimedes: buoyant force on an object equals the weight of fluid displaced. F_b=ρ_fluid·V_displaced·g. A steel ship: despite being denser than water, the ship's shape displaces a large volume of water. If the weight of displaced water > ship's weight, it floats. A steel cube sinks (dense, displaces small volume); the same steel shaped into a hollow hull displaces much more water → buoyancy > weight → floats.","medium"),
      P("What does Bernoulli's Principle state, and how does it explain airplane lift?","Think about conservation of energy in fluid flow.","Bernoulli: in streamline flow, increase in fluid speed corresponds to decrease in pressure (and vice versa). P+½ρv²+ρgh=constant. Airplane wing (airfoil): curved upper surface forces air to travel farther/faster than under the flat lower surface → faster air above → lower pressure above → net upward force (lift). Also explains: carburetors, atomizers, curveball pitching.","medium")
    ]),
    T("Thermodynamics", [
      P("What is the first law of thermodynamics and how does it apply to an ideal gas?","ΔU=Q−W (or Q+W depending on convention).","First law: ΔU=Q−W. For ideal gas: ΔU depends only on temperature (internal energy = kinetic energy of molecules). Isothermal (constant T): ΔU=0, so Q=W (all heat goes to work. Adiabatic (no heat exchange): Q=0, ΔU=−W (work done by gas cools it). Isochoric (constant volume): W=0, ΔU=Q (all heat changes internal energy).","hard"),
      P("What is entropy and how does the second law limit heat engine efficiency?","Think about disorder and energy quality.","Entropy: measure of disorder/microstates. Second law: entropy of universe always increases. Heat engine efficiency: e=W/Q_h=1−Q_c/Q_h≤1−T_c/T_h (Carnot efficiency). No engine can be 100% efficient — some heat must be exhausted to a cold reservoir. Maximum efficiency (Carnot) requires reversible processes and depends only on temperatures of hot and cold reservoirs.","hard"),
      P("A heat pump absorbs 500J from cold reservoir and releases 800J to hot reservoir. Find work input and COP.","Energy conservation: W+Q_c=Q_h","W=Q_h−Q_c=800−500=300J. COP (heating) = Q_h/W=800/300≈2.67. For every 1J of electricity used, 2.67J of heat is delivered — more efficient than direct electric heating because it moves heat rather than generating it.","medium")
    ]),
    T("Electric Force, Field, and Potential", [
      P("What is electric potential (voltage) and how does it differ from electric field?","Think about scalar vs. vector.","Electric potential (V): electric potential energy per unit charge — V=U/q. Scalar quantity. Electric field (E): force per unit charge — vector. Relationship: E=−ΔV/Δd (field points from high to low potential; magnitude = rate of change of potential). Moving a charge from high to low potential: it loses potential energy (gains kinetic energy). Analogy: potential is like height, field is like the slope.","medium"),
      P("Two parallel plates are connected to a 100V battery separated by 2cm. Find E between plates.","E=V/d for uniform field.","E=100/0.02=5,000 V/m. Direction: from positive plate to negative plate.","easy"),
      P("What is a capacitor and how does inserting a dielectric affect capacitance?","Think about how dielectric polarizes.","Capacitor: two conductors storing equal and opposite charge; stores energy in electric field. C=Q/V; C=ε₀A/d for parallel plates. Dielectric: insulating material inserted between plates. Polar molecules in dielectric align with field → create opposing internal field → reduces net E between plates → allows more charge for same voltage → increases capacitance by factor κ (dielectric constant). C_new=κC₀.","hard")
    ]),
    T("Circuits", [
      P("What does a capacitor do in a DC circuit at steady state?","Think about what happens when capacitor is fully charged.","At steady state in DC circuit, a fully charged capacitor acts as an open circuit — no current flows through the capacitor branch. Voltage across capacitor equals voltage of the section it's connected to. During charging: capacitor initially acts like a short circuit, then current decreases exponentially as it charges. Time constant τ=RC determines how quickly it charges.","medium"),
      P("What is the difference between a real battery and an ideal battery?","Think about internal resistance.","Ideal battery: provides exactly its EMF (ε) regardless of current; no internal resistance. Real battery: has internal resistance r. Terminal voltage V=ε−Ir — actual voltage delivered decreases as current increases. At high currents (short circuit), terminal voltage → 0. Internal resistance causes energy dissipation (heat) inside battery, explains why batteries get warm and why they can't deliver unlimited current.","medium"),
      P("Compare series and parallel circuits in terms of current, voltage, and failure.","Think about what happens if one bulb burns out.","Series: same current through all components; voltage divides across them; total R increases. If one component fails (open circuit) → no current anywhere → all go out. Parallel: same voltage across all branches; current divides; total R decreases (adding branches). If one branch fails → other branches unaffected (house wiring is parallel). Adding bulbs in parallel: each gets full voltage → all equally bright; total current increases.","medium")
    ]),
    T("Magnetism and Electromagnetic Induction", [
      P("State the right-hand rule for force on a current in a magnetic field.","F=IL×B","Point fingers in direction of current (I), curl toward B field direction, thumb points in direction of force F on wire. F=ILBsinθ. If I parallel to B: no force (sinθ=0). Maximum force when current ⊥ field. This force is the basis of electric motors.","medium"),
      P("State Faraday's Law of electromagnetic induction.","Think about changing magnetic flux.","Faraday's Law: EMF=−ΔΦ_B/Δt. A changing magnetic flux (Φ=BAcosθ) through a loop induces an EMF (and thus current if circuit is closed). The negative sign (Lenz's Law): induced current creates a magnetic field that opposes the change in flux — nature resists changes in flux. Applications: generators, transformers, induction stoves, wireless charging.","medium"),
      P("How does a transformer work and what determines its voltage ratio?","Think about Faraday's law in primary and secondary coils.","Transformer: two coils wound on iron core. AC current in primary coil → changing magnetic flux in core → induces EMF in secondary. Ratio: V_s/V_p=N_s/N_p (turns ratio). Step-up transformer: more turns on secondary → higher voltage. Step-down: fewer turns → lower voltage. Power is conserved (ideal): V_pI_p=V_sI_s. Used in power transmission (step up to high voltage → lower current → less resistive loss) then step down for homes.","hard")
    ]),
    T("Geometric and Physical Optics", [
      P("State Snell's Law and explain why light bends when entering a denser medium.","Think about light slowing down.","Snell's Law: n₁sinθ₁=n₂sinθ₂. When light enters a denser medium (higher n, slower speed): wavelength decreases, but frequency unchanged. To maintain wave continuity at boundary, light bends toward normal (θ₂<θ₁ when n₂>n₁). When going from dense to less dense: bends away from normal. If angle is large enough, total internal reflection occurs (no refraction — basis of fiber optics).","medium"),
      P("How does a convex lens form a real image? Use the thin lens equation.","Think about focal length and object distance.","Convex lens: converging lens with focal length f>0. For object beyond focal point, real inverted image forms on opposite side. Thin lens equation: 1/do+1/di=1/f. Example: f=10cm, do=30cm → 1/di=1/10−1/30=2/30 → di=15cm (real, inverted, reduced by magnification M=−di/do=−0.5).","medium"),
      P("What is the difference between constructive and destructive interference of light?","Think about path length difference.","Constructive interference: two light waves arrive in phase (path difference = nλ) → amplitudes add → bright fringe. Destructive interference: waves arrive out of phase (path difference = (n+½)λ) → amplitudes cancel → dark fringe. Young's double-slit experiment demonstrates this with pattern of bright and dark bands (fringes). Iridescent colors in soap bubbles and oil slicks result from thin-film interference.","medium")
    ]),
    T("Quantum, Atomic, and Nuclear Physics", [
      P("How does the Bohr model explain atomic emission spectra?","Think about energy levels and photon emission.","Bohr model: electrons occupy specific energy levels (orbits). When an electron drops from higher level (E₂) to lower (E₁), a photon is emitted with energy: E_photon=E₂−E₁=hf. Since energy levels are discrete, only specific photon energies (specific wavelengths/colors) are emitted. This creates the characteristic line spectrum of each element — like a fingerprint. Used in spectroscopy to identify elements in stars and lab samples.","medium"),
      P("What is the de Broglie wavelength and what does it reveal about particles?","λ=h/p","De Broglie: matter has wave properties. Wavelength λ=h/mv (h=Planck's constant). Significance: electrons and other particles exhibit interference and diffraction — wave phenomena. For large objects (baseball), λ is so small as to be undetectable. For electrons (tiny mass, small momentum), λ is comparable to atomic dimensions → electron diffraction is real and observable. This wave-particle duality is fundamental to quantum mechanics.","hard"),
      P("What is pair production and pair annihilation?","Think about mass-energy equivalence.","Pair production: a high-energy photon (E≥2m_e c²=1.022 MeV) interacts with a nucleus and creates an electron-positron pair (matter + antimatter). Converts energy to mass. Pair annihilation: electron meets positron → both annihilate → two photons released (each 0.511 MeV, opposite directions). Converts mass to energy. Both demonstrate E=mc². Used in PET scans (positron emission tomography).","hard")
    ])
  ],
  # Unit 6 — AP Physics C: Mechanics
  [
    T("Kinematics (Calculus-Based)", [
      P("Given position x(t)=3t³−2t², find velocity and acceleration at t=2s.","v=dx/dt, a=dv/dt","v(t)=9t²−4t. v(2)=36−8=28 m/s. a(t)=18t−4. a(2)=36−4=32 m/s².","easy"),
      P("A particle has a(t)=6t−4 and v(0)=2, x(0)=0. Find x(3).","Integrate twice; apply initial conditions.","v(t)=∫(6t−4)dt=3t²−4t+C₁. v(0)=2→C₁=2. v(t)=3t²−4t+2. x(t)=t³−2t²+2t+C₂. x(0)=0→C₂=0. x(3)=27−18+6=15m.","medium"),
      P("Explain why calculus is essential for non-constant acceleration problems.","Think about what average acceleration misses.","Algebra assumes constant acceleration; calculus handles any a(t). For a=6t (linearly increasing), the average acceleration over [0,3] is 9 m/s², but simply using v=v₀+at would give the wrong velocity at any instant. Only integration of a(t) gives the correct v(t), and integration of v(t) gives correct x(t). Calculus is necessary for real-world problems where forces (and thus accelerations) vary with time.","hard")
    ]),
    T("Newton's Laws (Calculus-Based)", [
      P("A 2kg object experiences F=4t N (increasing with time). Find velocity at t=3s if v(0)=0.","Impulse = ∫F dt = Δp","∫₀³ 4t dt=[2t²]₀³=18 N·s=Δp. v(3)=18/2=9 m/s.","medium"),
      P("Set up the differential equation for a mass on a spring with damping.","Think about spring force and damping force.","Forces: spring (−kx), damping (−bv=−b·dx/dt). Newton's 2nd law: m·d²x/dt²=−kx−b(dx/dt) → m·ẍ+bẋ+kx=0. Solutions depend on damping: underdamped (oscillates with decreasing amplitude), critically damped (fastest return to equilibrium without oscillation), overdamped (slowly returns without oscillating).","hard"),
      P("A rocket loses mass as it burns fuel. Qualitatively explain how thrust acceleration changes.","Think about F=dp/dt for variable mass.","Thrust force F stays roughly constant (depends on exhaust velocity and mass flow rate). But as fuel burns, rocket mass decreases → F=ma → a=F/m increases as m decreases. This is why rocket acceleration increases over time even with constant thrust — the same force acts on less and less mass. Variable mass problems require the rocket equation: F_thrust=v_exhaust·(dm/dt).","hard")
    ]),
    T("Work, Energy, and Power", [
      P("Find the work done by F=3x² N on an object moved from x=0 to x=4m.","W=∫F dx","W=∫₀⁴ 3x² dx=[x³]₀⁴=64J.","medium"),
      P("Prove the work-energy theorem from Newton's second law using calculus.","Integrate F=ma with respect to displacement.","W=∫F dx=∫ma dx=∫m(dv/dt)dx=∫m(dv/dx)(dx/dt)dx=∫mv(dv/dx)dx=∫mv dv=[½mv²]=½mv²−½mv₀²=ΔKE. ✓","hard"),
      P("Define power and find instantaneous power of a force F=5x N acting on an object with v=2x m/s at x=3m.","P=F·v","At x=3: F=15N, v=6 m/s. P=F·v=15×6=90W.","medium")
    ]),
    T("Systems of Particles and Linear Momentum", [
      P("Find the center of mass of three masses: 1kg at x=0, 2kg at x=3, 3kg at x=6.","x_cm=Σm_i·x_i/M_total","M=6kg. x_cm=(1·0+2·3+3·6)/6=(0+6+18)/6=24/6=4m.","easy"),
      P("Two carts are initially at rest on a frictionless track. Cart A (1kg) explodes and separates. A moves right at 4 m/s. Find B's velocity if B=2kg.","Conservation of momentum from rest: 0=m_A·v_A+m_B·v_B","0=1(4)+2(v_B) → v_B=−2 m/s (moves left).","easy"),
      P("How does the center of mass theorem simplify problems with explosions or complex interactions?","Think about external forces only.","CM theorem: F_net_external=Ma_cm. Internal forces (between parts of the system) don't affect the motion of the center of mass. Practical use: in an explosion, no external forces → a_cm=0 → CM continues moving at same velocity. In a collision, we can analyze CM motion (determined by external forces) separately from relative motion of the parts.","medium")
    ]),
    T("Rotation", [
      P("A disk (I=½MR²) with M=5kg, R=0.4m starts from rest and has angular acceleration α=3 rad/s². Find torque.","τ=Iα","I=½(5)(0.16)=0.4 kg·m². τ=0.4×3=1.2 N·m.","easy"),
      P("State the parallel axis theorem and use it to find the moment of inertia of a disk rotating about its edge.","I=I_cm+Md²","I_cm of disk=½MR². d=R (edge). I_edge=½MR²+MR²=3MR²/2.","medium"),
      P("Compare translational and rotational kinetic energy for a rolling sphere.","Think about the two forms of KE for rolling.","Rolling sphere (v=Rω): KE_total=KE_translational+KE_rotational=½mv²+½Iω². For solid sphere: I=2/5 MR². KE_rot=½(2/5MR²)(v/R)²=1/5mv². KE_total=½mv²+1/5mv²=7/10mv². The rotational KE is 2/7 of total (I_rot/I_total=2/7). Rolling objects always have less speed at the bottom of a ramp than sliding objects because energy goes into rotation.","hard")
    ]),
    T("Oscillations", [
      P("Derive the period of a simple pendulum using dimensional analysis or the differential equation.","Torque=-mglsinθ≈-mglθ for small θ.","For small angles: τ=Iα → −mgl·θ=ml²·(d²θ/dt²) → d²θ/dt²=−(g/l)θ. This is SHM with ω²=g/l → T=2π/ω=2π√(l/g). Note: period independent of mass and (for small angles) amplitude.","hard"),
      P("A spring-mass system has E_total=0.5J, k=50 N/m. Find amplitude.","E=½kA²","A=√(2E/k)=√(1/50)=0.141m≈14.1cm.","medium"),
      P("How does damping affect the frequency and amplitude of oscillation?","Think about underdamped vs. critically damped.","Underdamped (small damping): oscillates with amplitude decreasing exponentially A(t)=A₀e^{−bt/2m}; frequency slightly less than natural frequency. Critically damped: returns to equilibrium fastest without oscillating (b²=4mk). Overdamped (large damping): returns slowly to equilibrium without oscillating. Quality factor Q = energy stored / energy lost per cycle — higher Q means more oscillation cycles before damping out.","hard")
    ]),
    T("Gravitation", [
      P("Derive Kepler's Third Law (T²∝r³) from Newton's law of gravitation and circular orbit mechanics.","Gravity provides centripetal force.","For circular orbit: GMm/r²=mv²/r → v²=GM/r. Circumference=2πr in time T: v=2πr/T. So (2πr/T)²=GM/r → T²=4π²r³/(GM). Therefore T²∝r³. ✓ (The proportionality constant is 4π²/(GM), the same for all objects orbiting the same body.)","hard"),
      P("What is gravitational potential energy and how does it differ from mgh?","Think about the reference point.","U=−GMm/r (reference: U=0 at r=∞). mgh approximation: valid near Earth's surface where g is approximately constant. Exact: ΔU=−GMm/r₂−(−GMm/r₁). mgh works when Δr<<R_Earth. For satellites, rockets, or anything leaving Earth's surface substantially, use the exact formula. Note: U is always negative (below zero) for bound gravitational systems.","medium"),
      P("Define escape velocity and derive its expression.","Think about setting total mechanical energy to zero.","Escape velocity: minimum speed to escape gravitational influence (reach r=∞ with v=0). Set E_total=0: ½mv_esc²+U=0 → ½mv²=GMm/R → v_esc=√(2GM/R). For Earth: v_esc≈11.2 km/s. Independent of mass of escaping object. Black holes: escape velocity>c → nothing escapes.","medium")
    ])
  ],
  # Unit 7 — AP Physics C: Electricity & Magnetism
  [
    T("Electrostatics", [
      P("Use Gauss's Law to find E outside a uniformly charged sphere.","∮E·dA=Q_enc/ε₀","Choose spherical Gaussian surface of radius r>R. By symmetry, E is uniform on surface and radial. ∮E·dA=E·4πr²=Q/ε₀ → E=Q/(4πε₀r²)=kQ/r². Same as point charge — sphere acts like all charge is concentrated at center.","hard"),
      P("What is the electric potential inside a conductor in electrostatic equilibrium?","Think about E field inside conductors.","Inside a conductor in electrostatic equilibrium: E=0 (any field would cause charges to move). Since E=−dV/dr and E=0, V=constant throughout conductor. All free charges reside on the surface. The potential inside equals the potential at the surface. Faraday cage: conductor shields interior from external electric fields.","medium"),
      P("A solid sphere has charge +Q and radius R. Find E and V at r=R/2 (inside), r=R (surface), r=2R (outside).","For conductor: E=0 inside; for insulator: use Gauss inside.","Conducting sphere: Inside (r<R): E=0, V=kQ/R (constant). At surface (r=R): E=kQ/R², V=kQ/R. Outside (r=2R): E=kQ/(4R²)=kQ/(4R²), V=kQ/(2R). (For insulating sphere with uniform charge, E inside increases linearly from 0 at center.)","hard")
    ]),
    T("Conductors, Capacitors, Dielectrics", [
      P("Derive the capacitance of a parallel plate capacitor.","C=Q/V; relate Q, E, and V.","E=σ/ε₀=Q/(ε₀A) between plates. V=Ed=Qd/(ε₀A). C=Q/V=ε₀A/d. With dielectric (κ): C=κε₀A/d.","medium"),
      P("Find the energy stored in a capacitor using three equivalent expressions.","U=QV/2=Q²/2C=CV²/2","All three are equivalent: start from U=∫V dq=∫(q/C)dq=Q²/(2C)=CV²/2=QV/2. The factor of 1/2 arises because voltage builds from 0 to V as charge accumulates — average voltage during charging is V/2.","medium"),
      P("Capacitors C₁=4μF and C₂=6μF are connected in series to 12V. Find charge on each and voltage across each.","Series: 1/C=1/C₁+1/C₂; same Q on each.","1/C=1/4+1/6=5/12 → C=2.4μF. Q=CV=2.4×12=28.8μC (same on both). V₁=Q/C₁=28.8/4=7.2V. V₂=28.8/6=4.8V. Check: 7.2+4.8=12V ✓","medium")
    ]),
    T("Electric Circuits", [
      P("Derive the time constant for an RC circuit and explain what it means.","Q(t)=Q_max(1−e^{−t/RC})","Kirchhoff's voltage law during charging: ε=V_R+V_C=iR+Q/C. With i=dQ/dt: RC·dQ/dt+Q=Cε. Solution: Q(t)=Cε(1−e^{−t/RC}). Time constant τ=RC: time for capacitor to reach 63.2% of full charge (1−1/e). After 5τ: ~99.3% charged. τ has units of seconds (Ω·F=s).","hard"),
      P("Apply Kirchhoff's laws to a circuit with a 12V battery, R₁=4Ω in series, and R₂=6Ω, R₃=3Ω in parallel.","Find equivalent R, then currents and voltages.","Parallel: 1/R₂₃=1/6+1/3=1/2 → R₂₃=2Ω. Total: R=4+2=6Ω. I_total=12/6=2A. V across parallel=2×2=4V. I₂=4/6=0.667A. I₃=4/3=1.33A. Check: 0.667+1.33=2A ✓","medium"),
      P("Derive the power delivered to a resistor and explain why P=I²R and P=V²/R are equivalent.","Use Ohm's Law to convert.","P=IV (general). For resistor: V=IR → P=I(IR)=I²R. Or I=V/R → P=(V/R)V=V²/R. All three forms (P=IV, I²R, V²/R) are equivalent — choose based on what's known. Physical meaning: electric energy converts to thermal energy (heat) at rate I²R — this is Joule heating.","medium")
    ]),
    T("Magnetic Fields", [
      P("An electron moves at 10⁶ m/s perpendicular to a 0.5T field. Find radius of circular motion.","F=qvB=mv²/r → r=mv/(qB)","r=mv/(qB)=(9.11×10⁻³¹)(10⁶)/((1.6×10⁻¹⁹)(0.5))=9.11×10⁻²⁵/8×10⁻²⁰≈1.14×10⁻⁵m=0.011mm.","hard"),
      P("Use the Biot-Savart Law concept to explain why the magnetic field of a long straight wire decreases as 1/r.","Think about how contributions from wire elements add up.","Biot-Savart: each current element contributes dB=μ₀I dl×r̂/(4πr²). For an infinite straight wire, integrating all elements: contributions add up to give B=μ₀I/(2πr). Field forms concentric circles around wire. As distance r increases, field decreases as 1/r (not 1/r² as for a point charge — because we're integrating along an infinite line source).","hard"),
      P("What does Ampere's Law state and when is it useful?","Think about symmetric configurations.","Ampere's Law: ∮B·dl=μ₀I_enc. The line integral of B around a closed loop equals μ₀ times the current enclosed. Useful when there's sufficient symmetry to pull B outside the integral (like Gauss's Law for E). Highly useful for: infinite straight wire (circular loop), solenoid (rectangular loop), toroid. Less useful for asymmetric current distributions.","medium")
    ]),
    T("Electromagnetism and Induction", [
      P("State Faraday's Law in integral form and explain Lenz's Law.","EMF=−dΦ_B/dt","Faraday: EMF=−dΦ_B/dt where Φ_B=∫B·dA is magnetic flux. Lenz's Law: the negative sign — induced EMF opposes the change in flux (nature resists change). Example: bar magnet pushed into coil → increasing flux → induced current creates opposing B field (acts like repelling magnet). Pull magnet away → induced current tries to maintain flux (attracts). Lenz's Law conserves energy (acts as a brake on the magnet).","medium"),
      P("Derive the inductance of a solenoid.","Use Faraday's Law and B inside solenoid.","B inside solenoid=μ₀nI (n=turns/m). Flux per turn=μ₀nIA. Total flux linkage=NΦ=nL·μ₀nIA=μ₀n²LA. By definition: L=NΦ/I=μ₀n²Al. Units: Henry (H=V·s/A). Inductance increases with n² — doubling turns/length quadruples inductance.","hard"),
      P("What is an LC circuit and what determines its oscillation frequency?","Think about energy exchange between capacitor and inductor.","LC circuit: capacitor and inductor in loop — no resistance. Energy oscillates: starts in capacitor (E field), charges inductor (B field), back to capacitor (reversed polarity), etc. Natural frequency: ω=1/√(LC), f=1/(2π√(LC)). Analogous to mass-spring oscillator: L↔m (inertia), 1/C↔k (restoring). Basis of radio tuning — adjusting C changes resonant frequency to select a station.","hard")
    ]),
    T("Maxwell's Equations (Introduction)", [
      P("State all four Maxwell's Equations in words.","Think about what each describes.","(1) Gauss's Law for E: electric fields originate from charges (∮E·dA=Q_enc/ε₀). (2) Gauss's Law for B: no magnetic monopoles — magnetic field lines always form closed loops (∮B·dA=0). (3) Faraday's Law: changing magnetic flux creates electric field (∮E·dl=−dΦ_B/dt). (4) Ampere-Maxwell Law: magnetic fields are created by currents AND changing electric fields (∮B·dl=μ₀I_enc+μ₀ε₀dΦ_E/dt). Together they unify electricity and magnetism.","hard"),
      P("What is Maxwell's displacement current and why was its inclusion essential?","Think about Ampere's Law applied to a charging capacitor.","Problem: apply Ampere's Law to a loop between capacitor plates (no current passes through) → gives B=0. But the magnetic field exists because current flows in the wires. Maxwell resolved this: a changing electric field (between the capacitor plates) produces a magnetic field — called displacement current (J_d=ε₀dE/dt). Adding this term to Ampere's Law makes it internally consistent and predicts electromagnetic waves.","hard"),
      P("How do Maxwell's equations predict that light is an electromagnetic wave?","Think about what happens when you combine Faraday and Ampere-Maxwell.","Combining Faraday's and Ampere-Maxwell's laws in empty space (no charges, no currents): we get wave equations for E and B. The wave speed: v=1/√(μ₀ε₀)=3×10⁸ m/s — exactly the measured speed of light. Maxwell concluded light is an electromagnetic wave — changing E field creates B field, changing B creates E field, and this self-sustaining wave propagates through space. Hertz confirmed with radio waves (1887).","hard")
    ])
  ]
]
