#!/usr/bin/env python3
"""Append comprehensive Science, History, CS, and Health vocab to flashcards.html."""
import pathlib

def c(g, term, definition):
    t = term.replace('\\','\\\\').replace('"','\\"')
    d = definition.replace('\\','\\\\').replace('"','\\"')
    return f'    {{g:{g},term:"{t}",def:"{d}"}}'

# ── SCIENCE ────────────────────────────────────────────────────────────────────
SCI_NEW = [
    # Grade 6 — Life & Earth Science basics
    c(6,'Organism','Any living thing. Must carry out life processes: grow, reproduce, respond to environment.'),
    c(6,'Biotic Factor','Living parts of an ecosystem: plants, animals, bacteria, fungi.'),
    c(6,'Abiotic Factor','Non-living parts of an ecosystem: sunlight, water, temperature, soil, air.'),
    c(6,'Food Chain','A linear sequence showing how energy passes from one organism to the next.'),
    c(6,'Food Web','A complex network of interconnected food chains in an ecosystem.'),
    c(6,'Producer','An organism (usually a plant) that makes its own food through photosynthesis.'),
    c(6,'Consumer','An organism that gets energy by eating other organisms.'),
    c(6,'Decomposer','An organism (fungi, bacteria) that breaks down dead matter and recycles nutrients.'),
    c(6,'Predator','An organism that hunts and eats another organism.'),
    c(6,'Prey','An organism that is hunted and eaten by a predator.'),
    c(6,'Habitat','The natural environment where an organism lives and finds what it needs to survive.'),
    c(6,'Population','All members of the same species living in the same area at the same time.'),
    c(6,'Community','All populations of different species living together in an area.'),
    c(6,'Nucleus','The control center of a cell that contains DNA and directs cell activities.'),
    c(6,'Cell Membrane','The flexible boundary surrounding all cells; controls what enters and exits.'),
    c(6,'Cell Wall','A rigid outer layer found in plant cells, fungi, and bacteria — not in animal cells.'),
    c(6,'Chloroplast','Organelle in plant cells where photosynthesis occurs. Contains chlorophyll.'),
    c(6,'Vacuole','Storage organelle. Plant cells have one large central vacuole; animal cells have small ones.'),
    c(6,'Cytoplasm','The jelly-like fluid filling a cell, in which organelles are suspended.'),
    c(6,'Matter','Anything that has mass and takes up space.'),
    c(6,'Physical Change','A change in matter that does NOT alter its chemical composition. Cutting, melting.'),
    c(6,'Chemical Change','A change that creates a new substance with different properties. Burning, rusting.'),
    c(6,'Density','Mass per unit volume. D = m/v. Determines if an object sinks or floats.'),
    c(6,'Mixture','A combination of two or more substances that are NOT chemically combined.'),
    c(6,'Solution','A homogeneous mixture where one substance dissolves evenly in another.'),
    c(6,'Solute','The substance that dissolves in a solution (the lesser component). Salt in saltwater.'),
    c(6,'Solvent','The substance that does the dissolving (the greater component). Water in saltwater.'),
    c(6,'Rock Cycle','The continuous process by which rocks transform between igneous, sedimentary, and metamorphic.'),
    c(6,'Weathering','The breaking down of rocks at Earth\'s surface by physical or chemical processes.'),
    c(6,'Erosion','The movement of weathered rock and sediment by water, wind, or ice.'),
    # Grade 7 — Life Science deeper
    c(7,'Prokaryote','A cell without a membrane-bound nucleus. Bacteria and archaea are prokaryotes.'),
    c(7,'Eukaryote','A cell with a membrane-bound nucleus. Plants, animals, fungi, and protists are eukaryotes.'),
    c(7,'Organelle','A specialized structure within a cell that performs a specific function.'),
    c(7,'Ribosome','Organelle where protein synthesis occurs. Found in all cells.'),
    c(7,'Endoplasmic Reticulum','Network of membranes in cells. Rough ER (with ribosomes) makes proteins; smooth ER makes lipids.'),
    c(7,'Golgi Apparatus','The cell\'s "post office" — packages and ships proteins made by the ER.'),
    c(7,'Chromosome','Structure made of DNA and protein that carries genes. Humans have 46 (23 pairs).'),
    c(7,'Genotype','The genetic makeup of an organism — the specific alleles it carries (e.g., Bb).'),
    c(7,'Phenotype','The observable traits of an organism resulting from its genotype and environment.'),
    c(7,'Heredity','The passing of traits from parents to offspring through genes.'),
    c(7,'Mutation','A change in the DNA sequence. Can be beneficial, harmful, or neutral.'),
    c(7,'Fossil','Preserved remains or traces of organisms that lived in the past.'),
    c(7,'Species','A group of organisms that can interbreed and produce fertile offspring.'),
    c(7,'Classification','Organizing living things into groups based on shared characteristics (taxonomy).'),
    c(7,'Kingdom','The broadest level of biological classification: Animalia, Plantae, Fungi, Protista, Monera.'),
    c(7,'Vertebrate','An animal with a backbone (spinal column). Fish, amphibians, reptiles, birds, mammals.'),
    c(7,'Invertebrate','An animal without a backbone. About 95% of all animal species are invertebrates.'),
    c(7,'Photosynthesis Equation','6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂. Plants make glucose from CO₂ and water.'),
    c(7,'Cellular Respiration','C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. Cells release energy from glucose.'),
    c(7,'ATP','Adenosine Triphosphate — the energy currency of the cell. Powers all cellular work.'),
    # Grade 8 — Physical Science
    c(8,'Force','A push or pull on an object. Measured in newtons (N). Can change speed or direction.'),
    c(8,'Net Force','The overall force on an object after all forces are combined. Determines acceleration.'),
    c(8,'Friction','A force opposing motion between two surfaces in contact.'),
    c(8,'Gravity','A force of attraction between any two objects with mass. Increases with mass, decreases with distance.'),
    c(8,'Inertia','An object\'s tendency to resist changes in motion. More mass = more inertia.'),
    c(8,'Acceleration','The rate of change in velocity. a = (v_f − v_i)/t. Can be speeding up, slowing, or turning.'),
    c(8,'Momentum','The product of mass and velocity. p = mv. A heavy, fast object has large momentum.'),
    c(8,'Work','Force applied over a distance in the direction of motion. W = F × d. Measured in joules.'),
    c(8,'Power','The rate of doing work. P = W/t. Measured in watts.'),
    c(8,'Thermal Energy','The total kinetic energy of all particles in a substance (related to temperature).'),
    c(8,'Conduction','Transfer of heat through direct contact between objects or particles.'),
    c(8,'Convection','Transfer of heat through movement of a fluid (liquid or gas).'),
    c(8,'Radiation','Transfer of energy through electromagnetic waves; doesn\'t need matter.'),
    c(8,'Electromagnetic Wave','A wave made of electric and magnetic fields that can travel through a vacuum.'),
    c(8,'Frequency','The number of wave cycles per second. Measured in hertz (Hz).'),
    c(8,'Wavelength','The distance between two consecutive peaks (or troughs) of a wave.'),
    c(8,'Amplitude (wave)','The height of a wave from rest position to crest. Related to energy of the wave.'),
    c(8,'Reflection','Bouncing of a wave off a surface.'),
    c(8,'Refraction','Bending of a wave as it passes from one medium to another at an angle.'),
    c(8,'Ohm\'s Law','V = IR. Voltage equals current times resistance. Fundamental law of electricity.'),
    c(8,'Electric Circuit','A closed path through which electric current flows.'),
    c(8,'Series Circuit','A circuit with only one path for current to flow. One break stops all flow.'),
    c(8,'Parallel Circuit','A circuit with multiple paths for current. One break doesn\'t stop all flow.'),
    # Grade 9 — Chemistry
    c(9,'Periodic Table','A chart organizing elements by atomic number and chemical properties into periods and groups.'),
    c(9,'Atomic Number','The number of protons in an atom\'s nucleus. Defines the element.'),
    c(9,'Atomic Mass','The average mass of an element\'s atoms, measured in atomic mass units (amu).'),
    c(9,'Proton','A positively charged particle in the nucleus. Number of protons = atomic number.'),
    c(9,'Neutron','A neutral (no charge) particle in the nucleus. Protons + neutrons = mass number.'),
    c(9,'Electron','A negatively charged particle orbiting the nucleus in energy levels (shells).'),
    c(9,'Isotope','Atoms of the same element with different numbers of neutrons (same protons, different mass).'),
    c(9,'Ion','An atom or molecule that has gained or lost electrons, giving it a charge.'),
    c(9,'Valence Electrons','Electrons in the outermost energy level. Determine how an atom bonds.'),
    c(9,'Electronegativity','An atom\'s ability to attract electrons in a chemical bond.'),
    c(9,'Oxidation','Loss of electrons in a chemical reaction. "OIL" — Oxidation Is Loss.'),
    c(9,'Reduction','Gain of electrons in a chemical reaction. "RIG" — Reduction Is Gain.'),
    c(9,'Reactant','A starting substance in a chemical reaction (left side of equation).'),
    c(9,'Product','A substance formed as a result of a chemical reaction (right side of equation).'),
    c(9,'Law of Conservation of Mass','Matter cannot be created or destroyed — atoms are rearranged in reactions.'),
    c(9,'Stoichiometry','Calculating the quantities of reactants and products in chemical reactions.'),
    c(9,'Molarity','Concentration of a solution: moles of solute per liter of solution. M = mol/L.'),
    c(9,'Acid','A substance that donates H⁺ ions in solution. pH < 7. Tastes sour, reacts with metals.'),
    c(9,'Base','A substance that accepts H⁺ ions (donates OH⁻). pH > 7. Tastes bitter, feels slippery.'),
    c(9,'Neutralization','A reaction between an acid and a base producing water and a salt.'),
    # Grade 10 — Biology
    c(10,'Protein Synthesis','The two-step process (transcription + translation) by which DNA directs protein production.'),
    c(10,'Transcription','DNA is read and copied into mRNA in the nucleus.'),
    c(10,'Translation','mRNA is read by ribosomes to assemble a protein from amino acids.'),
    c(10,'Codon','A three-base sequence on mRNA that codes for a specific amino acid.'),
    c(10,'Punnett Square','A diagram predicting the probability of offspring genotypes from a genetic cross.'),
    c(10,'Incomplete Dominance','Neither allele is fully dominant; heterozygotes show a blended phenotype. Red + white = pink.'),
    c(10,'Codominance','Both alleles are fully expressed in a heterozygote. AB blood type.'),
    c(10,'Sex-Linked Trait','A trait controlled by a gene on the X or Y chromosome. Color-blindness is X-linked.'),
    c(10,'Karyotype','An image of an organism\'s complete set of chromosomes arranged in pairs.'),
    c(10,'Evolution','Change in the genetic makeup of a population over time.'),
    c(10,'Speciation','The formation of a new species from existing populations, usually through reproductive isolation.'),
    c(10,'Homologous Structures','Body parts with similar underlying structure in different species, suggesting common ancestry.'),
    c(10,'Vestigial Structures','Body parts that have lost their original function through evolution (e.g., human tailbone).'),
    c(10,'Carrying Capacity','The maximum population size an environment can sustainably support.'),
    c(10,'Ecological Succession','The gradual change in an ecosystem over time from one community to another.'),
    # Grade 11 — Physics & Chemistry
    c(11,'Coulomb\'s Law','The force between charges: F = kq₁q₂/r². Like charges repel; opposite charges attract.'),
    c(11,'Magnetic Field','A region around a magnet where magnetic forces act on other magnets or moving charges.'),
    c(11,'Faraday\'s Law','A changing magnetic field induces an electric current. Basis of generators.'),
    c(11,'Thermodynamics','The study of heat, work, and energy transformations. Based on 4 laws.'),
    c(11,'First Law of Thermodynamics','Energy cannot be created or destroyed — only converted. (Conservation of energy).'),
    c(11,'Second Law of Thermodynamics','Entropy of a closed system always increases. Heat flows from hot to cold.'),
    c(11,'Wave-Particle Duality','Light and matter can behave as both waves and particles (quantum physics).'),
    c(11,'Photoelectric Effect','Light ejects electrons from a metal surface. Proved light is made of photons.'),
    c(11,'Equilibrium (chemistry)','A state where the rates of forward and reverse reactions are equal.'),
    c(11,'Le Chatelier\'s Principle','A system at equilibrium will shift to counteract any stress placed on it.'),
    c(11,'Hess\'s Law','The total enthalpy change of a reaction is the same regardless of the path taken.'),
    c(11,'Colligative Property','A property depending on the NUMBER of solute particles (boiling point elevation, freezing point depression).'),
    # Grade 12 — Advanced Science
    c(12,'Quantum Mechanics','The branch of physics describing behavior of matter and energy at atomic/subatomic scales.'),
    c(12,'Nuclear Fission','Splitting a heavy nucleus into lighter nuclei, releasing enormous energy. Used in nuclear power.'),
    c(12,'Nuclear Fusion','Combining light nuclei into a heavier one, releasing even more energy. Powers the Sun.'),
    c(12,'CRISPR','A gene-editing technology allowing scientists to precisely modify DNA sequences.'),
    c(12,'Stem Cell','An undifferentiated cell capable of developing into many different cell types.'),
    c(12,'Epigenetics','The study of heritable changes in gene expression that don\'t involve changes to DNA sequence.'),
    c(12,'Trophic Level','The position an organism occupies in a food chain. Producers = level 1; primary consumers = level 2.'),
    c(12,'Carbon Cycle','The movement of carbon through the atmosphere, oceans, soil, and living things.'),
    c(12,'Greenhouse Effect','The trapping of heat in Earth\'s atmosphere by gases like CO₂, methane, and water vapor.'),
    c(12,'Biogeochemical Cycle','The cycling of chemical elements through biotic and abiotic components of an ecosystem.'),
]

# ── HISTORY ────────────────────────────────────────────────────────────────────
HIST_NEW = [
    # Grade 6 — Ancient World
    c(6,'Artifact','An object made or used by humans in the past; studied by archaeologists.'),
    c(6,'Archaeology','The scientific study of past human cultures through material remains and artifacts.'),
    c(6,'Mesopotamia','Region between the Tigris and Euphrates rivers; site of some of the world\'s first civilizations.'),
    c(6,'Cuneiform','One of the earliest writing systems, developed in Mesopotamia around 3200 BCE.'),
    c(6,'Hieroglyphics','Ancient Egyptian writing system using pictorial symbols.'),
    c(6,'Pharaoh','The ruler of ancient Egypt, considered both a king and a god.'),
    c(6,'Dynasty','A series of rulers from the same family who pass power from one generation to the next.'),
    c(6,'Republic','A government in which citizens elect representatives to make decisions on their behalf.'),
    c(6,'Senate','A governing body of elected representatives. Rome\'s Senate was central to the Republic.'),
    c(6,'Tyrant','In ancient Greece, a ruler who seized power without legal authority. Not necessarily cruel.'),
    c(6,'Oligarchy','Government by a small group of wealthy or powerful people.'),
    c(6,'Theocracy','A government ruled by religious leaders or based on divine authority.'),
    c(6,'Trade Route','A path used by merchants to exchange goods between regions or civilizations.'),
    c(6,'Silk Road','Ancient network of trade routes connecting China to the Mediterranean world.'),
    c(6,'Monotheism','Belief in one god. Judaism, Christianity, and Islam are monotheistic religions.'),
    c(6,'Polytheism','Belief in multiple gods. Ancient Greek, Roman, Egyptian, and Hindu religions.'),
    c(6,'Caste System','A rigid social hierarchy based on birth, especially associated with ancient and traditional India.'),
    c(6,'Mandate of Heaven','Chinese concept that emperors ruled with divine approval; losing it justified rebellion.'),
    # Grade 7 — Medieval to Early Modern
    c(7,'Magna Carta','1215 English document limiting royal power and establishing that the king must obey the law.'),
    c(7,'Crusades','A series of religious wars (1096–1291) by European Christians to reclaim the Holy Land.'),
    c(7,'Black Death','Bubonic plague pandemic (1347–1351) that killed ~1/3 of Europe\'s population.'),
    c(7,'Gutenberg\'s Press','The printing press (c. 1440) that made books affordable and spread literacy across Europe.'),
    c(7,'Humanism','An intellectual movement placing human potential and reason at the center, rather than religion.'),
    c(7,'Scientific Revolution','16th–17th century transformation in scientific thought: Copernicus, Galileo, Newton.'),
    c(7,'Heliocentric Model','Copernicus\'s theory that the Earth and planets orbit the Sun (not Earth-centered).'),
    c(7,'Absolute Monarchy','A system where a ruler has unlimited, unchecked power over government and subjects.'),
    c(7,'Divine Right of Kings','The doctrine that monarchs derive their authority directly from God.'),
    c(7,'Mercantilism','Economic theory that wealth = gold/silver; colonies exist to enrich the mother country.'),
    c(7,'Triangular Trade','The three-legged trade route linking Europe, Africa, and the Americas; central to the slave trade.'),
    c(7,'Middle Passage','The brutal ocean crossing that enslaved Africans were forced to endure to the Americas.'),
    c(7,'Encomienda','Spanish colonial system granting colonizers the labor of indigenous peoples.'),
    # Grade 8 — American History
    c(8,'Declaration of Independence','1776 document declaring the 13 colonies independent from Britain, authored by Jefferson.'),
    c(8,'Constitution','The supreme law of the United States (1787), establishing the framework of government.'),
    c(8,'Bill of Rights','The first 10 amendments to the U.S. Constitution, protecting individual freedoms.'),
    c(8,'Separation of Powers','Dividing government into three branches (legislative, executive, judicial) to prevent tyranny.'),
    c(8,'Amendment','A formal change or addition to the U.S. Constitution. There are 27 amendments.'),
    c(8,'Popular Sovereignty','The principle that government authority comes from the people.'),
    c(8,'Judicial Review','The Supreme Court\'s power to declare laws unconstitutional (established in Marbury v. Madison).'),
    c(8,'Louisiana Purchase','1803 deal where the U.S. bought ~828,000 square miles from France for $15 million.'),
    c(8,'Industrial Revolution','Late 18th–19th century shift from hand production to machine manufacturing.'),
    c(8,'Sectionalism','Excessive loyalty to the interests of one\'s region over the nation as a whole.'),
    c(8,'Emancipation Proclamation','Lincoln\'s 1863 executive order declaring enslaved people in Confederate states free.'),
    c(8,'Reconstruction','1865–1877 federal program to reintegrate Confederate states and protect newly freed people.'),
    c(8,'Jim Crow Laws','State and local laws enforcing racial segregation in the South after Reconstruction.'),
    c(8,'Gilded Age','Late 19th century U.S. era of rapid industrialization, massive inequality, and political corruption.'),
    # Grade 9 — World Conflicts & Ideologies
    c(9,'Imperialism','Policy of extending a nation\'s power through colonization, military force, or economic dominance.'),
    c(9,'Alliance System','Network of mutual-defense treaties among European powers; a cause of WWI escalation.'),
    c(9,'Trench Warfare','WWI military tactic of fighting from dug trenches; led to stalemate and massive casualties.'),
    c(9,'Armistice','An agreement to stop fighting; WWI ended with the Armistice of November 11, 1918.'),
    c(9,'Treaty of Versailles','1919 peace treaty ending WWI; blamed Germany, demanded reparations, redrew borders.'),
    c(9,'Fascism','Far-right authoritarian nationalism emphasizing the state over the individual; Mussolini, Hitler.'),
    c(9,'Holocaust','The systematic genocide of 6 million Jews and millions of others by Nazi Germany.'),
    c(9,'Blitzkrieg','German "lightning war" strategy using fast, combined-arms attacks to overwhelm opponents.'),
    c(9,'D-Day','June 6, 1944 — Allied invasion of Normandy, France; largest seaborne invasion in history.'),
    c(9,'United Nations','International organization founded 1945 to maintain peace and promote cooperation.'),
    c(9,'Marshall Plan','U.S. program (1948–1952) providing economic aid to rebuild war-torn Western Europe.'),
    c(9,'Iron Curtain','Churchill\'s term for the ideological/physical boundary dividing Cold War Europe.'),
    c(9,'Containment','U.S. Cold War policy of preventing the spread of Soviet communism beyond existing borders.'),
    c(9,'Proxy War','A conflict where competing powers support opposing sides without directly fighting each other.'),
    # Grade 10 — Modern World
    c(10,'Apartheid','South Africa\'s system of institutionalized racial segregation (1948–1991).'),
    c(10,'Colonialism','Establishing colonies in foreign territories to exploit resources and extend political control.'),
    c(10,'Partition of India','1947 division of British India into independent Hindu-majority India and Muslim-majority Pakistan.'),
    c(10,'Korean War','1950–1953 conflict between North Korea (Soviet-backed) and South Korea (US-backed); ended in stalemate.'),
    c(10,'Cuban Missile Crisis','1962 thirteen-day standoff between U.S. and USSR over Soviet missiles in Cuba.'),
    c(10,'Vietnam War','1955–1975 conflict in Southeast Asia between North Vietnam (communist) and South Vietnam (U.S.-backed).'),
    c(10,'Space Race','Cold War competition between the U.S. and USSR to achieve superiority in space exploration.'),
    c(10,'Détente','A period of reduced Cold War tensions in the 1970s through diplomacy and arms-control agreements.'),
    c(10,'Glasnost','Gorbachev\'s policy of "openness" in the USSR allowing greater political transparency.'),
    c(10,'Perestroika','Gorbachev\'s policy of "restructuring" to reform the Soviet economic and political system.'),
    c(10,'Nonviolent Resistance','Achieving political change through peaceful means; used by Gandhi and Martin Luther King Jr.'),
    c(10,'Palestinian-Israeli Conflict','Ongoing territorial and political struggle over land and self-determination in the Middle East.'),
    # Grade 11 — U.S. in the 20th Century
    c(11,'Progressive Era','1890s–1920s reform period addressing industrialization\'s ills: child labor, corruption, suffrage.'),
    c(11,'Muckraker','Investigative journalist exposing corruption and social problems during the Progressive Era.'),
    c(11,'19th Amendment','1920 constitutional amendment granting women the right to vote.'),
    c(11,'Great Migration','1910–1970 movement of ~6 million Black Americans from the South to Northern cities.'),
    c(11,'Harlem Renaissance','1920s–30s flourishing of African American art, literature, and music centered in Harlem, NYC.'),
    c(11,'Dust Bowl','1930s environmental disaster of severe drought and dust storms devastating the Great Plains.'),
    c(11,'McCarthyism','1950s anti-communist hysteria led by Senator McCarthy; accused many without evidence.'),
    c(11,'Brown v. Board of Education','1954 Supreme Court ruling that racial segregation in public schools was unconstitutional.'),
    c(11,'Great Society','LBJ\'s 1960s domestic programs creating Medicare, Medicaid, and expanding civil rights.'),
    c(11,'Watergate Scandal','1972–74 political scandal leading to Nixon\'s resignation over a cover-up of a break-in.'),
    # Grade 12 — Contemporary World
    c(12,'Genocide Convention','1948 international treaty defining and prohibiting genocide.'),
    c(12,'Universal Declaration of Human Rights','1948 UN document listing fundamental rights of all people regardless of nationality.'),
    c(12,'Neoliberalism','Economic policy emphasizing free markets, deregulation, privatization, and reduced government spending.'),
    c(12,'Climate Change','Long-term shifts in global temperatures and weather patterns, significantly accelerated by human activity.'),
    c(12,'Terrorism','The use of violence and intimidation against civilians to achieve political or ideological goals.'),
    c(12,'Arab Spring','2010–2012 wave of pro-democracy uprisings across the Arab world.'),
    c(12,'Cybersecurity','Protecting computer systems and networks from theft, damage, or unauthorized access.'),
    c(12,'International Law','A body of rules and principles governing relations between nations.'),
    c(12,'Supranational Organization','A body with authority over member nations (e.g., EU, UN, WTO).'),
    c(12,'Refugee','A person forced to flee their country due to war, persecution, or natural disaster.'),
]

# ── CS ─────────────────────────────────────────────────────────────────────────
CS_NEW = [
    # Grade 6 — Foundations
    c(6,'Hardware','The physical components of a computer: CPU, RAM, hard drive, keyboard, monitor.'),
    c(6,'Software','Programs and operating systems that run on a computer.'),
    c(6,'Input Device','Hardware that sends data TO the computer: keyboard, mouse, microphone, camera.'),
    c(6,'Output Device','Hardware that receives data FROM the computer: monitor, speakers, printer.'),
    c(6,'CPU (Central Processing Unit)','The "brain" of the computer that carries out instructions.'),
    c(6,'RAM (Random Access Memory)','Short-term memory the CPU uses for active tasks. Cleared when power off.'),
    c(6,'Storage','Long-term memory (hard drive, SSD, USB). Persists when power is off.'),
    c(6,'Operating System','Software that manages hardware and runs other programs. Windows, macOS, Linux.'),
    c(6,'Network','A group of computers connected to share resources and communicate.'),
    c(6,'Internet','A global network of networks connected by standardized protocols.'),
    c(6,'Decomposition','Breaking a complex problem into smaller, more manageable sub-problems.'),
    c(6,'Pattern Recognition','Identifying similarities or patterns within problems to solve them more efficiently.'),
    c(6,'Abstraction','Focusing on essential information while ignoring irrelevant details.'),
    c(6,'Flowchart','A diagram using shapes and arrows to map the steps of an algorithm or process.'),
    c(6,'Pseudocode','Plain-language description of an algorithm\'s steps — not actual code, but code-like.'),
    c(6,'Debugging','Finding and fixing errors (bugs) in code.'),
    # Grade 7 — Programming Concepts
    c(7,'Syntax (CS)','The set of rules governing how code must be written in a programming language.'),
    c(7,'Runtime Error','An error that occurs while a program is executing, causing it to crash.'),
    c(7,'Logic Error','A bug where code runs without crashing but produces incorrect output.'),
    c(7,'Compile','To translate source code into machine code that a computer can execute.'),
    c(7,'Interpreter','A program that executes code line by line without compiling the whole program first.'),
    c(7,'Constant','A named value that CANNOT change during program execution.'),
    c(7,'Operator','A symbol performing an operation: arithmetic (+,-,*,/), comparison (==,<,>), logical (and, or, not).'),
    c(7,'Concatenation','Joining two or more strings together. "Hello" + " World" = "Hello World".'),
    c(7,'Nested Loop','A loop inside another loop. The inner loop completes all iterations for each outer iteration.'),
    c(7,'Scope','The region of code where a variable is accessible (local vs. global scope).'),
    c(7,'Global Variable','A variable accessible throughout the entire program.'),
    c(7,'Local Variable','A variable only accessible within the function or block where it was defined.'),
    c(7,'Import / Library','Pre-written code that adds functionality to your program. import math, import random.'),
    # Grade 8 — Data Structures & Algorithms
    c(8,'Stack','A data structure where the last item added is the first removed (LIFO — Last In, First Out).'),
    c(8,'Queue','A data structure where the first item added is the first removed (FIFO — First In, First Out).'),
    c(8,'Dictionary / Hash Map','A data structure storing key-value pairs for fast lookup. {"name":"Dee","age":14}.'),
    c(8,'Linear Search','Checking each element one by one until the target is found. O(n) time.'),
    c(8,'Binary Search','Efficiently finding a target in a sorted list by halving the search space each step. O(log n).'),
    c(8,'Bubble Sort','Simple sorting algorithm that repeatedly swaps adjacent elements if out of order. O(n²).'),
    c(8,'Merge Sort','Efficient divide-and-conquer sorting algorithm. Splits, sorts, then merges. O(n log n).'),
    c(8,'Iteration','Repeating a set of instructions a certain number of times or until a condition is met.'),
    c(8,'Modulo (%)','The remainder after division. 17 % 5 = 2. Used to check divisibility and wrap values.'),
    c(8,'Boolean Logic','Logic using AND, OR, NOT to combine true/false conditions.'),
    c(8,'Truthy / Falsy','In Python/JS, values treated as True or False in conditionals (e.g., 0, "", None are falsy).'),
    # Grade 9 — OOP & Design
    c(9,'Encapsulation','Bundling data (attributes) and methods together in a class, hiding internal details.'),
    c(9,'Polymorphism','The ability of different classes to be treated as the same type via shared interfaces.'),
    c(9,'Abstraction (OOP)','Hiding complex implementation details and exposing only what is necessary.'),
    c(9,'Constructor','A special method that runs when an object is created, setting initial attribute values.'),
    c(9,'Method','A function defined inside a class that operates on the object\'s data.'),
    c(9,'Instance','A specific object created from a class. Each instance has its own attribute values.'),
    c(9,'Attribute','A variable belonging to a class or object, storing its properties/state.'),
    c(9,'Super() / Parent Class','Calling a method from the parent class in an inherited child class.'),
    c(9,'Interface','A contract specifying methods a class must implement, without providing the code.'),
    c(9,'Design Pattern','A reusable solution to a common software design problem (e.g., Singleton, Observer).'),
    c(9,'UML Diagram','Unified Modeling Language diagram — a visual blueprint for software design.'),
    c(9,'Agile Development','An iterative software development approach focusing on collaboration and rapid delivery.'),
    # Grade 10 — Web & Systems
    c(10,'HTML','HyperText Markup Language — the structure/skeleton of web pages.'),
    c(10,'CSS','Cascading Style Sheets — controls the visual appearance of HTML elements.'),
    c(10,'JavaScript','A programming language running in browsers, making web pages interactive.'),
    c(10,'DOM (Document Object Model)','A tree representation of an HTML document that JavaScript can manipulate.'),
    c(10,'HTTP/HTTPS','Protocols for transferring data on the web. HTTPS adds encryption for security.'),
    c(10,'IP Address','A unique numerical label identifying a device on a network (e.g., 192.168.1.1).'),
    c(10,'DNS (Domain Name System)','Translates human-readable domain names (google.com) into IP addresses.'),
    c(10,'Client-Server Model','Architecture where clients request resources from servers that respond with data.'),
    c(10,'Packet','A small unit of data transmitted over a network. Large files are split into packets.'),
    c(10,'Firewall','A security system that monitors and controls incoming/outgoing network traffic.'),
    c(10,'Hexadecimal','Base-16 number system using 0-9 and A-F. Used in color codes (#FF5733) and memory addresses.'),
    c(10,'ASCII','American Standard Code for Information Interchange — encodes characters as numbers (A=65, a=97).'),
    c(10,'Unicode','A universal character encoding standard supporting virtually all writing systems.'),
    # Grade 11 — Algorithms & Data
    c(11,'Big O Notation','A way to describe algorithm efficiency as input grows: O(1), O(log n), O(n), O(n²).'),
    c(11,'Space Complexity','How much memory an algorithm uses relative to input size.'),
    c(11,'Graph (Data Structure)','A collection of nodes (vertices) connected by edges. Used for networks, maps, social connections.'),
    c(11,'Tree (Data Structure)','A hierarchical data structure with a root node and child nodes. Binary trees, search trees.'),
    c(11,'Linked List','A chain of nodes, each storing data and a pointer to the next node.'),
    c(11,'Hashing','Converting data to a fixed-size value (hash) for fast retrieval in hash tables.'),
    c(11,'Dynamic Programming','Optimizing algorithms by storing results of sub-problems to avoid redundant computation.'),
    c(11,'Greedy Algorithm','Making locally optimal choices at each step, hoping for a global optimum.'),
    c(11,'Regular Expression','A sequence of characters defining a search pattern, used for text matching.'),
    c(11,'REST API','An architectural style for web APIs using HTTP methods (GET, POST, PUT, DELETE).'),
    c(11,'JSON','JavaScript Object Notation — a lightweight data format for transmitting data between systems.'),
    c(11,'Cloud Computing','Delivering computing services (servers, storage, databases) over the internet.'),
    # Grade 12 — Advanced & Society
    c(12,'Neural Network','A machine learning model inspired by the brain, made of layers of interconnected nodes.'),
    c(12,'Training Data','The dataset used to teach a machine learning model to recognize patterns.'),
    c(12,'Overfitting','When a model learns training data too well and performs poorly on new data.'),
    c(12,'Natural Language Processing','AI that enables computers to understand, interpret, and generate human language.'),
    c(12,'Blockchain','A distributed, decentralized ledger recording transactions across many computers.'),
    c(12,'Public Key Cryptography','Encryption using a public key to encrypt and a private key to decrypt data.'),
    c(12,'Two-Factor Authentication','Security requiring two verification methods: something you know + something you have.'),
    c(12,'Digital Footprint','The trail of data you leave when using the internet — both active and passive.'),
    c(12,'Net Neutrality','The principle that ISPs must treat all internet traffic equally, without throttling.'),
    c(12,'Moore\'s Law','Observation that transistor count on chips doubles ~every 2 years, increasing computing power.'),
]

# ── HEALTH ─────────────────────────────────────────────────────────────────────
HEALTH_NEW = [
    # Grade 6 — Nutrition & Body
    c(6,'Fat','A nutrient providing energy (9 cal/g), insulation, and vitamin absorption. Saturated vs. unsaturated.'),
    c(6,'Vitamin','Organic compounds needed in small amounts for normal body function. A, B, C, D, E, K.'),
    c(6,'Mineral','Inorganic nutrients essential for body processes. Calcium (bones), iron (blood), potassium.'),
    c(6,'Water','Essential nutrient making up ~60% of body weight. Involved in almost every body process.'),
    c(6,'Calorie','A unit of energy from food. The body needs calories to fuel all functions.'),
    c(6,'Digestive System','Organ system that breaks down food into nutrients: mouth, esophagus, stomach, intestines.'),
    c(6,'Respiratory System','Organ system bringing oxygen in and expelling CO₂: nose, trachea, lungs, diaphragm.'),
    c(6,'Skeletal System','The 206 bones of the body providing structure, protection, and blood cell production.'),
    c(6,'Muscular System','Three types of muscle: skeletal (voluntary), smooth (involuntary), cardiac (heart).'),
    c(6,'Nervous System','The brain, spinal cord, and nerves that control and coordinate body functions.'),
    c(6,'Endocrine System','Glands that produce hormones regulating growth, metabolism, and reproduction.'),
    c(6,'Hormone','A chemical messenger produced by endocrine glands that travels through the bloodstream.'),
    c(6,'Physical Fitness','The ability to carry out daily tasks with energy and without fatigue. 5 components.'),
    c(6,'Flexibility','The range of motion around a joint. Improved by stretching and yoga.'),
    c(6,'Muscular Strength','The maximum force a muscle can exert in a single effort.'),
    c(6,'Muscular Endurance','The ability of a muscle to sustain repeated contractions over time.'),
    c(6,'Cardiorespiratory Endurance','The ability of the heart and lungs to supply oxygen during sustained exercise.'),
    # Grade 7 — Disease & Prevention
    c(7,'Bacteria','Single-celled prokaryotic microorganisms. Most are harmless; some cause disease.'),
    c(7,'Virus','A non-living pathogen that invades cells and uses them to reproduce. Cannot be treated with antibiotics.'),
    c(7,'Antibiotic','A medicine that kills or slows bacterial growth. Does NOT work against viruses.'),
    c(7,'Antibody','A protein made by the immune system that specifically neutralizes a pathogen.'),
    c(7,'Antigen','A foreign substance (on a pathogen) that triggers the immune system to produce antibodies.'),
    c(7,'Inflammation','The immune system\'s response to injury or infection: redness, swelling, heat, pain.'),
    c(7,'White Blood Cells','Immune cells that detect and destroy pathogens. Also called leukocytes.'),
    c(7,'Lymphatic System','A network of vessels and nodes filtering fluid and fighting infection. Works with immunity.'),
    c(7,'Non-Communicable Disease','A disease that cannot spread person to person. Heart disease, cancer, diabetes.'),
    c(7,'Risk Factor','Something that increases the likelihood of developing a disease or injury.'),
    c(7,'Preventive Health','Actions taken to prevent illness before it occurs: exercise, diet, vaccines, screenings.'),
    c(7,'Screenings','Medical tests to detect diseases early, before symptoms appear.'),
    c(7,'Reproductive Health','Health related to the reproductive system and sexual development.'),
    # Grade 8 — Mental & Emotional Health
    c(8,'Emotional Intelligence','The ability to recognize, understand, and manage your own and others\' emotions.'),
    c(8,'Coping Strategy','A method used to manage stress and difficult emotions in a healthy way.'),
    c(8,'Resilience','The ability to recover from setbacks, adapt to challenges, and keep going.'),
    c(8,'Self-Esteem','How a person feels about their own worth and value.'),
    c(8,'Body Image','How a person perceives and feels about their own physical appearance.'),
    c(8,'Eating Disorder','A serious mental health condition involving distorted eating behaviors (anorexia, bulimia, binge eating).'),
    c(8,'Peer Pressure','Social influence from peers to behave in a certain way, which may be positive or negative.'),
    c(8,'Refusal Skills','Strategies for saying no to risky behaviors while maintaining relationships.'),
    c(8,'Conflict Resolution','Peaceful strategies for resolving disagreements: communication, compromise, mediation.'),
    c(8,'Cyberbullying','Using technology to harass, threaten, or humiliate someone.'),
    c(8,'Healthy Relationship','A relationship built on mutual respect, trust, honesty, and support.'),
    c(8,'Abuse','Mistreatment of a person; can be physical, emotional, verbal, or sexual.'),
    # Grade 9 — Substances & Decision Making
    c(9,'Stimulant','A drug that speeds up the central nervous system. Caffeine, nicotine, amphetamines, cocaine.'),
    c(9,'Depressant','A drug that slows the central nervous system. Alcohol, benzodiazepines.'),
    c(9,'Hallucinogen','A drug causing altered perceptions of reality. LSD, psilocybin, mescaline.'),
    c(9,'Nicotine','An addictive stimulant in tobacco. Causes physical dependence and cardiovascular damage.'),
    c(9,'Alcohol','A legal depressant drug affecting coordination, judgment, and reaction time.'),
    c(9,'Blood Alcohol Content (BAC)','Percentage of alcohol in the bloodstream. 0.08% is the legal driving limit in most U.S. states.'),
    c(9,'Withdrawal','Physical and mental symptoms when stopping a substance the body has become dependent on.'),
    c(9,'Gateway Drug','A substance whose use is thought to lead to using harder drugs.'),
    c(9,'Harm Reduction','Strategies to minimize the negative effects of risky behaviors.'),
    c(9,'Abstinence','Choosing not to engage in a behavior (substance use, sexual activity) to avoid associated risks.'),
    c(9,'Decision-Making Model','A step-by-step process for making thoughtful choices: identify options, consider consequences, decide.'),
    # Grade 10 — Reproduction & Development
    c(10,'Puberty','The period of physical maturation driven by hormones; leads to reproductive capability.'),
    c(10,'Menstrual Cycle','The monthly cycle (~28 days) preparing the female body for possible pregnancy.'),
    c(10,'Fertilization','The union of a sperm cell and an egg cell to form a zygote.'),
    c(10,'STI (Sexually Transmitted Infection)','An infection spread through sexual contact. Examples: chlamydia, HIV, HPV.'),
    c(10,'HIV/AIDS','HIV is the virus that attacks immune cells; AIDS is the advanced stage of HIV infection.'),
    c(10,'Contraception','Methods used to prevent pregnancy. Examples: condoms, birth control pills, IUDs.'),
    c(10,'Prenatal Care','Medical care during pregnancy to monitor the health of mother and developing baby.'),
    c(10,'Infant Mortality Rate','The number of infant deaths per 1,000 live births. An indicator of public health quality.'),
    c(10,'Life Expectancy','The average number of years a person is expected to live based on current mortality rates.'),
    # Grade 11 — Advanced Health Topics
    c(11,'Chronic Pain','Long-lasting pain persisting beyond the expected period of healing.'),
    c(11,'Post-Traumatic Stress Disorder (PTSD)','A mental health condition triggered by experiencing or witnessing a traumatic event.'),
    c(11,'Schizophrenia','A serious mental disorder affecting perception of reality, including hallucinations and delusions.'),
    c(11,'Bipolar Disorder','A mental health condition with extreme mood swings between mania and depression.'),
    c(11,'CBT (Cognitive Behavioral Therapy)','A therapy changing negative thought patterns to improve emotional regulation and behavior.'),
    c(11,'Mindfulness','Focusing attention on the present moment, without judgment. Reduces stress and anxiety.'),
    c(11,'Nutritional Label','FDA-required label on food showing serving size, calories, nutrients, and % daily values.'),
    c(11,'Glycemic Index','A measure of how quickly a food raises blood sugar levels.'),
    c(11,'Saturated Fat','Solid at room temperature; linked to increased LDL (bad) cholesterol. Found in meat and dairy.'),
    c(11,'Unsaturated Fat','Liquid at room temperature; beneficial for heart health. Found in nuts, olive oil, fish.'),
    c(11,'Trans Fat','Artificially hydrogenated fat; raises LDL and lowers HDL. Banned in many countries.'),
    c(11,'Cardiovascular Disease','Conditions affecting the heart and blood vessels; leading cause of death globally.'),
    c(11,'Type 2 Diabetes','A condition where the body doesn\'t use insulin properly, leading to high blood sugar.'),
    # Grade 12 — Community & Global Health
    c(12,'Social Determinants of Health','Non-medical factors (income, education, environment) that shape health outcomes.'),
    c(12,'Health Equity','The state in which every person has a fair opportunity to be as healthy as possible.'),
    c(12,'Pandemic','An epidemic that has spread across a large region, multiple countries, or worldwide.'),
    c(12,'Herd Immunity','When enough of a population is immune to a disease that its spread is significantly slowed.'),
    c(12,'Morbidity','The rate of disease in a population.'),
    c(12,'Mortality','The rate of death in a population.'),
    c(12,'Hospice Care','Compassionate care for people in the final phase of a terminal illness, focusing on comfort.'),
    c(12,'Advance Directive','A legal document stating a person\'s wishes for medical treatment if they cannot speak for themselves.'),
    c(12,'Organ Donation','Consenting to have organs/tissues removed after death for transplantation to save others\' lives.'),
    c(12,'Health Insurance','A contract providing financial coverage for medical expenses.'),
    c(12,'Opioid Crisis','The widespread misuse of prescription and illegal opioids in the U.S., causing record overdose deaths.'),
]

# ── PATCH ──────────────────────────────────────────────────────────────────────
def find_bracket_end(text, start):
    depth, i, in_str, sc = 0, start, False, None
    while i < len(text):
        ch = text[i]
        if in_str:
            if ch == '\\': i += 2; continue
            if ch == sc: in_str = False
        else:
            if ch in ('"', "'", '`'): in_str = True; sc = ch
            elif ch == '[': depth += 1
            elif ch == ']':
                depth -= 1
                if depth == 0: return i
        i += 1
    return -1

p = pathlib.Path('/sessions/admiring-stoic-pascal/mnt/outputs/flashcards.html')
html = p.read_text(encoding='utf-8')

def append_to_subject(html, subject_key, new_entries):
    marker = f'{subject_key}: ['
    pos = html.find(marker)
    if pos == -1:
        print(f'ERROR: {subject_key} not found'); return html
    bracket_start = html.find('[', pos)
    bracket_end = find_bracket_end(html, bracket_start)
    if bracket_end == -1:
        print(f'ERROR: no closing ] for {subject_key}'); return html
    insertion = ',\n' + ',\n'.join(new_entries)
    html = html[:bracket_end] + insertion + '\n  ]' + html[bracket_end+1:]
    print(f'{subject_key}: +{len(new_entries)} cards')
    return html

html = append_to_subject(html, 'science', SCI_NEW)
html = append_to_subject(html, 'history', HIST_NEW)
html = append_to_subject(html, 'cs', CS_NEW)
html = append_to_subject(html, 'health', HEALTH_NEW)

p.write_text(html, encoding='utf-8')
print(f'\nDone. File: {p.stat().st_size // 1024} KB')
