#!/usr/bin/env python3
"""Appends extra vocabulary to existing categories in language.html."""
import pathlib

def v(char, rom, meaning, cat, strokes=None, tips=""):
    s = 'null' if strokes is None else str(strokes)
    tips_e = tips.replace('\\','\\\\').replace('"','\\"')
    return f'  {{char:"{char}",rom:"{rom}",meaning:"{meaning}",cat:"{cat}",strokes:{s},tips:"{tips_e}"}}'

# ── MANDARIN EXTRA ──────────────────────────────────────────────
MAN_EXTRA = [
    # greetings
    v("好久不见","hǎo jiǔ bù jiàn","Long time no see","greetings",None,"好=good, 久=long time, 不=not, 见=see."),
    v("最近怎么样","zuì jìn zěn me yàng","How have you been?","greetings",None,"最近=recently, 怎么样=how is it?"),
    v("生日快乐","shēng rì kuài lè","Happy Birthday","greetings",None,"生日=birthday, 快乐=happy."),
    v("新年快乐","xīn nián kuài lè","Happy New Year","greetings",None,"新=new, 年=year, 快乐=happy."),
    v("恭喜恭喜","gōng xǐ gōng xǐ","Congratulations","greetings",None,"恭喜 repeated for emphasis. Common at Chinese New Year."),
    v("加油","jiā yóu","Go for it! / You can do it!","greetings",None,"加=add, 油=oil/fuel. 'Add fuel!' — cheer someone on."),
    v("祝你好运","zhù nǐ hǎo yùn","Good luck","greetings",None,"祝=wish, 你=you, 好运=good luck."),
    v("慢走","màn zǒu","Goodbye / Take care (to departing guest)","greetings",None,"慢=slow, 走=go. Said when someone leaves your home."),
    v("不好意思","bù hǎo yì si","Excuse me / I'm embarrassed","greetings",None,"Used for minor social embarrassment or to get attention."),
    v("随便","suí biàn","Whatever you like / As you wish","greetings",None,"随=follow, 便=convenience. Very common casual phrase."),
    # numbers — more
    v("两","liǎng","Two (pair/of something)","numbers",7,"Used before measure words: 两个人=two people. Not 二!"),
    v("百分之","bǎi fēn zhī","Percent (%)","numbers",None,"百分之五十=50%. Literally 'out of a hundred parts.'"),
    v("倍","bèi","Times / Fold","numbers",10,"两倍=double, 三倍=triple."),
    v("二十一","èr shí yī","Twenty-one (21)","numbers",None,"十一=11, 十二=12… pattern continues to 十九=19."),
    v("五十五","wǔ shí wǔ","Fifty-five (55)","numbers",None,"Two-digit numbers: tens digit + 十 + ones digit."),
    v("一亿","yī yì","One hundred million","numbers",None,"亿(yì)=100 million. Key unit in Chinese large numbers."),
    v("第三","dì sān","Third","numbers",None,"第+number=ordinal. 第一=1st, 第二=2nd, 第三=3rd."),
    # colors — more
    v("深红","shēn hóng","Dark red / Crimson","colors",None,"深=deep/dark. 深+color = dark shade of that color."),
    v("浅蓝","qiǎn lán","Light blue","colors",None,"浅=shallow/light. 浅+color = light shade."),
    v("深蓝","shēn lán","Dark blue / Navy","colors",None,"深蓝色. Navy blue."),
    v("青色","qīng sè","Cyan / Teal","colors",None,"青 = blue-green. Appears in 青蛙(frog) and 青春(youth)."),
    v("米色","mǐ sè","Beige / Cream","colors",None,"米=rice. Rice-colored = beige!"),
    v("透明","tòu míng","Transparent / Clear","colors",None,"透=penetrate, 明=bright. See-through."),
    v("靛蓝","diàn lán","Indigo","colors",None,"One of the 7 rainbow colors. 红橙黄绿蓝靛紫."),
    v("玫瑰红","méi guī hóng","Rose / Magenta","colors",None,"玫瑰=rose flower. Rose-red color."),
    v("橄榄绿","gǎn lǎn lǜ","Olive green","colors",None,"橄榄=olive. Military/earthy green."),
    v("天蓝","tiān lán","Sky blue","colors",None,"天=sky. Sky-blue, a light brilliant blue."),
    # animals — sea
    v("海豚","hǎi tún","Dolphin","animals",None,"海=sea, 豚=pig (old word). Sea-pig!"),
    v("鲨鱼","shā yú","Shark","animals",None,"鲨 has the fish radical 鱼."),
    v("鲸鱼","jīng yú","Whale","animals",None,"鲸 has the fish radical. World's largest animal."),
    v("螃蟹","páng xiè","Crab","animals",None,"螃蟹 has the insect radical 虫. Popular seafood."),
    v("虾","xiā","Shrimp / Prawn","animals",None,"虾 has the insect radical 虫."),
    v("章鱼","zhāng yú","Octopus","animals",None,"章=chapter, 鱼=fish. Eight-armed 'chapter-fish'!"),
    v("海星","hǎi xīng","Starfish","animals",None,"海=sea, 星=star. Sea-star!"),
    v("水母","shuǐ mǔ","Jellyfish","animals",None,"水=water, 母=mother. Water-mother!"),
    # animals — birds
    v("老鹰","lǎo yīng","Eagle","animals",None,"老=old/honored, 鹰=hawk/eagle. Majestic bird."),
    v("猫头鹰","māo tóu yīng","Owl","animals",None,"猫头=cat-head, 鹰=eagle. Cat-headed eagle!"),
    v("企鹅","qǐ é","Penguin","animals",None,"企=stand on tiptoe, 鹅=goose. Tiptoe-goose!"),
    v("鸽子","gē zi","Pigeon / Dove","animals",None,"鸽 has the bird radical. Symbol of peace."),
    v("乌鸦","wū yā","Crow","animals",None,"乌=black, 鸦=crow. Black crow."),
    v("天鹅","tiān é","Swan","animals",None,"天=sky, 鹅=goose. Sky-goose!"),
    v("孔雀","kǒng què","Peacock","animals",None,"孔雀 — national bird of India. Stunning plumage."),
    v("燕子","yàn zi","Swallow (bird)","animals",None,"燕 is a pictograph of a swallow in flight."),
    # animals — insects & reptiles
    v("蚂蚁","mǎ yǐ","Ant","animals",None,"蚂蚁 has the insect radical 虫 in both characters."),
    v("蚊子","wén zi","Mosquito","animals",None,"蚊 has the insect radical 虫."),
    v("蜘蛛","zhī zhū","Spider","animals",None,"Both characters have the insect radical 虫."),
    v("蜻蜓","qīng tíng","Dragonfly","animals",None,"蜻蜓 has insect radical 虫. Graceful fliers."),
    v("萤火虫","yíng huǒ chóng","Firefly","animals",None,"萤=glowing, 火=fire, 虫=insect. Fire-insect!"),
    v("鳄鱼","è yú","Crocodile","animals",None,"鳄 has the fish radical 鱼."),
    v("蜥蜴","xī yì","Lizard","animals",None,"蜥蜴 both have insect radical 虫."),
    v("蟑螂","zhāng láng","Cockroach","animals",None,"Both characters have insect radical 虫."),
    # food — vegetables
    v("胡萝卜","hú luó bo","Carrot","food",None,"胡=foreign, 萝卜=radish. 'Foreign radish'!"),
    v("黄瓜","huáng guā","Cucumber","food",None,"黄=yellow, 瓜=gourd. Yellow gourd? Now mostly green!"),
    v("白菜","bái cài","Napa cabbage","food",None,"白=white, 菜=vegetable. A staple of Chinese cooking."),
    v("菠菜","bō cài","Spinach","food",None,"菠 came from 波斯(Persia) — originally a Persian vegetable!"),
    v("蘑菇","mó gu","Mushroom","food",None,"蘑菇 — China is the world's largest mushroom producer."),
    v("大蒜","dà suàn","Garlic","food",None,"大=big, 蒜=garlic. Essential in Chinese cooking."),
    v("生姜","shēng jiāng","Ginger","food",None,"生=raw, 姜=ginger. Used fresh or dried."),
    v("玉米","yù mǐ","Corn","food",None,"玉=jade, 米=rice. Jade-rice — corn looks like jade kernels!"),
    v("西红柿","xī hóng shì","Tomato","food",None,"西=west, 红=red, 柿=persimmon. Western red persimmon!"),
    v("洋葱","yáng cōng","Onion","food",None,"洋=foreign/ocean, 葱=scallion. Foreign scallion!"),
    v("土豆","tǔ dòu","Potato","food",None,"土=earth, 豆=bean. Earth-bean!"),
    v("南瓜","nán guā","Pumpkin / Squash","food",None,"南=south, 瓜=gourd. Southern gourd."),
    v("西兰花","xī lán huā","Broccoli","food",None,"西=west, 兰=orchid, 花=flower. Western orchid-flower!"),
    v("茄子","qié zi","Eggplant","food",None,"茄子 has the grass radical 艹. Purple beauty."),
    # food — fruits
    v("草莓","cǎo méi","Strawberry","food",None,"草=grass, 莓=berry. Grass-berry!"),
    v("葡萄","pú tao","Grape","food",None,"葡萄 — both have grass radical. From Central Asia."),
    v("梨","lí","Pear","food",None,"梨 has the tree radical 木 at the bottom."),
    v("菠萝","bō luó","Pineapple","food",None,"Also: 凤梨(fèng lí)=phoenix pear. Taiwan prefers 凤梨."),
    v("樱桃","yīng táo","Cherry","food",None,"樱=cherry tree, 桃=peach. Cherry-peach!"),
    v("桃子","táo zi","Peach","food",None,"桃 has the tree radical 木. Symbol of longevity."),
    v("李子","lǐ zi","Plum","food",None,"李 also means 'plum tree' and is a common surname!"),
    v("蓝莓","lán méi","Blueberry","food",None,"蓝=blue, 莓=berry."),
    v("芒果","máng guǒ","Mango","food",None,"Loanword phonetically from 'mango'."),
    # food — condiments & more dishes
    v("酱油","jiàng yóu","Soy sauce","food",None,"酱=sauce, 油=oil. Essential Chinese condiment."),
    v("醋","cù","Vinegar","food",None,"醋 has the alcohol radical 酉."),
    v("蜂蜜","fēng mì","Honey","food",None,"蜂=bee, 蜜=honey. Bee-honey!"),
    v("黄油","huáng yóu","Butter","food",None,"黄=yellow, 油=oil. Yellow oil."),
    v("奶酪","nǎi lào","Cheese","food",None,"奶=milk, 酪=dairy product."),
    v("酸奶","suān nǎi","Yogurt","food",None,"酸=sour, 奶=milk. Sour milk."),
    v("火锅","huǒ guō","Hot pot","food",None,"火=fire, 锅=pot. Beloved communal dining experience!"),
    v("北京烤鸭","běi jīng kǎo yā","Peking Duck","food",None,"北京=Beijing, 烤=roast, 鸭=duck. Famous dish!"),
    v("小笼包","xiǎo lóng bāo","Soup dumplings","food",None,"小=small, 笼=steamer basket, 包=bun. Shanghai specialty."),
    v("炒饭","chǎo fàn","Fried rice","food",None,"炒=stir-fry, 饭=rice. Quick and delicious."),
    v("春卷","chūn juǎn","Spring roll","food",None,"春=spring, 卷=roll. Traditionally eaten at Spring Festival."),
    # family — more
    v("父母","fù mǔ","Parents","family",None,"父=father, 母=mother. Combined = parents."),
    v("兄弟姐妹","xiōng dì jiě mèi","Siblings","family",None,"兄弟=brothers, 姐妹=sisters. All siblings together."),
    v("亲戚","qīn qi","Relatives","family",None,"亲=close/relative, 戚=relative. Extended family."),
    v("堂兄弟","táng xiōng dì","Paternal cousins (m.)","family",None,"堂=hall/paternal side. Father's brother's children."),
    v("表姐妹","biǎo jiě mèi","Maternal cousins (f.)","family",None,"表=surface/maternal side. Mother's sibling's children."),
    v("同事","tóng shì","Colleague","family",None,"同=same, 事=work/matter. Work-together person."),
    v("邻居","lín jū","Neighbor","family",None,"邻=adjacent, 居=reside."),
    v("祖先","zǔ xiān","Ancestors","family",None,"祖=ancestor, 先=before/first."),
    v("后代","hòu dài","Descendants","family",None,"后=after, 代=generation."),
    v("丈母娘","zhàng mǔ niáng","Mother-in-law (wife's mom)","family",None,"Refers specifically to the wife's mother."),
    v("公公","gōng gong","Father-in-law (husband's dad)","family",None,"Wife refers to husband's father as 公公."),
    v("婆婆","pó po","Mother-in-law (husband's mom)","family",None,"Wife refers to husband's mother as 婆婆."),
    # body — more
    v("脖子","bó zi","Neck","body",None,"脖 has the flesh radical 月."),
    v("胸","xiōng","Chest","body",None,"胸 has the flesh radical 月."),
    v("膝盖","xī gài","Knee","body",None,"膝 has the flesh radical 月. 跪下=kneel."),
    v("脚踝","jiǎo huái","Ankle","body",None,"脚=foot, 踝=ankle."),
    v("手腕","shǒu wàn","Wrist","body",None,"手=hand, 腕=wrist."),
    v("手肘","shǒu zhǒu","Elbow","body",None,"手=hand, 肘=elbow."),
    v("眉毛","méi máo","Eyebrow","body",None,"眉=eyebrow, 毛=hair/fur."),
    v("睫毛","jié máo","Eyelash","body",None,"睫=eyelash, 毛=hair. 睫毛膏=mascara."),
    v("嘴唇","zuǐ chún","Lips","body",None,"嘴=mouth, 唇=lip. 嘴唇=lips (both)."),
    v("下巴","xià bā","Chin","body",None,"下=below, 巴=appendage/chin."),
    v("额头","é tóu","Forehead","body",None,"额=forehead, 头=head."),
    v("皮肤","pí fū","Skin","body",None,"皮=skin/leather, 肤=skin."),
    v("骨头","gǔ tou","Bone","body",None,"骨 is also a radical. 骨气=backbone (spirit)."),
    v("大脑","dà nǎo","Brain","body",None,"大=big, 脑=brain."),
    v("肺","fèi","Lungs","body",None,"肺 has the flesh radical 月."),
    v("肝","gān","Liver","body",None,"肝 has the flesh radical 月. 肝脏=liver organ."),
    v("肾","shèn","Kidney","body",None,"肾 has the flesh radical 月."),
    v("血","xuè","Blood","body",None,"血 looks like a vessel with liquid inside."),
    # time — more
    v("秒","miǎo","Second (time)","time",None,"秒 has the grain radical 禾. 一秒钟=one second."),
    v("现在","xiàn zài","Now / Present","time",None,"现=appear/present, 在=at/exist."),
    v("过去","guò qù","Past","time",None,"过=pass, 去=go. 'Gone past.'"),
    v("未来","wèi lái","Future","time",None,"未=not yet, 来=come. 'Not yet come.'"),
    v("上个月","shàng gè yuè","Last month","time",None,"上=above/previous, 个=measure word, 月=month."),
    v("下个月","xià gè yuè","Next month","time",None,"下=below/next, 个=measure word, 月=month."),
    v("节日","jié rì","Holiday / Festival","time",None,"节=festival/section, 日=day."),
    v("生日","shēng rì","Birthday","time",None,"生=born, 日=day. 生日快乐=Happy Birthday!"),
    v("春节","chūn jié","Chinese New Year / Spring Festival","time",None,"China's biggest holiday. 阖家团圆=family reunion."),
    v("中秋节","zhōng qiū jié","Mid-Autumn Festival","time",None,"中=middle, 秋=autumn, 节=festival. Moon cake festival!"),
    v("世纪","shì jì","Century","time",None,"世纪. 二十一世纪=21st century."),
    v("千年","qiān nián","Millennium","time",None,"千=thousand, 年=year."),
    v("同时","tóng shí","At the same time","time",None,"同=same, 时=time. Simultaneously."),
    # verbs — more
    v("想","xiǎng","Think / Want to","verbs",None,"想 has the heart radical 心. 我想去=I want to go."),
    v("知道","zhī dào","Know","verbs",None,"知=know, 道=way/path. 你知道吗=Do you know?"),
    v("有","yǒu","Have","verbs",None,"有 is one of the most used verbs. 我有=I have."),
    v("做","zuò","Do / Make","verbs",None,"做 vs 作: 做 is more concrete, 作 more abstract."),
    v("帮助","bāng zhù","Help","verbs",None,"帮=help, 助=assist. 需要帮助吗=Need help?"),
    v("找","zhǎo","Find / Look for","verbs",None,"找 has the hand radical 扌. 我在找=I'm looking for."),
    v("给","gěi","Give / For","verbs",None,"给 has the silk radical 纟. 给我=give me."),
    v("拿","ná","Take / Hold","verbs",None,"拿=take with hands. 拿走=take away."),
    v("开","kāi","Open / Start","verbs",None,"开门=open door, 开始=start, 开车=drive."),
    v("关","guān","Close / Turn off","verbs",None,"关门=close door, 关灯=turn off light."),
    v("用","yòng","Use","verbs",None,"用=use. 有用=useful. 没用=useless."),
    v("需要","xū yào","Need","verbs",None,"需=require, 要=want/need. 我需要=I need."),
    v("住","zhù","Live / Stay","verbs",None,"住 has the person radical 亻. 你住哪里=where do you live?"),
    v("等","děng","Wait","verbs",None,"等 has the bamboo radical 竹. 等一下=wait a moment."),
    v("问","wèn","Ask","verbs",None,"问 has the mouth radical 口. 问题=question."),
    v("回答","huí dá","Answer","verbs",None,"回=return, 答=answer. Reply to a question."),
    v("记住","jì zhù","Remember","verbs",None,"记=record, 住=stay/fix. Fix in memory."),
    v("忘记","wàng jì","Forget","verbs",None,"忘 has heart radical 心. 忘记了=forgot it."),
    v("开始","kāi shǐ","Start / Begin","verbs",None,"开=open, 始=start/begin."),
    v("结束","jié shù","End / Finish","verbs",None,"结=tie up, 束=bind. Wrap up and finish."),
    v("同意","tóng yì","Agree","verbs",None,"同=same, 意=meaning. Share the same meaning."),
    v("理解","lǐ jiě","Understand","verbs",None,"理=reason, 解=untangle. More nuanced than 知道."),
    v("改变","gǎi biàn","Change","verbs",None,"改=change/correct, 变=transform."),
    v("解释","jiě shì","Explain","verbs",None,"解=untangle, 释=release. Untangle and explain."),
]

# ── JAPANESE EXTRA ───────────────────────────────────────────────
JPN_EXTRA = [
    # greetings
    v("お久しぶりです","Ohisashiburi desu","Long time no see (formal)","greetings",None,"久しぶり=long interval. Casual: 久しぶり!"),
    v("お誕生日おめでとう","Otanjōbi omedetō","Happy Birthday","greetings",None,"誕生日=birthday, おめでとう=congratulations."),
    v("明けましておめでとう","Akemashite omedetō","Happy New Year","greetings",None,"明ける=dawn/new year begins. Said in January."),
    v("ご苦労様","Gokurōsama","Thank you for your hard work","greetings",None,"Said to someone who finished a task. Superior to subordinate."),
    v("頑張って","Ganbatte","Good luck / Do your best","greetings",None,"頑張る=to do one's best. Powerful Japanese encouragement."),
    v("大丈夫ですか","Daijōbu desu ka","Are you okay?","greetings",None,"大丈夫=okay/fine. 大丈夫！=I'm fine! Very versatile."),
    v("よかった","Yokatta","I'm glad / That's good","greetings",None,"Past tense of 良い(good). 'That was good.'"),
    v("なるほど","Naruhodo","I see / I understand","greetings",None,"Used to show understanding. Very common in conversation."),
    v("そうですか","Sō desu ka","Is that so? / Really?","greetings",None,"そう=so, です=is, か=question. Shows active listening."),
    v("お疲れ様でした","Otsukaresama deshita","Good work (formal)","greetings",None,"Said at end of work. Crucial workplace phrase."),
    # numbers
    v("二十一","nijūichi","Twenty-one (21)","numbers",None,"二十(nijū)=20+一(ichi)=1. Simple pattern!"),
    v("五十","gojū","Fifty (50)","numbers",None,"五(go)=5+十(jū)=10."),
    v("二百","nihyaku","Two hundred (200)","numbers",None,"二(ni)=2+百(hyaku)=100. Note: 三百=sanbyaku (irregular)."),
    v("一万","ichiman","Ten thousand (10,000)","numbers",None,"万(man) is key unit. 一億(ichioku)=100 million."),
    v("半分","hanbun","Half","numbers",None,"半(han)=half, 分(bun)=part/portion."),
    v("何番","nanban","What number?","numbers",None,"何=what, 番=number/turn. 何番ですか=What number?"),
    # colors
    v("濃い青","koi ao","Dark blue","colors",None,"濃い(koi)=thick/dark + 青(ao)=blue."),
    v("薄い青","usui ao","Light blue","colors",None,"薄い(usui)=thin/light + 青(ao)=blue."),
    v("水色","mizuiro","Sky blue / Aqua","colors",None,"水(mizu)=water + 色(iro)=color. Water-color!"),
    v("肌色","hadairo","Skin color / Peach","colors",None,"肌(hada)=skin + 色(iro)=color."),
    v("透明","tōmei","Transparent / Clear","colors",None,"透(tō)=penetrate, 明(mei)=bright. See-through."),
    v("虹色","nijiiro","Rainbow-colored","colors",None,"虹(niji)=rainbow + 色(iro)=color. Seven-colored!"),
    v("藍色","aiiro","Indigo","colors",None,"藍(ai)=indigo plant. Traditional Japanese indigo dyeing is an art."),
    v("エメラルド","emerarudo","Emerald green","colors",None,"From English 'emerald'. Katakana loanword."),
    # animals — sea
    v("イルカ","iruka","Dolphin","animals",None,"イルカ. Kanji: 海豚(iruka)=sea-pig. Smart and playful."),
    v("サメ","same","Shark","animals",None,"サメ. Kanji: 鮫. Found in Japanese coastal waters."),
    v("クジラ","kujira","Whale","animals",None,"クジラ. Kanji: 鯨. Japan has a complex history with whaling."),
    v("カニ","kani","Crab","animals",None,"カニ. Kanji: 蟹. かに=crab. タラバガニ=king crab!"),
    v("エビ","ebi","Shrimp / Prawn","animals",None,"エビ. Kanji: 海老(ebi)=sea-elder! Used in tempura."),
    v("タコ","tako","Octopus","animals",None,"タコ. Kanji: 蛸. たこ焼き(takoyaki)=octopus balls!"),
    v("ヒトデ","hitode","Starfish","animals",None,"ヒトデ. Kanji: 海星 or 人手=human hand!"),
    v("クラゲ","kurage","Jellyfish","animals",None,"クラゲ. Kanji: 水母(kurage)=water-mother."),
    # animals — birds & insects
    v("ワシ","washi","Eagle","animals",None,"ワシ. Kanji: 鷲. Symbol of power. Also means 'I' in some dialects!"),
    v("フクロウ","fukurō","Owl","animals",None,"フクロウ. Kanji: 梟. Popular in Japanese cafes."),
    v("ペンギン","pengin","Penguin","animals",None,"ペンギン. Loanword. Popular zoo animal in Japan."),
    v("ハト","hato","Pigeon / Dove","animals",None,"ハト. Kanji: 鳩. Symbol of peace at Hiroshima."),
    v("カラス","karasu","Crow","animals",None,"カラス. Kanji: 烏. Intelligent birds. Common in Tokyo!"),
    v("ハクチョウ","hakuchō","Swan","animals",None,"ハクチョウ. Kanji: 白鳥(hakuchō)=white bird."),
    v("アリ","ari","Ant","animals",None,"アリ. Kanji: 蟻. アリさん(ant-san) in children's songs."),
    v("カ","ka","Mosquito","animals",None,"カ. Kanji: 蚊. Hot summer pest in Japan."),
    v("クモ","kumo","Spider","animals",None,"クモ. Kanji: 蜘蛛. Also: 雲(kumo)=cloud! Same sound."),
    v("トンボ","tonbo","Dragonfly","animals",None,"トンボ. Kanji: 蜻蛉. Symbol of Japan — called 秋津島(Akitsushima)."),
    v("ホタル","hotaru","Firefly","animals",None,"ホタル. Kanji: 蛍. Beloved symbol of summer evenings."),
    # food — vegetables & fruits
    v("にんじん","ninjin","Carrot","food",None,"にんじん. Kanji: 人参. 人参(ninjin) also means ginseng!"),
    v("きゅうり","kyūri","Cucumber","food",None,"きゅうり. Kanji: 胡瓜. Kappa (mythical creature) loves it!"),
    v("キャベツ","kyabetsu","Cabbage","food",None,"キャベツ. From English 'cabbage'. Used in okonomiyaki."),
    v("ほうれん草","hōrensō","Spinach","food",None,"ほうれん草. Rich in iron. お浸し(ohitashi)=spinach dish."),
    v("きのこ","kinoko","Mushroom","food",None,"きのこ. Kanji: 茸. Japan loves mushrooms — shiitake, matsutake!"),
    v("にんにく","ninniku","Garlic","food",None,"にんにく. Kanji: 大蒜. Essential in Japanese cooking."),
    v("しょうが","shōga","Ginger","food",None,"しょうが. Kanji: 生姜. Used fresh in Japanese dishes."),
    v("とうもろこし","tōmorokoshi","Corn","food",None,"とうもろこし. Popular in Hokkaido."),
    v("トマト","tomato","Tomato","food",None,"トマト. Katakana loanword from English/Spanish."),
    v("たまねぎ","tamanegi","Onion","food",None,"たまねぎ. Kanji: 玉葱=ball-green-onion."),
    v("じゃがいも","jagaimo","Potato","food",None,"じゃがいも. From Jaga(rta). 肉じゃが=meat-potato stew."),
    v("かぼちゃ","kabocha","Pumpkin","food",None,"かぼちゃ. From 'Cambodia'! Beloved autumn vegetable."),
    v("いちご","ichigo","Strawberry","food",None,"いちご. Kanji: 苺. Japan produces premium strawberries!"),
    v("ぶどう","budō","Grape","food",None,"ぶどう. Kanji: 葡萄. 山梨(Yamanashi) is famous for grapes."),
    v("なし","nashi","Asian pear","food",None,"なし. Kanji: 梨. Crispy, sweet Japanese pears."),
    v("もも","momo","Peach","food",None,"もも. Kanji: 桃. 桃太郎(Momotaro)=Peach Boy fairy tale!"),
    # food — condiments & dishes
    v("しょうゆ","shōyu","Soy sauce","food",None,"しょうゆ. Kanji: 醤油. Essential Japanese condiment."),
    v("みりん","mirin","Sweet rice wine (cooking)","food",None,"みりん. Kanji: 味醂. Adds sweetness and gloss to dishes."),
    v("だし","dashi","Broth / Stock","food",None,"だし. The foundation of Japanese cooking — kombu + bonito."),
    v("わさび","wasabi","Wasabi","food",None,"わさび. Kanji: 山葵(wasabi)=mountain hollyhock. Real wasabi is rare!"),
    v("しょうが","shōga","Pickled ginger","food",None,"しょうが. Eaten with sushi to cleanse the palate."),
    v("のり","nori","Seaweed / Nori","food",None,"のり. Kanji: 海苔. Used in sushi, onigiri, ramen."),
    v("豆腐","tōfu","Tofu","food",None,"豆腐(tōfu). 豆(tō)=bean, 腐(fu)=fermented. Miso soup staple."),
    v("枝豆","edamame","Edamame","food",None,"枝豆(edamame). 枝=branch, 豆=bean. Branch-bean!"),
    v("焼き鳥","yakitori","Grilled chicken skewer","food",None,"焼き=grilled, 鳥=bird. Popular izakaya food."),
    v("たこ焼き","takoyaki","Octopus balls","food",None,"タコ=octopus, 焼き=grilled. Osaka's famous street food."),
    v("お好み焼き","okonomiyaki","Savory pancake","food",None,"お好み=as you like, 焼き=grilled. 'Grill what you like'!"),
    v("天丼","tendon","Tempura rice bowl","food",None,"天ぷら(tenpura)+丼(don/bowl). Crispy tempura over rice."),
    v("カレーライス","karē raisu","Curry rice","food",None,"From English. Japan's most popular home-cooked dish!"),
    # family
    v("両親","ryōshin","Parents","family",None,"両=both, 親=parent. Both parents together."),
    v("兄弟","kyōdai","Siblings / Brothers","family",None,"兄弟(kyōdai). 兄=older brother, 弟=younger brother."),
    v("親戚","shinseki","Relatives","family",None,"親=related, 戚=relatives. Extended family."),
    v("いとこ","itoko","Cousin","family",None,"いとこ. Kanji: 従兄弟 or 従姉妹."),
    v("同僚","dōryō","Colleague","family",None,"同=same, 僚=colleague. Workplace companions."),
    v("ご近所","gokinjo","Neighbor","family",None,"近所(kinjo)=neighborhood. ご is polite prefix."),
    v("ご先祖","gosenzo","Ancestors","family",None,"先祖=ancestors. 先=before, 祖=ancestor."),
    # body
    v("首","kubi","Neck","body",None,"首(kubi). Also means 'head' in old Japanese. 首相=prime minister."),
    v("胸","mune","Chest","body",None,"胸(mune). 胸が痛い=my chest hurts."),
    v("ひざ","hiza","Knee","body",None,"ひざ. Kanji: 膝. ひざまずく=kneel."),
    v("くるぶし","kurubushi","Ankle","body",None,"くるぶし. Kanji: 踝."),
    v("手首","tekubi","Wrist","body",None,"手(te)=hand, 首(kubi)=neck. Hand-neck!"),
    v("ひじ","hiji","Elbow","body",None,"ひじ. Kanji: 肘."),
    v("まゆ毛","mayuge","Eyebrow","body",None,"まゆ=eyebrow, 毛=hair."),
    v("まつ毛","matsuge","Eyelash","body",None,"まつ=eyelash, 毛=hair."),
    v("くちびる","kuchibiru","Lips","body",None,"くちびる. Kanji: 唇. 口(kuchi)=mouth related."),
    v("あご","ago","Chin / Jaw","body",None,"あご. Kanji: 顎."),
    v("ひたい","hitai","Forehead","body",None,"ひたい. Kanji: 額. Also means 'amount/sum'."),
    v("皮膚","hifu","Skin","body",None,"皮膚(hifu). 皮=skin/leather, 膚=skin."),
    v("骨","hone","Bone","body",None,"骨(hone). 骨が折れる=break a bone."),
    v("血","chi","Blood","body",None,"血(chi). 血液型=blood type. Very important in Japan!"),
    v("脳","nō","Brain","body",None,"脳(nō). 脳みそ=brain. 脳科学=neuroscience."),
    v("肺","hai","Lungs","body",None,"肺(hai). 肺炎=pneumonia."),
    # time
    v("秒","byō","Second (time)","time",None,"秒(byō). 三十秒=thirty seconds."),
    v("今","ima","Now / Right now","time",None,"今(ima). 今すぐ=right now. 今日(kyō)=today."),
    v("過去","kako","Past","time",None,"過去(kako). 過=pass, 去=go."),
    v("未来","mirai","Future","time",None,"未来(mirai). 未=not yet, 来=come."),
    v("先月","sengetsu","Last month","time",None,"先(sen)=before/previous, 月(getsu)=month."),
    v("来月","raigetsu","Next month","time",None,"来(rai)=coming/next, 月(getsu)=month."),
    v("祝日","shukujitsu","Public holiday","time",None,"祝=celebrate, 日=day. Japan has 16 public holidays!"),
    v("誕生日","tanjōbi","Birthday","time",None,"誕生=birth, 日=day. お誕生日おめでとう!"),
    v("お正月","oshōgatsu","New Year / New Year holiday","time",None,"Most important Japanese holiday. Jan 1-3."),
    v("お盆","obon","Obon festival","time",None,"Buddhist ancestor festival in August. Families reunite."),
    v("世紀","seiki","Century","time",None,"世紀(seiki). 二十一世紀=21st century."),
    v("同時に","dōji ni","At the same time","time",None,"同時(dōji)=same time + に=at."),
    # verbs
    v("思う","omou","Think / Feel","verbs",None,"思う(omou). 私は思う=I think. More intuitive than 考える."),
    v("知る","shiru","Know / Come to know","verbs",None,"知る(shiru). 知ってる=I know. 知らない=I don't know."),
    v("持つ","motsu","Have / Hold","verbs",None,"持つ(motsu). 持っている=to have/own."),
    v("する","suru","Do / Make","verbs",None,"する(suru). Most versatile verb! 勉強する=study."),
    v("手伝う","tetsudau","Help","verbs",None,"手伝う(tetsudau). 手(te)=hand, 伝=transmit. Lend a hand."),
    v("探す","sagasu","Look for / Search","verbs",None,"探す(sagasu). 仕事を探す=look for a job."),
    v("あげる","ageru","Give (to someone)","verbs",None,"あげる vs くれる: あげる=you give out, くれる=someone gives to you."),
    v("もらう","morau","Receive","verbs",None,"もらう(morau). プレゼントをもらう=receive a gift."),
    v("開ける","akeru","Open","verbs",None,"開ける(akeru). ドアを開ける=open the door."),
    v("閉める","shimeru","Close","verbs",None,"閉める(shimeru). 窓を閉めて=close the window."),
    v("使う","tsukau","Use","verbs",None,"使う(tsukau). スマホを使う=use a smartphone."),
    v("必要とする","hitsuyō to suru","Need","verbs",None,"必要(hitsuyō)=necessary + とする. Also: 〜が要る(iru)."),
    v("住む","sumu","Live / Reside","verbs",None,"住む(sumu). 東京に住む=live in Tokyo."),
    v("待つ","matsu","Wait","verbs",None,"待つ(matsu). ちょっと待って=wait a moment."),
    v("聞く","kiku","Ask / Listen","verbs",None,"聞く(kiku) = both listen AND ask. Context matters!"),
    v("答える","kotaeru","Answer","verbs",None,"答える(kotaeru). 質問に答える=answer a question."),
    v("覚える","oboeru","Remember / Memorize","verbs",None,"覚える(oboeru). 単語を覚える=memorize vocabulary."),
    v("忘れる","wasureru","Forget","verbs",None,"忘れる(wasureru). 忘れないで=don't forget."),
    v("始める","hajimeru","Start / Begin","verbs",None,"始める(hajimeru). さあ始めよう=let's begin!"),
    v("終わる","owaru","End / Finish","verbs",None,"終わる(owaru). 授業が終わる=class ends."),
    v("同意する","dōi suru","Agree","verbs",None,"同意(dōi)=agreement + する=do."),
    v("変える","kaeru","Change","verbs",None,"変える(kaeru). Also: 帰る(kaeru)=return home. Same sound!"),
    v("説明する","setsumei suru","Explain","verbs",None,"説明(setsumei)=explanation + する=do."),
    v("遊ぶ","asobu","Play / Have fun","verbs",None,"遊ぶ(asobu). 友達と遊ぶ=hang out with friends."),
]

# ── HINDI EXTRA ───────────────────────────────────────────────────
HIN_EXTRA = [
    # greetings
    v("बहुत दिनों बाद","Bahut dinon baad","Long time no see","greetings",None,"बहुत=many, दिनों=days, बाद=after. 'After many days.'"),
    v("जन्मदिन मुबारक","Janmadin mubaarak","Happy Birthday","greetings",None,"जन्मदिन=birthday, मुबारक=blessed/congratulations (from Arabic)."),
    v("नया साल मुबारक","Naya saal mubaarak","Happy New Year","greetings",None,"नया=new, साल=year, मुबारक=blessed."),
    v("बधाई हो","Badhaai ho","Congratulations","greetings",None,"बधाई=congratulations, हो=be. Said for achievements."),
    v("हिम्मत रखो","Himmat rakho","Be brave / Keep courage","greetings",None,"हिम्मत=courage, रखो=keep. Encouraging phrase."),
    v("शुभकामनाएँ","Shubhkaamnayen","Best wishes","greetings",None,"शुभ=auspicious, कामना=wish. Plural wishes."),
    v("अरे वाह","Are vaah","Wow! / Amazing!","greetings",None,"अरे=hey/oh, वाह=wow. Exclamation of delight."),
    v("क्या बात है","Kya baat hai","What a thing! / Excellent!","greetings",None,"क्या=what, बात=thing/matter, है=is. Expression of admiration."),
    v("चलो ठीक है","Chalo theek hai","Okay, that's fine","greetings",None,"चलो=okay/let's go, ठीक=fine, है=is."),
    v("मैं समझ गया","Main samajh gaya","I understand (m.)","greetings",None,"मैं=I, समझ=understand, गया=went/did. Feminine: गई."),
    # numbers
    v("तेईस","teis","Twenty-three (23)","numbers",None,"Hindi numbers 13-19 and beyond have unique names."),
    v("पचहत्तर","pachattar","Seventy-five (75)","numbers",None,"Hindi large numbers have their own names — not built like English."),
    v("करोड़","karod","Ten million (1 crore)","numbers",None,"करोड़ = 10 million. The crore is India's big number unit!"),
    v("प्रतिशत","pratishat","Percent (%)","numbers",None,"प्रति=per, शत=hundred. 'Per hundred.'"),
    v("गुना","guna","Times / Fold","numbers",None,"दो गुना=double. तीन गुना=triple."),
    v("तीसरा","teesra","Third","numbers",None,"तीसरा(m)/तीसरी(f). Ordinal numbers change for gender."),
    v("चौथा","chautha","Fourth","numbers",None,"चौथा(m)/चौथी(f)=fourth."),
    # colors
    v("गहरा लाल","gahra laal","Dark red / Crimson","colors",None,"गहरा=deep/dark. गहरा+color=dark shade."),
    v("हल्का नीला","halka neela","Light blue","colors",None,"हल्का=light/pale. हल्का+color=light shade."),
    v("आसमानी","aasmani","Sky blue","colors",None,"आसमान=sky. Sky-colored! Beautiful word."),
    v("मेहंदी","mehandi","Henna green","colors",None,"मेहंदी=henna plant. Dark green-brown color of henna."),
    v("पारदर्शी","paaradarshai","Transparent / Clear","colors",None,"पार=through, दर्शी=seeing. See-through."),
    v("सतरंगी","satrangi","Seven-colored / Rainbow","colors",None,"सात=seven, रंग=color. 'Seven-colored' = rainbow."),
    v("नीलम","neelam","Sapphire blue","colors",None,"नीलम=sapphire gem. Rich deep blue."),
    v("मैरून","mairon","Maroon","colors",None,"From English 'maroon'. Dark brownish-red."),
    # animals — sea
    v("डॉल्फिन","dolphin","Dolphin","animals",None,"डॉल्फिन. From English. 'सुसु' is Ganges river dolphin!"),
    v("शार्क","shaark","Shark","animals",None,"शार्क. From English. हिंदी महासागर में पाई जाती है."),
    v("व्हेल","whale","Whale","animals",None,"व्हेल. From English. World's largest animal."),
    v("केकड़ा","kekda","Crab","animals",None,"केकड़ा. Found in India's coastal waters."),
    v("झींगा","jheengha","Shrimp / Prawn","animals",None,"झींगा. Popular seafood in coastal India."),
    v("ऑक्टोपस","octopus","Octopus","animals",None,"ऑक्टोपस. From English. Eight-armed creature."),
    v("जेलीफ़िश","jellyfish","Jellyfish","animals",None,"जेलीफ़िश. From English."),
    # animals — birds
    v("चील","cheel","Eagle / Kite","animals",None,"चील. Common bird of prey in Indian cities."),
    v("उल्लू","ullu","Owl","animals",None,"उल्लू. Sacred to goddess Lakshmi. Also slang for 'fool'!"),
    v("पेंगुइन","penguin","Penguin","animals",None,"पेंगुइन. From English. Lives in Antarctica."),
    v("कौआ","kauwa","Crow","animals",None,"कौआ. Very intelligent bird. Common across India."),
    v("हंस","hans","Swan / Goose","animals",None,"हंस. Sacred to goddess Saraswati. Symbol of grace."),
    v("गिद्ध","giddh","Vulture","animals",None,"गिद्ध. Important scavenger bird in Indian ecosystems."),
    v("तीतर","teetar","Partridge","animals",None,"तीतर. Game bird. Famous in folk songs."),
    # animals — insects
    v("चींटी","cheenti","Ant","animals",None,"चींटी. Very common insect. मेहनती=hardworking (like an ant)."),
    v("मच्छर","machchhar","Mosquito","animals",None,"मच्छर. Major health concern in India — carries malaria."),
    v("मकड़ी","makdi","Spider","animals",None,"मकड़ी. मकड़ी का जाल=spider web."),
    v("ड्रैगनफ्लाई","dragonfly","Dragonfly","animals",None,"ड्रैगनफ्लाई or व्याध पतंग. Graceful flier."),
    v("जुगनू","jugnu","Firefly","animals",None,"जुगनू. Magical summer evenings in rural India."),
    v("मगरमच्छ","magarmachchh","Crocodile","animals",None,"मगरमच्छ. Found in India's rivers — mugger crocodile!"),
    v("छिपकली","chhipkali","Lizard","animals",None,"छिपकली. Common house lizard in India."),
    v("बिच्छू","bichhoo","Scorpion","animals",None,"बिच्छू. Found in dry regions of India."),
    # food — vegetables
    v("गाजर","gajar","Carrot","food",None,"गाजर. गाजर का हलवा=carrot pudding (famous dessert!)."),
    v("खीरा","kheera","Cucumber","food",None,"खीरा. खीरे का रायता=cucumber yogurt dish."),
    v("पत्तागोभी","pattagobhi","Cabbage","food",None,"पत्ता=leaf, गोभी=cauliflower/brassica."),
    v("पालक","palak","Spinach","food",None,"पालक. पालक पनीर=spinach with cottage cheese. Famous dish!"),
    v("मशरूम","mushroom","Mushroom","food",None,"मशरूम. From English. मशरूम मसाला=mushroom curry."),
    v("लहसुन","lahsun","Garlic","food",None,"लहसुन. Essential in Indian cooking. 'Never enough garlic.'"),
    v("अदरक","adrak","Ginger","food",None,"अदरक. अदरक की चाय=ginger tea. Beloved remedy!"),
    v("मकई","makai","Corn","food",None,"मकई. भुट्टा=roasted corn on the cob. Street food!"),
    v("बैंगन","baingan","Eggplant / Brinjal","food",None,"बैंगन. बैंगन का भरता=roasted eggplant mash."),
    v("भिंडी","bhindi","Okra / Lady finger","food",None,"भिंडी. भिंडी फ्राई=fried okra. Popular vegetable."),
    v("मूली","mooli","Radish","food",None,"मूली. मूली पराठा=radish stuffed flatbread."),
    v("शिमला मिर्च","shimla mirch","Bell pepper","food",None,"शिमला=a hill city, मिर्च=pepper. From Shimla!"),
    v("मटर","matar","Peas","food",None,"मटर. मटर पनीर=peas with cottage cheese."),
    # food — fruits
    v("स्ट्रॉबेरी","strawberry","Strawberry","food",None,"स्ट्रॉबेरी. From English. Grown in Himachal Pradesh."),
    v("अंगूर","angoor","Grape","food",None,"अंगूर. नासिक(Nashik) is India's wine region."),
    v("नाशपाती","naashpaati","Pear","food",None,"नाशपाती. Popular fruit, especially in North India."),
    v("अनानास","ananaas","Pineapple","food",None,"अनानास. From Portuguese. Grown in Northeast India."),
    v("चेरी","cherry","Cherry","food",None,"चेरी. From English. Grown in Kashmir."),
    v("आड़ू","aadu","Peach","food",None,"आड़ू. Grown in Himachal Pradesh. Summer fruit."),
    v("आलूबुखारा","aaloobukhara","Plum","food",None,"आलू=potato-like, बुखारा=from Bukhara (Central Asia)."),
    v("तरबूज","tarbooj","Watermelon","food",None,"तरबूज. From Persian. Loved in Indian summers!"),
    v("पपीता","papita","Papaya","food",None,"पपीता. From Portuguese. Grown throughout India."),
    v("नारियल","nariyal","Coconut","food",None,"नारियल. Sacred in Hindu rituals. Kerala is coconut capital!"),
    # food — condiments & dishes
    v("इमली","imli","Tamarind","food",None,"इमली. Sweet-sour flavor. Base of many chutneys."),
    v("मेथी","methi","Fenugreek","food",None,"मेथी. Bitter herb used in Indian cooking."),
    v("जीरा","jeera","Cumin","food",None,"जीरा. जीरा पानी=cumin water. Digestive drink."),
    v("धनिया","dhania","Coriander","food",None,"धनिया. Fresh leaves AND seeds used differently."),
    v("शहद","shahad","Honey","food",None,"शहद. From Arabic. Natural sweetener."),
    v("मक्खन","makkhan","Butter","food",None,"मक्खन. मक्खन मलाई=fresh butter and cream."),
    v("पनीर","paneer","Cottage cheese","food",None,"पनीर. Staple protein for vegetarians. Used in 50+ dishes!"),
    v("दही","dahi","Yogurt / Curd","food",None,"दही. Eaten daily in India. दही-चावल=curd rice (South India)."),
    v("राजमा","rajma","Kidney beans","food",None,"राजमा. राजमा-चावल=beans and rice. North Indian comfort food!"),
    v("छोले","chhole","Chickpeas","food",None,"छोले. छोले-भटूरे=chickpeas with fried bread. Delhi specialty!"),
    v("खिचड़ी","khichdi","Rice and lentil porridge","food",None,"खिचड़ी. Comfort food. Simple and nutritious."),
    v("पकौड़ा","pakoda","Fritter","food",None,"पकौड़ा. Battered and fried vegetables. Monsoon snack!"),
    v("मिठाई","mithai","Sweets / Confectionery","food",None,"मिठाई. India has hundreds of types! Given at celebrations."),
    # family
    v("माता-पिता","maata-pita","Parents","family",None,"माता=mother, पिता=father. Combined = parents."),
    v("भाई-बहन","bhai-behen","Siblings","family",None,"भाई=brother, बहन=sister. Brothers and sisters."),
    v("रिश्तेदार","rishtedaar","Relatives","family",None,"रिश्ता=relationship. All extended family."),
    v("चचेरा भाई","chachera bhai","Paternal cousin (m.)","family",None,"चाचा(uncle) का बेटा=uncle's son = paternal cousin."),
    v("ममेरा भाई","mamera bhai","Maternal cousin (m.)","family",None,"मामा(maternal uncle) का बेटा=maternal uncle's son."),
    v("साले","saale","Brother-in-law (wife's bro)","family",None,"साले. Wife's brother. साली=wife's sister."),
    v("जीजा","jeeja","Brother-in-law (sister's husband)","family",None,"जीजा. Husband of your sister."),
    v("सहेली","saheli","Female friend","family",None,"सहेली. Specifically female-to-female friendship."),
    v("यार","yaar","Best friend / Buddy","family",None,"यार. From Persian. Very affectionate term."),
    v("गुरु","guru","Teacher / Spiritual guide","family",None,"गुरु. The word 'guru' was adopted into English!"),
    # body
    v("गर्दन","gardan","Neck","body",None,"गर्दन. गर्दन दर्द=neck pain. From Persian."),
    v("छाती","chhaati","Chest","body",None,"छाती. छाती ठोकना=beat chest (show confidence)."),
    v("घुटना","ghutna","Knee","body",None,"घुटना. घुटने टेकना=kneel down."),
    v("टखना","takhna","Ankle","body",None,"टखना. पैर मुड़ना=twist ankle."),
    v("कलाई","kalaai","Wrist","body",None,"कलाई. कलाई पर घड़ी=watch on wrist."),
    v("कोहनी","kohni","Elbow","body",None,"कोहनी. कोहनी मारना=elbow (poke)."),
    v("भौंह","bhaunh","Eyebrow","body",None,"भौंह. भौंह उठाना=raise an eyebrow (surprise/doubt)."),
    v("पलक","palak","Eyelid / Eyelash","body",None,"पलक. पलक झपकाना=blink. पलक पर=on the eyelid."),
    v("होंठ","honth","Lips","body",None,"होंठ. होंठ हिलाना=move lips."),
    v("ठोड़ी","thodi","Chin","body",None,"ठोड़ी. ठोड़ी पर हाथ=hand on chin (thinking)."),
    v("माथा","maatha","Forehead","body",None,"माथा. माथे पर बिंदी=dot on forehead. Cultural/religious."),
    v("चमड़ी","chamdi","Skin","body",None,"चमड़ी or त्वचा(tvach). त्वचा is more formal."),
    v("हड्डी","haddi","Bone","body",None,"हड्डी. हड्डी टूटना=break a bone."),
    v("खून","khoon","Blood","body",None,"खून. From Persian. खून बहाना=shed blood."),
    v("दिमाग़","dimaag","Brain / Mind","body",None,"दिमाग़. दिमाग़ लगाओ=use your brain!"),
    v("फेफड़े","phephde","Lungs","body",None,"फेफड़े (plural). फेफड़ों में दर्द=lung pain."),
    # time
    v("सेकंड","second","Second (time)","time",None,"सेकंड. From English. एक सेकंड=one second."),
    v("अभी","abhi","Right now / Just now","time",None,"अभी. अभी आता हूँ=I'm coming right now."),
    v("अतीत","ateet","Past","time",None,"अतीत. अतीत में=in the past. Sanskrit-derived."),
    v("भविष्य","bhavishy","Future","time",None,"भविष्य. भविष्य में=in the future."),
    v("पिछले महीने","pichle mahine","Last month","time",None,"पिछला=previous, महीना=month."),
    v("अगले महीने","agle mahine","Next month","time",None,"अगला=next, महीना=month."),
    v("त्योहार","tyohaar","Festival / Holiday","time",None,"त्योहार. India has hundreds of festivals!"),
    v("दिवाली","diwali","Diwali","time",None,"दिवाली. Festival of Lights. Biggest Hindu celebration!"),
    v("होली","holi","Holi","time",None,"होली. Festival of Colors. Spring celebration."),
    v("ईद","eid","Eid","time",None,"ईद. Important Islamic festival celebrated in India."),
    v("क्रिसमस","christmas","Christmas","time",None,"क्रिसमस. Celebrated by millions of Indian Christians."),
    v("शताब्दी","shataabdi","Century","time",None,"शताब्दी. शत=hundred, अब्दी=year/period."),
    v("दशक","dashak","Decade","time",None,"दशक. दस=ten + अक(time period). Ten years."),
    # verbs
    v("सोचना","sochna","Think","verbs",None,"सोचना. सोचो!=think! ज़रा सोचो=think for a moment."),
    v("जानना","jaanana","Know","verbs",None,"जानना. मैं जानता/जानती हूँ=I know."),
    v("रखना","rakhna","Keep / Place / Put","verbs",None,"रखना. यहाँ रखो=put it here."),
    v("मिलना","milna","Meet / Get","verbs",None,"मिलना. कल मिलते हैं=see you tomorrow (we'll meet)."),
    v("मदद करना","madad karna","Help","verbs",None,"मदद=help (from Arabic), करना=to do."),
    v("ढूँढना","dhundna","Search / Look for","verbs",None,"ढूँढना. मैं ढूँढ रहा/रही हूँ=I am searching."),
    v("देना","dena","Give","verbs",None,"देना. मुझे दो=give it to me."),
    v("लेना","lena","Take / Receive","verbs",None,"लेना. ले लो=take it. देना/लेना=give/take."),
    v("खोलना","kholna","Open","verbs",None,"खोलना. दरवाज़ा खोलो=open the door."),
    v("बंद करना","band karna","Close / Shut","verbs",None,"बंद=closed + करना=do. 'Make closed.'"),
    v("इस्तेमाल करना","istemal karna","Use","verbs",None,"इस्तेमाल=use (from Arabic) + करना=do."),
    v("चाहिए","chahiye","Need / Should","verbs",None,"चाहिए. मुझे पानी चाहिए=I need water. Very useful!"),
    v("रहना","rehna","Live / Stay","verbs",None,"रहना. आप कहाँ रहते हैं=where do you live?"),
    v("इंतज़ार करना","intezaar karna","Wait","verbs",None,"इंतज़ार=waiting (from Arabic) + करना=do."),
    v("पूछना","poochhna","Ask","verbs",None,"पूछना. कुछ पूछना है=I want to ask something."),
    v("जवाब देना","jawaab dena","Answer","verbs",None,"जवाब=answer (from Arabic) + देना=give."),
    v("याद करना","yaad karna","Remember","verbs",None,"याद=memory (from Arabic) + करना=do."),
    v("भूलना","bhoolna","Forget","verbs",None,"भूलना. मत भूलो=don't forget."),
    v("शुरू करना","shuru karna","Start / Begin","verbs",None,"शुरू=beginning (from Arabic) + करना=do."),
    v("ख़त्म करना","khatam karna","Finish / End","verbs",None,"ख़त्म=finished (from Arabic) + करना=do."),
    v("मानना","maanana","Agree / Accept / Believe","verbs",None,"मानना. मैं मानता/मानती हूँ=I agree/believe."),
    v("समझाना","samjhaana","Explain","verbs",None,"समझाना. Causative of समझना=understand. Make understand."),
    v("बदलना","badalna","Change","verbs",None,"बदलना. सब बदल गया=everything changed."),
]

# ── Append to each language's vocab array ────────────────────────
p = pathlib.Path("/sessions/admiring-stoic-pascal/mnt/outputs/language.html")
html = p.read_text(encoding="utf-8")

def find_matching_bracket(text, start):
    depth, i, in_str, sc = 0, start, False, None
    while i < len(text):
        c = text[i]
        if in_str:
            if c == '\\': i += 2; continue
            if c == sc: in_str = False
        else:
            if c in ('"', "'", '`'): in_str = True; sc = c
            elif c == '[': depth += 1
            elif c == ']':
                depth -= 1
                if depth == 0: return i
        i += 1
    return -1

def append_vocab(html, lang_marker, new_entries):
    lang_pos = html.find(lang_marker)
    if lang_pos == -1: print(f"ERROR: {lang_marker} not found"); return html
    vocab_pos = html.find("vocab:[", lang_pos)
    if vocab_pos == -1: print(f"ERROR: vocab:[ not found for {lang_marker}"); return html
    bracket_pos = vocab_pos + 6
    end_pos = find_matching_bracket(html, bracket_pos)
    if end_pos == -1: print(f"ERROR: no matching ] for {lang_marker}"); return html
    # Insert before the closing ]
    insertion = ",\n" + ",\n".join(new_entries)
    html = html[:end_pos] + insertion + "\n    ]" + html[end_pos+1:]
    print(f"Appended {len(new_entries)} words to {lang_marker}")
    return html

html = append_vocab(html, "mandarin:", MAN_EXTRA)
html = append_vocab(html, "japanese:", JPN_EXTRA)
html = append_vocab(html, "hindi:", HIN_EXTRA)

p.write_text(html, encoding="utf-8")
print(f"\nDone! File size: {p.stat().st_size//1024} KB")
print(f"Extra words added: MAN={len(MAN_EXTRA)}, JPN={len(JPN_EXTRA)}, HIN={len(HIN_EXTRA)}")
