#!/usr/bin/env python3
"""Patches language.html with expanded vocabulary for all 3 languages."""
import pathlib, re

def v(char, rom, meaning, cat, strokes=None, tips=""):
    s = f'null' if strokes is None else str(strokes)
    tips_escaped = tips.replace('\\','\\\\').replace('"','\\"').replace("'","\\'")
    return f'  {{char:"{char}",rom:"{rom}",meaning:"{meaning}",cat:"{cat}",strokes:{s},tips:"{tips_escaped}"}}'

# ── MANDARIN ────────────────────────────────────────────────────
MAN = [
    # greetings
    v("你好","nǐ hǎo","Hello","greetings",12,"你(you)+好(good). 你 has the person radical 亻."),
    v("谢谢","xiè xiè","Thank you","greetings",17,"谢 means 'to thank'. Repeated for emphasis."),
    v("再见","zài jiàn","Goodbye","greetings",14,"再=again, 见=see. Literally 'see again'."),
    v("对不起","duì bu qǐ","Sorry","greetings",20,"对=correct, 不=not, 起=rise. Formal apology."),
    v("没关系","méi guān xi","No worries","greetings",18,"没=not, 关系=matter. 'It doesn't matter.'"),
    v("早上好","zǎo shang hǎo","Good morning","greetings",18,"早=early, 上=up, 好=good."),
    v("下午好","xià wǔ hǎo","Good afternoon","greetings",15,"下午=afternoon, 好=good."),
    v("晚上好","wǎn shang hǎo","Good evening","greetings",20,"晚=evening, 上=up, 好=good."),
    v("请","qǐng","Please","greetings",10,"请 is also used to mean 'invite' or 'please enter'."),
    v("不客气","bù kèqì","You're welcome","greetings",12,"客气=polite/courteous. 'Don't be polite' = you're welcome."),
    v("好的","hǎo de","Okay / Alright","greetings",8,"好=good, 的 is a particle. Casual agreement."),
    v("是","shì","Yes / Is","greetings",9,"是 means 'is/are/am'. Also used for emphatic 'yes'."),
    v("欢迎","huān yíng","Welcome","greetings",14,"欢=happy, 迎=receive/welcome."),
    v("保重","bǎo zhòng","Take care","greetings",16,"保=protect, 重=important. Used when parting."),
    v("久仰","jiǔ yǎng","Honored to meet you","greetings",18,"Formal: 'I've long admired you.'"),
    v("初次见面","chū cì jiàn miàn","Nice to meet you","greetings",22,"初次=first time, 见面=meet."),
    v("请进","qǐng jìn","Please come in","greetings",15,"请=please, 进=enter."),
    # numbers
    v("零","líng","Zero (0)","numbers",13,"13 strokes. Used to say 0 or fill gaps: 108=一零八."),
    v("一","yī","One (1)","numbers",1,"One single horizontal stroke. The simplest character."),
    v("二","èr","Two (2)","numbers",2,"Two horizontal strokes, upper one shorter."),
    v("三","sān","Three (3)","numbers",3,"Three horizontal strokes of increasing length."),
    v("四","sì","Four (4)","numbers",5,"Five strokes. Looks like a box with two lines inside."),
    v("五","wǔ","Five (5)","numbers",4,"Cross-like shape."),
    v("六","liù","Six (6)","numbers",4,"Top dot and horizontal, then two curved strokes."),
    v("七","qī","Seven (7)","numbers",2,"Horizontal then vertical with a curve."),
    v("八","bā","Eight (8)","numbers",2,"Two diverging strokes — lucky number in China!"),
    v("九","jiǔ","Nine (9)","numbers",2,"Curved horizontal then a downward hook."),
    v("十","shí","Ten (10)","numbers",2,"A cross: horizontal then vertical."),
    v("十一","shí yī","Eleven (11)","numbers",3,"十(10)+一(1). Chinese numbers build logically!"),
    v("十二","shí èr","Twelve (12)","numbers",4,"十(10)+二(2)."),
    v("二十","èr shí","Twenty (20)","numbers",4,"二(2)+十(10). 'Two tens.'"),
    v("三十","sān shí","Thirty (30)","numbers",5,"三(3)+十(10). 'Three tens.'"),
    v("五十","wǔ shí","Fifty (50)","numbers",6,"五(5)+十(10)."),
    v("一百","yī bǎi","One hundred (100)","numbers",7,"百 means hundred. 白+一 at top."),
    v("一千","yī qiān","One thousand (1,000)","numbers",8,"千 means thousand."),
    v("一万","yī wàn","Ten thousand (10,000)","numbers",7,"万 is unique to Chinese/Japanese — a unit of 10,000."),
    v("半","bàn","Half","numbers",5,"Used in 半小时 (half hour), 一半 (one half)."),
    v("第一","dì yī","First","numbers",8,"第 is the ordinal prefix, like 'th/st/nd' in English."),
    # colors
    v("红色","hóng sè","Red","colors",12,"红 has the silk radical 纟. Red = luck in China."),
    v("蓝色","lán sè","Blue","colors",16,"蓝 has the grass radical 艹 on top."),
    v("绿色","lǜ sè","Green","colors",14,"绿 also has the silk radical 纟."),
    v("白色","bái sè","White","colors",7,"白 means pure/white. Used in 白饭 (plain rice)."),
    v("黑色","hēi sè","Black","colors",12,"黑 — bottom part shows fire 灬 (soot)."),
    v("黄色","huáng sè","Yellow","colors",13,"Yellow was the emperor's color in imperial China."),
    v("粉色","fěn sè","Pink","colors",12,"粉=powder/pink. Also means flour."),
    v("橙色","chéng sè","Orange","colors",16,"橙 is also the word for the orange fruit."),
    v("紫色","zǐ sè","Purple","colors",14,"Historically a royal color in China too."),
    v("棕色","zōng sè","Brown","colors",16,"棕 refers to palm tree fiber — naturally brown."),
    v("灰色","huī sè","Gray","colors",12,"灰=ash, 色=color. Ash-colored."),
    v("金色","jīn sè","Gold","colors",10,"金 means gold/metal. Also used in 金钱 (money)."),
    v("银色","yín sè","Silver","colors",11,"银 means silver. Used in 银行 (bank)."),
    v("彩色","cǎi sè","Colorful","colors",17,"彩=colorful/multicolored. 彩虹=rainbow."),
    # animals
    v("猫","māo","Cat","animals",11,"犭 radical. Many animal chars share this radical."),
    v("狗","gǒu","Dog","animals",8,"狗 has the dog radical 犭."),
    v("鱼","yú","Fish","animals",8,"Looks like a fish with a tail — pictographic!"),
    v("鸟","niǎo","Bird","animals",5,"Simplified pictograph of a bird."),
    v("马","mǎ","Horse","animals",3,"Simplified. Traditional 馬 shows body and legs."),
    v("熊猫","xióng māo","Panda","animals",20,"熊=bear, 猫=cat. Bear-cat!"),
    v("兔子","tù zi","Rabbit","animals",13,"兔 is the rabbit. One of the 12 zodiac animals."),
    v("老虎","lǎo hǔ","Tiger","animals",13,"老=old/honorific, 虎=tiger. Zodiac animal."),
    v("大象","dà xiàng","Elephant","animals",15,"大=big, 象=elephant/image."),
    v("猴子","hóu zi","Monkey","animals",14,"猴 has the dog radical 犭. Monkey = zodiac animal."),
    v("蛇","shé","Snake","animals",11,"One of the 12 zodiac animals."),
    v("龙","lóng","Dragon","animals",5,"Sacred creature in Chinese culture — symbol of power."),
    v("牛","niú","Cow / Ox","animals",4,"Zodiac animal. Used in 牛奶 (milk)."),
    v("猪","zhū","Pig","animals",11,"Last of the 12 zodiac animals."),
    v("羊","yáng","Sheep / Goat","animals",6,"Zodiac animal. 羊肉=lamb/mutton."),
    v("鸡","jī","Chicken","animals",7,"Zodiac animal. 鸡蛋=egg."),
    v("狼","láng","Wolf","animals",10,"犭 radical. 狼=wolf. Appears in many idioms."),
    v("熊","xióng","Bear","animals",14,"熊猫(panda) uses this character for bear."),
    v("鸭子","yā zi","Duck","animals",14,"鸭 has the bird radical 鸟."),
    v("青蛙","qīng wā","Frog","animals",15,"青=green/blue, 蛙=frog."),
    v("蝴蝶","hú dié","Butterfly","animals",24,"Two insect radical 虫 characters."),
    v("蜜蜂","mì fēng","Bee","animals",20,"蜜=honey, 蜂=bee. Both have insect radical 虫."),
    v("狮子","shī zi","Lion","animals",12,"犭 radical. Not native to China but in culture."),
    v("乌龟","wū guī","Turtle","animals",18,"乌=black, 龟=turtle. Symbol of longevity."),
    # food
    v("米饭","mǐ fàn","Rice","food",12,"米=uncooked rice, 饭=cooked rice/meal."),
    v("面条","miàn tiáo","Noodles","food",14,"面=noodles/face, 条=strip."),
    v("茶","chá","Tea","food",9,"艹 radical on top — tea comes from a plant!"),
    v("水","shuǐ","Water","food",4,"Pictographic — looks like flowing water."),
    v("苹果","píng guǒ","Apple","food",14,"苹=duckweed, 果=fruit."),
    v("鸡蛋","jī dàn","Egg","food",15,"鸡=chicken, 蛋=egg."),
    v("面包","miàn bāo","Bread","food",15,"面=flour/dough, 包=wrap."),
    v("牛奶","niú nǎi","Milk","food",12,"牛=cow, 奶=breast/milk."),
    v("肉","ròu","Meat","food",6,"Used in 猪肉(pork), 牛肉(beef), 鸡肉(chicken)."),
    v("蔬菜","shū cài","Vegetables","food",17,"蔬=vegetable, 菜=dish/vegetable."),
    v("水果","shuǐ guǒ","Fruit","food",12,"水=water, 果=fruit."),
    v("糖","táng","Sugar / Candy","food",16,"Also means candy. 巧克力=chocolate."),
    v("盐","yán","Salt","food",13,"Essential seasoning. 加盐=add salt."),
    v("豆腐","dòu fu","Tofu","food",16,"豆=bean, 腐=fermented/soft. Bean curd."),
    v("饺子","jiǎo zi","Dumplings","food",16,"Traditional for Chinese New Year."),
    v("汤","tāng","Soup","food",13,"汤 has the water radical 氵."),
    v("蛋糕","dàn gāo","Cake","food",21,"蛋=egg, 糕=cake/pastry."),
    v("香蕉","xiāng jiāo","Banana","food",24,"香=fragrant, 蕉=plantain."),
    v("西瓜","xī guā","Watermelon","food",13,"西=west, 瓜=melon. Beloved summer fruit!"),
    v("橙子","chéng zi","Orange (fruit)","food",20,"橙=orange tree. 橙汁=orange juice."),
    v("咖啡","kā fēi","Coffee","food",14,"Transliteration of 'coffee'. 口 radical (mouth sounds)."),
    v("果汁","guǒ zhī","Juice","food",13,"果=fruit, 汁=juice/liquid."),
    v("冰淇淋","bīng qí lín","Ice cream","food",24,"冰=ice, 淇淋 from 'cream'. Phonetic borrowing."),
    v("包子","bāo zi","Steamed bun","food",12,"包=wrap. Filled steamed buns."),
    v("饼干","bǐng gān","Cookie / Biscuit","food",18,"饼=flat bread, 干=dry."),
    v("辣椒","là jiāo","Chili pepper","food",22,"辣=spicy, 椒=pepper."),
    v("豆子","dòu zi","Beans","food",14,"豆=bean. 豆浆=soy milk."),
    # family
    v("爸爸","bà ba","Father","family",16,"爸 has 父(father) on top. Casual: 爸."),
    v("妈妈","mā ma","Mother","family",12,"妈 has 女(woman) radical. Casual: 妈."),
    v("哥哥","gē ge","Older brother","family",20,"哥 repeated for affection."),
    v("姐姐","jiě jie","Older sister","family",16,"姐 has 女 radical."),
    v("弟弟","dì di","Younger brother","family",14,"弟 means 'younger brother'."),
    v("妹妹","mèi mei","Younger sister","family",16,"妹 has 女 radical + 未(not yet)."),
    v("爷爷","yé ye","Paternal grandfather","family",20,"爷=grandfather/father. Paternal side."),
    v("奶奶","nǎi nai","Paternal grandmother","family",18,"奶 has 女 radical. Dad's mom."),
    v("外公","wài gōng","Maternal grandfather","family",17,"外=outside/maternal, 公=grandfather."),
    v("外婆","wài pó","Maternal grandmother","family",14,"外=maternal side, 婆=old woman/grandmother."),
    v("叔叔","shū shu","Uncle (father's younger bro)","family",16,"叔=father's younger brother specifically."),
    v("阿姨","ā yí","Aunt","family",12,"Also used politely for any older woman."),
    v("儿子","ér zi","Son","family",7,"儿=child/son. 女儿=daughter."),
    v("女儿","nǚ ér","Daughter","family",8,"女=woman/female, 儿=child."),
    v("丈夫","zhàng fu","Husband","family",12,"Formal word for husband."),
    v("妻子","qī zi","Wife","family",9,"Formal word for wife."),
    v("朋友","péng yǒu","Friend","family",16,"朋=friend group, 友=friend. 好朋友=best friend."),
    v("同学","tóng xué","Classmate","family",18,"同=same, 学=study. 'Study-together person'."),
    v("老师","lǎo shī","Teacher","family",13,"老=old/honored, 师=master/teacher."),
    v("孩子","hái zi","Child","family",11,"孩=child, 子=child/son. Gender-neutral."),
    # body
    v("头","tóu","Head","body",5,"头 also means 'top/first' in compounds."),
    v("眼睛","yǎn jing","Eyes","body",16,"眼=eye, 睛=eyeball. Both have 目(eye) radical."),
    v("耳朵","ěr duo","Ears","body",15,"耳=ear. 耳朵 adds 朵 (measure word for flowers/ears)."),
    v("鼻子","bí zi","Nose","body",13,"鼻=nose. Recognizable radical on top."),
    v("嘴","zuǐ","Mouth","body",16,"嘴 has 口(mouth) radical at the bottom."),
    v("手","shǒu","Hand","body",4,"手 is also a radical in many characters."),
    v("脚","jiǎo","Foot","body",13,"脚 has 月(flesh) radical. Also: 足(foot)."),
    v("腿","tuǐ","Leg","body",13,"腿 has the flesh radical 月."),
    v("心","xīn","Heart","body",4,"心 is a radical in emotion characters: 思(think),想(want)."),
    v("头发","tóu fa","Hair","body",12,"头=head, 发=hair/send out."),
    v("牙齿","yá chǐ","Teeth","body",18,"牙=tooth, 齿=teeth. 刷牙=brush teeth."),
    v("脸","liǎn","Face","body",10,"脸 has the flesh radical 月."),
    v("肚子","dù zi","Stomach","body",14,"肚 has the flesh radical 月."),
    v("背","bèi","Back","body",9,"背 also means 'to memorize' or 'to carry on back'."),
    v("胳膊","gē bo","Arm","body",20,"胳膊 has flesh radical 月 in both characters."),
    v("手指","shǒu zhǐ","Finger","body",13,"手=hand, 指=point/finger."),
    v("肩膀","jiān bǎng","Shoulder","body",24,"Both characters have flesh radical 月."),
    # time
    v("今天","jīn tiān","Today","time",9,"今=now/this, 天=day/sky."),
    v("明天","míng tiān","Tomorrow","time",15,"明=bright/next, 天=day. 'Next bright day.'"),
    v("昨天","zuó tiān","Yesterday","time",16,"昨=yesterday, 天=day."),
    v("星期一","xīng qī yī","Monday","time",19,"星期=week, 一=one. Mon=day 1 of the week."),
    v("星期二","xīng qī èr","Tuesday","time",20,"星期=week, 二=two."),
    v("星期三","xīng qī sān","Wednesday","time",21,"星期=week, 三=three."),
    v("星期四","xīng qī sì","Thursday","time",23,"星期=week, 四=four."),
    v("星期五","xīng qī wǔ","Friday","time",21,"星期=week, 五=five."),
    v("星期六","xīng qī liù","Saturday","time",21,"星期=week, 六=six."),
    v("星期天","xīng qī tiān","Sunday","time",21,"星期=week, 天=sky/day. Sunday!"),
    v("早上","zǎo shang","Morning","time",10,"早=early, 上=up."),
    v("下午","xià wǔ","Afternoon","time",10,"下=down/under, 午=noon."),
    v("晚上","wǎn shang","Evening / Night","time",12,"晚=late, 上=up."),
    v("年","nián","Year","time",6,"新年快乐=Happy New Year!"),
    v("月","yuè","Month / Moon","time",4,"Same character for month and moon."),
    v("周","zhōu","Week","time",8,"Also: 星期(xīng qī)."),
    v("小时","xiǎo shí","Hour","time",11,"小=small, 时=time."),
    v("分钟","fēn zhōng","Minute","time",14,"分=divide/minute, 钟=clock."),
    v("春天","chūn tiān","Spring","time",12,"春=spring. 春节=Spring Festival (Chinese New Year)."),
    v("夏天","xià tiān","Summer","time",11,"夏=summer. China's hottest season."),
    v("秋天","qiū tiān","Autumn / Fall","time",13,"秋=autumn. 秋天 is harvest season."),
    v("冬天","dōng tiān","Winter","time",10,"冬=winter. 冬至=Winter Solstice festival."),
    # verbs
    v("吃","chī","Eat","verbs",6,"吃 has the mouth radical 口. 吃饭=eat a meal."),
    v("喝","hē","Drink","verbs",12,"喝 has the mouth radical 口. 喝水=drink water."),
    v("说","shuō","Speak / Say","verbs",14,"说 has the speech radical 讠. 说话=speak."),
    v("听","tīng","Listen","verbs",7,"听 has the ear radical 耳. 听音乐=listen to music."),
    v("看","kàn","Look / Watch","verbs",9,"看 = watch/read/look. 看书=read a book."),
    v("走","zǒu","Walk / Go","verbs",7,"走=walk/go away. 走吧=let's go!"),
    v("来","lái","Come","verbs",8,"来=come. 来了=here/coming!"),
    v("去","qù","Go","verbs",5,"去=go. 去哪里=where are you going?"),
    v("要","yào","Want","verbs",9,"要=want/need. 我要=I want."),
    v("喜欢","xǐ huān","Like","verbs",18,"喜=happy, 欢=joyful. 我喜欢=I like."),
    v("爱","ài","Love","verbs",10,"爱 has 心(heart) inside. 我爱你=I love you."),
    v("学习","xué xí","Study","verbs",19,"学=learn, 习=practice. 学习中文=study Chinese."),
    v("工作","gōng zuò","Work","verbs",11,"工=work/craft, 作=make/do."),
    v("睡觉","shuì jiào","Sleep","verbs",17,"睡=sleep, 觉=feel/sense."),
    v("买","mǎi","Buy","verbs",6,"买 has 贝(shell/money) radical at the bottom."),
    v("写","xiě","Write","verbs",5,"写=write. 写字=write characters."),
    v("读","dú","Read","verbs",22,"读 has the speech radical 讠. 读书=read/study."),
    v("跑","pǎo","Run","verbs",12,"跑 has the foot radical 足."),
    v("笑","xiào","Laugh / Smile","verbs",10,"笑 has bamboo radical 竹 on top."),
    v("哭","kū","Cry","verbs",10,"哭 has 口(mouth) repeated at the bottom."),
    v("唱歌","chàng gē","Sing","verbs",20,"唱=sing, 歌=song."),
    v("跳舞","tiào wǔ","Dance","verbs",22,"跳=jump/dance, 舞=dance."),
    v("游泳","yóu yǒng","Swim","verbs",20,"游=swim/travel, 泳=swim. Both have water radical."),
]

# ── JAPANESE ────────────────────────────────────────────────────
JPN = [
    # greetings
    v("こんにちは","Konnichiwa","Hello (daytime)","greetings",None,"Used late morning to evening. は is read 'wa' here."),
    v("おはようございます","Ohayō gozaimasu","Good morning (formal)","greetings",None,"Casual: おはよう. One of the most common greetings."),
    v("こんばんは","Konbanwa","Good evening","greetings",None,"Used after sunset. 今晩(konban)=this evening."),
    v("おやすみなさい","Oyasuminasai","Good night","greetings",None,"Said before sleeping. Casual: おやすみ."),
    v("ありがとうございます","Arigatō gozaimasu","Thank you (formal)","greetings",None,"Casual: ありがとう. Very important!"),
    v("どういたしまして","Dōitashimashite","You're welcome","greetings",None,"The standard reply to ありがとう."),
    v("すみません","Sumimasen","Excuse me / Sorry","greetings",None,"Used to get attention OR apologize. Very versatile!"),
    v("ごめんなさい","Gomennasai","I'm sorry","greetings",None,"Deeper apology than すみません."),
    v("はい","Hai","Yes","greetings",None,"Polite yes. Can also mean 'I understand' or 'here I am'."),
    v("いいえ","Iie","No","greetings",None,"Polite no. Often softened: いいえ、けっこうです."),
    v("さようなら","Sayōnara","Goodbye (formal)","greetings",None,"Formal/final goodbye. Casual: じゃあね or またね."),
    v("またね","Mata ne","See you later","greetings",None,"Casual farewell. また=again, ね=right?/okay?"),
    v("初めまして","Hajimemashite","Nice to meet you","greetings",None,"Always said when meeting someone for the first time."),
    v("よろしくお願いします","Yoroshiku onegaishimasu","Please treat me well","greetings",None,"Said after introducing yourself. Crucial phrase!"),
    v("お元気ですか","Ogenki desu ka","How are you?","greetings",None,"元気(genki)=energetic/healthy. お is polite prefix."),
    v("元気です","Genki desu","I'm fine","greetings",None,"Direct reply to お元気ですか."),
    v("わかりました","Wakarimashita","I understand","greetings",None,"Past tense of わかる (to understand)."),
    v("お大事に","Odaijini","Take care (when ill)","greetings",None,"Said to someone who is sick. 大事=important/precious."),
    # numbers
    v("零・〇","rei / zero","Zero (0)","numbers",None,"Zero in Japanese can be れい(rei) or ゼロ(zero)."),
    v("一","ichi","One (1)","numbers",1,"Kanji 一 is one horizontal stroke."),
    v("二","ni","Two (2)","numbers",2,"Kanji 二 is two horizontal strokes."),
    v("三","san","Three (3)","numbers",3,"Kanji 三 is three horizontal strokes."),
    v("四","shi / yon","Four (4)","numbers",5,"よん(yon) preferred — し sounds like 死(death)."),
    v("五","go","Five (5)","numbers",4,"Kanji 五. ご(go)."),
    v("六","roku","Six (6)","numbers",4,"Kanji 六. ろく(roku)."),
    v("七","nana / shichi","Seven (7)","numbers",2,"なな(nana) is safer than しち."),
    v("八","hachi","Eight (8)","numbers",2,"Lucky number — 八 widens at bottom, symbolizing prosperity."),
    v("九","kyū","Nine (9)","numbers",2,"きゅう(kyū). く sounds like 苦(suffering) so きゅう preferred."),
    v("十","jū","Ten (10)","numbers",2,"Kanji 十 is a cross. じゅう(jū)."),
    v("十一","jūichi","Eleven (11)","numbers",3,"十(10)+一(1). Japanese numbers build logically."),
    v("十二","jūni","Twelve (12)","numbers",4,"十(10)+二(2)."),
    v("二十","nijū","Twenty (20)","numbers",4,"二(2)+十(10). 'Two tens.'"),
    v("三十","sanjū","Thirty (30)","numbers",5,"三(3)+十(10)."),
    v("百","hyaku","One hundred (100)","numbers",6,"百(hyaku). 二百=nihyaku, 三百=sanbyaku."),
    v("千","sen","One thousand (1,000)","numbers",3,"千(sen). 二千=nisen."),
    v("万","man","Ten thousand (10,000)","numbers",3,"万(man) is a key Japanese counting unit."),
    v("半分","hanbun","Half","numbers",None,"半(han)=half, 分(bun)=part."),
    # colors
    v("赤","aka","Red","colors",7,"赤(aka). Also: レッド(reddo) from English."),
    v("青","ao","Blue / Green","colors",8,"青(ao) covers both! Context matters."),
    v("白","shiro","White","colors",5,"白(shiro). 白ご飯(shirogohan)=plain white rice."),
    v("黒","kuro","Black","colors",11,"黒(kuro). Used in 黒板(kokuban)=blackboard."),
    v("黄色","kiiro","Yellow","colors",14,"黄(ki)+色(iro)=yellow color."),
    v("ピンク","pinku","Pink","colors",None,"From English 'pink'. Katakana for foreign words."),
    v("オレンジ","orenji","Orange","colors",None,"From English 'orange'. Also: だいだい色(daidaiiro)."),
    v("紫","murasaki","Purple","colors",12,"紫(murasaki). Traditional Japanese color."),
    v("茶色","chairo","Brown","colors",12,"茶(cha)=tea, 色(iro)=color. Tea-colored!"),
    v("灰色","haiiro","Gray","colors",10,"灰(hai)=ash, 色(iro)=color."),
    v("金色","kiniro","Gold","colors",9,"金(kin)=gold/metal, 色(iro)=color."),
    v("銀色","giniro","Silver","colors",14,"銀(gin)=silver, 色(iro)=color."),
    v("緑","midori","Green","colors",14,"緑(midori) = specifically green (not 青)."),
    # animals
    v("犬","inu","Dog","animals",4,"犬(inu). The kanji looks like a person with a dot — the dog's tail!"),
    v("猫","neko","Cat","animals",11,"猫(neko). The 犭 radical appears like in Chinese."),
    v("魚","sakana","Fish","animals",11,"魚(sakana). Also read うお(uo) in some compounds."),
    v("鳥","tori","Bird","animals",11,"鳥(tori). Also means chicken in food contexts."),
    v("馬","uma","Horse","animals",10,"馬(uma). One of the 12 zodiac animals."),
    v("うさぎ","usagi","Rabbit","animals",None,"うさぎ. Written in hiragana. Kanji: 兎."),
    v("とら","tora","Tiger","animals",None,"とら. Kanji: 虎. One of the zodiac animals."),
    v("ぞう","zou","Elephant","animals",None,"ぞう. Kanji: 象. 象 also means 'symbol/image'."),
    v("さる","saru","Monkey","animals",None,"さる. Kanji: 猿. Zodiac animal."),
    v("へび","hebi","Snake","animals",None,"へび. Kanji: 蛇. Zodiac animal."),
    v("うし","ushi","Cow","animals",None,"うし. Kanji: 牛. Zodiac animal."),
    v("ぶた","buta","Pig","animals",None,"ぶた. Kanji: 豚. Last zodiac animal."),
    v("ひつじ","hitsuji","Sheep","animals",None,"ひつじ. Kanji: 羊. Zodiac animal."),
    v("にわとり","niwatori","Chicken","animals",None,"にわとり. Kanji: 鶏. Zodiac animal."),
    v("おおかみ","ōkami","Wolf","animals",None,"おおかみ. Kanji: 狼. Features in Japanese folklore."),
    v("くま","kuma","Bear","animals",None,"くま. Kanji: 熊. くまのプーさん=Winnie the Pooh!"),
    v("かえる","kaeru","Frog","animals",None,"かえる. Kanji: 蛙. Also means 'to return home'!"),
    v("ちょう","chō","Butterfly","animals",None,"ちょう. Kanji: 蝶. Symbol of transformation."),
    v("はち","hachi","Bee","animals",None,"はち. Kanji: 蜂. はちみつ=honey."),
    v("しか","shika","Deer","animals",None,"しか. Kanji: 鹿. Sacred at Nara shrine."),
    v("きつね","kitsune","Fox","animals",None,"きつね. Kanji: 狐. Sacred messenger in Shinto."),
    v("たぬき","tanuki","Raccoon dog","animals",None,"たぬき. Kanji: 狸. Magical trickster in folklore."),
    # food
    v("ご飯","gohan","Rice / Meal","food",None,"ご飯. 朝ご飯=breakfast, 昼ご飯=lunch, 夕ご飯=dinner."),
    v("お水","omizu","Water","food",None,"水(mizu)=water. お is polite prefix. お水ください=water please."),
    v("お茶","ocha","Tea","food",None,"茶(cha)=tea. 緑茶=green tea, 麦茶=barley tea."),
    v("寿司","sushi","Sushi","food",13,"One of Japan's most famous dishes worldwide."),
    v("ラーメン","rāmen","Ramen","food",None,"Katakana — foreign-origin word. Hot noodle soup."),
    v("パン","pan","Bread","food",None,"From Portuguese 'pão'. Katakana loanword."),
    v("牛乳","gyūnyū","Milk","food",None,"牛(gyū)=cow, 乳(nyū)=milk. More formal than ミルク."),
    v("肉","niku","Meat","food",None,"牛肉(gyūniku)=beef, 豚肉(butaniku)=pork, 鶏肉(toriniku)=chicken."),
    v("野菜","yasai","Vegetables","food",None,"野(ya)=field, 菜(sai)=greens/vegetable."),
    v("果物","kudamono","Fruit","food",None,"果(ka)=fruit, 物(mono)=thing."),
    v("卵","tamago","Egg","food",None,"卵(tamago). 目玉焼き(medamayaki)=fried egg."),
    v("砂糖","satō","Sugar","food",None,"砂(sa)=sand, 糖(tō)=sugar. Sand-like sugar!"),
    v("塩","shio","Salt","food",None,"塩(shio). お塩ください=please pass the salt."),
    v("みそ汁","misoshiru","Miso soup","food",None,"Traditional Japanese soup served with most meals."),
    v("てんぷら","tenpura","Tempura","food",None,"Battered and fried vegetables or seafood."),
    v("おにぎり","onigiri","Rice ball","food",None,"Portable rice triangles with filling. Popular snack."),
    v("うどん","udon","Udon noodles","food",None,"Thick white wheat noodles. Comfort food."),
    v("そば","soba","Soba noodles","food",None,"Thin buckwheat noodles. Eaten hot or cold."),
    v("アイスクリーム","aisukurīmu","Ice cream","food",None,"English loanword in katakana. アイス for short."),
    v("ケーキ","kēki","Cake","food",None,"From English 'cake'. Very popular in Japan."),
    v("バナナ","banana","Banana","food",None,"Loanword. Japan's most popular fruit by volume."),
    v("りんご","ringo","Apple","food",None,"りんご. Kanji: 林檎. 青森(Aomori) is famous for apples."),
    v("コーヒー","kōhī","Coffee","food",None,"From Dutch 'koffie'. Japan has a strong coffee culture."),
    v("ジュース","jūsu","Juice","food",None,"From English 'juice'. Also used for soft drinks."),
    v("おかし","okashi","Sweets / Snacks","food",None,"おかし. Kanji: お菓子. Japanese sweets are famous!"),
    # family
    v("お父さん","otōsan","Father","family",None,"お父さん for others' fathers. Own father: 父(chichi)."),
    v("お母さん","okāsan","Mother","family",None,"お母さん for others' mothers. Own mother: 母(haha)."),
    v("お兄さん","onīsan","Older brother","family",None,"お兄さん for others'. Own: 兄(ani)."),
    v("お姉さん","onēsan","Older sister","family",None,"お姉さん for others'. Own: 姉(ane)."),
    v("弟","otōto","Younger brother","family",8,"弟(otōto). Own younger brother."),
    v("妹","imōto","Younger sister","family",8,"妹(imōto). 女 radical. Own younger sister."),
    v("おじいさん","ojiisan","Grandfather","family",None,"おじいさん. Own grandfather: 祖父(sofu)."),
    v("おばあさん","obāsan","Grandmother","family",None,"おばあさん. Own grandmother: 祖母(sobo)."),
    v("おじさん","ojisan","Uncle","family",None,"おじさん. Also used for middle-aged men generally."),
    v("おばさん","obasan","Aunt","family",None,"おばさん. Also used for middle-aged women."),
    v("息子","musuko","Son","family",None,"息子(musuko). 息=breath, 子=child."),
    v("娘","musume","Daughter","family",None,"娘(musume). Also means 'young woman/girl'."),
    v("夫","otto","Husband","family",None,"夫(otto). Formal. Casual: 旦那(danna)."),
    v("妻","tsuma","Wife","family",None,"妻(tsuma). Formal. Casual: 奥さん(okusan)."),
    v("友達","tomodachi","Friend","family",None,"友(tomo)=friend, 達=plural suffix."),
    v("先生","sensei","Teacher","family",None,"先生(sensei). Also used for doctors and experts."),
    v("学生","gakusei","Student","family",None,"学(gaku)=study, 生(sei)=life/person."),
    v("隣人","rinjin","Neighbor","family",None,"隣(rin)=next to, 人(jin)=person."),
    # body
    v("頭","atama","Head","body",None,"頭(atama). 頭が痛い=I have a headache."),
    v("目","me","Eyes","body",None,"目(me). 目が大きい=big eyes. 目 is the eye radical."),
    v("耳","mimi","Ears","body",None,"耳(mimi). 耳が聞こえない=can't hear."),
    v("鼻","hana","Nose","body",None,"鼻(hana). Also means flower! Same pronunciation, different kanji."),
    v("口","kuchi","Mouth","body",None,"口(kuchi). 口 is also a radical in many characters."),
    v("手","te","Hand","body",None,"手(te). 手伝う(tetsudau)=help. 握手(akushu)=handshake."),
    v("足","ashi","Foot / Leg","body",None,"足(ashi). 足りない=not enough. Foot AND leg."),
    v("心","kokoro","Heart","body",None,"心(kokoro). Emotional heart. 心配=worry(heartcare)."),
    v("髪","kami","Hair","body",None,"髪(kami). 髪の毛(kaminoke)=hair. Also: 神(kami)=god!"),
    v("歯","ha","Tooth / Teeth","body",None,"歯(ha). 歯ブラシ=toothbrush. 歯磨き=brushing teeth."),
    v("顔","kao","Face","body",None,"顔(kao). 顔が広い=know many people (wide face)."),
    v("お腹","onaka","Stomach","body",None,"お腹(onaka). お腹が空いた=I'm hungry (stomach is empty)."),
    v("背中","senaka","Back","body",None,"背(se)=back/height, 中(naka)=middle."),
    v("肩","kata","Shoulder","body",None,"肩(kata). 肩こり=shoulder stiffness (common in Japan)."),
    v("指","yubi","Finger","body",None,"指(yubi). 親指=thumb, 人差し指=index finger."),
    v("体","karada","Body","body",None,"体(karada). 体に気をつけて=take care of your body."),
    # time
    v("今日","kyō","Today","time",None,"今日(kyō). Also read こんにち in こんにちは."),
    v("明日","ashita","Tomorrow","time",None,"明日(ashita or asu). 明=bright/next."),
    v("昨日","kinō","Yesterday","time",None,"昨日(kinō). 昨=past."),
    v("月曜日","getsuyōbi","Monday","time",None,"月(getsu)=moon/Monday. 曜日=day of week."),
    v("火曜日","kayōbi","Tuesday","time",None,"火(ka)=fire. Days named after 5 elements + sun + moon."),
    v("水曜日","suiyōbi","Wednesday","time",None,"水(sui)=water."),
    v("木曜日","mokuyōbi","Thursday","time",None,"木(moku)=wood/tree."),
    v("金曜日","kin'yōbi","Friday","time",None,"金(kin)=gold/metal. 花金(hanakin)=fun Friday!"),
    v("土曜日","doyōbi","Saturday","time",None,"土(do)=earth/soil."),
    v("日曜日","nichiyōbi","Sunday","time",None,"日(nichi)=sun. Rest day."),
    v("朝","asa","Morning","time",None,"朝(asa). 朝ご飯=breakfast. 朝早く=early morning."),
    v("昼","hiru","Noon / Daytime","time",None,"昼(hiru). 昼ご飯=lunch. 昼寝=nap."),
    v("夜","yoru","Night / Evening","time",None,"夜(yoru). 夜ふかし=staying up late."),
    v("今年","kotoshi","This year","time",None,"今(ko)=now, 年(toshi)=year."),
    v("来年","rainen","Next year","time",None,"来(rai)=come/next, 年(nen)=year."),
    v("去年","kyonen","Last year","time",None,"去(kyo)=past/go away, 年(nen)=year."),
    v("週","shū","Week","time",None,"週(shū). 先週=last week, 来週=next week."),
    v("時間","jikan","Hour / Time","time",None,"時(ji)=time/hour, 間(kan)=interval."),
    v("春","haru","Spring","time",None,"春(haru). 桜(sakura)=cherry blossom blooms in spring."),
    v("夏","natsu","Summer","time",None,"夏(natsu). お盆(obon)=summer ancestor festival."),
    v("秋","aki","Autumn","time",None,"秋(aki). 紅葉(kōyō)=autumn leaves."),
    v("冬","fuyu","Winter","time",None,"冬(fuyu). お正月(oshōgatsu)=New Year in winter."),
    # verbs
    v("食べる","taberu","Eat","verbs",None,"食べる(taberu). 何を食べる=what to eat?"),
    v("飲む","nomu","Drink","verbs",None,"飲む(nomu). 飲み物(nomimono)=beverage."),
    v("話す","hanasu","Speak / Talk","verbs",None,"話す(hanasu). 日本語を話す=speak Japanese."),
    v("聞く","kiku","Listen / Hear","verbs",None,"聞く(kiku). Also means 'to ask'!"),
    v("見る","miru","See / Watch","verbs",None,"見る(miru). テレビを見る=watch TV."),
    v("歩く","aruku","Walk","verbs",None,"歩く(aruku). 散歩(sanpo)=walk/stroll."),
    v("来る","kuru","Come","verbs",None,"来る(kuru). Irregular verb! て-form: きて."),
    v("行く","iku","Go","verbs",None,"行く(iku). どこへ行く=where are you going?"),
    v("欲しい","hoshii","Want (thing)","verbs",None,"欲しい(hoshii). For wanting objects."),
    v("好き","suki","Like","verbs",None,"好き(suki). 大好き(daisuki)=love/really like."),
    v("愛する","aisuru","Love","verbs",None,"愛する(aisuru). 愛(ai)=love. 愛してる=I love you."),
    v("勉強する","benkyōsuru","Study","verbs",None,"勉強(benkyō)=study. する makes it a verb."),
    v("働く","hataraku","Work","verbs",None,"働く(hataraku). 仕事(shigoto)=job/work."),
    v("寝る","neru","Sleep","verbs",None,"寝る(neru). もう寝る=going to sleep now."),
    v("買う","kau","Buy","verbs",None,"買う(kau). 買い物(kaimono)=shopping."),
    v("書く","kaku","Write","verbs",None,"書く(kaku). 漢字を書く=write kanji."),
    v("読む","yomu","Read","verbs",None,"読む(yomu). 本を読む=read a book."),
    v("走る","hashiru","Run","verbs",None,"走る(hashiru). マラソンを走る=run a marathon."),
    v("笑う","warau","Laugh","verbs",None,"笑う(warau). 笑顔(egao)=smiling face."),
    v("泣く","naku","Cry","verbs",None,"泣く(naku). 泣き声=sound of crying."),
    v("歌う","utau","Sing","verbs",None,"歌う(utau). カラオケで歌う=sing at karaoke!"),
    v("踊る","odoru","Dance","verbs",None,"踊る(odoru). 踊り(odori)=dance/dancing."),
    v("泳ぐ","oyogu","Swim","verbs",None,"泳ぐ(oyogu). 水泳(suiei)=swimming."),
    v("遊ぶ","asobu","Play","verbs",None,"遊ぶ(asobu). 友達と遊ぶ=play with friends."),
    # hiragana/writing
    v("あいうえお","a i u e o","Vowels: a, i, u, e, o","writing",None,"The 5 Japanese vowels. Every syllable ends with one of these!"),
    v("か き く け こ","ka ki ku ke ko","K-row","writing",None,"Add ゛to get が ぎ ぐ げ ご (ga gi gu ge go)."),
    v("さ し す せ そ","sa shi su se so","S-row","writing",None,"し is 'shi' not 'si'. Common exception!"),
    v("た ち つ て と","ta chi tsu te to","T-row","writing",None,"ち='chi', つ='tsu' — two exceptions to the pattern."),
    v("な に ぬ ね の","na ni nu ne no","N-row","writing",None,"の(no) is also a possessive particle."),
    v("は ひ ふ へ ほ","ha hi fu he ho","H-row","writing",None,"は is 'wa' as topic marker. ふ is 'fu' not 'hu'."),
    v("ま み む め も","ma mi mu me mo","M-row","writing",None,"Regular row — no exceptions!"),
    v("や ゆ よ","ya yu yo","Y-row","writing",None,"Only 3 sounds. Used in compound sounds: きゃ(kya), みょ(myo)."),
    v("ら り る れ ろ","ra ri ru re ro","R-row","writing",None,"Japanese R is between English R and L. Flap sound!"),
    v("わ を ん","wa wo n","W-row + N","writing",None,"を(wo) only used as object particle. ん is the only standalone consonant."),
    v("ア イ ウ エ オ","A I U E O","Katakana vowels","writing",None,"Katakana is used for foreign words and loanwords."),
    v("カ キ ク ケ コ","KA KI KU KE KO","Katakana K-row","writing",None,"Compare: か(hiragana) → カ(katakana). Angular style!"),
]

# ── HINDI ────────────────────────────────────────────────────────
HIN = [
    # greetings
    v("नमस्ते","Namaste","Hello / Greetings","greetings",None,"Universal greeting. Hands together, slight bow. Works morning to night."),
    v("धन्यवाद","Dhanyavaad","Thank you (formal)","greetings",None,"Formal. Casual: शुक्रिया (Shukriya) from Urdu."),
    v("माफ़ करना","Maaf karna","Sorry / Excuse me","greetings",None,"माफ़=forgive, करना=to do. 'Please forgive me.'"),
    v("हाँ","Haan","Yes","greetings",None,"Informal. Formal: जी हाँ (jī hān)."),
    v("नहीं","Nahīn","No","greetings",None,"Formal: जी नहीं. Very common word!"),
    v("जी हाँ","Jī hān","Yes (polite)","greetings",None,"जी is a polite particle. Used with elders."),
    v("जी नहीं","Jī nahīn","No (polite)","greetings",None,"Polite no. Add जी to soften any response."),
    v("शुभ प्रभात","Shubh prabhat","Good morning","greetings",None,"Formal. Casual: सुप्रभात(Suprabhat). शुभ=auspicious."),
    v("शुभ दोपहर","Shubh dopahar","Good afternoon","greetings",None,"शुभ=good, दोपहर=afternoon/noon."),
    v("शुभ रात्रि","Shubh raatri","Good night","greetings",None,"Formal good night. Casual: शुभ रात (Shubh raat)."),
    v("ठीक है","Theek hai","Okay / Alright","greetings",None,"Very common expression. ठीक=okay/correct, है=is."),
    v("बहुत अच्छा","Bahut achcha","Very good","greetings",None,"बहुत=very, अच्छा=good. Great for complimenting!"),
    v("आपका स्वागत है","Aapka swaagat hai","You're welcome","greetings",None,"आपका=your, स्वागत=welcome, है=is."),
    v("कृपया","Kripaya","Please","greetings",None,"Add to any request for politeness. Like 'please' in English."),
    v("फिर मिलेंगे","Phir milenge","See you again","greetings",None,"फिर=again, मिलेंगे=we will meet."),
    v("ध्यान रखना","Dhyaan rakhna","Take care","greetings",None,"ध्यान=attention/care, रखना=to keep."),
    v("समझ गया","Samajh gaya","I understand (m.)","greetings",None,"समझ=understand, गया=went/did. Female: समझ गई."),
    v("खुश रहो","Khush raho","Stay happy","greetings",None,"खुश=happy, रहो=stay/remain. Warm farewell."),
    # numbers
    v("शून्य","shunya","Zero (0)","numbers",None,"शून्य(shunya). Sanskrit origin — India invented zero!"),
    v("एक","ek","One (1)","numbers",None,"एक. Related to English 'one' — same Indo-European root!"),
    v("दो","do","Two (2)","numbers",None,"दो. Related to English 'two', Latin 'duo'."),
    v("तीन","teen","Three (3)","numbers",None,"तीन. Related to English 'three', Latin 'tres'."),
    v("चार","chaar","Four (4)","numbers",None,"चार. Related to Latin 'quattuor', Spanish 'cuatro'."),
    v("पाँच","paanch","Five (5)","numbers",None,"पाँच. ँ shows nasal sound. Related to 'pentagon'."),
    v("छह","chhah","Six (6)","numbers",None,"छह. छ is an aspirated 'ch' sound."),
    v("सात","saat","Seven (7)","numbers",None,"सात. Related to Latin 'septem', English 'seven'."),
    v("आठ","aath","Eight (8)","numbers",None,"आठ. आ is a long 'aa' vowel."),
    v("नौ","nau","Nine (9)","numbers",None,"नौ. Related to Latin 'novem', English 'nine'."),
    v("दस","das","Ten (10)","numbers",None,"दस. Related to Greek 'deka', English 'decimal'."),
    v("ग्यारह","gyaarah","Eleven (11)","numbers",None,"Hindi numbers 11+ are unique — not built like English."),
    v("बारह","baarah","Twelve (12)","numbers",None,"बारह — a dozen."),
    v("पंद्रह","pandrah","Fifteen (15)","numbers",None,"पंद्रह — 15."),
    v("बीस","bees","Twenty (20)","numbers",None,"बीस — 20."),
    v("तीस","tees","Thirty (30)","numbers",None,"तीस — 30."),
    v("पचास","pachaas","Fifty (50)","numbers",None,"पचास — 50."),
    v("सौ","sau","One hundred (100)","numbers",None,"सौ — 100. एक सौ = one hundred."),
    v("हज़ार","hazaar","One thousand (1,000)","numbers",None,"हज़ार — 1,000. From Persian."),
    v("लाख","laakh","One hundred thousand","numbers",None,"लाख (100,000) — a key Indian number unit!"),
    v("आधा","aadha","Half","numbers",None,"आधा=half. आधा घंटा=half an hour."),
    v("पहला","pahla","First","numbers",None,"पहला(m)/पहली(f)=first. Ordinal number."),
    v("दूसरा","doosra","Second","numbers",None,"दूसरा(m)/दूसरी(f)=second."),
    # colors
    v("लाल","laal","Red","colors",None,"लाल. Red = auspicious; used in weddings, celebrations."),
    v("नीला","neela","Blue","colors",None,"नीला(m)/नीली(f). Adjectives change for gender in Hindi!"),
    v("हरा","hara","Green","colors",None,"हरा(m)/हरी(f). हरियाली=lush greenery."),
    v("पीला","peela","Yellow","colors",None,"पीला(m)/पीली(f). Haldi(turmeric) is beloved yellow spice."),
    v("सफ़ेद","safed","White","colors",None,"सफ़ेद. From Arabic/Persian influence on Hindi."),
    v("काला","kaala","Black","colors",None,"काला(m)/काली(f). काली माता=the dark goddess."),
    v("गुलाबी","gulaabi","Pink","colors",None,"गुलाब=rose. गुलाबी=rose-colored/pink!"),
    v("नारंगी","naarangi","Orange","colors",None,"नारंग=orange fruit. Saffron-orange is sacred in Hinduism."),
    v("बैंगनी","baingani","Purple","colors",None,"बैंगन=eggplant. Purple like an eggplant!"),
    v("भूरा","bhoora","Brown","colors",None,"भूरा(m)/भूरी(f). Earth/soil colored."),
    v("धूसर","dhoosar","Gray","colors",None,"धूसर or स्लेटी(slate-colored). Gray."),
    v("सुनहरा","sunahara","Gold","colors",None,"सुनहरा. From सोना(gold). Golden/golden-colored."),
    v("चाँदी","chaandi","Silver","colors",None,"चाँदी=silver (metal). Used for color and the metal."),
    v("इंद्रधनुष","indradhanush","Rainbow","colors",None,"इंद्र=Indra(rain god), धनुष=bow. God's bow!"),
    # animals
    v("कुत्ता","kutta","Dog","animals",None,"कुत्ता(m)/कुत्ती(f). Very common pet."),
    v("बिल्ली","billi","Cat","animals",None,"बिल्ली(f)/बिल्ला(m)."),
    v("हाथी","haathi","Elephant","animals",None,"Sacred in Hinduism. Associated with Lord Ganesha."),
    v("शेर","sher","Lion / Tiger","animals",None,"शेर can mean lion or tiger. National animal: बाघ(tiger)."),
    v("मोर","mor","Peacock","animals",None,"India's national bird. Associated with Lord Krishna."),
    v("खरगोश","khargosh","Rabbit","animals",None,"खरगोश — soft fluffy ears!"),
    v("बाघ","baagh","Tiger","animals",None,"बाघ — India's national animal. Bengal tiger."),
    v("बंदर","bandar","Monkey","animals",None,"बंदर. Hanuman(monkey god) is beloved in Hinduism."),
    v("साँप","saanp","Snake","animals",None,"साँप. Cobras are associated with Lord Shiva."),
    v("गाय","gaay","Cow","animals",None,"गाय — sacred in Hinduism. Revered, not eaten by Hindus."),
    v("सूअर","soor","Pig","animals",None,"सूअर. Varaha(boar) is an avatar of Vishnu."),
    v("भेड़","bhed","Sheep","animals",None,"भेड़. भेड़ की ऊन=sheep's wool."),
    v("मुर्गा","murga","Rooster / Chicken","animals",None,"मुर्गा(m)/मुर्गी(f). मुर्गी के अंडे=chicken eggs."),
    v("भेड़िया","bhediya","Wolf","animals",None,"भेड़िया. Features in Indian fables."),
    v("भालू","bhaalu","Bear","animals",None,"भालू. Sloth bear is native to India."),
    v("मेंढक","mendak","Frog","animals",None,"मेंढक. Associated with monsoon rains."),
    v("तितली","titali","Butterfly","animals",None,"तितली. Symbol of transformation and beauty."),
    v("मधुमक्खी","madhumakkhi","Bee","animals",None,"मधु=honey, मक्खी=fly. Honey-fly!"),
    v("हिरण","hiran","Deer","animals",None,"हिरण. The golden deer appears in the Ramayana."),
    v("कबूतर","kabootar","Pigeon","animals",None,"कबूतर. Common in Indian cities; symbol of peace."),
    v("तोता","tota","Parrot","animals",None,"तोता. Sacred to Kamadeva, god of love."),
    v("ऊँट","oont","Camel","animals",None,"ऊँट. The ship of the Thar Desert in Rajasthan."),
    v("मछली","machhli","Fish","animals",None,"मछली. 'मछली जल की रानी है' = famous children's rhyme."),
    v("गधा","gadha","Donkey","animals",None,"गधा. Also informally means 'dumb/stubborn person'."),
    # food
    v("रोटी","roti","Flatbread","food",None,"Staple bread. Also called चपाती(chapati)."),
    v("चावल","chaawal","Rice","food",None,"चावल=uncooked rice. पका हुआ चावल=cooked rice."),
    v("पानी","paani","Water","food",None,"पानी लाइए=please bring water."),
    v("चाय","chai","Tea","food",None,"India's beloved spiced milk tea! From Chinese 茶(chá)."),
    v("दाल","daal","Lentils","food",None,"Daily staple. दाल-चावल=comfort food."),
    v("ब्रेड","bred","Bread","food",None,"From English 'bread'. Western-style bread."),
    v("दूध","doodh","Milk","food",None,"दूध. Sacred offering to gods. दूध पीना=drink milk."),
    v("मांस","maas","Meat","food",None,"मांस. Not eaten by vegetarians (many Hindus are vegetarian)."),
    v("सब्ज़ी","sabzi","Vegetables","food",None,"सब्ज़ी. India has a huge vegetarian food culture!"),
    v("फल","phal","Fruit","food",None,"फल. फलों की दुकान=fruit shop."),
    v("अंडा","anda","Egg","food",None,"अंडा. अंडा भुर्जी=scrambled eggs."),
    v("चीनी","cheeni","Sugar","food",None,"चीनी=sugar. Also means 'Chinese person/thing'!"),
    v("नमक","namak","Salt","food",None,"नमक. नमक डालना=add salt. नमक-मिर्च=salt-pepper."),
    v("आम","aam","Mango","food",None,"आम=mango AND common/ordinary! India=mango capital."),
    v("केला","kela","Banana","food",None,"केला. Offered to Lord Hanuman. Nutritious snack."),
    v("सेब","seb","Apple","food",None,"सेब. Himachal Pradesh is famous for apples."),
    v("आलू","aloo","Potato","food",None,"आलू. आलू पराठा=potato stuffed bread. Beloved!"),
    v("प्याज़","pyaaz","Onion","food",None,"प्याज़. India is the world's 2nd largest onion producer."),
    v("टमाटर","tamaatar","Tomato","food",None,"टमाटर. From English/Portuguese. 'Tomato' is a loanword."),
    v("मिर्च","mirch","Chili pepper","food",None,"मिर्च. India loves spicy food! लाल मिर्च=red chili."),
    v("हल्दी","haldi","Turmeric","food",None,"हल्दी. Sacred yellow spice. Used in cooking and ceremonies."),
    v("समोसा","samosa","Samosa","food",None,"समोसा. Fried pastry with potato filling. Very popular!"),
    v("बिरयानी","biryaani","Biryani","food",None,"बिरयानी. Spiced rice dish — India's favorite!"),
    v("लड्डू","laddoo","Laddoo","food",None,"लड्डू. Round sweet ball. Offered to Lord Ganesha."),
    v("नान","naan","Naan bread","food",None,"नान. Leavened flatbread baked in a tandoor oven."),
    v("घी","ghee","Clarified butter","food",None,"घी. Sacred in Hindu rituals. Used in cooking."),
    v("कॉफ़ी","coffee","Coffee","food",None,"कॉफ़ी. From English/Arabic. South India loves filter coffee!"),
    v("जूस","juice","Juice","food",None,"जूस. From English. गन्ने का जूस=sugarcane juice."),
    # family
    v("पिताजी","pitaaji","Father","family",None,"Respectful. Casual: पापा(papa) or बाबा. जी adds respect."),
    v("माँ","maa","Mother","family",None,"माँ. Formal: माता जी. ँ = nasal sound."),
    v("भाई","bhai","Brother","family",None,"भाई. Casual friendly term too: भाई साहब=respected sir."),
    v("बहन","behen","Sister","family",None,"बहन. Respectful: बहन जी. दीदी(didi)=older sister."),
    v("दादा","daada","Paternal grandfather","family",None,"दादा. Dad's father. दादाजी for respect."),
    v("दादी","daadi","Paternal grandmother","family",None,"दादी. Dad's mother. दादीजी for respect."),
    v("नाना","naana","Maternal grandfather","family",None,"नाना. Mom's father. नानाजी for respect."),
    v("नानी","naani","Maternal grandmother","family",None,"नानी. Mom's mother. नानीजी for respect."),
    v("चाचा","chacha","Uncle (dad's younger bro)","family",None,"चाचा. Specific to father's younger brother."),
    v("चाची","chaachi","Aunt (chaacha's wife)","family",None,"चाची. Wife of चाचा."),
    v("मामा","mama","Maternal uncle","family",None,"मामा. Mom's brother. Different from Western 'mama'!"),
    v("मामी","maami","Maternal aunt","family",None,"मामी. Wife of मामा."),
    v("बेटा","beta","Son","family",None,"बेटा. Also used affectionately for any young boy."),
    v("बेटी","beti","Daughter","family",None,"बेटी. बेटी बचाओ=save the daughter (social campaign)."),
    v("पति","pati","Husband","family",None,"पति. Formal word. Casual: शौहर(shauhar) in Urdu."),
    v("पत्नी","patni","Wife","family",None,"पत्नी. Formal word. Casual: बीवी(biwi) in Urdu."),
    v("दोस्त","dost","Friend","family",None,"दोस्त. From Persian. यार(yaar) is also casual for friend."),
    v("शिक्षक","shikshak","Teacher (m.)","family",None,"शिक्षक(m)/शिक्षिका(f). गुरु(guru)=spiritual teacher."),
    v("छात्र","chhaatra","Student (m.)","family",None,"छात्र(m)/छात्रा(f)."),
    v("पड़ोसी","padosi","Neighbor","family",None,"पड़ोसी. पड़ोस=neighborhood."),
    # body
    v("सिर","sir","Head","body",None,"सिर. सिर दर्द=headache. सिर हिलाना=nod."),
    v("आँख","aankh","Eye","body",None,"आँख. आँखें(plural). आँखें बंद करो=close your eyes."),
    v("कान","kaan","Ear","body",None,"कान. कान से सुनना=hear with ears."),
    v("नाक","naak","Nose","body",None,"नाक. नाक बंद होना=stuffy nose."),
    v("मुँह","munh","Mouth","body",None,"मुँह. मुँह खोलो=open your mouth."),
    v("हाथ","haath","Hand","body",None,"हाथ. हाथ मिलाना=shake hands."),
    v("पाँव","paanv","Foot","body",None,"पाँव or पैर. पैर छूना=touch feet (sign of respect)."),
    v("दिल","dil","Heart","body",None,"दिल. From Persian. दिल से=from the heart."),
    v("बाल","baal","Hair","body",None,"बाल. बाल कटवाना=get a haircut."),
    v("दाँत","daant","Tooth / Teeth","body",None,"दाँत. दाँत साफ़ करना=brush teeth."),
    v("चेहरा","chehra","Face","body",None,"चेहरा. चेहरा धोना=wash face."),
    v("पेट","pet","Stomach","body",None,"पेट. पेट भरा है=stomach is full."),
    v("पीठ","peeth","Back","body",None,"पीठ. पीठ दर्द=back pain. Very common complaint!"),
    v("कंधा","kandha","Shoulder","body",None,"कंधा. कंधे से कंधा मिलाना=stand shoulder to shoulder."),
    v("उँगली","ungali","Finger","body",None,"उँगली. उँगली उठाना=point a finger."),
    v("घुटना","ghutna","Knee","body",None,"घुटना. घुटने टेकना=kneel down."),
    v("पेट की नाभि","naabhi","Navel","body",None,"नाभि. Sacred in yoga — center of the body."),
    # time
    v("आज","aaj","Today","time",None,"आज. आज का दिन=today's day."),
    v("कल","kal","Tomorrow / Yesterday","time",None,"कल means BOTH! Context tells you which."),
    v("परसों","parson","Day after tomorrow / before yesterday","time",None,"परसों = 2 days away (past or future)."),
    v("सोमवार","somvaar","Monday","time",None,"सोम=moon (Soma). Moon's day."),
    v("मंगलवार","mangalvaar","Tuesday","time",None,"मंगल=Mars. Mars's day — like Tuesday!"),
    v("बुधवार","budhvaar","Wednesday","time",None,"बुध=Mercury. Mercury's day."),
    v("गुरुवार","guruvaar","Thursday","time",None,"गुरु=Jupiter/teacher. Jupiter's day."),
    v("शुक्रवार","shukravaar","Friday","time",None,"शुक्र=Venus. Venus's day — like Friday!"),
    v("शनिवार","shanivaar","Saturday","time",None,"शनि=Saturn. Saturn's day — like Saturday!"),
    v("रविवार","ravivaar","Sunday","time",None,"रवि=sun. Sun's day — like Sunday!"),
    v("सुबह","subah","Morning","time",None,"सुबह. सुबह उठना=wake up in the morning."),
    v("दोपहर","dopahar","Afternoon / Noon","time",None,"दो=two, पहर=time period. 'Second time period.'"),
    v("शाम","shaam","Evening","time",None,"शाम. शाम की चाय=evening tea ritual."),
    v("रात","raat","Night","time",None,"रात. रात को=at night. रातों रात=overnight."),
    v("साल","saal","Year","time",None,"साल. नया साल=New Year."),
    v("महीना","mahina","Month","time",None,"महीना. बारह महीने=twelve months."),
    v("हफ़्ता","hafta","Week","time",None,"हफ़्ता. From Arabic. सात दिन का हफ़्ता=7-day week."),
    v("घंटा","ghanta","Hour","time",None,"घंटा. एक घंटा=one hour."),
    v("मिनट","minat","Minute","time",None,"मिनट. From English 'minute'."),
    v("वसंत","vasant","Spring","time",None,"वसंत. वसंत पंचमी=spring festival of Saraswati."),
    v("गर्मी","garmi","Summer","time",None,"गर्मी. Hot season. मई-जून are hottest months."),
    v("बरसात","barsaat","Monsoon / Rainy season","time",None,"बरसात. July-Sept monsoon is vital for Indian agriculture."),
    v("सर्दी","sardi","Winter","time",None,"सर्दी. सर्दी लगना=feel cold. Mild in most of India."),
    # verbs
    v("खाना","khaana","Eat","verbs",None,"खाना=eat AND food! खाना खाना=eat food."),
    v("पीना","peena","Drink","verbs",None,"पीना. पानी पीना=drink water."),
    v("बोलना","bolna","Speak / Say","verbs",None,"बोलना. हिंदी बोलना=speak Hindi."),
    v("सुनना","sunna","Listen","verbs",None,"सुनना. ध्यान से सुनना=listen carefully."),
    v("देखना","dekhna","See / Watch","verbs",None,"देखना. टीवी देखना=watch TV."),
    v("चलना","chalna","Walk / Move","verbs",None,"चलना. चलो=let's go (casual command)."),
    v("आना","aana","Come","verbs",None,"आना. आओ=come (casual). आइए=come (polite)."),
    v("जाना","jaana","Go","verbs",None,"जाना. जाओ=go (casual). जाइए=go (polite)."),
    v("चाहना","chahna","Want / Love","verbs",None,"चाहना. मैं चाहता/चाहती हूँ=I want."),
    v("पसंद करना","pasand karna","Like","verbs",None,"पसंद=liking. मुझे पसंद है=I like it."),
    v("प्यार करना","pyaar karna","Love","verbs",None,"प्यार=love. मैं तुमसे प्यार करता/करती हूँ=I love you."),
    v("पढ़ना","padhna","Read / Study","verbs",None,"पढ़ना=read AND study. किताब पढ़ना=read a book."),
    v("काम करना","kaam karna","Work","verbs",None,"काम=work/task. काम करना=to work."),
    v("सोना","sona","Sleep","verbs",None,"सोना=sleep AND gold! Context tells you which."),
    v("खरीदना","kharidna","Buy","verbs",None,"खरीदना. बाज़ार से खरीदना=buy from the market."),
    v("लिखना","likhna","Write","verbs",None,"लिखना. पत्र लिखना=write a letter."),
    v("दौड़ना","daudna","Run","verbs",None,"दौड़ना. तेज़ दौड़ना=run fast."),
    v("हँसना","hansna","Laugh","verbs",None,"हँसना. हँसी=laughter. खिलखिलाना=giggle."),
    v("रोना","rona","Cry","verbs",None,"रोना. रोना मत=don't cry."),
    v("खेलना","khelna","Play","verbs",None,"खेलना. क्रिकेट खेलना=play cricket (India's passion!)."),
    v("गाना","gaana","Sing","verbs",None,"गाना=sing AND song. गाना गाना=sing a song."),
    v("नाचना","naachna","Dance","verbs",None,"नाचना. नृत्य(nritya)=classical dance."),
    v("सीखना","seekhna","Learn","verbs",None,"सीखना. हिंदी सीखना=learn Hindi!"),
    v("समझना","samajhna","Understand","verbs",None,"समझना. क्या समझे?=Do you understand?"),
]

def make_vocab_js(entries):
    return "[\n" + ",\n".join(entries) + "\n    ]"

# Read and patch HTML
p = pathlib.Path("/sessions/admiring-stoic-pascal/mnt/outputs/language.html")
html = p.read_text(encoding="utf-8")

def find_matching_bracket(text, start):
    depth = 0
    i = start
    in_str = False
    sc = None
    while i < len(text):
        c = text[i]
        if in_str:
            if c == '\\': i += 2; continue
            if c == sc: in_str = False
        else:
            if c in ('"', "'", '`'): in_str = True; sc = c
            elif c == '[': depth += 1
            elif c == ']':
                depth -= 1
                if depth == 0: return i
        i += 1
    return -1

def patch_vocab(html, lang_marker, new_entries):
    # Find the language section
    lang_pos = html.find(lang_marker)
    if lang_pos == -1:
        print(f"ERROR: could not find {lang_marker}")
        return html
    # Find vocab:[ after the language marker
    vocab_pos = html.find("vocab:[", lang_pos)
    if vocab_pos == -1:
        vocab_pos = html.find("vocab: [", lang_pos)
        if vocab_pos == -1:
            print(f"ERROR: could not find vocab:[ for {lang_marker}")
            return html
        bracket_pos = vocab_pos + 7
    else:
        bracket_pos = vocab_pos + 6
    end_pos = find_matching_bracket(html, bracket_pos)
    if end_pos == -1:
        print(f"ERROR: could not find end of vocab array for {lang_marker}")
        return html
    new_vocab = "vocab:" + make_vocab_js(new_entries)
    html = html[:vocab_pos] + new_vocab + html[end_pos+1:]
    print(f"Patched {lang_marker}: {len(new_entries)} words")
    return html

html = patch_vocab(html, "mandarin:", MAN)
html = patch_vocab(html, "japanese:", JPN)
html = patch_vocab(html, "hindi:", HIN)

# Update CATS to include new categories
old_cats = """const CATS = {
  flashcards:  ['all','greetings','numbers','colors','animals','food','family','writing'],
  quiz:        ['all','greetings','numbers','colors','animals','food','family'],
  writing:     ['all','greetings','numbers','colors','animals','food','family','writing'],
  phrasebook:  [],
};"""
new_cats = """const CATS = {
  flashcards:  ['all','greetings','numbers','colors','animals','food','family','body','time','verbs','writing'],
  quiz:        ['all','greetings','numbers','colors','animals','food','family','body','time','verbs'],
  writing:     ['all','greetings','numbers','colors','animals','food','family','body','time','verbs','writing'],
  phrasebook:  [],
};"""
if old_cats in html:
    html = html.replace(old_cats, new_cats)
    print("Updated CATS")
else:
    print("CATS pattern not found — check manually")

p.write_text(html, encoding="utf-8")
print(f"\nDone! File size: {p.stat().st_size//1024} KB")
print(f"Total words: MAN={len(MAN)}, JPN={len(JPN)}, HIN={len(HIN)}")
