"""Missing tests part 2: AP History units 5-9"""

def mc(q, a, b, c, d, correct, exp):
    return {"type":"mc","q":q,"choices":[a,b,c,d],"correct":correct,"exp":exp}

AP_HISTORY_U5 = {
  "title": "AP Comparative Government and Politics",
  "questions": [
    mc("Which of the following is a unitary state?","United States","Germany","France","Canada",2,"France is a unitary state — the central government holds sovereign power. The US, Germany, Canada are federal."),
    mc("A federal system differs from a unitary system in that:","Power is concentrated in the central government","Sovereignty is shared between national and subnational governments","There is no constitution","Elections are indirect",1,"Federalism divides sovereignty between central and regional governments (states, provinces, Länder)."),
    mc("Which country has a parliamentary system where the executive is drawn from the legislature?","United States","Mexico","United Kingdom","Iran",2,"The UK has a Westminster parliamentary system — the Prime Minister must command a Commons majority."),
    mc("A 'fusion of powers' characterizes which type of system?","Presidential","Parliamentary","Federal","Theocratic",1,"Parliamentary systems fuse executive and legislative power; the Cabinet is drawn from Parliament."),
    mc("Which of the following best describes a rentier state?","A state that derives most revenue from taxation","A state that derives most revenue from natural resource exports (e.g., oil)","A state where rent control dominates policy","A state with strong civil society",1,"Rentier states (e.g., Nigeria, Russia) rely on resource rents, reducing incentive for taxation and accountability."),
    mc("China's political system is best described as:","Multi-party democracy","Liberal democracy with one dominant party","Single-party authoritarian state led by the CCP","Federal republic",2,"China is a one-party state led by the Chinese Communist Party with no meaningful electoral competition."),
    mc("The concept of 'legitimacy' in politics refers to:","A government's military strength","The right to rule — acceptance of authority as valid by the governed","The size of a state's territory","A state's economic output",1,"Legitimacy: the belief that a government's authority is rightful and justified. Weber identified traditional, charismatic, and rational-legal types."),
    mc("Which country uses a proportional representation electoral system?","United Kingdom (House of Commons)","United States (House of Representatives)","Germany (Bundestag proportional seats)","Mexico (Senate majority seats)",2,"Germany uses mixed-member proportional representation. UK and US use single-member plurality (first-past-the-post)."),
    mc("A majoritarian electoral system tends to produce:","Many small parties","Two dominant parties (Duverger's law)","Coalition governments","Proportional outcomes",1,"Single-member plurality systems (first-past-the-post) produce two-party systems per Duverger's law."),
    mc("Civil society refers to:","Government institutions","The military and police","Organizations and associations independent of the state (NGOs, unions, media)","The civil service",2,"Civil society: voluntary organizations between the state and individual — churches, unions, NGOs, independent media."),
    mc("Which country has a Supreme Leader who holds ultimate authority over elected officials?","Mexico","Nigeria","Russia","Iran",3,"Iran's Supreme Leader (Ayatollah) is above the elected President and Parliament — a theocratic overlay on elected institutions."),
    mc("'Corporatism' in Mexico historically referred to:","Free market capitalism","State-organized incorporation of interest groups (labor, peasants) into the ruling party (PRI)","Military control of politics","Parliamentary government",1,"The PRI's corporatist structure incorporated sectors of society into party structures, controlling opposition."),
    mc("Which of the following is a characteristic of a failed state?","Strong tax collection","Monopoly on legitimate use of force","Inability to control territory or provide basic services","High GDP per capita",2,"Failed states cannot maintain security, enforce law, or provide basic services across their territory."),
    mc("The European Union is best described as:","A federal superstate","A supranational organization where members transfer some sovereignty to shared institutions","A military alliance only","A free trade zone with no political integration",1,"The EU is supranational — member states transfer some sovereignty to EU institutions (Commission, Parliament, Court)."),
    mc("Nigeria's political system is best described as:","Unitary presidential","Federal presidential republic","Parliamentary monarchy","Single-party state",1,"Nigeria is a federal presidential republic with 36 states, modeled partly on the US system."),
    mc("Which concept describes the tendency of authoritarian regimes to allow some democratic forms without democratic substance?","Consolidation","Hybrid regime / competitive authoritarianism","Polyarchy","Parliamentarism",1,"Hybrid regimes (e.g., Russia, some Latin American states) hold elections but manipulate them to ensure the incumbent wins."),
    mc("In Russia, which institution holds the most political power in practice?","The Duma (legislature)","The Constitutional Court","The Presidency","The Federation Council",2,"Russia's presidency dominates — the president controls government formation, security, and foreign policy under Putin's system."),
    mc("A 'state' in political science is defined by:","A national identity","Weber's criteria: permanent population, defined territory, effective government, sovereignty","A democratic government","Common language and culture",1,"Weber's definition: state = monopoly on legitimate use of force within a territory. Montevideo Convention adds these four criteria."),
    mc("Political culture refers to:","Formal laws and institutions","Shared values, beliefs, and attitudes toward politics and government in a society","The culture of the political elite","Electoral rules and procedures",1,"Political culture (Almond and Verba): the pattern of attitudes and values toward the political system in a society."),
    mc("Which country has a bicameral legislature where the upper house (Senate) is directly elected?","United Kingdom","China","Mexico","Iran",2,"Mexico's Senate is directly elected. The UK's Lords is appointed; China and Iran have different structures."),
  ]
}

AP_HISTORY_U6 = {
  "title": "AP Human Geography",
  "questions": [
    mc("The concept of 'sense of place' refers to:","The geographic coordinates of a location","The emotional and subjective meanings attached to a location","The physical characteristics of a site","The administrative boundaries of a region",1,"Sense of place: the subjective, emotional attachment people develop to a place based on experience and meaning."),
    mc("The demographic transition model describes:","Migration patterns across countries","Stages of population change as societies industrialize (high birth/death → low birth/death)","Economic development phases","Urban growth patterns",1,"DTM: Stage 1 (high birth/death) → Stage 2 (death rate drops) → Stage 3 (birth rate drops) → Stage 4 (low both)."),
    mc("'Push factors' in migration theory are:","Attractions of the destination","Conditions that drive people away from their origin (poverty, conflict, disaster)","Government policies promoting migration","Cultural ties to a new country",1,"Push factors repel people from their origin; pull factors attract them to a destination."),
    mc("A primate city is one that:","Is the national capital","Is disproportionately large compared to the next-largest cities","Has the highest GDP","Is located at the geographic center of a country",1,"Primate city: significantly larger than the second city. Common in developing countries (e.g., Bangkok, Buenos Aires)."),
    mc("The rank-size rule states that:","All cities are the same size","The nth-largest city is 1/n the size of the largest city","Cities grow geometrically","Population is evenly distributed",1,"Rank-size rule: a country's cities follow a predictable size hierarchy where rank × population = approximately constant."),
    mc("Cultural diffusion refers to:","The extinction of cultural practices","The spread of cultural elements from one area to another","The preservation of indigenous culture","Migration of cultural groups",1,"Cultural diffusion: spread of ideas, practices, and innovations across space through contact, migration, or media."),
    mc("'Sequent occupance' explains how:","Languages evolve over time","Successive waves of inhabitants leave their cultural imprint on a landscape","Political boundaries are established","Cities grow outward",1,"Sequent occupance: landscapes are layered with the cultural traces of successive occupants (Native American → colonial → modern)."),
    mc("The von Thünen model of agricultural land use predicts:","Flat uniform plane with concentric rings of agricultural activity based on distance from market","All crops are grown uniformly","Mountain regions have different crops","Soil quality determines crop type",0,"Von Thünen: uniform plain; market in center; rings of land use from intensive (dairy, market gardening) to extensive (grain, ranching) outward."),
    mc("Urbanization is primarily driven by:","Rural-to-urban migration and natural increase in cities","Declining birth rates","Government mandates","Deindustrialization",0,"Urbanization results from rural-to-urban migration (economic opportunity) and natural population increase in cities."),
    mc("The concept of 'core-periphery' in world-systems theory describes:","Mountain vs. valley areas","Wealthy industrialized nations (core) exploiting developing nations (periphery)","Urban vs. rural areas","Northern vs. southern hemispheres",1,"Wallerstein's world-systems theory: core nations extract resources and labor from peripheral nations, maintaining global inequality."),
    mc("Gentrification refers to:","Urban sprawl into rural areas","Renovation of deteriorated urban neighborhoods, often displacing lower-income residents","Decline of a city's population","Suburbanization of wealthier residents",1,"Gentrification: renovation and influx of wealthier residents into working-class neighborhoods, raising property values and displacing residents."),
    mc("Which stage of the epidemiological transition is characterized by degenerative diseases?","Stage 1: Pestilence and famine","Stage 2: Receding pandemics","Stage 3: Degenerative and human-created diseases","Stage 4: Delayed degenerative diseases",2,"Stage 3: chronic diseases (heart disease, cancer) replace infectious disease as leading causes of death as societies industrialize."),
    mc("A 'lingua franca' is:","A dying language","A common language used for communication between speakers of different native languages","A language spoken by an ethnic minority","A dialect of a major language",1,"Lingua franca: a bridge language for communication between groups with different native tongues (e.g., English, Swahili, Mandarin)."),
    mc("The 'fertility rate' most important for population projections is the:","Crude birth rate","Total fertility rate (TFR) — average births per woman over her lifetime","Death rate","Infant mortality rate",1,"TFR is the key measure: TFR > 2.1 = population growth; TFR < 2.1 = eventual population decline."),
    mc("Which factor most influences agricultural patterns according to modern commercial agriculture theory?","Climate alone","Market access, transportation costs, and technology","Soil type exclusively","Cultural preferences",1,"Modern commercial agriculture is driven by market access (transportation, distribution networks) and technological inputs."),
    mc("'Irredentism' refers to:","Granting independence to a territory","A movement to unite ethnically related people in adjacent territories under one state","The merger of two sovereign states","Ethnic cleansing",1,"Irredentism: a state's claim to territory in another country based on ethnic, historical, or cultural ties (e.g., Hungary's claims post-WWI)."),
    mc("The Burgess concentric zone model places the highest-income residents:","Nearest the CBD","In the outer rings / suburbs","In the transition zone","In industrial zones",1,"Burgess model: CBD → transition zone → working class → middle class → commuter zone (outermost, highest income)."),
    mc("'Remittances' in the context of migration refers to:","Government payments to immigrants","Money sent by migrants back to their home country/family","Trade payments between countries","Foreign aid",1,"Remittances: money transferred by migrants to relatives in their origin country — major income source for many developing nations."),
    mc("The concept of a 'boundary' vs. a 'border' in political geography distinguishes:","Large vs. small states","A legal line vs. the zone where two cultures/states meet","Maritime vs. land divisions","Democratic vs. authoritarian states",1,"Boundary: the legal/political line. Border: the zone around it with cross-boundary activity, culture, and identity."),
    mc("'Centrifugal forces' in political geography are those that:","Unite a state and strengthen national identity","Pull a state apart — regional, ethnic, linguistic divisions","Attract foreign investment","Promote urbanization",1,"Centrifugal forces (ethnic conflict, regional inequality, separatism) weaken state cohesion; centripetal forces (national identity, shared language) strengthen it."),
  ]
}

AP_HISTORY_U7 = {
  "title": "AP Macroeconomics",
  "questions": [
    mc("GDP measures:","The total value of goods and services produced in a country in a given period","Total government spending","Total exports minus imports","The income of all citizens wherever they live",0,"GDP = total market value of all final goods and services produced within a country's borders in a year."),
    mc("The business cycle describes:","Long-run economic growth trend","Short-run fluctuations in economic activity (expansion, peak, recession, trough)","Seasonal changes in prices","Government budget cycles",1,"Business cycle: recurring patterns of expansion and contraction in economic output around the long-run trend."),
    mc("Aggregate demand is the total demand for:","Only consumer goods","All final goods and services in an economy at different price levels (C + I + G + NX)","Government services","Intermediate goods",1,"AD = C + I + G + NX. It slopes downward because lower price levels increase purchasing power and competitiveness."),
    mc("Which of the following would shift aggregate supply to the right (increase AS)?","Rising oil prices","Decrease in productivity","Technological improvement that lowers production costs","Increase in wages",2,"SRAS shifts right (increases) with lower input costs, improved technology, or increased productivity."),
    mc("The multiplier effect occurs when:","Government spending decreases tax revenue","An initial change in spending leads to a larger change in GDP","Prices rise with money supply","Interest rates fall with bond prices",1,"Multiplier = 1/(1-MPC). Spending ripples through the economy as each round of income creates more spending."),
    mc("Contractionary monetary policy involves:","Increasing the money supply","Decreasing the money supply by raising interest rates or selling bonds","Cutting government spending","Lowering taxes",1,"Contractionary monetary policy: Fed raises interest rates / sells bonds → reduces money supply → reduces inflation."),
    mc("The natural rate of unemployment includes:","Only cyclical unemployment","Frictional and structural unemployment (not cyclical)","All unemployment during a recession","Zero unemployment",1,"Natural rate = frictional + structural. Cyclical unemployment is above the natural rate during recessions."),
    mc("The Phillips curve (short-run) shows:","A positive relationship between inflation and unemployment","A trade-off: lower unemployment is associated with higher inflation","A long-run relationship that is vertical","A positive relationship between GDP and unemployment",1,"Short-run Phillips curve: inverse relationship between inflation and unemployment. Expansionary policy lowers unemployment but raises inflation."),
    mc("Which of the following is an example of automatic stabilizers?","Fed raising interest rates","Congress passing a stimulus bill","Unemployment insurance payments that increase during recessions","Discretionary tax cuts",2,"Automatic stabilizers (unemployment insurance, progressive taxes) automatically cushion recessions without new legislation."),
    mc("Crowding out occurs when:","Government spending replaces private investment by raising interest rates","Taxes are cut during recessions","The Fed buys government bonds","Exports exceed imports",0,"Crowding out: government borrowing raises interest rates, reducing private investment. This limits fiscal policy effectiveness."),
    mc("If the marginal propensity to consume (MPC) = 0.8, the spending multiplier is:","0.8","4","5","2",2,"Multiplier = 1/(1-MPC) = 1/0.2 = 5. A $1 increase in spending increases GDP by $5."),
    mc("A current account surplus means a country:","Imports more than it exports","Has more government revenue than spending","Exports more than it imports (net lender to the world)","Has high inflation",2,"Current account surplus: exports > imports. The country is a net lender — it sends goods and receives financial claims."),
    mc("The quantity theory of money (MV = PQ) implies that if velocity and output are stable:","Inflation equals money growth rate","Higher money supply reduces prices","Output grows with money supply","Velocity determines output",0,"MV = PQ: if V and Q are constant, doubling M doubles P (price level). This is the monetarist view of inflation."),
    mc("Open market operations refer to the Fed:","Changing the required reserve ratio","Buying or selling government securities to change the money supply","Setting the federal funds rate target","Regulating bank capital requirements",1,"OMO: Fed buys bonds → injects money (expansionary); Fed sells bonds → removes money (contractionary)."),
    mc("A budget deficit occurs when:","GDP falls","Government spending exceeds tax revenue in a given period","The trade balance is negative","Inflation exceeds unemployment",1,"Budget deficit: G > T (government spending > tax revenues). Financed by borrowing (issuing bonds)."),
    mc("In the long run, the aggregate supply curve is:","Downward sloping","Horizontal","Vertical at the natural rate of output","Positively sloped",2,"LRAS is vertical at potential GDP (full employment output). In the long run, price level doesn't affect output."),
    mc("Stagflation is characterized by:","High growth and low inflation","High inflation combined with high unemployment and slow growth","Low unemployment and high output","Deflation and recession",1,"Stagflation (1970s): simultaneous high inflation and high unemployment — adverse supply shock shifts SRAS left."),
    mc("The loanable funds market determines:","The price level","The real interest rate through interaction of savings (supply) and investment (demand)","The money supply","Nominal GDP",1,"Loanable funds: supply = saving; demand = investment borrowing. Equilibrium sets the real interest rate."),
    mc("Which measure best represents the standard of living?","Nominal GDP","Real GDP per capita","Total GDP","The trade balance",1,"Real GDP per capita adjusts for inflation and population — the best single measure of average living standards."),
    mc("The Fisher effect states that:","Real interest rate = nominal rate + inflation","Nominal interest rate = real interest rate + expected inflation","Inflation causes unemployment","Exchange rates equal purchasing power",1,"Fisher effect: nominal interest rate adjusts to expected inflation so that the real rate remains stable."),
  ]
}

AP_HISTORY_U8 = {
  "title": "AP Microeconomics",
  "questions": [
    mc("The law of demand states that:","Higher prices lead to higher quantity demanded","There is an inverse relationship between price and quantity demanded, all else equal","Demand increases with income always","Supply determines demand",1,"Law of demand: as price rises, quantity demanded falls (inverse relationship), ceteris paribus."),
    mc("Which of the following shifts the demand curve to the right?","A rise in the good's own price","A decrease in consumer income (for normal goods)","An increase in consumer income (for normal goods)","A fall in the price of a complementary good",2,"Demand curve shifts right with: ↑ income (normal good), ↑ price of substitutes, ↓ price of complements, ↑ preferences."),
    mc("Price elasticity of demand measures:","How much quantity demanded changes with a change in supply","The responsiveness of quantity demanded to a change in price","The slope of the demand curve only","Consumer surplus",1,"|PED| = % change in Qd / % change in P. Elastic demand (|PED|>1) means consumers respond strongly to price changes."),
    mc("If demand is inelastic, a price increase will:","Decrease total revenue","Increase total revenue (since quantity falls less than price rises)","Leave total revenue unchanged","Cause a surplus",1,"Inelastic demand: price and total revenue move together. Elastic demand: they move oppositely."),
    mc("Marginal cost is:","Total cost divided by quantity","The change in total cost from producing one more unit","Fixed cost per unit","Average variable cost",1,"MC = ΔTC/ΔQ. Marginal cost is the cost of producing the next unit."),
    mc("Profit is maximized when:","Price equals average total cost","Marginal revenue equals marginal cost (MR = MC)","Total revenue is maximized","Marginal cost is minimized",1,"MR = MC is the profit-maximizing condition for all market structures (with MR < MC leading to loss on additional units)."),
    mc("A perfectly competitive firm in the long run earns:","Economic profit","Normal profit (zero economic profit) as entry/exit drives price to minimum ATC","Monopoly profit","Losses",1,"Long-run competitive equilibrium: P = minimum ATC. Economic profit = 0. Firms earn normal (accounting) profit."),
    mc("Which characteristic distinguishes a monopoly from perfect competition?","Many buyers","Price-taking behavior","Single seller with barriers to entry and no close substitutes","Homogeneous products",2,"Monopoly: one seller, barriers to entry, unique product, price maker. Perfect competition: many sellers, price takers."),
    mc("Deadweight loss in a monopoly results from:","The monopolist earning profit","Output being below the competitive level — mutually beneficial transactions do not occur","High prices alone","Consumer surplus transfer to producers",1,"DWL: monopolist restricts output below efficient level (Q where P=MC), causing lost surplus for both consumers and producers."),
    mc("A natural monopoly exists when:","One firm has a patent","A firm is vertically integrated","One firm can produce the entire market output at lower average cost than multiple firms (due to economies of scale)","The government grants exclusive rights",2,"Natural monopoly: declining LRATC over the entire market demand range — one firm is most efficient (utilities, infrastructure)."),
    mc("Price discrimination requires:","Identical prices for all buyers","Market power, separable markets, and inability of buyers to resell","Perfect competition","Elastic demand",1,"Price discrimination: charge different prices to different groups. Requires market power + ability to segment markets + no arbitrage."),
    mc("The shutdown rule for a competitive firm in the short run is:","Shut down if P < ATC","Shut down if P < AVC (price doesn't cover variable costs)","Shut down if economic profit < 0","Shut down if TR < TC",1,"Short-run shutdown: if P < AVC, firm loses more by operating than by closing. If P > AVC, operating reduces losses."),
    mc("An oligopoly is characterized by:","Many small firms","One dominant firm","A few firms with interdependence — each firm's decisions affect others","Free entry and exit",2,"Oligopoly: few firms (e.g., airline, auto industry) with strategic interdependence. Studied with game theory."),
    mc("The prisoner's dilemma illustrates why:","Cooperation always results","Self-interest leads to outcomes worse than if players cooperated (Nash equilibrium is suboptimal)","Monopolies are inefficient","Price floors cause surpluses",1,"Prisoner's dilemma: dominant strategy leads to mutual defection (worse outcome). Explains oligopoly cheating on cartels."),
    mc("Consumer surplus is:","Price minus marginal cost","The difference between what consumers are willing to pay and what they actually pay","Total revenue minus total cost","The area under the supply curve",1,"Consumer surplus = willingness to pay − actual price paid. It's the area above price and below the demand curve."),
    mc("An excise tax on a good with inelastic demand will:","Be borne mainly by producers","Be borne mainly by consumers","Be split equally","Cause large quantity reductions",1,"Inelastic demand: consumers can't easily reduce purchases, so they bear most of the tax burden."),
    mc("Externalities are:","Costs and benefits experienced only by the buyer and seller","Costs or benefits that spill over to third parties not in the transaction","Government interventions","Import tariffs",1,"Externality: spillover effect on third parties. Negative (pollution) = overproduction; positive (education) = underproduction relative to social optimum."),
    mc("The Coase theorem states that:","Government must correct all externalities","If property rights are clearly defined and transaction costs are zero, private bargaining leads to efficient outcomes","Externalities always require taxation","Market failures are unavoidable",1,"Coase theorem: well-defined property rights + zero transaction costs → private negotiation reaches efficiency regardless of initial assignment."),
    mc("Monopsony refers to:","A single seller","A single buyer with market power (e.g., a dominant employer in a labor market)","Government price control","A cartel of sellers",1,"Monopsony: one buyer (market power on demand side). In labor markets, a monopsonist pays less than competitive wage."),
    mc("In the long run, all costs are:","Fixed","Variable — all inputs can be adjusted","Sunk","Marginal",1,"In the long run, all costs are variable — firms can adjust all inputs, including capital/plant size. No fixed costs in LR."),
  ]
}

AP_HISTORY_U9 = {
  "title": "AP Psychology",
  "questions": [
    mc("Which perspective emphasizes unconscious drives and childhood experiences?","Behavioral","Humanistic","Psychoanalytic/Psychodynamic","Cognitive",2,"Freud's psychoanalytic theory: behavior is driven by unconscious conflicts, repressed memories, and early childhood experiences."),
    mc("A neuron transmits signals through:","Blood flow only","Electrical impulses along the axon and chemical neurotransmitters across synapses","Hormones only","Glial cell connections",1,"Neurons: electrical signal travels down axon; neurotransmitters cross the synapse to receptor sites on the next neuron."),
    mc("Classical conditioning involves:","Learning through consequences (rewards/punishments)","Learning by associating a neutral stimulus with an unconditioned stimulus until it produces the same response","Observational learning","Cognitive restructuring",1,"Classical conditioning (Pavlov): NS paired with UCS → NS becomes CS that produces CR. Stimulus substitution."),
    mc("In operant conditioning, a negative reinforcer:","Punishes unwanted behavior","Is removed after a behavior to increase the likelihood of that behavior","Is added after behavior to decrease it","Is the same as punishment",1,"Negative reinforcement: removing an aversive stimulus to increase behavior (e.g., taking aspirin removes pain → you take it more). NOT punishment."),
    mc("The term 'long-term potentiation' (LTP) refers to:","Forgetting over time","Strengthening of synaptic connections with repeated activation — the neural basis of learning","Sensory adaptation","REM sleep",1,"LTP: repeated stimulation strengthens synaptic connections. 'Neurons that fire together wire together.' Neural basis of memory."),
    mc("Maslow's hierarchy of needs places which need at the top (self-fulfillment)?","Safety needs","Esteem needs","Physiological needs","Self-actualization",3,"Maslow's hierarchy: physiological → safety → love/belonging → esteem → self-actualization (reaching one's full potential)."),
    mc("The 'bystander effect' refers to:","People helping in emergencies due to proximity","Reduced likelihood of an individual helping when others are present (diffusion of responsibility)","Conformity to group norms","Obedience to authority",1,"Bystander effect (Latané and Darley): as more bystanders are present, each feels less personal responsibility to intervene."),
    mc("In Piaget's theory, conservation refers to:","Protecting the environment","The understanding that quantity remains the same despite changes in shape or arrangement","Object permanence","Formal operational thinking",1,"Conservation: understanding that volume/mass/number is unchanged despite perceptual changes (e.g., same clay, different shape). Develops in concrete operational stage."),
    mc("The DSM-5 is:","A test of intelligence","The Diagnostic and Statistical Manual — the standard classification system for psychological disorders","A personality inventory","A type of therapy",1,"DSM-5 (Diagnostic and Statistical Manual, 5th ed.): classifies and defines psychological disorders by symptom criteria."),
    mc("Which sleep stage is characterized by rapid eye movements, vivid dreaming, and muscle paralysis?","Stage 1 NREM","Stage 3 NREM (slow wave)","REM sleep","Stage 2 NREM",2,"REM (Rapid Eye Movement) sleep: vivid dreams, activated brain similar to waking, voluntary muscles paralyzed (sleep atonia)."),
    mc("A double-blind study controls for:","Sampling bias","Both participant and experimenter expectations/biases (placebo effect, experimenter effect)","Demand characteristics only","Random assignment",1,"Double-blind: neither participants nor researchers know who received treatment vs. placebo, eliminating expectation biases."),
    mc("The fundamental attribution error is the tendency to:","Underestimate situational factors and overestimate dispositional (personality) factors when explaining others' behavior","Blame ourselves for failures","Attribute success to luck","Underestimate our own abilities",0,"FAE: we over-attribute others' behavior to their character and under-attribute to the situation. Opposite for ourselves (actor-observer bias)."),
    mc("Cognitive dissonance occurs when:","Two people disagree","A person holds conflicting beliefs or acts contrary to beliefs, creating psychological discomfort","Memory fails","A stimulus generalizes to similar stimuli",1,"Cognitive dissonance (Festinger): discomfort from inconsistent cognitions or actions/beliefs. Motivates attitude change to restore consistency."),
    mc("The heritability of a trait refers to:","How much genetics determine the trait absolutely","The proportion of variation in a trait within a population that is attributable to genetic differences","Whether a trait is genetic","The percent of the genome involved in a trait",1,"Heritability: what proportion of the population's variation in a trait is due to genetic differences (not a statement about individuals)."),
    mc("Serotonin is most associated with:","Pain response","Mood regulation, sleep, and appetite — low levels linked to depression","Motor control only","Fight-or-flight response",1,"Serotonin: mood, sleep, appetite, digestion. SSRIs (antidepressants) block serotonin reuptake, increasing synaptic serotonin."),
    mc("Which type of therapy focuses on identifying and changing maladaptive thought patterns?","Psychoanalysis","Humanistic therapy","Cognitive-behavioral therapy (CBT)","Behavior modification only",2,"CBT: identifies distorted cognitions (e.g., catastrophizing) and replaces them with realistic thinking. Evidence-based for depression, anxiety."),
    mc("The Stanford Prison Experiment (Zimbardo) demonstrated:","That personality is fixed","The power of social roles and situational factors to shape behavior even in normal people","That obedience requires direct authority","The bystander effect",1,"Zimbardo's study: randomly assigned 'guards' and 'prisoners' quickly adopted roles, showing how situations shape behavior."),
    mc("Retroactive interference occurs when:","Old memories block new learning","New learning disrupts retrieval of old memories","Two stimuli are confused","REM sleep prevents memory consolidation",1,"Retroactive interference: new information interferes with retrieval of old information. Proactive: old interferes with new."),
    mc("Psychologists distinguish between crystallized and fluid intelligence. Crystallized intelligence:","Declines sharply after age 30","Consists of accumulated knowledge and skills; generally stable or increases with age","Is measured by reaction time","Is the same as IQ",1,"Crystallized intelligence: knowledge/skills accumulated through experience (vocabulary, facts). Fluid intelligence: processing speed and novel problem-solving — declines with age."),
    mc("The concept of 'learned helplessness' (Seligman) explains:","Why people become overconfident","How repeated uncontrollable negative events lead to passive, depressed behavior — a model of depression","How rewards increase motivation","Classical conditioning of fear",1,"Learned helplessness: after repeated inescapable aversive events, organisms stop trying even when escape becomes possible. Model of depression."),
  ]
}

if __name__ == '__main__':
    for name, data in [("AP History U5 Comparative Gov", AP_HISTORY_U5),
                        ("AP History U6 Human Geo", AP_HISTORY_U6),
                        ("AP History U7 Macro", AP_HISTORY_U7),
                        ("AP History U8 Micro", AP_HISTORY_U8),
                        ("AP History U9 Psychology", AP_HISTORY_U9)]:
        print(f"{name}: {len(data['questions'])} questions")
